### ISSUE TITLE
feature: inventory for MCAD and ODH in KubeStellar

### ISSUE THREAD

**Issue by clubanderson** [kubestellar/kubestellar#1001]
### Feature Description

There is a list of elements that the MCAD and ODH folks would like to store in KubeStellar's inventory module.  Would it be feasible to suggest our inventory API as a place to store them or should we recommend other options?

### Proposed Solution

use the KubeStellar inventory (location objects) if possible.

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by MikeSpreitzer** [comment]
MCAD is discussing this at https://github.ibm.com/MCC/regulated-multicloud-ai-workflows/issues/7 .

We _could_ say that our MCCM should have a different inventory representation than MCAD chooses, but that sounds like unnecessary complexity to me.  I like the idea of converging on an inventory representation that allows the set of cluster properties to be appropriate for the overall use case.  You could argue that KS MCCM has this today: a Location object has metadata.labels that can be used for whatever collection of cluster properties are needed.  The sig-multicluster inventory proposal has a slightly more modeled concept on an usage-specific set of cluster properties.

**Comment by clubanderson** [comment]
@MikeSpreitzer  I saw your comments on the inventory issue.  Do we plan on adopting the sig-multicluster proposal as part of KubeStellar?

**Comment by clubanderson** [comment]
closing this issue as the MCC folks have adopted their own inventory spec.  We look ahead to adopting sig-multicluster proposal for KS
