### ISSUE TITLE
Helm missing in required packages on Quickstart

### ISSUE THREAD

**Issue by rubambiza** [kubestellar/kubestellar#1017]
**Context**: I was recently running Kubestellar Quickstart as a k8s workload (release-0.7) on WSL (Ubuntu 16.04). The kubestellar bootstrap script failed on line 89 saying `helm command not found`. So, I looked into how to install helm ( 👉🏾helm.sh/docs/intro/install).

**Recommendation**: It is worth adding the helm installer pointer  to the list of required packages for all OS flavors.

**Comment by clubanderson** [comment]
@namasl can you open a PR for the require-packages file?

**Comment by clubanderson** [comment]
@rubambiza this has been updated on our documentation online - can you confirm and close?

**Comment by rubambiza** [comment]
@clubanderson Are you referring to the [Quickstart 0.7 release](https://docs.kubestellar.io/release-0.7/Getting-Started/quickstart/)? If so, I don't see the update yet.

**Comment by clubanderson** [comment]
No. We make changes to main.
