### ISSUE TITLE
K8s hosting cluster missing kubestellar server on bootstrap

### ISSUE THREAD

**Issue by rubambiza** [kubestellar/kubestellar#1018]
**Context**: [see #1017 for initial context]. After installing helm and re-running bootstrap script, the KubeStellar bootstrap completed successfully. I also made sure to export the KUBECONFIG variable. After waiting a few minutes to see if the kubestellar-server pod is running, the `kubectl get deployments -n kubestellar` command runs into **error: the server doesn’t have a resource type ‘deployments’**. However, the `kubectl ws tree` command spits out the right thing, and I was able to proceed creating clusters, IMW, etc.

**Comment by MikeSpreitzer** [comment]
There is stuff that contributors know and is not clearly written down anywhere.  This doc problem is the real bug here.

0. (This is general Kubernetes knowledge, which can be referenced.)  A Kubernetes client generally makes two levels of selection of which physical space it uses: (1) the client uses one particular kubeconfig file, and (2) the client uses one particular "context" within that kubeconfig file.
1. (This is somewhat written down in KubeStellar documentation, apparently not prominently enough.) When deploying KubeStellar MCCM as workload in a Kubernetes cluster, note that the step of fetching a kubeconfig file for working with the various physical spaces that hold the MCCM workload and API objects is indeed fetching a kubeconfig file --- that is not the same as the kubeconfig file that was used to manipulate the cluster that hosts MCCM as a workload.

**Comment by rubambiza** [comment]
@MikeSpreitzer Thanks for the above clarifications. I come with limited kubernetes experience from interning with another IBM team where a lot of the infrastructure was already set up when I joined. So, bear with me as I get excited/frustrated in learning how the sausage is made. As a nOOb to both Kubernetes and KubeStellar, it has been a bit of a learning curve modifying the quickstart to make my own hello-world using our existing applications. A few thoughts in response to yours:

0. This makes total sense! I have definitely seen this structure in the `kubestellar.kubeconfig` file that gets generated every time I go through the tutorial.

1. I think this is related to your point 2. How can I tell the difference not only between the different physical/name spaces, but also when I have shifted in __workspaces__ within a single physical/name space? It seems like using kind clusters should simplify things, but I keep coming up from the trenches with more questions than answers. For example, I usually take breaks when I run into uncharted territory (e.g., my workload did not get deployed in my versions of `florin` and `guilder`), only to come back and the server supporting whatever workspace/namespace/context I was working in starts timing out 👇 ). ![Kubestellar-Timeouts](https://github.com/kubestellar/kubestellar/assets/11816517/fee9d88b-f1c4-4b5a-98a7-0f83157c8d43)
Did I jump at the deep end of the proverbial kubestellar pool too quickly? You don't have to answer that. I can reserve some of these questions for my bi-weekly/monthly meetings with @dumb0002 and @clubanderson.

**Comment by clubanderson** [comment]
@rubambiza I had this happen to me the other day.  make sure your context is set to 'root' to start with - 'kubectl config use-context root'

at times you can get lost in the hierarchy and then you will get API timeouts like this

@namasl @KPRoche please add this type of issue and resolution to your work with a troubleshooting guide.

**Comment by clubanderson** [comment]
@rubambiza can you give an update on this issue?

**Comment by rubambiza** [comment]
@clubanderson I had an issue where everything seemed to go smoothly until the time when I deployed a modified version of the Apache Server workload (i.e., an SDF hello-world as documented in the email to you and Braulio). @dumb0002 and I tried to troubleshoot last Friday, and we agreed that it makes sense to replicate a version of the kubestellar inside a cluster + Apache workload to verify that all the syncers and whatnot are set up properly and THEN modify the workload. I will be doing so this Th/F when I return from a conference and report back.

**Comment by clubanderson** [comment]
excellent - we are making lots of updates to make your experience better, so keep the feedback coming.  Thank you

**Comment by rubambiza** [comment]
@clubanderson Updates from the weekend:

- Kubestellar server pod showed up as running (yay!)
- Creating the IMW/WMWs seems to work fine (yay!)
- **Deploying the HTTP server workload does not work in the `example-wmw` workspace**.

Based on a previous convo with Braulio, it might be something in machinery where kubestellar is not able to communicate properly with the edge syncers.

**Comment by rubambiza** [comment]
@clubanderson I gave up on running KS as a workload. When I ran it as a bare process, everything went smoothly and I was able to run a hello world of SDF. I think running it as a workload clashed with some of the networking on WSL, but it is still worth investigating why it failed. @dumb0002 thought it had something to do with the DNS config, and he will look into it.

For more context, I ran KS as a bare process using release-0.7 and the instructions on main to create the IMW and WMW.

**Comment by clubanderson** [comment]
@rubambiza that's great to hear.  We just ran into a similar problem with Debian.  You might benefit from those instructions.  https://github.com/kubestellar/kubestellar/issues/1192.  And the full set of instructions is coming in our new quickstart guide - to be launched any day now.  Check out 'docs/content/common-subs/debian-kind-docker.md' in PR https://github.com/kubestellar/kubestellar/pull/1116/files?short_path=734d3c9#diff-734d3c9fe5537be13a3d0cbe069c852b53592fc256ba7efd7099c98e4f46a138.  This might also work for you - would be curious to know.  If it is the case, then we can added a note that says it is for WSL also.  I suspect this might work for you.

**Comment by rubambiza** [comment]
@clubanderson It's good to hear the issue has been observed in other OS flavors, and thanks for the pointers. If it is okay with you, I will until the new Quickstart is stable before I try it on my only dev machine because we are finally making progress on the SDF 2.0 implementation. @dumb0002 offered to set up a sandbox WSL env, try the new workaround, and report before I can try it.

**Comment by clubanderson** [comment]
@rubambiza would you like to keep this issue open, or are you satisfied with the current usage?

**Comment by rubambiza** [comment]
I am good right now. Thanks for checking. Closing now.
