### ISSUE TITLE
bug: version problems on web

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#1020]
### Describe the bug

(1) https://kubestellar.io/ redirects to release _0.3_ .  I am sure that is not intended.

(2) I think it is past time to update https://github.com/kubestellar/kubestellar/blob/main/VERSION , no reason to not say that 0.7 is stable.

### Steps To Reproduce

See above.

### Expected Behavior

See above.

**Comment by clubanderson** [comment]
fixed
