### ISSUE TITLE
feature: Be able to identify which Space the object resides in (from the object)

### ISSUE THREAD

**Issue by andreyod** [kubestellar/kubestellar#1021]
### Feature Description

KCP objects have special annotation("kcp.io/cluster") that holds a reference to the cluster. From that reference is is also possible to obtain the  workspace. This annotation is set by KCP and will not be available in other providers.
For example, when we use a watch or List over an APIExport using kube-bind, we get a list of objects and such annotation is the only way to know which cluster the object belongs to. 

### Proposed Solution

Be able to get the cluster (or space) from the  object (e.g., through the NS name, annotation, other way)

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by waltforme** [comment]
Can I have some more information? If my understanding is correct, the KS platform objects (EdgePlacements, for example) are the ones that kube-bind is responsible to sync between the KS space and other spaces. OTOH, the objects that representing users' workloads are not. Am I right?

**Comment by waltforme** [comment]
I guess we have a solution for this right? And, since that solution is documented and tracked by #1208, can we close this (duplicated) one?

**Comment by ezrasilvera** [comment]
Included in https://github.com/kubestellar/kubestellar/issues/1208   second section
