### ISSUE TITLE
bug: Documentation no longer specifies go (and version) in prerequisites to install

### ISSUE THREAD

**Issue by KPRoche** [kubestellar/kubestellar#1026]
### Describe the bug

The "required packages" include files no longer mention go, and any of the examples which include a "make build" command may fail as a result.

### Steps To Reproduce

1. go to https://docs.kubestellar.io/main/Coding%20Milestones/PoC2023q1/example1/
2. Read and follow the instructions to install prerequisites
3. Continue down to https://docs.kubestellar.io/main/Coding%20Milestones/PoC2023q1/example1/#get-kubestellar
4. reach the make build command and run it
5. if go is not installed, or too old a version is installed, this will fail

### Expected Behavior

Add mention that _if you will be building kubestellar from the source, you need to have go>= 1.19 installed_. This used to be in the prerequisites include file.
If it was removed from there as excess because its not needed for the containerized quickstart using bootstrap, which also pulls in those required software include files, call out the requirement for go in the main file after the prereqs section.

**Comment by clubanderson** [comment]
@KPRoche I think that is in the top of the page under required packages, no?

**Comment by clubanderson** [comment]
hmm, well, that was there a while back - guess it needs to be re-added

**Comment by KPRoche** [comment]
nope 
![image](https://github.com/kubestellar/kubestellar/assets/25445603/0522597b-22a1-4523-b593-1da50fb17f26)
![image](https://github.com/kubestellar/kubestellar/assets/25445603/f2b13166-1223-4985-be1e-8cffc13f72ff)

I think it was pulled out in the name of simplifying the quickstart

**Comment by KPRoche** [comment]
> hmm, well, that was there a while back - guess it needs to be re-added
It is a conditional requirement IFF you are doing a build. Might be worth standing it out from the main prereqs as an optional requirement

**Comment by KPRoche** [comment]
QUESTION: **when** is go actually required? only for doing a make build or code development, or does it need to be installed for the using one of the release archives?
In other words, if I'm not building my own binaries, but just want to run from one of the releases, do I need to install go?

**Comment by MikeSpreitzer** [comment]
Right, it depends on the role of the person involved.  For a user of a release, there is no go compilation involved.  For a contributor who is building, go compilation is involved.

**Comment by clubanderson** [comment]
@KPRoche @fab7 can you work together to knock this out?

**Comment by KPRoche** [comment]
> @KPRoche @fab7 can you work together to knock this out?
@clubanderson 
Would you prefer this be mentioned in the pre-reqs include file, or as a note for contributors/developers in the text specific to the extended example?

**Comment by clubanderson** [comment]
well, you opened the issue - where do you think it fits best?  Where is it most useful/helpful?

**Comment by KPRoche** [comment]
I think including it in the prereqs is still appropriate, at least in the overview section. I'll create a fork and a PR.

**Comment by KPRoche** [comment]
PR #1233 created

**Comment by clubanderson** [comment]
is this closed now @KPRoche ?
