### ISSUE TITLE
feature: Support to deploy a workload packaged as a Helm chart to a workload execution cluster

### ISSUE THREAD

**Issue by dumb0002** [kubestellar/kubestellar#1040]
### Feature Description

Some workloads are packaged as helm charts. We need to be able to deploy such applications to a workload execution cluster via KubeStellar. 

### Proposed Solution

To be able to use a helm chart to deploy a workload to a workload execution cluster via KubeStellar

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by MikeSpreitzer** [comment]
The real work here presumably is instantiating the Helm chart in a WDS, since KubeStellar will get it from the WDS to the WEC.

**Comment by clubanderson** [comment]
I think this works ok.  I have done it a few times.  Yes, we are missing some automation around special types/kinds that are required, but that is cared for in another issue.  Closing this for now.
