### ISSUE TITLE
bug: Wrong release shows in docs pages for main

### ISSUE THREAD

**Issue by KPRoche** [kubestellar/kubestellar#1045]
### Describe the bug

**main** pages in docs.kubestellar.io show the wrong release in the header

### Steps To Reproduce

1. go to docs.kubestellar.io/main
2. Look in right hand side: shows release 0.6.0 ![image](https://github.com/kubestellar/kubestellar/assets/25445603/37bd8b61-039b-4343-8738-cb933a0c859b)
3. change to another release via twisty. Now shows release 0.7.0

### Expected Behavior

Should show actual release (0.7.0) for main

**Comment by clubanderson** [comment]
Clear your cache and try again

**Comment by clubanderson** [comment]
Or use chrome incognito

**Comment by clubanderson** [comment]
@KPRoche can this be closed?

**Comment by KPRoche** [comment]
Yes
