### ISSUE TITLE
bug: can't create SyncTarget yaml for WEC - kubectl-kubestellar-prep_for_syncer: line 184: 27522 Killed: 9 "$bindir/kubectl-kubestellar-syncer_gen" "$stname" --syncer-image "$syncer_image" -o "$output"

### ISSUE THREAD

**Issue by clubanderson** [kubestellar/kubestellar#1049]
### Describe the bug

receiving:

```
kubectl kubestellar prep-for-cluster --imw root:example-imw1 wec5 env=wec5 
Current workspace is "root:example-imw1".
--- current directory is /Users/andan02/projects
current ws is root:example-imw1
imw is .
current cwsi is root:example-imw1
edge.kubestellar.io apibinding exists in workspace root:example-imw1
Current workspace is "root:example-imw1".
Current workspace is "root:espw".
/opt/homebrew/bin/kubectl-kubestellar-prep_for_syncer: line 184: 27522 Killed: 9               "$bindir/kubectl-kubestellar-syncer_gen" "$stname" --syncer-image "$syncer_image" -o "$output"
Current workspace is "root:example-imw1".
Current workspace is "root".
```

### Steps To Reproduce

1. install kubestellar v0.7.0 via helm into openshift
2. download kubestellar kubectl plugin scripts and put them in path
3. run 'kubestellar-release' to confirm v0.7.0 for plugins
4. run 'kubectl kubestellar get-external-kubeconfig -o ~/ks.config'
5. run 'KUBECONFIG=~/ks.config kubectl ws root'
6. run 'KUBECONFIG=~/ks.config kubectl kubestellar prep-for-cluster --imw root:example-imw1 wec5 env=wec5'

receive output:
```
kubectl kubestellar prep-for-cluster --imw root:example-imw1 wec5 env=wec5 
Current workspace is "root:example-imw1".
--- current directory is /Users/andan02/projects
current ws is root:example-imw1
imw is .
current cwsi is root:example-imw1
edge.kubestellar.io apibinding exists in workspace root:example-imw1
Current workspace is "root:example-imw1".
Current workspace is "root:espw".
/opt/homebrew/bin/kubectl-kubestellar-prep_for_syncer: line 184: 27522 Killed: 9               "$bindir/kubectl-kubestellar-syncer_gen" "$stname" --syncer-image "$syncer_image" -o "$output"
Current workspace is "root:example-imw1".
Current workspace is "root".
```

### Expected Behavior

expected to receive SyncTarget directions

**Comment by clubanderson** [comment]
invalid issue - looks like it was a plugin to core mismatch

**Comment by MikeSpreitzer** [comment]
Thank you for including the steps to reproduce. That was very helpful. It revealed a bug in the documentation, #1062 .

**Comment by MikeSpreitzer** [comment]
In the "Steps To Reproduce" section of the opening comment, it looks to me like there is _NOT_ a version mismatch. The `kubestellar-release` command is looked up on the `$PATH` of the shell where you issue it; when it prints "v0.7.0" that would tell me there is consistency with a core that is also v0.7.0.
