### ISSUE TITLE
bug: no way to get kubectl plugins for kubestellar without downloading and extracting release tar file

### ISSUE THREAD

**Issue by clubanderson** [kubestellar/kubestellar#1050]
### Describe the bug

I am unable to use the curl-2-bash script with '--deploy false' to extract using the command.  

```
bash <(curl -s https://raw.githubusercontent.com/kubestellar/kubestellar/release-0.7/bootstrap/bootstrap-kubestellar.sh) --kubestellar-version v0.7.0 --deploy false
```

I get a .kcp directory and no other files.

just as we run 'kubestellar-release' to find the version of the plugins, and just as we use 'get-external-config' to get the kubeconfig necessary to communicate with kubestellar's underlying platform, we should have 'get-plugins' to get the matching version of kubestellar kubectl plugins downloaded and in the proper path.  Perhaps this is a brew installation script.  Whatever it is, it should be standard and easy to use.  Maybe host the binaries in the kubestellar install and allow someone to simply curl them out of kubestellar itself.  

### Steps To Reproduce

1. run 'bash <(curl -s https://raw.githubusercontent.com/kubestellar/kubestellar/release-0.7/bootstrap/bootstrap-kubestellar.sh) --kubestellar-version v0.7.0 --deploy false'
2. list directory

output is .kcp and no other files.

### Expected Behavior

I expect a simple way to get the right version of kubestellar kubectl plugins that match the version of the kubestellar server I am trying to communicate with in the kubeconfig.

**Comment by MikeSpreitzer** [comment]
The current bootstrap script's deliberately designed behavior is to get you the executables _that are not already on your path_.  In some console session that you fortunately shared recently I noticed that the bootstrap script said that it was not adding executables because it found them already on your `$PATH` (under /opt/homebrew).  We could change the behavior of the bootstrap script.  @francostellari is the original author.

**Comment by MikeSpreitzer** [comment]
The current behavior of the bootstrap script is described in https://docs.kubestellar.io/main/Coding%20Milestones/PoC2023q1/commands/#bootstrap .  We deliberately chose to not put a full description of the bootstrap script in the quickstart, for the sake of keeping the quickstart short.  The user guide being started in #1042 references the quickstart but not the full doc for the bootstrap script; I think it would be appropriate to also point to the full doc for the bootstrap script.

**Comment by clubanderson** [comment]
closing this issue - focusing on #1051 instead.
