### ISSUE TITLE
feature: helm as the default and primary method for installing kubestellar

### ISSUE THREAD

**Issue by clubanderson** [kubestellar/kubestellar#1054]
### Feature Description

We will de-emphasize the use of installing processes on top of bare metal from now on.  Containerized deployment of KubeStellar will be our primary method of using it. 

### Proposed Solution

1) introduce a 3rd kind cluster for kubestellar core
2) split release into ks core and ks plugins
3) get helm chart to deploy 4 pods based on 4 containers based on our 3 controllers and 1 kcp to support kubestellar to further support 4 separate logs (1 from each ks process and 1 from kcp)

Installing kubestellar is now a 2 step process
Step 0 - pre reqs (includes matching version of kubestellar kubectl plugin)
Step 1 - install ks (includes everything up to and including automatically creating 1 imw and 1 wmw)

using kubestellar is now also a 2 step process
Step 2 - install syncer (location and sync target)
Step 4 - deploy workload (edgeplacement)

Users will use helm to install kubestellar core on their laptop inside a kind cluster and then connect to other kind clusters with syncers.  Users will also use helm to install our core on openshift, kubernetes, etc.

users will use brew to install kubestellar plugins

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by pdettori** [comment]
I love brew, it's great for macOS and I use it all the time. But it's less popular for linux distress, perhaps for that we can just give the option to download and copy the binaries.

**Comment by clubanderson** [comment]
It's the best option we have for cross platform support. What other package managers would you like to support?

**Comment by clubanderson** [comment]
Helm is now supported, brew is coming in new PR

**Comment by clubanderson** [comment]
working great - great job @francostellari
