### ISSUE TITLE
feature: create simplified diagram of kubestellar that will be used universally for all user facing communications

### ISSUE THREAD

**Issue by clubanderson** [kubestellar/kubestellar#1056]
### Feature Description

current versions of kubestellar diagrams are overwhelming to users. 

### Proposed Solution

create a simple KubeStellar diagram that shows 2 KubeStellar components - core and syncer.  The diagram should show core running on any kubernetes cluster (kind, kubernetes, openshift, etc) and syncer running on any kubernetes cluster (kind, microshift, Kubernetes, openshift).  Our api for a) location, b) SyncTarget, and c) edgeplacement are the only interfaces we will expose and visualize on top of the 2 block diagram (core, syncer).  Simple, easy to understand, easy to use.

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by pdettori** [comment]
@clubanderson here is a proposal:
![kubestellar-high-level-arch](https://github.com/kubestellar/kubestellar/assets/6678093/eeee7149-4977-4b27-9273-992350738d03)

**Comment by clubanderson** [comment]
Thank you @pdettori , I think this is the next reveal/level after the even simpler diagram of "KubeStellar Core" "KubeStellar Syncer".  @KPRoche can you add a diagram that has just 2 blocks in it?

**Comment by KPRoche** [comment]
Something like this? (can refine later once I'm at work)
![kubestellar flow](https://github.com/kubestellar/kubestellar/assets/25445603/50d1cc15-8f9d-4836-a0b2-c2d0d9f97a9c)

**Comment by KPRoche** [comment]
After conversations with Andy, an even simpler version with no semantic loading regarding comms direction.
![Kubestellar no user simple](https://github.com/kubestellar/kubestellar/assets/25445603/2e6d94f2-0149-49c0-8309-d3c1d2b3003e)
![Kubestellar with user simple](https://github.com/kubestellar/kubestellar/assets/25445603/c40f67f5-7373-4449-bc2a-08572529ac97)

**Comment by clubanderson** [comment]
Looks good for now. Closing. Thank you
