### ISSUE TITLE
feature: CI needs to test deployment of KubeStellar core in a kube cluster

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#1060]
### Feature Description

We need the regular testing for every PR to include checking that the result of the merging the PR is a KubeStellar version that can be deployed as workload in a Kubernetes cluster and pass an end-to-end test.

This particular test will necessarily include building the container image(s) involved, arranging that those will be the ones used in the remainder of the test, creating a Kubernetes cluster to deploy the core into, and creating a WEC to exercise.

### Proposed Solution

Write a test that is like example1 but follows the deploy-as-workload path and first builds the core image(s) that will be used.

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by clubanderson** [comment]
this is included in the new user-quickstart

**Comment by clubanderson** [comment]
Completed

**Comment by MikeSpreitzer** [comment]
The user quickstarts only test stuff that has been released, they do not test the contents of the PR being evaluated.

**Comment by MikeSpreitzer** [comment]
Additional progress has been made with PRs #1231, #1236, and #1237. Still missing is the path through brew, that still fetches and uses older content published earlier.

**Comment by MikeSpreitzer** [comment]
@KPRoche found https://apple.stackexchange.com/questions/84403/how-to-use-homebrew-to-install-local-archive , which documents how to short-circuit the fetch of a remote archive --- but ONLY if you already have THE SAME bits (same SHA256 content hash). We want to test the archive that would be built from the contents of the PR, not the last released archive.

**Comment by MikeSpreitzer** [comment]
One way to understand the problem is to look at the picture in https://docs.google.com/drawings/d/11a20h5Q50YPCnPkQjVKFNc0cfzi6xfhlerJ9IlXCRRQ and consider whether the graph among top-level things is a DAG (that would untangle dependencies making a cleanly factored system). The answer is no, because of the loop between github.com/kubestellar/kubestellar and github.com/kubestellar/homebrew-kubestellar .
