### ISSUE TITLE
feature: UX - add a "clusters:all" label in our location objects by default

### ISSUE THREAD

**Issue by clubanderson** [kubestellar/kubestellar#1065]
### Feature Description

If I want to send the same workload to every WEC in an environment, I need to edit every location object (1 for each WEC) and put "clusters:all" into each location

We should have at least a global group that allows you to deploy to every location out-of-the-box.  This is in addition to the locations self-named label that it receives when we create the object.  Location should be targeted by its own name and by 1 "all" group.  Gives users a hint at how to setup regions and etc.

### Proposed Solution

add a "clusters: all" label for every location, by default.  

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by clubanderson** [comment]
@MikeSpreitzer what do you suggest?

**Comment by clubanderson** [comment]
@KPRoche you have some ideas - weigh in please.

**Comment by KPRoche** [comment]
@MikeSpreitzer made a very good point in our meeting that "clusters;all" or "locations:all" breaks the semantic expectation in labels that starting the label with a plural implies that the part after the colon should be a list, not a simple string.
@clubanderson can you show me what your edited file (or a snippet) with the label looks like?
