### ISSUE TITLE
bug: UX - syncer has gone offline and I have no way of knowing it is offline and for how long

### ISSUE THREAD

**Issue by clubanderson** [kubestellar/kubestellar#1067]
### Describe the bug

I found 2 syncers were offline for some period of time by opening the pod log for the syncer on each WEC.  This is an antipattern in light of our ability to report status on workload objects, but not on our syncer.  Of course, if the syncer is offline, there is no way to get status back, so it would be good to just get an indication on how long it has been since the mailbox has heard from the syncer.  

### Steps To Reproduce

1. install Kubestellar Core v0.7.0 
2. create imw and wmw
3. prep-for-cluster for a WEC
4. install the syncer (v0.7.0) on the WEC
5. restart kubestellar core
6. syncer loses certificate and goes offline

there is no indication in the location or SyncTarget object as to when the syncer was last heard from.  And, even it is a status in those objects, they are not usually managed by argocd and therefore there is no way to quickly see which syncers are offline for an extended period of time

### Expected Behavior

1) make it possible to manage the location object in argocd - not sure how this would work since the process of creating a syncer is done with kubestellar-prep-for-cluster.
2) record the last contact with a syncer in an argocd management object - edgeplacement is the only one I can think of right now.

**Comment by pdettori** [comment]
The original kcp syncer used to send heartbeating info which was updating the SyncTarget (by default every 60 s). Perhaps SynTarget might be the place for such info?

**Comment by MikeSpreitzer** [comment]
Did anybody look at https://github.com/kubestellar/kubestellar/blob/v0.7.0/pkg/apis/edge/v1alpha1/syncer-config.go#L149 ?

I would recommend having the syncer heartbeat to only one place, and other core controller(s) can relay from there as appropriate. I think the SyncerConfig is the logical place, since it is the focus of the syncer's attention.

**Comment by yana1205** [comment]
Yes, the current Syncer only reads SyncerConfig and doesn't update it. It makes sense that Syncer updates `LastSyncerHeartbeatTime` on regular basis as TMC Syncer does.

**Comment by clubanderson** [comment]
@yana1205 to investigate - Thank you

**Comment by clubanderson** [comment]
reporting this back to the user as a part of the location or edgeplacement status would be good to help customers know when their syncer(s) are offline.  This would save time for folks unaware that this is a condition that could occur
