### ISSUE TITLE
bug: mention of pcluster in output of our Kubestellar-prep-for-cluster

### ISSUE THREAD

**Issue by clubanderson** [kubestellar/kubestellar#1071]
### Describe the bug

output of prep-for-cluster includes pcluster reference

`
Current workspace is "root:example-imw1".
--- current directory is /Users/andan02/projects/MCC/cicd/workloads/odh-operator-edgeplacement
current ws is root:example-imw1
imw is .
current cwsi is root:example-imw1
edge.kubestellar.io apibinding exists in workspace root:example-imw1
synctarget.edge.kubestellar.io/wec6 created
location.edge.kubestellar.io/wec6 created
synctarget.edge.kubestellar.io/wec6 labeled
location.edge.kubestellar.io/wec6 labeled
Current workspace is "root:example-imw1".
Current workspace is "root:espw".
Creating service account "kubestellar-syncer-wec6-2agyzzih"
Creating cluster role "kubestellar-syncer-wec6-2agyzzih" to give service account "kubestellar-syncer-wec6-2agyzzih"

 1. write and sync access to the synctarget "kubestellar-syncer-wec6-2agyzzih"
 2. write access to apiresourceimports.

Creating or updating cluster role binding "kubestellar-syncer-wec6-2agyzzih" to bind service account "kubestellar-syncer-wec6-2agyzzih" to cluster role "kubestellar-syncer-wec6-2agyzzih".

Wrote physical cluster manifest to wec6-syncer.yaml for namespace "kubestellar-syncer-wec6-2agyzzih". Use

  KUBECONFIG=<pcluster-config> kubectl apply -f "wec6-syncer.yaml"

to apply it. Use

  KUBECONFIG=<pcluster-config> kubectl get deployment -n "kubestellar-syncer-wec6-2agyzzih" kubestellar-syncer-wec6-2agyzzih

to verify the syncer pod is running.
Current workspace is "root:example-imw1".
Current workspace is "root".`

### Steps To Reproduce

1. run 'KUBECONFIG=~/ks.config kubectl kubestellar prep-for-cluster --imw root:example-imw1 wec6 env=wec6'
2. observe output

### Expected Behavior

replace 'pcluster' with 'workload execution cluster'

**Comment by MikeSpreitzer** [comment]
The offending text is "physical cluster", right?

**Comment by clubanderson** [comment]
The output of the prep-for-cluster includes the syncer instructions. In the syncer instructions the term "pcluster" is being used. More than once I think.

**Comment by clubanderson** [comment]
I don't see it here. I guess I pasted in the wrong output. But yes, physical cluster is in this output. 

Probably should do a search through the code base and replace all instances of "pcluster" and "physical cluster" at this time.

**Comment by clubanderson** [comment]
here it is

`--- current directory is /Users/andan02/projects/kubestellar/core-helm-chart
current ws is root:imw1
imw is .
current cwsi is root:imw1
edge.kubestellar.io apibinding exists in workspace root:imw1
synctarget.edge.kubestellar.io/wec5-wmw labeled
location.edge.kubestellar.io/wec5-wmw labeled
Current workspace is "root:imw1".
Current workspace is "root:espw".
Creating service account "kubestellar-syncer-wec5-wmw-1tln0c28"
Creating cluster role "kubestellar-syncer-wec5-wmw-1tln0c28" to give service account "kubestellar-syncer-wec5-wmw-1tln0c28"

 1. write and sync access to the synctarget "kubestellar-syncer-wec5-wmw-1tln0c28"
 2. write access to apiresourceimports.

Creating or updating cluster role binding "kubestellar-syncer-wec5-wmw-1tln0c28" to bind service account "kubestellar-syncer-wec5-wmw-1tln0c28" to cluster role "kubestellar-syncer-wec5-wmw-1tln0c28".

Wrote physical cluster manifest to wec5-wmw-syncer.yaml for namespace "kubestellar-syncer-wec5-wmw-1tln0c28". Use

  KUBECONFIG=<pcluster-config> kubectl apply -f "wec5-wmw-syncer.yaml"

to apply it. Use

  KUBECONFIG=<pcluster-config> kubectl get deployment -n "kubestellar-syncer-wec5-wmw-1tln0c28" kubestellar-syncer-wec5-wmw-1tln0c28

to verify the syncer pod is running.
Current workspace is "root:imw1".
Current workspace is "root:imw1".`

**Comment by clubanderson** [comment]
because it was in brackets, gh hid it.  I removed the brackets - you can see the text in the 4 line from the bottom.

**Comment by clubanderson** [comment]
@namasl would you look at this?

**Comment by namasl** [comment]
I take it that "physical cluster" is old terminology for what is now "workload execution cluster"?

**Comment by clubanderson** [comment]
correct @namasl
