### ISSUE TITLE
bug: inability to run 'kubectl get all' in any kubestellar workspace

### ISSUE THREAD

**Issue by clubanderson** [kubestellar/kubestellar#1074]
### Describe the bug

I have to guess which kinds of resources are in which workspaces.  I should be able to run "get all" and get back a list of resources in the current workspace, and even allow -r to allow recursive to show everything in the tree in and below the current workspace.

### Steps To Reproduce

1. kubectl ws root
2. kubectl get all

observe failure to get all objects in a workspace

```KUBECONFIG=~/ks-stage.config kubectl get all   
error: the server doesn't have a resource type "all"
```

### Expected Behavior

I expect to have a way to list all resources in a workspace.  I am blind without this functionality.

**Comment by pdettori** [comment]
I was able to replicate for root and few other workspaces. In a tree like the following:
```
$ k ws tree
.
└── root
    ├── compute
    ├── espw
    │   ├── a6cysmxemjhawr3w-mb-2fd89d20-97d9-444c-ac3f-ce3df34cad5e
    │   └── a6cysmxemjhawr3w-mb-878d8eaf-6ae3-4571-9c72-916b2ff4f8d9
    ├── my-org
    │   ├── wmw-c
    │   └── wmw-s
```
I can actually get `kubectl get all` to work on wmw-c, wmw-s and the 2 workspaces under espw. It looks like it is related to the type of workspace and the API bindings that are applied to that workspace. It seems that this is an intrinsic behavior of kcp, not sure if that can be changed.

**Comment by clubanderson** [comment]
`KUBECONFIG=~/ks.config kubectl ws root:espw:2xkvbgexveffrnrz-mb-fe9d4c4b-cbc8-4be6-8ef9-bba45aa0100b
Current workspace is "root:espw:2xkvbgexveffrnrz-mb-fe9d4c4b-cbc8-4be6-8ef9-bba45aa0100b".
 andan02@Andrews-MacBook-Pro  ~/projects/MCC/cicd/workloads/odh-operator-edgeplacement   main ?  KUBECONFIG=~/ks.config kubectl get all                                        ✔  3698  22:43:55
error: the server doesn't have a resource type "all"
 andan02@Andrews-MacBook-Pro  ~/projects/MCC/cicd/workloads/odh-operator-edgeplacement   main ?  KUBECONFIG=~/ks.config kubectl ws root                                      1 ↵  3699  22:43:57
Current workspace is "root".
 andan02@Andrews-MacBook-Pro  ~/projects/MCC/cicd/workloads/odh-operator-edgeplacement   main ?  KUBECONFIG=~/ks.config kubectl get all                                        ✔  3700  22:44:09
error: the server doesn't have a resource type "all"
 andan02@Andrews-MacBook-Pro  ~/projects/MCC/cicd/workloads/odh-operator-edgeplacement   main ?  KUBECONFIG=~/ks.config kubectl ws root:wec6-wmw                             1 ↵  3701  22:44:11
Current workspace is "root:wec6-wmw".
 andan02@Andrews-MacBook-Pro  ~/projects/MCC/cicd/workloads/odh-operator-edgeplacement   main ?  KUBECONFIG=~/ks.config kubectl get all                                        ✔  3702  22:44:18
No resources found in default namespace.
 andan02@Andrews-MacBook-Pro  ~/projects/MCC/cicd/workloads/odh-operator-edgeplacement   main ?  KUBECONFIG=~/ks.config kubectl ws root:example-imw1                           ✔  3703  22:44:19
Current workspace is "root:example-imw1".
 andan02@Andrews-MacBook-Pro  ~/projects/MCC/cicd/workloads/odh-operator-edgeplacement   main ?  KUBECONFIG=~/ks.config kubectl get all                                        ✔  3704  22:44:32
error: the server doesn't have a resource type "all"`

**Comment by clubanderson** [comment]
and, adding to this, I can run "k get all" on the openshift cluster itself.

```
k get all

NAME                                              READY   STATUS    RESTARTS   AGE
pod/core-thanos-query-77d9bb8dcc-cq8nm            1/1     Running   0          3d12h
pod/core-thanos-query-frontend-7c9bc69875-zqv99   1/1     Running   0          3d12h

NAME                                 TYPE           CLUSTER-IP       EXTERNAL-IP                            PORT(S)                        AGE
service/core-thanos-query            ClusterIP      172.21.132.185   <none>                                 9090/TCP                       3d12h
service/core-thanos-query-frontend   ClusterIP      172.21.213.66    <none>                                 9090/TCP                       3d12h
service/core-thanos-query-grpc       ClusterIP      172.21.247.42    <none>                                 10901/TCP                      3d12h
service/kubelet                      ClusterIP      None             <none>                                 10250/TCP,10255/TCP,4194/TCP   5d17h
service/kubernetes                   ClusterIP      172.21.0.1       <none>                                 443/TCP                        8d
service/openshift                    ExternalName   <none>           kubernetes.default.svc.cluster.local   <none>                         7d11h
service/openshift-apiserver          ClusterIP      172.21.189.80    <none>                                 443/TCP                        8d
service/openshift-oauth-apiserver    ClusterIP      172.21.40.18     <none>                                 443/TCP                        8d

NAME                                         READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/core-thanos-query            1/1     1            1           3d12h
deployment.apps/core-thanos-query-frontend   1/1     1            1           3d12h

NAME                                                    DESIRED   CURRENT   READY   AGE
replicaset.apps/core-thanos-query-77d9bb8dcc            1         1         1       3d12h
replicaset.apps/core-thanos-query-frontend-7c9bc69875   1         1         1       3d12h
```

**Comment by clubanderson** [comment]
after clearing the cache I am now able to see "all" in a ns on WMW.  I still am unable to 'get all' on an MB, root, and IMW

```
KUBECONFIG=~/ks.config kubectl ws root:wec6-wmw                
Current workspace is "root:wec6-wmw".

KUBECONFIG=~/ks.config kubectl get all                                   
No resources found in default namespace.

KUBECONFIG=~/ks.config kubectl get ns                                   
NAME                         STATUS   AGE
data-science                 Active   22h
default                      Active   3d11h
kuberay-operator             Active   3d
mcad                         Active   23h
opendatahub                  Active   23h
openshift-operators          Active   23h
openshift-operators-redhat   Active   23h

KUBECONFIG=~/ks.config kubectl get all -n data-science                   
No resources found in data-science namespace.

KUBECONFIG=~/ks.config kubectl get all -n kuberay-operator               
NAME                       TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)    AGE
service/kuberay-operator   ClusterIP   <none>       <none>        8080/TCP   23h

NAME                               READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/kuberay-operator   0/1     0            0           23h

KUBECONFIG=~/ks.config kubectl ws root:example-imw1                    
Current workspace is "root:example-imw1".

KUBECONFIG=~/ks.config kubectl get all                                    
error: the server doesn't have a resource type "all"

KUBECONFIG=~/ks.config kubectl ws root:espw:2xkvbgexveffrnrz-mb-fe9d4c4b-cbc8-4be6-8ef9-bba45aa0100b
Current workspace is "root:espw:2xkvbgexveffrnrz-mb-fe9d4c4b-cbc8-4be6-8ef9-bba45aa0100b".

KUBECONFIG=~/ks.config kubectl get all                                    
error: the server doesn't have a resource type "all"

KUBECONFIG=~/ks.config kubectl ws root                               
Current workspace is "root".

KUBECONFIG=~/ks.config kubectl get all                                   
error: the server doesn't have a resource type "all"
```

**Comment by clubanderson** [comment]
@dumb0002 can you try this out with your plugin set against kscore-prod

**Comment by MikeSpreitzer** [comment]
Remember that "all" is from a concept called "categories". Look in https://v1-24.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.24/#customresourcedefinitionnames-v1-apiextensions-k8s-io , you can see that a CRD can put a resource into a set of "categories". It is traditional to put most resources in the "all" category, but that is only a convention and it is not always followed. For our own definitions, we use the usual funky golang-based IDL with markup described in https://book.kubebuilder.io/reference/markers/crd.html ; look at the doc on `// +kubebuilder:resource` and its `categories` option. As you can see below, none of our current definitions exercises this option.

```
mspreitz@mjs13 kubestellar % grep kubebuilder:resource pkg/apis/edge/v1alpha1/*.go
pkg/apis/edge/v1alpha1/edge-placement.go:// +kubebuilder:resource:scope=Cluster,shortName=epl
pkg/apis/edge/v1alpha1/edge-syncconfig.go:// +kubebuilder:resource:scope=Cluster,shortName=esc
pkg/apis/edge/v1alpha1/single-placement.go:// +kubebuilder:resource:scope=Cluster,shortName=sps,path=singleplacementslices
pkg/apis/edge/v1alpha1/syncer-config.go:// +kubebuilder:resource:scope=Cluster,shortName=escfg
pkg/apis/edge/v1alpha1/synctarget_types.go:// +kubebuilder:resource:scope=Cluster
pkg/apis/edge/v1alpha1/types_location.go:// +kubebuilder:resource:scope=Cluster
```

**Comment by clubanderson** [comment]
Going to close this as I am working on a utility that lists the objects in supported api-resources rather than relying on get all.
