### ISSUE TITLE
feature: automatic configuration of nonnamespaced apigroup, resources, and names based on the resources in a wmw

### ISSUE THREAD

**Issue by clubanderson** [kubestellar/kubestellar#1080]
### Feature Description

Why are we making our customers indicate the nonNameSpacedObjects they need to support their workloads, when the information is in the resources that are in the wmw?

### Proposed Solution

remove the need for users to handcraft the nonNameSpacedObjects in the edgeplacement.  Either remove this section in the spec or create it automatically for them.

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by pdettori** [comment]
Are there use cases where there are resources that may exist in the WMW that should not be delivered to the WECs ?

**Comment by ezrasilvera** [comment]
@clubanderson How do you suggest we decide which resources are downsynced? How do we decide today which cluster-wide-resources we downsync ?

**Comment by MikeSpreitzer** [comment]
@clubanderson, just to make sure I understand: the suggestion here is that users should be unable to configure which cluster-scoped objects are downsynced, instead every EdgePlacement object implicitly selects all cluster-scoped objects? If so, that seems a bit blunt to me. Convenient in some cases, but blunt. For one example, note that the KubeStellar control objects are cluster-scoped, but they do not make sense to downsync. There are also the APIBinding objects that are needed to even make the KubeStellar API available. Perhaps the suggestion is that every EdgePlacement object implicitly selects all cluster-scoped objects except the KubeStellar control objects and the APIBinding objects? I suspect that the list of desired exceptions will not end there. Switching to kube-bind will add other control objects, for one example. Remember that we also have an open issue for how to deal with RedHat-style operators; that may add additional control or other sorts of infrastructure cluster-scoped objects that should not be downsynced. Would you settle instead for an explicit list of APIGroups with no more details per APIGroup?

**Comment by clubanderson** [comment]
I am not implying that all clusterscoped resources in a cluster should be downsynced.  What I am saying is that it is easy to identify which clusterscoped resources are required by a workload.  Once identified, those resources, resourcenames, apigroups should be automatically added to the spec for edgeplacement.  We should not require an operator to iteratively guess at what clusterscoped resources they need in their MB.  And, to add to this, the clusterscoped resources likely already exist at the synctarget, so the only reason why they are needed in the MB is so that the workload can be applied there.  So the cluster-scoped objects are just transitory and are (likely) not needed at the target.  So that is even more the reason for not asking the operator to do the work manually.

**Comment by clubanderson** [comment]
we know which resources are being synced from a wmw to an MB, therefore we can also detect which clusterscoped objects are necessary to support them.  If there are additional clusterscoped objects that the operator wants to specify, then they can do so, but we should take care of the base requirements to get the workload applied.

**Comment by clubanderson** [comment]
when you attempt to apply a resource into an MB you either succeed or fail.  If you fail, you get a response that indicates the API that is missing.  You simply catch that and incorporate it automatically.

**Comment by clubanderson** [comment]
We are failing to deploy resources because the clusterscoped resources the workload depends on are missing.  We should detect and automatically add those resources to the MB so that there is no need for the user to do so

**Comment by ezrasilvera** [comment]
The "fail and then downsync" is an interesting approach, I'm not sure I would go with that for production at this point. I think we need something more decisive/controlled.  E.g., You may get other failure reasons ...

**Comment by ezrasilvera** [comment]
Also note that the fail is on the WEC, I think we want to minimize the failures on the WEC even if it's "by design" , e.g., it can mess up logs, error alerts, etc.

**Comment by clubanderson** [comment]
no, the failure is in MB.  You stage (apply) your workload to a WDS/WMW.  The MB gets the workload you intend it to have by joining the namespaceSelector and locationSelector from the edgeplacement.  So you know what and where.  The MB represents/contains the staged resources you want synced - it's the manifestation of that join.  As soon as the workload goes to the MB it either applies or fails to apply.  You know, at that exact moment, which clusterscoped resource you are missing and you can then adjust the edgeplacement (automatically) to include them.  If we do this, then we are at par with ArgoCD in the sense that you define the edgeplacement, submit your workload, and it is synchronized to the WEC, no questions asked of the operator.  Just make sure to label the namespace - which is something you can do automatically with ArgoCD or by hand.

**Comment by clubanderson** [comment]
the need to adjust the nonNamespacedObjects each time I adjust my workload or add a new one, is a thorough pain.

**Comment by MikeSpreitzer** [comment]
>  If you fail, you get a response that indicates the API that is missing

That is exactly about CustomResourceDefinitions. My take on #1064 will pro-actively prevent those errors.

**Comment by clubanderson** [comment]
yes, that will get you to the point where you have the proper CRD exposed.  Do you just wildcard all CRD resourceNames?  That seems like too much.

In ClusterScoped, the automatic inclusion of the CRD resource is great, this is helpful.  What do we do about namespaced CRDs?  I am having to find and include the CRD definition for the specific resource alongside the edgeplacement each time.

**Comment by MikeSpreitzer** [comment]
Let's follow up specifically about #1064 in that issue. I think you will see there that the idea is about implicitly downsyncing the CRDs that define the kinds of the objects that match the explicit criteria. Every CRD object is cluster-scoped; the resource that is _defined by_ that object may be namespaced or cluster-scoped. The objects matched by explicit criteria may be namespaced or cluster-scoped. The idea there is not about having a controller modify the EdgePlacement objects, it is about adjusting the interpretation of them.

**Comment by clubanderson** [comment]
my point is, as easy as it is to apply workloads to a namespace using kubectl, it should be just as easy to apply workloads to a wmw, and it should be just as easy to synchronize to an MB.  We have to make this easier.  I will refrain from making suggestions anymore.  Let's just use the criteria of ease-of-use.  Our users should not have to remember a ton of commands and places to look to ensure their workload is getting to the syncer.  How we get there, I will leave to you to refine what we have to get to that place.

**Comment by clubanderson** [comment]
controllers in the center can discern what other objects can be included (see #1064).
