### ISSUE TITLE
bug: placement translator failure

### ISSUE THREAD

**Issue by clubanderson** [kubestellar/kubestellar#1081]
### Describe the bug

IiwgInVzZXJuYW1lIjogImlhbWFwaWtleSIsICJlbWFpbCI6ICJpYW1hcGlrZXkiLCAicGFzc3dvcmQiOiAiTXduOW5vRjZJRFJFb1lpTHlvbGUyMTRMNWhKbmJCaFdTNUhvWkx5bGFDREEifX19"},"kind":"Secret","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"kubestellar-wec6-odh-operator","odh":"sync"},"name":"prod-all-icr-io","namespace":"data-science"},"type":"kubernetes.io/dockerconfigjson"}
 >
I1003 23:40:20.943272    1996 workload-projector.go:1084] "Overwriting key/val" sourceCluster="24cddnmyacru1w74" destSP={Cluster:2xkvbgexveffrnrz LocationName:wec6 SyncTargetName:wec6 SyncTargetUID:fe9d4c4b-cbc8-4be6-8ef9-bba45aa0100b} destGVK=0x1a6e4a0 namespace="data-science" name="prod-all-icr-io" which="labels" key="app.kubernetes.io/instance" oldVal="kubestellar-wec5-odh-operator" newVal="kubestellar-wec6-odh-operator"
I1003 23:40:21.141830    1996 workload-projector.go:1084] "Overwriting key/val" sourceCluster="24cddnmyacru1w74" destSP={Cluster:2xkvbgexveffrnrz LocationName:wec6 SyncTargetName:wec6 SyncTargetUID:fe9d4c4b-cbc8-4be6-8ef9-bba45aa0100b} destGVK=0x1a6e4a0 namespace="data-science" name="cos-access" which="annotations" key="kubectl.kubernetes.io/last-applied-configuration" oldVal=<
	{"apiVersion":"v1","data":{"cos-endpoint":"aHR0cHM6Ly9zMy51cy1lYXN0LmNsb3VkLW9iamVjdC1zdG9yYWdlLmFwcGRvbWFpbi5jbG91ZA==","cos-key":"NmI4MjYzMWNiZjM2NGM2ODg1MDE2YjU5MTdkMWU5NmI=","cos-secret":"NDlhNGVmODk1ZDlkYWI1YjdmMTJmNzNlZDRlZTM2OWU3YTJlMzRhNTE1YTc4MTdm"},"kind":"Secret","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"kubestellar-wec5-odh-operator","odh":"sync"},"name":"cos-access","namespace":"data-science"},"type":"Opaque"}
 > newVal=<
	{"apiVersion":"v1","data":{"cos-endpoint":"aHR0cHM6Ly9zMy51cy1lYXN0LmNsb3VkLW9iamVjdC1zdG9yYWdlLmFwcGRvbWFpbi5jbG91ZA==","cos-key":"NmI4MjYzMWNiZjM2NGM2ODg1MDE2YjU5MTdkMWU5NmI=","cos-secret":"NDlhNGVmODk1ZDlkYWI1YjdmMTJmNzNlZDRlZTM2OWU3YTJlMzRhNTE1YTc4MTdm"},"kind":"Secret","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"kubestellar-wec6-odh-operator","odh":"sync"},"name":"cos-access","namespace":"data-science"},"type":"Opaque"}
 >
I1003 23:40:21.141956    1996 workload-projector.go:1084] "Overwriting key/val" sourceCluster="24cddnmyacru1w74" destSP={Cluster:2xkvbgexveffrnrz LocationName:wec6 SyncTargetName:wec6 SyncTargetUID:fe9d4c4b-cbc8-4be6-8ef9-bba45aa0100b} destGVK=0x1a6e4a0 namespace="data-science" name="cos-access" which="labels" key="app.kubernetes.io/instance" oldVal="kubestellar-wec5-odh-operator" newVal="kubestellar-wec6-odh-operator"
I1003 23:40:21.941973    1996 workload-projector.go:1084] "Overwriting key/val" sourceCluster="24cddnmyacru1w74" destSP={Cluster:2xkvbgexveffrnrz LocationName:wec6 SyncTargetName:wec6 SyncTargetUID:fe9d4c4b-cbc8-4be6-8ef9-bba45aa0100b} destGVK=0x1a6e4a0 namespace="kuberay-operator" name="kuberay-operator" which="labels" key="app.kubernetes.io/instance" oldVal="kubestellar-wec5-kuberay-operator" newVal="kubestellar-wec6-kuberay-operator"
E1003 23:40:22.141181    1996 workload-projector.go:1021] "Failed to create object in mailbox workspace" err="the server could not find the requested resource" worker=1 objectRef={cluster:24cddnmyacru1w74 groupResource:{Group:kfdef.apps.kubeflow.org Resource:kfdefs} namespace:opendatahub name:odh-core} destination={Cluster:2xkvbgexveffrnrz LocationName:wec6 SyncTargetName:wec6 SyncTargetUID:fe9d4c4b-cbc8-4be6-8ef9-bba45aa0100b}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1907ea6]

goroutine 252 [running]:
k8s.io/apimachinery/pkg/apis/meta/v1/unstructured.(*Unstructured).GetResourceVersion(...)
	/Users/andan02/go/pkg/mod/github.com/kcp-dev/kubernetes/staging/src/k8s.io/apimachinery@v0.0.0-20230210192259-aaa28aa88b2d/pkg/apis/meta/v1/unstructured/unstructured.go:282
github.com/kubestellar/kubestellar/pkg/placement.(*workloadProjector).syncSourceToDestLocked.func1()
	/Users/andan02/projects/main/kubestellar/pkg/placement/workload-projector.go:1006 +0x8a6
github.com/kubestellar/kubestellar/pkg/placement.(*workloadProjector).syncSourceObject(0x10?, {0x251e078, 0xc0023580f0}, {{0xc0028de780, 0x10}, {{0x0, 0x0}, {0xc003410180, 0x8}}, {0xc000b43c40, ...}, ...})
	/Users/andan02/projects/main/kubestellar/pkg/placement/workload-projector.go:915 +0x21b
github.com/kubestellar/kubestellar/pkg/placement.(*workloadProjector).sync1Config(0xc00040c400, {0x251e078, 0xc0023580f0}, {0x1f29020?, 0xc004559c20?})
	/Users/andan02/projects/main/kubestellar/pkg/placement/workload-projector.go:667 +0x3d0
github.com/kubestellar/kubestellar/pkg/placement.(*workloadProjector).configSyncLoop(0xc00040c400, {0x251e078, 0xc00019af60}, 0x0?)
	/Users/andan02/projects/main/kubestellar/pkg/placement/workload-projector.go:651 +0x214
created by github.com/kubestellar/kubestellar/pkg/placement.(*workloadProjector).Run
	/Users/andan02/projects/main/kubestellar/pkg/placement/workload-projector.go:629 +0x47

### Steps To Reproduce

1. run kubestellar

### Expected Behavior

placement translator should not tip over. hopefully this goes away when it is in a replicataset

**Comment by MikeSpreitzer** [comment]
This looks like a duplicate of #1076 , which at the moment has been fixed in `main` but not in `release-0.7`.

**Comment by clubanderson** [comment]
likely dupe of #1076 - closing for now.
