### ISSUE TITLE
feature: ability to select namespaces by names rather than label selector

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#1084]
### Feature Description

In some use cases some workload objects --- and `Namespace` objects _are_ objects --- are authored by a third party (not the KS user). Requiring the KS user to add labels to these objects is problematic (not necessarily insoluble, but more trouble than we want to require for users). One example of this is in https://github.com/kubestellar/kubestellar/blob/a60700c53c83270394c804bc4e7ea6dd9d6be5e9/pkg/apis/edge/v1alpha1/edge-placement.go#L107-L111 , which says that the _only_ way that users can filter on namespace is by using a label selector on the namespace's labels. There should be a way to filter based on the namespace's name.

### Proposed Solution

Add a field that holds a list of strings, each of which is a dead-simple pattern (i.e., `*` can match any substring, all other characters are literals) for matching namespace names. A namespace matches the whole DownsyncObjectTest if it matches either the new field or the old list of label selectors.

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by clubanderson** [comment]
I like this idea and I like that wildcard is supported.  Would there be a need for REGEX in the string?

**Comment by MikeSpreitzer** [comment]
I am looking for feedback from users on the expressiveness needed.
I would caution that going to full regex has two potential problems: (1) _which_ kind of regex do you want? (go has its, python has its, gnu has its, ...); (2) all of them are pretty powerful programming languages, I would not be surprised if vulnerabilities are discovered in the future.

I am wondering this:
- list, or single, or both?
- literal, simple pattern (how simple?), full regex (which kind of regex)?

**Comment by clubanderson** [comment]
I think a simple list is good enough for now.  I usually have 1 and as many as 3 or 4 namespaces I have to include.  I am happy to take a simple list of 0 or more.  That would be good enough
