### ISSUE TITLE
feature: create helm chart for space framework

### ISSUE THREAD

**Issue by effi-ofer** [kubestellar/kubestellar#1086]
### Feature Description

Create a helm for installing the space framework abstraction layer

### Proposed Solution

Create helm chart

### Want to contribute?

- [X] I would like to work on this issue.

**Comment by clubanderson** [comment]
@francostellari can you help here to get us closer to decoupling?

**Comment by ezrasilvera** [comment]
Replaced with https://github.com/kubestellar/kubestellar/issues/1215
