### ISSUE TITLE
bug: Need way to better config dns servers/search for WEC

### ISSUE THREAD

**Issue by KPRoche** [kubestellar/kubestellar#1087]
### Describe the bug

I had a stubborn bug where a Raspberry Pi with a static IP address on a wired lan (eth0) could successfully ping the cluster running my Kubestellar core (on the same network), but every time I deployed a WEC on that pi, nslookup inside the WEC failed.

The problem turned out to be that WiFi was enabled on the pi, it was connected to an SSID but not authenticated to that network, and NetworkManager kept overwriting the host /etc/resolv.conf with a line that set search to that network.

When I launched my WEC with KIND, that search server was added to the internal resolv.conf on the cluster, so it never got to the host DNS servers and couldn't find my core cluster.

Disabling WiFI on the Pi eliminated that search line in the file, and a WEC deployed after that point was able to reach the core cluster.

### Steps To Reproduce

1. Connect raspberry Pi to wired lan
2. let rPi also connect to a local wifi but do not authenticate
3. launch WEC (like florin in the example)
4. launch kubestellar syncer in the WEC
5. the WEC will fail to reach the kubestellar core defined in yaml for that syncer

### Expected Behavior

The DNS setup process during cluster creation is rather opaque.

Perhaps being able to pass in the ip address as well as the hostname (FQDN) of the ks-core cluster might help?

**Comment by clubanderson** [comment]
@KPRoche is this still an issue for you/us?

**Comment by KPRoche** [comment]
I think this is just one specific example of the subtleties of how DNS issues can have block the functionality of kubestellar (see  #1192 for another one). A generally robust way to ensure connections can be made, or even a connection test to check things early in the configuration/deployment process is needed. Perhaps we should collect them into one issue as examples of how things can go wrong? Or make it a chapter of our troubleshooting.

**Comment by clubanderson** [comment]
ok - maybe merge this info into your troubleshooting issue and close this so it isn't dangling?

**Comment by KPRoche** [comment]
I have transcribed this into a troubleshooting document and am closing the issue.
