### ISSUE TITLE
bug: shortcut on the webpage to edit the docs does not use the branch 

### ISSUE THREAD

**Issue by dumb0002** [kubestellar/kubestellar#1093]
### Describe the bug

The shortcut on the webpage to edit the docs only points to the main branch

### Steps To Reproduce

Edit the KS docs for a release using the shortcut on the webpage 

### Expected Behavior

The shortcut on the webpage to edit the docs should point to the branch associated with the release # of the page.

**Comment by clubanderson** [comment]
fixed - thank you for reporting this
