### ISSUE TITLE
feature: need a way to deploy 1000's of syncers automatically

### ISSUE THREAD

**Issue by clubanderson** [kubestellar/kubestellar#1096]
### Feature Description

managing the creation of a config and deploying it to remote clusters is going to be painful.  Is there a better way to create AND deploy 100's (or more) syncers.

### Proposed Solution

I don't know, but we should try to figure this out.

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by clubanderson** [comment]
@yana1205 a good use of your time would be to figure out how we can take a lubeconfig context and use it to automatically create and deploy a syncer and connect it to kubestellar. I want to remove the need for us to do more then get the WECs kubeconfig.  I don't want to do a login and then a deploy. I want those steps combined somehow. We might even figure out a way to do "get-external-config" from a regular kubernetes cluster (OpenShift or otherwise) using some sort of http oidc/sso from the command line. Similar to how ibm cloud does this to allow login to a remote endpoint without needing to do anything on a browser. 

Take, for example, ArgoCD. They have a command "ArgoCD cluster add" which takes as a parameter the name of a kubeconfig and the name of the context in that kubefconfig and then automatically deploys the ArgoCD agent and from that point on you just deploy your work. I'd like us to have something similar or better. Maybe the tool can take values or be interactive and allow you to select a kubeconfig from a list of existing ones found on your laptop, then select a context (or a list of contexts, and then deploy the syncer to those. 

In fact, we should allow a list of kubeconfig/context pairs as input (maybe in a yaml file or from a command line) that then installs the syncer to those locations. 

@yana1205 what do you think?

**Comment by clubanderson** [comment]
Maybe we plan ahead to have this feature work with the location creation feature in kubestellar such that if a location is created, and we have the kubeconfig available, we create the location, the synctarget, the syncconfig and we automatically deploy the syncer. As we add more syncers we do not want to manage them by hand. We have to create, update, delete, sync, upgrade in an efficient way. Just more thoughts to influence your initial design so that we can make incremental progress. Not everything is needed all at once, but we should not make it hard to enhance after the first revision.

**Comment by yuji-watanabe-jp** [comment]
@yana1205 will look into this and prepare some automation. @clubanderson

**Comment by clubanderson** [comment]
@dumb0002 this coincides with your MCC Stress Testing effort.  As you get closer to hardening the stack, you will need to make sure we can deploy to many 1000's of WECs.  Please work with @yana1205 to figure out a strategy to automate/streamline the distribution of many syncers across an estate.

**Comment by clubanderson** [comment]
@francostellari @ezrasilvera @pdettori @MikeSpreitzer can you weigh in on some possible approaches.
