### ISSUE TITLE
`kubectl kubestellar get-log` is obsolete

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#1097]
The helm chart change (#1077, now merged) made the old way of getting controller and kcp server logs obsolete. We should not try to maintain our own bespoke CLI for getting logs; we made a deliberate move to be more ordinary, now the important logs appear as container logs in the core Pod. The obsolete log-fetching CLI (implementation and documentation) should be deleted. This begs for documentation about observability (the core pod offers both logs and Prometheus metrics).

**Comment by MikeSpreitzer** [comment]
@francostellari 
@clubanderson 
@dumb0002 
@cwiklik

**Comment by clubanderson** [comment]
That's awesome. Does this mean I can close that PR?

**Comment by clubanderson** [comment]
I closed the PR #912 that I created as part of completing the needful for this issue

**Comment by clubanderson** [comment]
@MikeSpreitzer please advise on what else remains and let @namasl know about it.  He is taking over the kubectl plugin clientgo conversion work from me.

**Comment by MikeSpreitzer** [comment]
What @clubanderson deleted was a PR that adds an alternative to the plugin that is already there. What remains is to delete the plugin that is already there, delete the documentation for how to use that plugin, and write the documentation for what to do instead.

**Comment by clubanderson** [comment]
@MikeSpreitzer please review to see if this can be closed

**Comment by MikeSpreitzer** [comment]
The title and leading subject matter is moot now.
Someone should open fresh issue(s) about observability.
