### ISSUE TITLE
Thanos expects rough play

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#1102]
Thanos creates a ConfigMap named `user-workload-monitoring-config` in the namespace `openshift-user-workload-monitoring` and expects users to modify it. The syncer avoids modifying it because that object lacks the annotation that the syncer uses to mark objects managed by the syncer. The syncer is trying to play too nicely.

**Comment by clubanderson** [comment]
@MikeSpreitzer is this issue closed as a matter of #1103 and #1105 merging?  Is there more to do?

**Comment by MikeSpreitzer** [comment]
Implemented by #1103 and #1105

**Comment by clubanderson** [comment]
Reopening to allow for a test first with upcoming release.

**Comment by clubanderson** [comment]
we are now using customization to achieve the post-edit.
