### ISSUE TITLE
bug: in latest helm, that uses source from main branch, unable to create a MB because it expects v1alpha1 version of kubestellar api - we are now at v2alpha1 in main

### ISSUE THREAD

**Issue by clubanderson** [kubestellar/kubestellar#1109]
### Describe the bug

```
KUBECONFIG=~/mcc-kscore-stage.config kubectl kubestellar ensure location wec7-wmw loc-name=wec7-wmw env=prod            
--- current directory is /
current ws is root:imw1
imw is .
current cwsi is root:imw1
edge.kubestellar.io apibinding exists in workspace root:imw1
error: resource mapping not found for name: "wec7-wmw" namespace: "" from "STDIN": no matches for kind "SyncTarget" in version "edge.kubestellar.io/v1alpha1"
ensure CRDs are installed first
/opt/homebrew/bin/kubestellar/bin/kubectl-kubestellar-ensure-location: Creation of SyncTarget failed
```

### Steps To Reproduce

1. install latest helm chart for kubestellar
2. imw1, wec7-wmw, and wec8-wmw were created by helm automatically as input to chart via values.yml
3. KUBECONFIG=~/mcc-kscore-stage.config kubectl ws tree                                                         
```
.
└── root
    ├── compute
    ├── espw
    ├── imw1
    ├── wec7-wmw
    └── wec8-wmw
```
4. KUBECONFIG=~/mcc-kscore-stage.config kubectl kubestellar ensure location wec7-wmw loc-name=wec7-wmw env=prod            
```
--- current directory is /
current ws is root:imw1
imw is .
current cwsi is root:imw1
edge.kubestellar.io apibinding exists in workspace root:imw1
error: resource mapping not found for name: "wec7-wmw" namespace: "" from "STDIN": no matches for kind "SyncTarget" in version "edge.kubestellar.io/v1alpha1"
ensure CRDs are installed first
/opt/homebrew/bin/kubestellar/bin/kubectl-kubestellar-ensure-location: Creation of SyncTarget failed

```

### Expected Behavior

I expect to be able to create a MB for an existing WMW and then to create a syncer to deploy to the WECs

**Comment by MikeSpreitzer** [comment]
This suggests version mismatches. Progress on this requires knowing the versions involved. The branch named `main` is a variable that refers to different commits over time. Instantiating a Helm chart (sometimes called "creating a release" in Helm jargon, but only sometimes) involves saying what value to use for each of the chart's parameters. This chart's parameters are listed in https://github.com/kubestellar/kubestellar/blob/main/core-helm-chart/values.yaml , along with their default values. What did you use for the `image.repository` and `image.tag` parameters? An image tag is also a pointer that can vary over time. What image is actually being used? An unambiguous answer would include the SHA256 digest. If you could use `kubectl exec` to execute `kubestellar-version` in any of the containers then that would also give version information. What version of the kubestellar plugins are you using? `kubestellar-version` in your shell would give information on that.

The error message suggests that you are using release-0.7 plugins against a recent core.

**Comment by clubanderson** [comment]
on mcc-kscore-stage the output of Kubestellar-version is:

`{"major":"1","minor":"24","gitVersion":"v1.24.3+kcp-v0.7.0","gitCommit":"c09408c2","gitTreeState":"dirty","buildDate":"2023-08-30T13:48:46Z","goVersion":"go1.19.12","compiler":"gc","platform":"darwin/arm64"}`

helm values:
<img width="1238" alt="Screenshot 2023-10-10 at 8 57 24 AM" src="https://github.com/kubestellar/kubestellar/assets/407614/84f47a8b-4738-4bf3-a60d-74ef8deb3310">

**Comment by francostellari** [comment]
@clubanderson while I did not fully understand the versioning issue above I would like to clarify the following compatibility issue:

Old helm chart (aka --version < 1) is compatible with all and only ks containers v0.4.0, v0.6.0, v0.7.0 but NOT main-mc
New helm chart (aka --version == 1) is compatible ONLY with ks image main-mc (at the moment) and NOT any other version (including stable or latest)

**Comment by MikeSpreitzer** [comment]
@clubanderson : I think he said that and more. He said that the new Helm chart has to be used with a recent core image (which your display of chart parameters shows you did).
