### ISSUE TITLE
No way to easily tell which MB is associated with which WDS(s)

### ISSUE THREAD

**Issue by clubanderson** [kubestellar/kubestellar#1118]
### Feature Description

I am frustrated when I look at a ws tree output and can’t tell which alphanumeric MB listing is associated with which WDS. 

I have to write down which MB goes to which cluster. Adds to the cognitive load. 

Wec5 - root:espw:ty2tudato80j5zjy-mb-9774bdbc-46c3-495f-a1b9-9ddd6199aefc
Wec6 - root:espw:ty2tudato80j5zjy-mb-199d9ec8-eb94-43e1-81ac-9847bdee8056

### Proposed Solution

We can use something other than alphanumerics. We could use a given name at MB creation time. We could also use a unique name like those assigned randomly to docker containers. Anything that is human readable is better than what we have now. And anything that can be easily associated with a WDS is even better than that. 

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by MikeSpreitzer** [comment]
The mailbox workspaces are an internal detail, not designed for users to deal with or even see.

The last part of the https://docs.kubestellar.io/main/Coding%20Milestones/PoC2023q1/example1/#the-mailbox-controller section shows contributors how to relate mailbox workspaces with Locations. Following are two commands from there.

The following command gets you a listing of all.

```
kubectl get Workspace -o "custom-columns=NAME:.metadata.name,SYNCTARGET:.metadata.annotations['edge\.kubestellar\.io/sync-target-name'],CLUSTER:.spec.cluster"
```

The following command looks up the MBWS for a particular Location (guilder).

```
GUILDER_WS=$(kubectl get Workspace -o json | jq -r '.items | .[] | .metadata | select(.annotations ["edge.kubestellar.io/sync-target-name"] == "guilder") | .name')
```

**Comment by clubanderson** [comment]
@ezrasilvera @MikeSpreitzer do you have ideas on how to make this more human-readable?

**Comment by clubanderson** [comment]
you must execute the following from the 'root' workspace.

`
kubectl ws root
kubectl get Workspace -o "custom-columns=NAME:.metadata.name,SYNCTARGET:.metadata.annotations['edge\.kubestellar\.io/sync-target-name'],CLUSTER:.spec.cluster"
`

**Comment by MikeSpreitzer** [comment]
We could address this along with 1193 by putting the desired information in a label.
