### ISSUE TITLE
bug: KubeStellar external.kubeconfig is invalidated upon restating KCP pod/container

### ISSUE THREAD

**Issue by francostellari** [kubestellar/kubestellar#1120]
### Describe the bug

If the KCP pod/container is restarted, a client external.kubeconfig previously obtained from `kubestellar` secret will  not be valid anymore, and will need to be retrieved again from the updated `kubestellar` secret.

This is an important limitation because a client may not know when/if kcp was restarted.

Fundamentally, this issue is related to a design behavior of kcp, which, upon restart, changes/update the Kubernetes user bearer token in the kubeconfig.

The solution is to create a new user with the right privileges that uses the certificates that we maintain.

### Steps To Reproduce

1. Deploy kubestellar with helm chart --version1
2. Wait for Kubestellar to be ready
3. Retrieve the external.kubeconfig from `kubestellar` secret
4. Verify from the host OS that there is communication, for example with `kubectl ws tree`
5. Delete the KubeStellar pod
6. Wait for Kubestellar to be ready
7. Verify from the host OS that there is a failing communication to kcp, for example with `kubectl ws tree` ==> FAIL
8. Retrieve the new external.kubeconfig from `kubestellar` secret
9. Verify from the host OS that there is communication, for example with `kubectl ws tree`

### Expected Behavior

Deleting/restarting the pod should not invalidate the external.kubeconfig

**Comment by MikeSpreitzer** [comment]
The problem is even more general, not limited to "external". The problem is that we have chosen to make the KubeStellar controllers and other clients use kubeconfig "contexts" that involve the user named "kcp-admin" and that user's credential is a bearer token that is only good for one run of the kcp server --- restarting the kcp server causes a new bearer token to be generated and the server does not accept any other (e.g., older).

**Comment by clubanderson** [comment]
will tackle with SF in December

**Comment by MikeSpreitzer** [comment]
A hopeful clue: in kcp v0.11.0, the user named "shard-admin" is able to create workspaces.

```
bash-3.2$ kubectl --user shard-admin create -f -
apiVersion: tenancy.kcp.io/v1alpha1
kind: Workspace
metadata:
  name: fubarz
workspace.tenancy.kcp.io/fubarz created
```

**Comment by MikeSpreitzer** [comment]
I fear the space framework also has the kcp-admin fragility. While having other trouble with user-quickstart-test, I looked at the Secret named `kcpsec` (which I think the space-manager reads to get the credentials it uses as a client of kcp) in the `kubestellar` namespace in the hosting cluster. That Secret has a `data.kubeconfig` containing the base64 encoding of a kubeconfig that says

```
...
contexts:
...
- context:
    cluster: workspace.kcp.io/current
    user: kcp-admin
  name: workspace.kcp.io/current
...
current-context: workspace.kcp.io/current
...
```
