### ISSUE TITLE
bug: Replicas on each edge cannot be different

### ISSUE THREAD

**Issue by kapilagrawal95** [kubestellar/kubestellar#1123]
### Describe the bug

Not sure if this is a bug but was wondering if this is the right design choice. **Scenario:** I followed the tutorial by creating a workspace, spawning two clusters and deploying a common workload on both the clusters. When I logged in, in one of the clusters I tried to increase the replicas to 2. But this was reversed by the syncer. The kcp has too much power on the edge. Shouldn’t this be reversed?

### Steps To Reproduce

Follow tutorial as mentioned here: https://docs.kubestellar.io/release-0.7/Getting-Started/quickstart/

Except in step of deploying commonstuff (shown below):

```kubectl apply -f - <<EOF
apiVersion: v1
kind: Namespace
metadata:
  name: commonstuff
  labels: {common: "si"}
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: commonstuff
  name: httpd-htdocs
data:
  index.html: |
    <!DOCTYPE html>
    <html>
      <body>
        This is a common web site.
      </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: commonstuff
  name: commond
spec:
  selector: {matchLabels: {app: common} }
  template:
    metadata:
      labels: {app: common}
    spec:
      containers:
      - name: httpd
        image: library/httpd:2.4
        **replicas: 1**
        ports:
        - name: http
          containerPort: 80
          hostPort: 8081
          protocol: TCP
        volumeMounts:
        - name: htdocs
          readOnly: true
          mountPath: /usr/local/apache2/htdocs
      volumes:
      - name: htdocs
        configMap:
          name: httpd-htdocs
          optional: false
EOF
```

Added a replicas line (enclosed as ** in the above code snippet)

After finishing deploying commonstuff, in just the florin cluster, scaled replicas to 3 using the following:

```kubectl --context kind-florin scale deployment commond --replicas=3 -n commonstuff```

However, got this:

<img width="468" alt="image" src="https://github.com/kubestellar/kubestellar/assets/12952642/68e7225d-57c4-4038-9981-351dcfb0c287">

### Expected Behavior

Expecting to scale replicas to 3 just for florin cluster. Guilder should still continue to run at 3.

### Additional Context

Is this a design choice? In practice, shouldn't each edge operator have the power to scale replicas up/down depending on their usage?

**Comment by clubanderson** [comment]
Yes. We recently noticed this also and fixed it. Check out https://github.com/kubestellar/kubestellar/issues/1099. Release 0.8 will have this feature. Release will be out next week. Thank you for trying us out. Keep the feedback coming.

**Comment by kapilagrawal95** [comment]
Thanks! I will wait for Release 0.8.

Closing this for now.

**Comment by MikeSpreitzer** [comment]
The opening comment here is exactly the aspiration I was talking about in https://github.com/kubestellar/kubestellar/issues/1112#issuecomment-1756770302 . For another example, consider deploying a workload with horizontal pod autoscaling.

**Comment by kapilagrawal95** [comment]
Thanks @MikeSpreitzer . I went through the [comment](https://github.com/kubestellar/kubestellar/issues/1112) and the [article](https://medium.com/@mspreitz/seven-ways-to-stub-your-toes-on-the-edge-c45e060bc4f4). The article exactly pointed the problem that I describe in this issue about replicas. 

However, I don't completely understand the difference between your proposal of "keeping imprecision" and the idea of "downsync-overwrite" that will released in 0.8? This implementation of using "downsync-overwrite" flags achieve imprecision? Isn't that right?

**Comment by clubanderson** [comment]
I think what @MikeSpreitzer is saying is that if you leave out the number of Replicas at the source then KubeStellar won't try to overwrite that part of the spec.

**Comment by MikeSpreitzer** [comment]
The difference shows up when you consider the case of wanting to update part of an object's desired state but not all of it.
