### ISSUE TITLE
bug: doc for "Fetch a log from a KubeStellar runtime container" lacks namespace

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#1124]
### Describe the bug

The KubeStellar Helm chart is not always instantiated into the default or current namespace. The section named "Fetch a log from a KubeStellar runtime container" in commands.md does not recognize that namespace is an issue.

### Steps To Reproduce

Read the doc

### Expected Behavior

No sharp edge here.

**Comment by MikeSpreitzer** [comment]
A little more broadly: we seem to be increasing our expectations for how much the user understands Kubernetes. Perhaps this section should be less operational and more about explaining the structure that the chart creates. Really, there should be doc on observability, both logs and metrics, and that would involve explaining the Kubernetes objects involved. Note also that this is telling users about implementation details that may change in the future.

**Comment by clubanderson** [comment]
on a related note: I updated commands.md for 'get-internal-config' and 'get-external-config' to include namespace

**Comment by MikeSpreitzer** [comment]
Moot now.
