### ISSUE TITLE
feature: Create edgeDeployment CRD

### ISSUE THREAD

**Issue by clubanderson** [kubestellar/kubestellar#1129]
### Feature Description

we need a way to store, via concatenation, all individual yaml content from individual workload items dropped off in the WDS.  Once in an edgeDeployment object in the KubeStellar namespace, the KubeStellar syncer can pull and apply contents of edgeDeployment.  This reduces complexity of the internal workflow for KubeStellar.  This also eliminates the MBS.  One fewer workspace to manage and maintain.  Removing the MBS and using the KubeStellar namespace is also a more scalable solution.

### Proposed Solution

create the edgeDeployment CRD which is capable of containing all individual yaml definitions for a workload that is destined for a specific location(s).

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by MikeSpreitzer** [comment]
Is this intended to preserve the option for 1:many distribution? If so, how does this reduce complexity of the internal workflow for KubeStellar?

**Comment by MikeSpreitzer** [comment]
Another feature of the current design is supporting many:1 distribution. An example use case would be where an organization has a base layer of functionality they want distributed to every WEC, plus some more specialized applications that each goes to a subset of the WECs. That can be served by one EdgePlacement that directs the base layer to all the WECs, and an EdgePlacement for each specialized application.

Is the design revision here intended to keep that functionality?

**Comment by MikeSpreitzer** [comment]
We already limit the privileges of each syncer in the core, to its mailbox space. It is easy to limit privileges according to space, by namespace, and to individually configured object (changing that configuration is done by changing RBAC objects typically but there are other authorization customization techniques available such as webhooks).

If we preserve 1:many distribution and many:1 distribution then it might be easiest for the placement translator to produce one EdgeManifest object per (EdgePlacement,WEC). That would involve multiple EdgeManifest objects per WEC, that is multiple per syncer, in general --- with the collection varying dynamically. The easiest way to get the privileges limited per syncer would to put each syncer's collection in a distinct namespace.

**Comment by clubanderson** [comment]
Changing name of CRD to edgeDeployment to map back to the mental model of what a standard Kube deployment does.  This helps the user understand why this mechanism exists and how it might operate.  Our doc will satisfy details on top of that existing mental model.

As for your comments @MikeSpreitzer.  It is fine to suggest multiple namespaces. That sounds more scalable and secure.  great suggestion

**Comment by clubanderson** [comment]
@yana1205 this is what we talked about over lunch.  This would be the kubestellar equivalent to manifestwork.  The edgeDeployment CRD would hold any and all objects that are matched by the edgeplacement object

**Comment by clubanderson** [comment]
@nirrozenbaum this is the KubeStellar Syncer interface for the new pluggable placement translator you are working on.  Please work with @yana1205 to include his definition for the edgeDeployment CRD as 1 type of output that PT will support.  The other output is manifestWork.

**Comment by nirrozenbaum** [comment]
added `pluggable-transport` label since this should be aligned with the pluggable transport and is very much related.
