### ISSUE TITLE
feature: Support upsync from KubeStellar syncer

### ISSUE THREAD

**Issue by clubanderson** [kubestellar/kubestellar#1131]
### Feature Description

The KubeStellar Syncer has upsync capability.  Would like to support this in the new pluggable transport layer.

### Proposed Solution

allow upsync of resources to the kubestellar management server (hub)

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by nirrozenbaum** [comment]
@clubanderson pluggable-transport should implement upsync, but this is out of scope in phase 1.
for downsync only, there is no syncer config.. so I'm not sure this is relevant for next sprint.

**Comment by clubanderson** [comment]
gotcha - let me re-title and push to next spring for discussion

**Comment by nirrozenbaum** [comment]
out of scope for ks-0.20 for phase1. will be discussed in preparation for phase2.
pushed for later sprint.
