### ISSUE TITLE
feature: Remove MB space

### ISSUE THREAD

**Issue by clubanderson** [kubestellar/kubestellar#1132]
### Feature Description

The MBS is no longer necessary now that edgeDeployment is created and placed in KubeStellar namespace, and syncerconfigs are created and managed by the Mailbox Controller in the KubeStellar namespace

### Proposed Solution

remove the MBS workspace/space creation:
- [ ] from the installers, 
- [ ] from the kubectl plugins, 
- [ ] and from the documentation

### Want to contribute?

- [x] I would like to work on this issue.

**Comment by nirrozenbaum** [comment]
closing, as not relevant to ks-0.20
