### ISSUE TITLE
feature: Remove IS space - locations and synctargets move to KubeStellar namespace

### ISSUE THREAD

**Issue by clubanderson** [kubestellar/kubestellar#1133]
### Feature Description

The Inventory Space is no longer necessary now that locations and synctargets will be created and maintained in the KubeStellar namespace.  We need to remove the IS workspace/space.

### Proposed Solution

Remove the IS workspace/space:

- [ ] from the installer,
- [ ] from the kubectl plugins
- [ ] from the documentation

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by nirrozenbaum** [comment]
not relevant for ks-0.20. closing for now.
