### ISSUE TITLE
feature: Update Where Resolver to combine locations and synctargets from KubeStellar namespace

### ISSUE THREAD

**Issue by clubanderson** [kubestellar/kubestellar#1134]
### Feature Description

Now that the locations and synctargets are in the KubeStellar namespace, it is necessary for the Where Resolver to be updated to combine locations and synctargets from the KubeStellar namespace, not the IS, with edgePlacements in order to create singlePlacementSlice objects.

### Proposed Solution

Update the Where Resolver to use location and synctarget objects from the KubeStellar namespace and not the IS workspace/space

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by nirrozenbaum** [comment]
not relevant for ks-0.20 (no more Where Resolver).
closing as not relevant.
