### ISSUE TITLE
feature: edgeplacement should be automatically updated to include clusterscoped objects based on feedback from kubestellar syncer returned status when deployment failures are indicated

### ISSUE THREAD

**Issue by clubanderson** [kubestellar/kubestellar#1138]
### Feature Description

I should not have to manually add clusterscoped objects to the edgeplacement object for my workload. KubeStellar should figure this out on its own. 

### Proposed Solution

Use status retrieved from kubestellar syncer, when status indicates clusterscoped objects are necessary before completing deployment. This information is available in status of deploying workload. ArgoCD is able to report this in their UI. KubeStellar should be able to find and use this too. 

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by MikeSpreitzer** [comment]
I do not think the syncer knows in general about what cluster scoped objects are required by what namespaced objects.  I think there are some particular cases where this is knowable. This would include the case of a downsynced CustomResourceDefinition. This would include the case of a downsynced APIBinding that defines a resource that is already in the WEC for some reason (e.g., a CustomResourceDefinition or APIService), remembering that a WEC is not a kcp workspace so an APIBinding is not effective there and we deliberately allow the WDS to have an APIBinding that imports the needed resource definition. Are you thinking of other cases?

**Comment by clubanderson** [comment]
You can learn what clusterscoped objects are required by listening to the syncer for errors on deployment and then using that feedback to adjust the edgeplacement object accordingly. Then the deployment would succeed on successive tries.

**Comment by MikeSpreitzer** [comment]
I assume you do not mean all syncer errors --- there are many of them, with different root causes --- but rather some specific ones. Those would be those complaining about resources (kinds of objects) not being defined, right?

**Comment by clubanderson** [comment]
absolutely 110% correct @MikeSpreitzer
