### ISSUE TITLE
bug: quickstart inconsistency wrt namespace for core

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#1141]
### Describe the bug

I am testing https://docs.kubestellar.io/release-0.8/Getting-Started/quickstart/ , and at the moment the release-0.8 branch points at commit ed2c599d67f0142b6f5e267226a8b8e76520a65a .

I chose to deploy the core as Kubernetes workload in a kind cluster, following the path in the quickstart.

I got to the point where it says to use `kubectl get deployments -n kubestellar` to check for one running Pod. That finds me no Deployment objects. The Helm chart seems to have been instantiated into the namespace named `default`.

Following is a complete typescript of the test.  The evidence of the namespace mismatch is at the end.

[kstest-v0.8.0-kind.log](https://github.com/kubestellar/kubestellar/files/12923249/kstest-v0.8.0-kind.log)

### Steps To Reproduce

See the typescript

### Expected Behavior

The quickstart works as written.

**Comment by MikeSpreitzer** [comment]
How should we fix this inconsistency? Change where the bootstrap command instantiates the chart (which requires changing the bootstrap script to either make this a constant or take it in an optional command line flag) or change where the quickstart text says to find the core Pod?

**Comment by clubanderson** [comment]
I would change the bootstrap script to take a default ns of kubestellar. IMO
