### ISSUE TITLE
bug: scripts that navigate from bin to peer directories vs symlinks

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#1152]
### Describe the bug

kubectl-kubestellar-deploy
`kubestellar init`

expect helm chart, config directory to be peer of bin. symlinks mess this up.

### Steps To Reproduce

Try kubectl-kubestellar-deploy after the brew install, for example. Or try any example with a symlink involved.

### Expected Behavior

stuff gets found

**Comment by clubanderson** [comment]
Are these 2 scripts primarily used to support manual deployment (non-helm)?  Can we come up with a new way to support our collaborators (not users) based on container only and eliminate the need for raw processes?  I have not examined these 2 scripts in a while.
