### ISSUE TITLE
feature: KubeStellar creates a paradigm shift for our users - the need to keep track of context since multicluster is the normal mode of operation

### ISSUE THREAD

**Issue by clubanderson** [kubestellar/kubestellar#1154]
### Feature Description

I am always fearful that I will issue a command to the wrong cluster when I am using KubeStellar.  I try to keep track of this with kubeconfig files, not context.  The combination of openshift login (token that expires every 24 hours) and space framework for WECs... When you have to do this for 1000's of clusters, this presents a real issue. 

remembering where you are in the kubestellar universe is difficult. I think now that we are moving into a universe where multi cluster is normal, we might need to make this easier for our user.  In the past, kube did not need this because it was 1:1 for normal ops.  For us, 1:many is now the norm.

what would a terminal session be without a prompt that shows you your context?

### Proposed Solution

2 suggestions, and I am sure there are more

1. could we introduce a "kubestellar tip" that shows someone how to add the "kube context" on the command line prompt?

something like
`/users/me/projects> (kubeconfig=admin.kubeconfig)`

2. maybe our kubectl commands report context as you run them.  

... lets get creative and look around for and/or think of other possible options

### Want to contribute?

- [ ] I would like to work on this issue.

### Additional Context

@KPRoche @francostellari do either of you have some ideas from all your lab work?  Maybe it's like keeping tack of ssh connections in a ssh/config file?  There must be something out there (a methodology, suggestion, app) that can do the job of keeping track of this type of 1:1 connections to keep people from making changes on the wrong system.

**Comment by KPRoche** [comment]
One option would be for kubestellar to check for a kubeconfig (or even a simple text file) in the directory from which you issued the terminal command in the absence of command flags specifically setting kubeconfig, namespace, or context. 
If present, use the local file, if not, default to the current environment settings. AND say in the response to the command which kubeconfig, ns, and context you are using.

Then you would simply need a folder corresponding to each location. That's still a lot, but you could organize it with directory structures.

OR added functionality where you can set a nickname for a target (location/workload) and invoke that, and kubestellar can find the matching kubeconfig, namespace and context.

**Comment by clubanderson** [comment]
could we somehow pull a small bit of info from the file currently pointed at by the KUBECONFIG env var and then add that to the command line in the shell?

**Comment by MikeSpreitzer** [comment]
The fundamental problem here is from the Kubernetes world, KubeStellar did not introduce it.  Already in the Kubernetes world people deal with multiple clusters, multiple kubeconfig files, and multiple "contexts" within a kubeconfig file. kcp adds something: the concepts of current workspace and previous workspace.

The Kubernetes world gives users choices about how to organize their kube client configs into kubeconfig files and contexts within those kubeconfig files. I have not seen any demonstrations of this in the course of working on this project, but that _is_ a variable. kubeconfig file contents can be merged, can be split.

I have seen people express different preferences from @clubanderson . It is not clear to me that there is one right way to exercise the user's freedom here.

Helping users make the relevant bits of state visible is definitely good. That is primarily two things: which kubeconfig file will be used, and which context within that kubeconfig file. kcp adds one more thing of high interest: which workspace is current.

**Comment by MikeSpreitzer** [comment]
I would not favor changing the way that kubectl selects the client config to use. Adding output to stdout sounds bad to me, since scripting is a thing. Adding output to stderr is not inconceivable. But since context (broadly construed) visualization in shells is a thing, I like that approach the best. Also, @eaepstein suggested a style of usage in which (if I recall correctly) the kubeconfig file is explicitly specified in each command.

**Comment by clubanderson** [comment]
found an answer to my kube context woes... I use oh-my-zsh (https://ohmyz.sh/) with powerline9k/10k (https://github.com/Powerlevel9k/powerlevel9k

I simply put:

`POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(kubecontext)`

at the end of my ~/.zshrc file

and now I have the current context and namespace from the kubefonfig currently pointed to by the KUBECONFIG env var.

@KPRoche give this a shot please.

**Comment by KPRoche** [comment]
looking at it... you're aware powerlevel9k has big "obsolete" warnings all over its page recommending powerline10k instead?

**Comment by clubanderson** [comment]
@KPRoche would you be so kind as to research how to use 10k, instead of 9k, with oh-my-zsh to show the context as I was able to do?

**Comment by eaepstein** [comment]
kubectl offers two ways to explicitly specify a cluster target: 
1. using --context flag when more than one context is contained in the default/specified kubeconfig file path, or
2. setting/overriding the KUBECONFIG envar.

However, --context is currently broken for some of kubestellar's kubectl plugins because they call the kubectl-kcp executable which reserves the use of --context for the KCP space. 

It is easy to specify to kind where to put the kubeconfig when starting a cluster:

`kind create cluster --name kshost --kubeconfig=kshost.kubeconfig`

Given that each kubectl target has its own kubeconfig file, the KUBECONFIG envar works nicely with an alias. For example:

  `alias kc-guilder="KUBECONFIG=$PWD/guilder.kubeconfig kubectl"`

And if multiple contexts already exist in a kubeconfig, they can be extracted easily:

`kubectl config view --minify --flatten  --context kind-guilder > guilder.kubeconfig`

**Comment by clubanderson** [comment]
good point @eaepstein.  The reason I brought up this issue is because maybe we can create something that is better than the 'export' or 'context' solution.  I am using a terminal enhancement to help me keep track of where I am.  Maybe that guidance is enough, maybe there are other solutions out there addressing this, maybe we could use or enhance or create something to help our users

@KPRoche please advise on how best to add 10k (instead of 9k) to get the desired affect.

**Comment by eaepstein** [comment]
@clubanderson There are a few drawbacks to replying on the command line prompt for context.

With a stateful command line, it takes an extra command when switching contexts:
- change context
- use common "kubectl" command to modify state

Another issue is when reviewing a history of commands issued. There is no command line prompt when reading history, one must look back to previous commands to figure out what context "kubectl" was modifying. 

Following directions in the example documentation was also a problem for me, as the last change context command was somewhere above, often on a previous page.

Using different aliases for kubectl is self documenting and can be more efficient at times.

**Comment by eaepstein** [comment]
@clubanderson I forgot to comment on the problem of maintaining many individual kubeconfig files.  OCM has a nice feature that supports forwarding API requests to managed clusters:
`https://open-cluster-management.io/scenarios/pushing-kube-api-requests/`
