### ISSUE TITLE
feature: keep must-gather in repo

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#1167]
### Feature Description

See https://ibm-research.slack.com/archives/C031BHTG2LB/p1697468004364649 for a draft of a listing of information for a user to gather when making a trouble report. "must-gather" is jargon for recommended information to gather. "must" is too strong a word to speak to users at this point.

### Proposed Solution

Add this to the bug-report template.

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by clubanderson** [comment]
check out - https://github.com/kubestellar/kubestellar/issues/new?assignees=&labels=kind%2Fbug&projects=&template=bug_report.yaml&title=bug%3A+

open a new bug with any changes to this template you would like.
