### ISSUE TITLE
bug: wrong value for `ks_tag` in v0.9.0 mkdocs.yml

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#1170]
### Describe the bug

The bootstrap commands displayed in https://docs.kubestellar.io/release-0.9/Getting-Started/quickstart/#2-install-and-run-kcp-and-kubestellar say `--kubestellar-version latest` but they should say `--kubestellar-version v0.9.0`.

The cause of the problem is at https://github.com/kubestellar/kubestellar/blob/v0.9.0/docs/mkdocs.yml#L11 . Older releases specify their own point release semver there.

### Steps To Reproduce

See above

### Expected Behavior

See above

**Comment by clubanderson** [comment]
fixed - I need to update the release instructions to cover this field.
