### ISSUE TITLE
bug: Port number inconsistency

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#1171]
### Describe the bug

#1157 changed the host port number in the example of creating a `kind` hosting cluster (from 6443 to 1024) but did not make the corresponding change to the literal port number in the quickstart.  https://docs.kubestellar.io/release-0.9/Getting-Started/quickstart/#deploy-kcp-and-kubestellar-as-kubernetes-workload still has a literal 6443 as the port number.

### Steps To Reproduce

See above

### Expected Behavior

Text that we expect users to copy-and-paste and work together actually does.

**Comment by clubanderson** [comment]
fixed by using "{{ config.ks_kind_port_num }}" in dev-env.md, helm-chart-readme, and doc referenced herein.  If you see other instances of 1024 lying around, please replace with '{{ config.ks_kind_port_num }}'
