### ISSUE TITLE
bug: incomplete editing in quickstart, object vs commands

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#1172]
### Describe the bug

https://docs.kubestellar.io/release-0.9/Getting-Started/quickstart/#deploy-kcp-and-kubestellar-as-kubernetes-workload displays some commands, but with line numbers (which is uncharacteristic) and the first display is introduced with text that says what is displayed is objects rather than commands.

### Steps To Reproduce

See above

### Expected Behavior

Complete edits.

**Comment by fileppb** [comment]
@MikeSpreitzer @clubanderson Hi, on a related note I haven't been able to find a description of the code management workflow in Kubestellar's documentation.  Maybe I'm just missing it. The Contributing Guide points to git best practices: https://gist.github.com/luismts/495d982e8c5b1a0ced4a57cf3d93cf60 which suggests that one best practice is to agree on a workflow: https://gist.github.com/luismts/495d982e8c5b1a0ced4a57cf3d93cf60#agree-on-a-workflow. But I don't see that workflow procedure documented for Kubestellar. So should the contributors just fork the repo, set upstream to main, branch from main, essentially working off the current main, branching from the fork and then doing a PR that eventually gets upstream, or should they branch from a common release tag and then push to a common DEV branch (which is what I've done in other projects)? And then gatekeepers would promote from DEV to a new release when ready. I know we were doing the former, but I don't see the workflow described anywhere.

**Comment by MikeSpreitzer** [comment]
@fileppb : yes, I think your observations are accurate, with the exception of the stuff about release branches. We occasionally make a release branch from `main`, with a bit of documentation in https://docs.kubestellar.io/main/Contribution%20guidelines/operations/release-management/ and some initial problem fixing.  On rare occasions some work gets back-ported from `main` to the most recent release branch.

**Comment by fileppb** [comment]
@MikeSpreitzer Thanks. I was addressing code management and I didn't see that you already have a placeholder for that in https://docs.kubestellar.io/main/Contribution%20guidelines/operations/code-management/  So clearly someone will be working on that document :--)

**Comment by clubanderson** [comment]
hey @fileppb - thank you for dropping a note in here.  Yes, it would be a good idea to put something in the 'code-management' page.  We are using the former description from your comment - create a fork from main, clone fork, create branch on fork, edit code, push branch, open PR.  @fileppb would you like to help us out by creating a first version of this code-management page for the project?

**Comment by clubanderson** [comment]
I am opening a separate issue for code-management now.

**Comment by clubanderson** [comment]
fixed the linenums in 0.9 and main
