### ISSUE TITLE
feature: complete the code-management page for doc site

### ISSUE THREAD

**Issue by clubanderson** [kubestellar/kubestellar#1187]
### Feature Description

we are missing doc for how to properly fork and submit PR for KubeStellar

### Proposed Solution

build out the code-management page with instructions

from @fileppb in a recent issue:
The Contributing Guide points to git best practices: https://gist.github.com/luismts/495d982e8c5b1a0ced4a57cf3d93cf60 which suggests that one best practice is to agree on a workflow: https://gist.github.com/luismts/495d982e8c5b1a0ced4a57cf3d93cf60#agree-on-a-workflow. But I don't see that workflow procedure documented for Kubestellar. So should the contributors just fork the repo, set upstream to main, branch from main, essentially working off the current main, branching from the fork and then doing a PR that eventually gets upstream, or should they branch from a common release tag and then push to a common DEV branch (which is what I've done in other projects)? And then gatekeepers would promote from DEV to a new release when ready. I know we were doing the former, but I don't see the workflow described anywhere.

from @clubanderson in response to @fi
it would be a good idea to put something in the 'code-management' page. We are using the former description from your comment - create a fork from main, clone fork, create branch on fork, edit code, push branch, open PR

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by clubanderson** [comment]
@fab7 and @namasl this is also something you might like to work on.

**Comment by clubanderson** [comment]
@fab7 could you include/write down the step-by-step to 'testing a regular PR locally' and testing a 'doc PR locally with mkdocs'.

**Comment by fab7** [comment]
#  HOW TO TEST A PR LOCALLY 

Here are the steps to checkout a git pull request for local testing.

## STEP-1: Checkout the Pull Request

Helpers: [[GitHub](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally)] [[DevOpsCube](
https://devopscube.com/checkout-git-pull-request/)]

### 1.1 Use the pull request number to fetch origin

Fetch the reference to the pull request based on its **ID** number, creating a new branch locally. Replace **ID** with your `PR #` and **BRANCH_NAME** with the desired branch name.
```
  git fetch origin pull/ID/head:BRANCH_NAME
```

### 1.2  Switch to the new branch

Checkout the **BRANCH_NAME** where you have all the changes from the pull request.
```
  git switch BRANCH_NAME
```
At this point, you can do anything you want with this branch. You can run some local tests, or merge other branches into the branch.

## STEP-2: Test and Build the Documentation (optional)

Use this procedure if you want to view and modify the documentation in the branch you have checked out. 

Helpers: [[KubeStellar/docs](https://github.com/kubestellar/kubestellar/tree/main/docs)] [[MkDocs](https://www.mkdocs.org/user-guide/installation/)]

### 2.1 Install MkDocs and its requirements
```
  cd docs
  pip install mkdocs
  pip install -r requirements.txt
 ```

### 2.2 Build and view the documentation
```
  mkdocs serve
```
Next, open a browser to http://localhost:8000/ and review the changes.

**Comment by clubanderson** [comment]
@fab7 Thank you for the information - I have updated the 'testing-doc-prs.md' in https://github.com/kubestellar/kubestellar/pull/1116.  Please have a look

**Comment by fileppb** [comment]
@clubanderson I am right in believing the code management section remains open? The local testing procedure described by Francois doesn't really seem to address the code workflow.

**Comment by clubanderson** [comment]
correct.  I added - https://docs.kubestellar.io/main/Contribution%20guidelines/operations/testing-doc-prs/.  The 'code management' page is not yet created.

**Comment by fileppb** [comment]
@clubanderson I'll take a stab at it :--)

**Comment by clubanderson** [comment]
Great. Thank you @fileppb

**Comment by clubanderson** [comment]
#1293 is now merged - closing
