### ISSUE TITLE
bug: kubestellar-syncer log (possibly the container name) is 'kcp syncer' - needs to be changed to kcp to kubestellar

### ISSUE THREAD

**Issue by clubanderson** [kubestellar/kubestellar#1189]
### Describe the bug

the kubestellar syncer container name/log name is currently 'kcp syncer'

### Steps To Reproduce

1. install the kubestellar syncer on openshift
2. view logs for kubestellar syncer pod

### Expected Behavior

'kcp' should be 'kubestellar'
<img width="1058" alt="Screenshot 2023-10-24 at 10 23 15 AM" src="https://github.com/kubestellar/kubestellar/assets/407614/2b73f1a9-be9b-4714-993a-f89a3205daaa">

**Comment by clubanderson** [comment]
@yana1205 can you address this with high priority for our next release (0.10.0) being released in a few weeks?

**Comment by yana1205** [comment]
Yes. I will fix it soon. I thought I have already fixed the container name.
