### ISSUE TITLE
feature: label workspaces to associate them with their function

### ISSUE THREAD

**Issue by clubanderson** [kubestellar/kubestellar#1193]
### Feature Description

when reviewing the list of our workspaces I have noticed that their is no label on them to indicate their purpose.  Lacking a label will make it hard to determine how to treat these workspaces from a UI or other domain management tool in the future.  For instance - IMW workspaces created explicitly for the purpose of holding inventory for kubestellar should be label 'kubestellar-workspace-type: inventory'

### Proposed Solution

add labels to workspaces as they are created.

IMW - 'kubestellar-workspace-type: inventory'
WDS - 'kubestellar-workspace-type: workload'
MB - 'kubestellar-workspace-type: mailbox'
ESPW - 'kubestellar-workspace-type: espw'

etc.

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by MikeSpreitzer** [comment]
Remember also that one physical space can play more than one role.
The labels have to identify roles.

How about the following labels?
- `"kubestellar.io/inventory": "true"`
- `"kubestellar.io/workload": "true"`
- `"kubestellar.io/core": "true"`
- `"kubestellar.io/mailbox": SourceSpaceID + "/" + SyncTarget.Name`

**Comment by clubanderson** [comment]
works for me.  This will help us when we are doing kubestellar deployment to kubestellar.

**Comment by ezrasilvera** [comment]
Can you clarify the MB one ?  Do you suggest that that label will replace the need to put it in the name ?

**Comment by clubanderson** [comment]
I think that MB will eventually be an NS, no?

**Comment by MikeSpreitzer** [comment]
@clubanderson : For mailbox workspaces, this applies only while we still have mailbox workspaces in their current form. When we switch to mailbox namespaces, things will be different in this regard.

@ezrasilvera : the proposal here is only about _adding_ information in labels.

**Comment by MikeSpreitzer** [comment]
Remember that a SyncTarget name can be too long and have invalid characters to put in a label value, so will need to add some clipping there.
