### ISSUE TITLE
bug: openshift quickstart says to send HTTP requests to localhost

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#1205]
### Describe the bug

In https://docs.kubestellar.io/main/Getting-Started/user-quickstart-openshift/#6-view-the-apache-web-server-running-on-ks-edge-cluster1-and-ks-edge-cluster2 I see

```
curl http://localhost:8094
```

... which is not going to work when the WEC is an OpenShift cluster in some cloud.

### Steps To Reproduce

See above.

### Expected Behavior

Instructions work.

**Comment by clubanderson** [comment]
so I guess we need to add a route to the example to expose the workload for the curl command to work?

**Comment by MikeSpreitzer** [comment]
I think a lower-infrastructure way of doing exposing the httpd would be to define plain Kubernetes `Service` objects and use `kubectl port-forward` to give the local (to the experimenter) access to those services.
