### ISSUE TITLE
Replace KCP-bind with kube-bind

### ISSUE THREAD

**Issue by ezrasilvera** [kubestellar/kubestellar#1208]
The main goal of this item is to replace KCP bind with kube-bind, transparently so KS is still fully functional (using KCP workspaces)
We can separate into two different sections/PRs

This work will be done through the branch:  https://github.com/kubestellar/kubestellar/tree/kube-bind

1. Use kube-bind, continue using the logical-cluster ID when processing the List/Watch objects comings from the Export
2. Remove the logical-cluster id with space-name coming from an internal mapping of the kube-bind annotation & space name

###Phase1:  Use kube-bind  PR:  https://github.com/kubestellar/kubestellar/pull/1265
1. the KS container image (used by all KS containers) should include the KB needed executables 
2. Setup scripts that build the ESPW, WDS, and IS should be changed to:
    * Run dex, 
    * ESPW: Run backend engine + import all KS CRDs + add KB export label + import the KB CRDs
    * IS, WDS: Run konnector, bind all KS resources
3. Mailbox controller - create bind for new MBs (can call script) - Note the above is done in the mb-controller container
4. Need to replace the check on all controllers that verify the export exists
Note: some of the KB components may reside on different containers (e.g., dex and konnectors for MBs) - need to verify access

### Phase2: Stop using the cluster-id
Background:
KCP objects have special annotation("kcp.io/cluster") that holds a reference to the cluster. From that reference is is also possible to obtain the workspace. This annotation is set by KCP and will not be available in other providers.
For example, when we use a watch or List over an APIExport using kube-bind, we get a list of objects and such annotation is the only way to know which cluster the object belongs to.

1. During bind generate a map of [provider NS for the consumer : space name] 
2. Change the relevant controllers code

Notes regarding SM integration:
1. When spaces are created through the SM, the SM will start the konnector process & (optionally) the backend engine process
2. When the space-manager will be used, the mapping of the provider NS of the consumer will be added to the space annotation

**Comment by MikeSpreitzer** [comment]
The two steps enumerated in the opening comment definitely belong in distinct PRs. The first step has no dependency on the space framework and can be taken before any introduction of the space framework. The second step pre-reqs use of the space framework, and can be delayed until some provider other than kcp is used.

**Comment by clubanderson** [comment]
@ezrasilvera can this be closed?
