### ISSUE TITLE
Possible synergy between the KubeStellar and the Flux CD community

### ISSUE THREAD

**Issue by waltforme** [kubestellar/kubestellar#1209]
I recently had some casual conversations with the flux community. We then scheduled a formal meeting with the maintainer(s) to discuss the possibility to seek for the synergy between Flux and KubeStellar.

**Comment by clubanderson** [comment]
@waltforme what are the next steps for this effort?

**Comment by clubanderson** [comment]
can you reach out to kingdon to understand/document what the 'repo structure' challenge is?

**Comment by waltforme** [comment]
I reached out to flux maintainers and tried to understand the problem. I didn't get a clear answer to the problem though. If my own understanding is correct, the problem is the growing complexity of the git repo structure when # of clusters increases. Unfortunately I don't think today KS has a solution to that. Let's close this issue for now. Will keep an eye on any possible engagement in the future.
