### ISSUE TITLE
Add the space-frame-work to the KS setup scripts

### ISSUE THREAD

**Issue by ezrasilvera** [kubestellar/kubestellar#1215]
The goal is to add the space framework to the existing KS setup scripts. This doesn't require any changes in the KS controller code.
Tasks:

### phase 1: PR-1   https://github.com/kubestellar/kubestellar/pull/1218
1. Setup and bringup the SF container (start the SM controller)
2. Install KubeFlex 
3. Use the existing KCP container (will be used as a KCP provider)
4. Create and configure the KubeFlex space provider,
5. Create and configure KCP provider

The space framework is not being used, only setup and configured. 

### Phase 2: PR-2
Change the KS scripts to use the space-manager + KCP space provider 
All direct KCP calls to create workspaces should be replaced with using the space manager
No KS controllers code is changed 

### Phase 3:  TBD
Change the KS controllers to use spaces through the usage of the Space Aware Client

**Comment by effi-ofer** [comment]
https://github.com/kubestellar/kubestellar/pull/1218 submitted for PR1.
