### ISSUE TITLE
bug: user-quickstart-openshift EdgePlacement does not match the Service object

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#1284]
### Describe the bug

The workload in https://docs.kubestellar.io/main/Getting-Started/user-quickstart-openshift/ has a `Service` object but the `EdgePlacement` does not have any downsync clause that matches that `Service` object.

### Steps To Reproduce

See above

### Expected Behavior

The quickstart works.

**Comment by clubanderson** [comment]
fixed in https://github.com/kubestellar/kubestellar/commit/fecfae8b77db8aaad965ea7032fc2295abaedaa0
