### ISSUE TITLE
bug: user-quickstart-openshift does not say how to get the kind `Route` defined

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#1285]
### Describe the bug

https://docs.kubestellar.io/main/Getting-Started/user-quickstart-openshift/ has an object of kind `Route` in the workload but nothing that _defines_ that kind of object (`Route` is not built into kcp or Kubernetes, it is an OpenShift thing).

### Steps To Reproduce

See above.

### Expected Behavior

The quickstart tells the reader enough to succeed.

**Comment by MikeSpreitzer** [comment]
How was this ever successfully tested?

**Comment by clubanderson** [comment]
fixed in https://github.com/kubestellar/kubestellar/commit/742c9067c9c31428df3d374cfd18ec85d66bf29a.  CURL and apply openshift route CRD.  Updated the openshift qs with instructions that work end-to-end
