### ISSUE TITLE
Remove kcp modules from Syncer integration tests (/test/e2e/*)

### ISSUE THREAD

**Issue by yana1205** [kubestellar/kubestellar#1315]
The Syncer integration test codes (/test/e2e/*) import and depend on kcp. KubeStellar is decoupling KCP now. The integration codes need to follow the KCP decoupling project. 

Plan:
- phase1: remove kcp modules from codes under /test/e2e/ and write alternative codes that manage the lifecycle of a workspace for tests 
  - KCP modules are removed from source codes but runtime is still KCP. Namely, we still need to run KCP firstly then run e2e/tests.
- phase2: use Space Framework.
  - No need to run KCP. We will use Space Framework. Namely, to run the tests, we run Space Manager Cluster then select preferred space providers (kube-flex, kcp, kind, etc). 

I would like to separate phase1 and 2 in different issues and track phase2 next year since phase2 is not containable for me in this year.

#### Related issues
https://github.com/kubestellar/kubestellar/issues/1266

**Comment by clubanderson** [comment]
@yana1205 please update this issue to give us status
