### ISSUE TITLE
Update documents to specify the steps needed to support spaces. 

### ISSUE THREAD

**Issue by effi-ofer** [kubestellar/kubestellar#1331]
### Feature Description

The documents in [https://docs.kubestellar.io/main/Coding%20Milestones/PoC2023q1/commands](https://docs.kubestellar.io/main/Coding%20Milestones/PoC2023q1/commands/#creating-a-workload-management-workspace) do not fully explain what's needed to support the space framework.

### Proposed Solution

.

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by clubanderson** [comment]
commands have been updated - Thank you 

per @effi-ofer and @ezrasilvera closing now
