### ISSUE TITLE
Refactor the networking of kube-bind related components

### ISSUE THREAD

**Issue by waltforme** [kubestellar/kubestellar#1341]
(Suggested by this [comment](https://github.com/kubestellar/kubestellar/pull/1265#discussion_r1409922543)): Right now dex is serving at 127.0.0.1. This works for today's pattern in which all bare processes are on the same host, or all clients and the server in the same kube pod. We need a more flexible approach later when today's pattern changes.

**Comment by clubanderson** [comment]
all components are working in a single pod.  There are no independent pods, therefore this issue is no longer necessary.  Will re-open if we move to multi-cluster (or when needed in multi-pod/components)

closing per @waltforme and @ezrasilvera
