### ISSUE TITLE
feature: change space manager context name from sm-mgt 

### ISSUE THREAD

**Issue by effi-ofer** [kubestellar/kubestellar#1348]
### Feature Description

The current name is sm-mgt.  We would like to change it to sm-core.  This will require changes in the scripts and the code.

### Proposed Solution

.

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by MikeSpreitzer** [comment]
Why is "core" better? In the space framework there is no core/periphery dichotomy.

**Comment by clubanderson** [comment]
pushing to sprint 9, minor detail.  Need time to discuss
