### ISSUE TITLE
feature: set the appropriate token for the host kubeconfig in entry.sh

### ISSUE THREAD

**Issue by effi-ofer** [kubestellar/kubestellar#1349]
### Feature Description

The code that gets the host kubeconfig in entry.sh does it this way:
`kubectl --kubeconfig $host_kubeconfig config set-credentials sm-mgt --token="$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)"`
which is potentially dangerous.

### Proposed Solution

This takes a snapshot of a bearer token that will be invalidated soon. This is a time bomb. A better approach has to be taken.

Can't we do something much simpler and ordinary? This script is specifically written to run in a Pod. When used inside a Pod, kubectl will, by default, use the credentials of that Pod.

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by clubanderson** [comment]
pushing to sprint 9.  Token can expire after 1 year.  Should discuss this to be fixed, along with preserving tokens on re-install.

per @ezrasilvera @effi-ofer 

/cc @francostellari
