### ISSUE TITLE
feature: teardown of example1

### ISSUE THREAD

**Issue by effi-ofer** [kubestellar/kubestellar#1362]
### Feature Description

From [docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-teardown.md]
```
kubectl delete workspace imw1
kubectl delete workspace $FLORIN_WS
kubectl delete workspace $GUILDER_WS
KUBECONFIG=$SM_CONFIG kubectl delete space imw1

```
Mike wrote: 

> BTW, this command should have been removed back when we made kubestellar init, rather than this example recipe, create imw1. The appropriate teardown instead is now to delete the inventory objects that this recipe created.

### Proposed Solution

Sounds like we have some cleanup to do here that is beyond the scope of the PR I am currently working on.

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by clubanderson** [comment]
needs review to determine what is the best way to complete this task.

**Comment by clubanderson** [comment]
@waltforme please weigh in.

/cc @waltforme

**Comment by waltforme** [comment]
We need to
- kill dex, example-backend, all konnectors;
- remove logs (example-backend, konnectors), cloned repositories (dex, kube-bind) along with built binaries.

**Comment by waltforme** [comment]
Do we still need this as switching to ks-0.20?
