### ISSUE TITLE
bug: captuing pod's bearer token is a time bomb

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#1438]
### Describe the bug

https://github.com/kubestellar/kubestellar/blob/d22d4272d1571ccc9f6ad836bb5a5e0b02605c22/core-container/entry.sh#L264 captures for use forevermore a bearer token that will expire within an hour

### Steps To Reproduce

read the code

### Expected Behavior

The system stays up for months

**Comment by ezrasilvera** [comment]
@MikeSpreitzer what is your recommendation instead?

**Comment by MikeSpreitzer** [comment]
I recommend that for scripting that runs in a pod in the host cluster, kube client programs (`kubectl`, controllers) wanting to access the host cluster/ SMAS be given no `--kubeconfig` and `$KUBECONFIG` be empty, so that the regular behavior of client-go in that case happens --- which uses the _current_ bearer token mounted and rotated by the kubelet.

**Comment by MikeSpreitzer** [comment]
The problem in the KubeStellar `entry.sh` has been fixed in #1444 .
The problem also appears in the Space Framework's `entry.sh`.

**Comment by MikeSpreitzer** [comment]
The space-manager process should take kubectl arguments in the regular way, using https://github.com/kubernetes/cli-runtime/blob/v0.24.3/pkg/genericclioptions/config_flags.go#L414 , like https://github.com/kubestellar/kubestellar/blob/main/cmd/kube-watchall/main.go does.

**Comment by MikeSpreitzer** [comment]
Moot
