### ISSUE TITLE
bug: concurrent write and read of space kubeconfig file

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#1447]
### Describe the bug

Many commands are implemented by a script that writes a kubeconfig file for a relevant space in a predictable place and later read it. Thus, two concurrent invocations of such a command that write and read the kubeconfig file for the same space constitute a data race.

### Steps To Reproduce

Look at where the scripts write the kubeconfig files.

### Expected Behavior

Concurrent command invocations do not read corrupted kubeconfig files.

**Comment by MikeSpreitzer** [comment]
@ezrasilvera 
@effi-ofer 
@andreyod

**Comment by MikeSpreitzer** [comment]
For example, the mailbox controller can do concurrent invocations of the kubestellar-kube-bind script.

**Comment by clubanderson** [comment]
@namasl please add this to your list of items to watch for when converting scripts to clientgo.

/cc @namasl

**Comment by clubanderson** [comment]
related to #414
