### ISSUE TITLE
:book: docs: contributing doc has a broken link

### ISSUE THREAD

**Issue by grahamwhiteuk** [kubestellar/kubestellar#1460]
### Describe the bug

[CONTRIBUTING.md](https://github.com/kubestellar/kubestellar/blob/main/CONTRIBUTING.md) links to [best practices in git commit management](https://www.futurelearn.com/info/blog/telling-stories-with-your-git-history) which is broken.

### Steps To Reproduce

Click on the link in the docs

### Expected Behavior

Link should resolve

### Additional Context

I took the liberty of looking up the article that's referenced in the Way Back machine.  I've converted it to markdown (attached below).

Changes made are:
* Convert the original HTML source into markdown
* Remove references to master (replaced with "the main branch")
* Removed first person references
* Corrected a few small grammatical problems

[COMMIT_BEST_PRACTICE.md](https://github.com/kubestellar/kubestellar/files/13659005/COMMIT_BEST_PRACTICE.md)

I'd be happy to submit a PR to resolve this but I'm not sure where you'd want to place such a document i.e. whether it goes in the repo, a separate repo, a wiki, a different blog post, etc???

**Comment by clubanderson** [comment]
@grahamwhiteuk Thank you for pointing this out.  I think you could post this to Medium as a blog post.  Then, we can link to it from our site.  The only thing I would do, if I were you, is to make sure you cite/reference the original article from the way-back version.  This way people know your work is partly original and partly a copy of an original work.  How does that sound?

**Comment by clubanderson** [comment]
then you can PR to point to that document and we can tag the article with kubestellar as well.

**Comment by grahamwhiteuk** [comment]
I don't write on Medium, I think it's the wrong platform choice for something like this (due to their paywall).  I do have a blog, but I do things slightly differently to that suggested in the original post.  If I were to write something it would look more like the content you see if you search for `advanced prototyping team engineering excellence` within the IBM Intranet (sorry I didn't want to add a link to an internal web page here).  That is, it's a bit more of a playbook for various engineering related bits and pieces.  Maybe there's somewhere more open we can re-publish the original work (with credit as you suggest).

**Comment by grahamwhiteuk** [comment]
How about https://hackmd.io/q22nrXjERBeIGb-fqwrUSg

If the above flies for you then I created a Kubestellar team on hackmd... very happy to add more Kubestellar community members to that space and indeed hand over ownership to you guys.

**Comment by clubanderson** [comment]
looks good to me.  you can retain ownership.  Just PR a change to our contributing.md that includes your new post as the source url for that broken link you found.  Thank you for helping us out.
