### ISSUE TITLE
Recover the supports to `linux/ppc64le` after including the automated kubectl-bind into core image

### ISSUE THREAD

**Issue by waltforme** [kubestellar/kubestellar#1487]
Our recently automated `kubectl-bind` uses `surf` to simulate the user's browser. However, `surf` lacks supports to ppc64le at build time.
```
#0 1029.4 /root/go/pkg/mod/github.com/headzoo/surf@v1.0.1/agent/agent_linux.go:19:23: cannot use buf.Sysname (variable of type [65]uint8) as [65]int8 value in argument to charsToString
#0 1029.4 /root/go/pkg/mod/github.com/headzoo/surf@v1.0.1/agent/agent_linux.go:29:23: cannot use buf.Release (variable of type [65]uint8) as [65]int8 value in argument to charsToString
```
Temporarily we can remove `linux/ppc64le` from Makefile's `CORE_PlATFORMS`, then build a multi-arch image which supports `linux/amd64` and `linux/arm64`.

In the long run we should resume the supports to `linux/ppc64le`.

**Comment by clubanderson** [comment]
work in progress.  @waltforme has opened a feature request in the upstream web sim lib to support ppc.  going to update the ks build to re-use existing lib instead of building binaries to support this feature.

**Comment by waltforme** [comment]
Done by #1505. Closing.
