### ISSUE TITLE
feature: fixing quickstart for kind and quickstart for openshift in the main branch

### ISSUE THREAD

**Issue by clubanderson** [kubestellar/kubestellar#1502]
### Feature Description

currently we have non-working qs for kind and qs for openshift. 

### Proposed Solution

would like this completed for the end of sprint 8 to get our "front door" working again for kubestellar.io

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by ezrasilvera** [comment]
In-progress, on-track
