### ISSUE TITLE
EPIC:  Track issues for ks-0.20 phase0

### ISSUE THREAD

**Issue by ezrasilvera** [kubestellar/kubestellar#1515]
This epic tracks the issues needed to complete phase0 

- [x] #1519
  - #1518
- [x] #1530
  - #1529
- [ ] #1575
- [ ] #1531
- [x] #1514 
- [ ] #1532 
- [ ]  #1533 
- [ ] #1544
- [ ] #1545
- [x] #1601

**Comment by effi-ofer** [comment]
Issue #1519 is part of this epic.

**Comment by ezrasilvera** [comment]
This can be tracked now through the project board for phase0 at https://github.com/orgs/kubestellar/projects/5/views/4
