### ISSUE TITLE
bug: duplicated buggy logic for evaluating object tests

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#1526]
### Describe the bug

https://github.com/kubestellar/kubestellar/blob/b3c0567a7b5e4050ec278c792e8eb4512242f8d3/pkg/placement/placement.go#L307-L321 functionally duplicates https://github.com/kubestellar/kubestellar/blob/b3c0567a7b5e4050ec278c792e8eb4512242f8d3/pkg/placement/selectors.go#L46-L60 and both are buggy. The LabelSelectors should be combined with OR --- at both loop levels --- but the existing logic combines with AND.

### Steps To Reproduce

Look at the code.

### Expected Behavior

Implementation matches API design.

**Comment by MikeSpreitzer** [comment]
@pdettori

**Comment by MikeSpreitzer** [comment]
I will be updating this code in #1525

**Comment by pdettori** [comment]
#1525 fixed this logic and it has been merged, so we can close this one.
