### ISSUE TITLE
bug: ks-0.20 Makefile is missing the `verify-boilerplate` target

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#1530]
### Describe the bug

All the PRs against branch `ks-0.20` are failing the GitHub workflow that verifies boilerplate, due to lack of the Makefile target for that.

### Steps To Reproduce

Look at any PR against `ks-0.20`

### Expected Behavior

CICD tests are not MIA

**Comment by pdettori** [comment]
@MikeSpreitzer - This has been addressed in #1529 . Please verify that CI checks now work.
