### ISSUE TITLE
bug: "multiple *matchLabels* expressions" is not a thing 

### ISSUE THREAD

**Issue by pdettori** [kubestellar/kubestellar#1539]
### Describe the bug

From [mspreitz](https://github.com/mspreitz)

https://github.com/kubestellar/kubestellar/blob/fb817e2f99e76c3b8b74bcfe40388d09c998f1ff/docs/content/v0.20/README.md?plain=1#L119-L120 mentions the possibility of "multiple  *matchLabels* expressions" --- in explicit contrast to "multiple *labelSelectors*" --- and I get the impression that https://github.com/kubestellar/kubestellar/blob/fb817e2f99e76c3b8b74bcfe40388d09c998f1ff/docs/content/v0.20/README.md?plain=1#L194-L196 is intended to be an example of "multiple  *matchLabels* expressions". But it is not, because there is no such thing. Each LabelSelector can only have at most one `matchLabels`. See https://github.com/kubernetes/apimachinery/blob/v0.29.0/pkg/apis/meta/v1/types.go#L1213-L1222 . What https://github.com/kubestellar/kubestellar/blob/fb817e2f99e76c3b8b74bcfe40388d09c998f1ff/docs/content/v0.20/README.md?plain=1#L194-L196 shows is multiple LabelSelectors. The way to get a conjunction of label tests is with one MatchLabels (or one MatchExpressions) that has two tests in it. For example, in https://github.com/kubestellar/kubestellar/blob/fb817e2f99e76c3b8b74bcfe40388d09c998f1ff/docs/content/v0.20/README.md?plain=1#L180 you probably wanted to write something more like the following

```yaml
  downsync:
  - labelSelectors:
    - matchLabels: {
        "app.kubernetes.io/managed-by": Helm,
        "app.kubernetes.io/instance":   postgres}
```

### Steps To Reproduce

look at 0.20 README.md

### Expected Behavior

Should have correct description of API.

**Comment by pdettori** [comment]
@MikeSpreitzer I believed this has been addressed in the latest interim README, could you pls. verify.

**Comment by MikeSpreitzer** [comment]
Yes, this is fixed now.
