### ISSUE TITLE
feature: more work needed on the Placement API

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#1544]
### Feature Description

- We might not want to call the Kind "Placement", since OCM uses exactly the same name for something conceptually different.
- The API Group should not have "edge" in it.
- Should the upsync criteria examine only immutable object attributes?

### Proposed Solution

We have discussed a few possibilities regarding Placement:
- A different name. `Binding` (if the API group provides enough context)? `WhatWhereBinding`? `WorkloadPlacement`? `WorkloadBinding`?
- Factor as in OCM, leaving `Placement` to talk only about "where" and have a distinct binding object. We would need to decide on names for both. This assumes that we continue with our own "where" API.
- Adopt the OCM placement API. It has the advantage of having an implementation that we could just use. It has the disadvantage of directly exposing OCM, hinding transport pluggability. It has the disadvantage of being more complex than we want for our use cases.

For the API group, it is convenient for that to be of the form `<something>.kubestellar.io` --- for a few reasons. For one, the scripting for code generation is oriented around that form.  For another, it leaves space for branching out when we decide we want to make a meaningful decision. Note that in release 0.15 we have two `<something>`s.

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by MikeSpreitzer** [comment]
@pdettori

**Comment by MikeSpreitzer** [comment]
On the API group, we will take a vote between these two choices:
- `control.kubestellar.io`
- `mc.kubestellar.io` (mc for Multi-Cluster)

**Comment by MikeSpreitzer** [comment]
On the subject of downsync vs upsync criteria: we decided that the upsync criteria would be modified to exclude the tests of object and namespace labels, and to refactor so that we have BasicObjectTest and that is inlined into ExtendedObjectTest.

**Comment by MikeSpreitzer** [comment]
During the architecture meeting we decided to delete upsync from the API for now, and re-opened the question of what to rename/refactor `ObjectTest` to.

**Comment by pdettori** [comment]
@MikeSpreitzer We are still going to have a DownSync field in the types, no? Then we could rename ObjectTest to DownSyncObjectTest, so when decide to add back UpSync we can just add UpSyncObjectTest and the UpSync field without having to change again ObjectTest.

**Comment by MikeSpreitzer** [comment]
@pdettori : yes, think that is probably the most practical approach.

**Comment by nirrozenbaum** [comment]
@MikeSpreitzer I wasn't in the loop about the name change, therefore raising the following point only now - 
a rename in Placement CR also requires rename to PlacementDecision obviously.

Conceptually, the CR that was called up until today Placement defines a **policy** for which objects to select and which clusters to select and creates the binding between them. the CR that was called PlacementDecision defines that concrete objects that were selected by the policy (the object selectors in Placement) and the concrete clusters that were selected by the policy (the cluster selectors in Placement).

I'm OK with the name `Binding`, but considering the above explanation I thought maybe we would like to rename Placement to `BindingPolicy` (cause that's not the binding itself, it's the selectors policy on the what and where) and PlacementDecision to `Binding` (cause that is the concrete binding).
 
wdyt?

as part of this change we do need to find an appropriate name also to the PlacementDecision and not only to Placement.

/cc @pdettori 
/cc @ezrasilvera

**Comment by pdettori** [comment]
@nirrozenbaum I am fine with `BindingPolicy`. I usually like short names but agree that this is more descriptive in this case.

**Comment by MikeSpreitzer** [comment]
The Slack poll for API group name has concluded. The winner is `control.kubestellar.io`.

**Comment by waltforme** [comment]
Start working on replacing API group `edge.kubestellar.io` with `control.kubestellar.io`.

**Comment by MikeSpreitzer** [comment]
@waltforme : what about the other API changes discussed here? It might be easiest to do them all in one swell foop.

**Comment by MikeSpreitzer** [comment]
Regarding @nirrozenbaum 's suggestion of renaming `Placement` to `BindingPolicy`, I could live with that. As for renaming `PlacementDecision`, I think it would be even more natural to rename it to `BindingDecision`.

**Comment by waltforme** [comment]
Sure I'd be happy to work on removing upsync and renaming ObjectTest, too.

For renaming of the two kinds, do we have conclusions or do we need more discussion?

**Comment by clubanderson** [comment]
naming is a good candidate for slack voting... please keep the community involved.

**Comment by nirrozenbaum** [comment]
@MikeSpreitzer @clubanderson @waltforme @ezrasilvera @pdettori 
please note that somewhere in the near future we're going to add status of the distribution to the CR that is called today `PlacementDecision`.  
the status will initially include the fields:
- were all wrapped object copied to mailbox namespaces (true/false)
- were all wrapped objects copied to all WECs (true/false)
- were all workload objects applied in the WECs.

now think about that - this is status of `Binding`, not of a `Decision`.
therefore, I believe the new name for `PlacementDecision` should be `Binding`.

**Comment by MikeSpreitzer** [comment]
I disagree with putting the current contents of `PlacementDecision` together in one object, for scalability and performance reasons. I think that instead of one object holding the complete list of destinations and complete list of workload objects, this should be doubly factored. The workload list and the destination list should be in separate objects. And we should not require either entire list to be in one object. Just like Kubernetes is replacing Endpoints with EndpointSlice, we should have a Slice type for the workload list and a Slice type for the destination list (which we had previously, called SinglePlacementSlice).

**Comment by MikeSpreitzer** [comment]
The previous discussion of status recognized some factoring of sorts of status. There is status about the distribution from WDS to mailbox. And status about the distribution from mailbox to WEC. And status about the attempts of the agent in the WEC to "make it so".

**Comment by nirrozenbaum** [comment]
@MikeSpreitzer to make a long story short - we do need to further discuss status reporting.
what I wrote above is just one of the options, I think we agree we will (eventually) have to report status. maybe it will be using summarization with a different CR, and maybe parts of the summarized status will be inside this object.

bottom line I was trying to say is that in order to leave room for adding status in the future, I think it's better to call it `Binding` rather than `BindingDecision`.

BTW, even without the status discussion I think `Binding` is a better name than `BindingDecision`. 
Initially we came with the name `Decision`, but thinking about it again, this name doesn't represent a desired state.
`Binding` is a name that represents desired state (the user would like to bind those object to those clusters).

**Comment by nirrozenbaum** [comment]
let's leave for now the status cause anyway that is out of scope in current version.

**Comment by MikeSpreitzer** [comment]
Yes, we need to discuss status more. What we need right now is just to leave enough options open.

In the current API, `Placement` and `PlacementDecision` are both binding constructs. The former identifies the what and the where by predicates, the latter by concrete lists.

Both expressions of desired binding are "desired state". Currently `Placement` has a little "reported state", `PlacementDecision` does not. As I mentioned earlier, it is not strictly necessary for each API object to have both "desired state" and "reported" state; that is only a common pattern, and there are established examples in Kubernetes and in uses of Kuberentes that do not follow that pattern.

**Comment by MikeSpreitzer** [comment]
So how about renaming as follows?
- `Placement` to `BindingPolicy`
- `PlacementDecision` to `BindingResolved`

**Comment by MikeSpreitzer** [comment]
For the Kind changes I am opening another Slack poll.

**Comment by MikeSpreitzer** [comment]
BTW, I think I maybe like "BindingResolved" a little better than "BindingResolution" because a "resolved binding" sounds like something that might have distribution status while "binding resolution" is squarely focused on just the resolution.

**Comment by nirrozenbaum** [comment]
@MikeSpreitzer I'm in favor of `BindingPolicy` instead of `Placement`.
for the second part, I really don't like the variations of `Resolution` and/or `Resolved`. 
why do we need to call a CR with `Resolution`/`Resolved`? 
Have you seen K8s resources called `Deployment` and `PodResolution`? no. 
it's just `Binding` exactly as it is just `Pod`.

the CR represents a binding (concrete, not a policy). 
the fact that the binding was resolved from BindingPolicy is nice and everything... but I haven't seen in any system CR called with resolved/resolution. this name sounds really strange to me.

**Comment by MikeSpreitzer** [comment]
@nirrozenbaum : The semantic relationship is unusual. A Pod is not the result of matching predicates against candidates. The only semantically similar example in Kubernetes that springs to mind is Service and Endpoints. An Endpoints _can be_ the concrete list of endpoints that result from evaluating criteria in a Service against the current population of Pods.

**Comment by nirrozenbaum** [comment]
what if Binding was not created as a result of a specific BindingPolicy?
what if we would like to distribute all CRDs and distribute all permissions but there is no BindingPolicy?

**Comment by MikeSpreitzer** [comment]
@nirrozenbaum : that would not change the fact that we have in our sights two ways of expressing bindings, one more concrete and one more of a pattern.

**Comment by MikeSpreitzer** [comment]
Regarding the Kind renaming, we took a vote in the community Slack channel and the winner is

- `Placement` becomes `BindingPolicy`
- `PlacementDecision` becomes `Binding`

**Comment by MikeSpreitzer** [comment]
Now that #1700 has merged, that leaves two API changes to make right now:

- Remove upsync
- Rename the Kinds

**Comment by waltforme** [comment]
#1717 removed upsync. Next we need to rename the Kinds.

**Comment by pdettori** [comment]
we should complete the renaming to complete the uc1-validation

**Comment by waltforme** [comment]
Yes, we should. @pdettori.
I created #1729 and labeled it with alpha.2 @ezrasilvera to specifically track the renaming.
