### ISSUE TITLE
feature: add parameter expansion customization to ks-0.20

### ISSUE THREAD

**Issue by pdettori** [kubestellar/kubestellar#1547]
### Feature Description

In addition to EdgePlacement, KubeStellar "Legacy" provides the ability to customize workloads distributed to the different WECs with the parameter expansion customization. We need to re-introduce this feature in ks-0.20.

### Proposed Solution

Evaluate if possible to re-use parts of the existing KS implementation or needs to be re-implemented from scratch.

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by ezrasilvera** [comment]
Verify with @clubanderson and @dumb0002 which customization is used in use-case1

**Comment by dumb0002** [comment]
@ezrasilvera, we are only using parameter expansion customization in the current version of the MCC stack

**Comment by pdettori** [comment]
Updated title and description to be more specific for what is needed in phase1

**Comment by ezrasilvera** [comment]
Covered by #1897
