### ISSUE TITLE
feature: reduce meaningless output in CICD test

### ISSUE THREAD

**Issue by effi-ofer** [kubestellar/kubestellar#1562]
### Feature Description

The current automatic test in CICD is outputing a line of text each time it's waiting for kubeflex to complete.  For example:
` Checking if a kubeflex kind instance already exists...`
Or 
`Waiting for shared backend DB to become ready...`

### Proposed Solution

Pipe standard output to /dev/null for certain commands.

### Want to contribute?

- [X] I would like to work on this issue.

**Comment by pdettori** [comment]
See https://github.com/kubestellar/kubeflex/issues/173

**Comment by effi-ofer** [comment]
This was "fixed" in PR #1565 but regressed back in PR #1572 since Mike is concerned about losing meaningful output from the kflex CLI.  Alternatives ways to handle this issue are by fixing the root issue in kubeflex or by optionally allow dumping of the output via a parameter.  Mike opened Issue #173 to handle so I am closing this issue.
