### ISSUE TITLE
feature: Standardize on newer version of Go

### ISSUE THREAD

**Issue by namasl** [kubestellar/kubestellar#1564]
**UPDATE**: Add a minimal version requirement in our Doc for developers

### Feature Description

Due to prior ties to KCP v0.11 we standardized on using Go v1.19, which was released in 2022-08-02. While we removed the requirement not to exceed this version (PR #1259), we are due to standardize on a more modern release.

### Proposed Solution

Standardize on Go 1.21(+)

### Want to contribute?

- [ ] I would like to work on this issue.

### Additional Context

[Kubernetes keeps a fairly tight tracking of supported Go versions](https://kubernetes.io/blog/2023/04/06/keeping-kubernetes-secure-with-updated-go-versions/), using [GODEBUG](https://tip.golang.org/doc/godebug) where necessary to maintain old behavior.

**Comment by pdettori** [comment]
Good point. We should check also images used for CI, the one currently running checks is using go 1.19.

**Comment by MikeSpreitzer** [comment]
Do we really need a `go` version check? The old one was nothing but a pain in the a--, until we disabled it.

**Comment by namasl** [comment]
Looks like PR #1627 covers all we'd need to do here.
