### ISSUE TITLE
bug: the one end-to-end test is in test/integration

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#1570]
### Describe the bug

Look at https://github.com/kubestellar/kubestellar/tree/ks-0.20/test . You will see just one subdirectory, `integration`, but the test it contains is an end-to-end test rather than an integration test.

### Steps To Reproduce

See above

### Expected Behavior

Things categorized in an ordinary way.

**Comment by effi-ofer** [comment]
Created PR #1574

**Comment by MikeSpreitzer** [comment]
Fixed in #1572
