### ISSUE TITLE
bug: Updating a Placement object and adding `wantSingletonReportedState: true` does not change the status

### ISSUE THREAD

**Issue by andreyod** [kubestellar/kubestellar#1580]
### Describe the bug

Updating the existing Placement object and adding `wantSingletonReportedState: true` to the spec, does not change the status on the WDS.

### Steps To Reproduce

1. Deploy Kubestellar. Follow https://github.com/kubestellar/kubestellar/blob/ks-0.20/docs/content/v0.20/README.md#setup including the optional step 3.a. In step 5 create and register only one workload cluster(cluster1).
2. Create a placement 
```shell
kubectl --context wds1 apply -f - <<EOF
apiVersion: edge.kubestellar.io/v1alpha1
kind: Placement
metadata:
  name: nginx-placement
spec:
  clusterSelectors:
  - matchLabels: {"location-group":"edge"}
  downsync:
  - objectSelectors:
    - matchLabels: {"app.kubernetes.io/name":"nginx"}
EOF
```
3. Deploy the app
```shell
kubectl --context wds1 apply -f - <<EOF
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/name: nginx
  name: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx
  labels:
    app.kubernetes.io/name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: public.ecr.aws/nginx/nginx:latest 
        ports:
        - containerPort: 80
EOF
```
4. Verify that the deployment has been created in cluster1
```shell
kubectl --context cluster1 get deployments -n nginx
```
5. Verify that the deployment status on wds1 is empty
```shell
kubectl --context wds1 get deployment nginx-deployment -n nginx -o yaml
``` 
6. Edit the Placement object and add `wantSingletonReportedState: true` to the spec
```shell
kubectl --context wds1 edit placement nginx-placement
``` 
7. Check again for the `nginx-deployment` status
```shell
kubectl --context wds1 get deployment nginx-deployment -n nginx -o yaml
```

### Expected Behavior

The update of the Placement object should trigger the status update for the `nginx-deployment` on wds1

**Comment by pdettori** [comment]
Thanks @andreyod - this is a scenario I did not test before, will need to investigate.

**Comment by namasl** [comment]
In addition to this I've found that the Deployment stays resident on all WECs after setting `wantSingletonReportedState: true`. If from the start the Location has `wantSingletonReportedState: true`, then only one cluster receives a Deployment.

**Comment by andreyod** [comment]
The root cause is that the singleton label is not propagated to the WorkStatus object when the Placement is updated.
The problem is that this WorkStatus is an api of status-addon and not Kubestellar.
So it make sense to update it in the status agent but I don't see what will trigger this update, because the status agent is basically watches the workloads on the WEC.
Another option is to update WorkStatus labels in the placement controller, but for this we will need to import WorkStatus api from the status-addon(may be OCM version conflicts), or to use dynamic client.

**Comment by andreyod** [comment]
@pdettori @MikeSpreitzer any comment on the preferred solution?

**Comment by andreyod** [comment]
Blocked by https://github.com/kubestellar/ocm-status-addon/issues/21

**Comment by MikeSpreitzer** [comment]
Currently the binding controller knows nothing about WorkStatus objects, right? As long as the status controller and binding controller are two distinct controllers, I think it is a simpler architecture to keep the binding controller away from the WorkStatus objects.

**Comment by MikeSpreitzer** [comment]
However, I am open to the argument that the WorkStatus and ManifestWork objects are just two parts of the same abstraction, and we should have just one controller above that abstraction (i.e., merge the binding controller and status controller into one).

**Comment by andreyod** [comment]
Fixed by https://github.com/kubestellar/kubestellar/pull/1825 and https://github.com/kubestellar/ocm-status-addon/pull/30
