### ISSUE TITLE
Enable the legacy workflows for release  0.14  branch

### ISSUE THREAD

**Issue by ezrasilvera** [kubestellar/kubestellar#1585]
Need to re-enable the workflows so people can validate fixes for release 0.14

**Comment by MikeSpreitzer** [comment]
I just did a survey of which workflows are **disabled** in the GitHub web UI. I found the following disabled.

- create KubeStellar-Syncer image
- docs-ecutable - ALL
- docs-ecutable - example1
- docs-ecutable - Mailbox
- docs-ecutable - Placement
- docs-ecutable - QS
- docs-ecutable - Scheduler
- docs-ecutable - Syncer
- docs-ecutable - User Quickstart Kind
-  docs-ecutable - User Quickstart Test
- docs-ecutable - Where Resolver
- Greetings

**Comment by MikeSpreitzer** [comment]
Is there any record of who disabled a given workflow, when, why?

**Comment by MikeSpreitzer** [comment]
The "create KubeStellar-Syncer image" workflow only reacts to workflow_dispatch events, so I am re-enabling it right now. Not that it matters, GitHub says it has never been run.

**Comment by MikeSpreitzer** [comment]
I have re-enabled the example1 and user-quickstart-test docs-ecutables in the GitHub web UI, now that their definitions in `main` exclude PR activity on `main`.

**Comment by MikeSpreitzer** [comment]
Not sure what to do about the Greetings workflow.

**Comment by MikeSpreitzer** [comment]
That missing example file was restored in #1661

**Comment by MikeSpreitzer** [comment]
I have re-enabled the remaining docs-ecutable workflows in the GitHub web UI, now that they only trigger for legacy branches and tags.

The only remaining question is what to do about the "Greetings" workflow.

**Comment by MikeSpreitzer** [comment]
I have re-enabled the Greetings workflow in the GitHub web UI.
