### ISSUE TITLE
feature: Clearly specify the synchronization semantics of finalizers on workload objects

### ISSUE THREAD

**Issue by dgrove-oss** [kubestellar/kubestellar#1589]
### Feature Description

Finalizers (https://kubernetes.io/docs/concepts/overview/working-with-objects/finalizers/) are a common pattern used to allow controllers to take action (eg cleanup resources) when an object is deleted.  Here are some scenarios that can occur where a precise definition of the Kubestellar synchronization semantics is neededl.

1. An object on a hub already has a finalizer (presumably added by a controller running on the hub).  A placement is then created such that the object is synchronized down to an execution cluster.  Is the finalizer down synched with the rest of the object's spec and metadata to the execution cluster?  If so, who is responsible for removing that finalizer when the object is deleted on the execution cluster (the operator may not be running on the execution cluster). 
2. As a follow on, what happens if a finalizer is added to the hub object after the initial down synchronization has completed.  Is this handled the same as a spec change on the hub (even though the finalizer is in the metadata, not the spec)?  Or are finalizers never downsynched (to avoid the problem noted above about a finalizer without a corresponding operator blocking deletion of the object). 
3. An object on an execution cluster is being synchronized by Kubesteller. An operator running on the execution cluster adds a finalizer to the copy of the object on the execution cluster.  
     a. Will the addition of the operator be preserved in the presence of (i) downsynched spec changes and (ii) downsynched metadata changes (if any, including the possible addition of other finalizers in the hub copy of the object)?
     b. Is the finalizer that was added in the execution cluster visible (upsynched) to the copy of the cluster in the hub object?
     c. If the finalizer is upsynched and the object is placed on multiple clusters, would that result in the finalizer being propagated to other execution clusters (including those that might not have the same operator installed)?  If so, this could also block deletion of the object on the other execution clusters since there would be no operator on those clusters that would be responsible for removing the finalizer.

### Proposed Solution

My guess is that the most reasonable semantics is that finalizers are never synchronized across clusters.

Therefore they will also never be overwritten during synchronization (and thus lost) and we will also avoid adding finalizers to objects in clusters that lack the operators to remove them when the objects are deleted.  

We should verify that this lack of synchronization is the semantics provided by OCM and document accordingly in the Kubesteller documentation.

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by nirrozenbaum** [comment]
Hi @dgrove-oss,
(1)+(2) answers - finalizers are not downsynced from the hub to the WECs by KubeStellar.
regarding (3):
(a) I need to check. this is an internal detail of how OCM agent was implemented. I'll get back to you with an answer. 
(b)+(c) - finalizer is not synced from WEC back to the hub. according to your description this finalizer was set locally on an edge cluster and therefore shouldn't be applied to all matching WECs of the original placement.

**Comment by pdettori** [comment]
@dgrove-oss  I just did a quick test and I can confirm that finalizers are preserved in the current implementation of KubeStellar with OCM Transport (snapshot v0.20.0-alpha.1 ) when the AppWrapper instance is updated (either in  the metadata or the specs). Here is how I tested:

1. Run scenario 6 as described in https://github.com/kubestellar/kubestellar/blob/main/docs/content/v0.20/examples.md#scenario-6---multi-cluster-workload-deployment-of-app-with-serviceaccount-with-argocd
2. Manually edit the app wrapper instance in cluster1 to add a finalizer 
```
kubectl --context cluster1 edit appwrappers 0001-aw-generic-deployment-3 
```
for example, add:

```
apiVersion: mcad.ibm.com/v1beta1
kind: AppWrapper
metadata:
  creationTimestamp: "2024-01-18T21:24:43Z"
  finalizers:
  - myfinalizer
  generation: 2
  ...
```  
3. Edit app wrapper in WDS2 to change the metadata, for example add a label
```
kubectl --context wds2 edit appwrappers.mcad.ibm.com 0001-aw-generic-deployment-3
```
4. Verify finalizer is still in the apprwapper in cluster1 and label was updated
```
kubectl --context cluster1 get appwrappers 0001-aw-generic-deployment-3 -o yaml
```
5. Repeat 3-4 this time changing the number of replicas for the deployment inside the app wrapper. Verify finalizer is still there and replicas have been updated.

I confirm that finalizer is not synced back to WDS.

**Comment by dgrove-oss** [comment]
Great.  Thanks for the quick turnaround!  Sounds like we have the "right" semantics.

**Comment by nirrozenbaum** [comment]
@dgrove-oss may I close the issue? or anything else is needed regarding this topic?

**Comment by pdettori** [comment]
@dgrove-oss @nirrozenbaum let's leave it open just so I remember to include in the docs

**Comment by pdettori** [comment]
Closing in favor of #1640
