### ISSUE TITLE
bug: Placement object's `spec.numberOfClusters` is ignored

### ISSUE THREAD

**Issue by namasl** [kubestellar/kubestellar#1594]
### Describe the bug

When creating a Placement object in the WDS that includes a `spec.numberOfClusters` parameter with a value less than the total number of matching WECs, all WECs still receive the workload.

### Steps To Reproduce

Follow [Scenario 1](https://github.com/kubestellar/kubestellar/blob/ks-0.20/docs/content/v0.20/README.md#scenario-1---multi-cluster-workload-deployment-with-kubectl), but replace the 2nd command box with the following, which requests that only 1 cluster receive the workload:
```kubectl --context wds1 apply -f - <<EOF
apiVersion: edge.kubestellar.io/v1alpha1
kind: Placement
metadata:
  name: nginx-placement
spec:
  clusterSelectors:
  numberOfClusters: 1
  - matchLabels: {"location-group":"edge"}
  downsync:
  - objectSelectors:
    - matchLabels: {"app.kubernetes.io/name":"nginx"}
EOF
```

At the last step of Scenario 1 you will see that both clusters received the deployment.

### Expected Behavior

If the `spec.numberOfClusters` value is less than the total number of WECs that match the placement, then a random subset of WECs totaling the provided value should receive the workload.

**Comment by pdettori** [comment]
yes, `spec.numberOfClusters` is in the spec but it has not been implemented - we have not agreed yet with @MikeSpreitzer and @ezrasilvera if we should keep that feature in the spec or not.
