### ISSUE TITLE
bug: ManifestWork objects not getting removed automatically

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#1598]
### Describe the bug

I am opening this for @namasl , who reported the following.

> ManifestWorks are not getting removed automatically, and so the WEC Deployments stay active. This is possibly related to why editing the Placement on the WEC from "wantSingletonReportedState: true" to "false" will go from one to multiple WEC deployments, but doing the reverse from "false" to "true" does not remove any deployments (as in #1580).

### Steps To Reproduce

See Nick.

### Expected Behavior

The ManifestWork objects are implementation details that users should not have to see or manipulate.

**Comment by pdettori** [comment]
@MikeSpreitzer this seems a duplicate of https://github.com/kubestellar/kubestellar/issues/1596 , which has more context.

**Comment by MikeSpreitzer** [comment]
See #1596 instead of this.
