### ISSUE TITLE
feature: Document the CLI alternative to syncing Argo CD apps

### ISSUE THREAD

**Issue by waltforme** [kubestellar/kubestellar#1601]
### Feature Description

In the examples, one of our scenario is to use Argo CD to populate workloads into WDSes. In that scenario, our current document instructs users to navigate to the Argo CD UI to play with and sync Argo CD Applications, which is nice.

We can make it even better by introducing an alternative to syncing Argo CD apps, which is using the `argocd` CLI. By doing that we can
- save a few steps for those users who don't have immediate access to the UI, e.g. who exercises the scenario on a VM via SSH;
- make it easier if one day we want to automate the scenario in our tests.

### Proposed Solution

Confirm the CLI alternative with latest kflex, then document it.

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by pdettori** [comment]
@waltforme could you please open a PR to update the current doc with the Argo scenario for that?

**Comment by waltforme** [comment]
Sure! Will do.

**Comment by ezrasilvera** [comment]
@waltforme Thanks - please link the PR to this issue . Thanks

**Comment by waltforme** [comment]
Sure! Linked #1609.
