### ISSUE TITLE
feature: rehome the status addon somewhere in the KubeStellar organization

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#1605]
### Feature Description

KubeStellar currently uses a "status addon" that lives in github.ibm.com/dettori/status-addon ; it should be somewhere under github.com/kubestellar/ . Currently the whole status addon has too many dependencies to go in g/k/k/ . Perhaps factor?

### Proposed Solution

Do something about it.

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by pdettori** [comment]
I am proposing to host status-addon on https://github.com/kubestellar/status-addon. 
@MikeSpreitzer @ezrasilvera @nirrozenbaum @clubanderson  if you have any concern please let me know.

**Comment by nirrozenbaum** [comment]
maybe I would call it ocm-status-addon (cause it's based on ocm addon-framework).
this name is self explained rather than having to explain in README that you've used that framework.
that's only a suggestion so feel free to accept/reject.

you have my vote, +1 from my side.

**Comment by ezrasilvera** [comment]
@pdettori @nirrozenbaum So is that going to be part of the transport?   Every transport will need to implement it (e.g., our syncer) ?

**Comment by nirrozenbaum** [comment]
I'll put here my initial thoughts. 
no doubt we need to further discuss this topic of status collection which was not addressed yet in current transport design.

IMO this implementation is OCM specific and can work as long as we use OCM based transport.
as of today, in the use case where singleton status is required the team are fine with using OCM as transport, so it gives a solution for this use case.
in general as part of the generic transport layer, we need to define a generic way to collect status updates from the WEC and require some pluggable logic, same as we did with objects distribution from hub to WECs.
as we stated in the previous transport discussions - the current design answers downsync only. no upsync nor singleton status which is a private case of status collection (we make progress of transport design&impl in a phased approach).
I believe once we have a generic design implemented we can replace the above status addon. 

I'd be happy to hear what Paolo thinks about this topic.

**Comment by pdettori** [comment]
@nirrozenbaum I agree that we need to further discuss. At this time we have a clear use case for [MCAD](https://github.com/project-codeflare/multi-cluster-app-dispatcher) that requires full singleton status and we need to support it, we can use the approach in `ocm-status-addon` which is currently working and discuss how to generalize once we spec out  other transport implementations.

**Comment by pdettori** [comment]
Since no one has been opposing this proposal, I will start working on bringing `ocm-status-addon` under the https://github.com/kubestellar/ org

**Comment by pdettori** [comment]
Community vote was closed with 9 votes in favor, will go ahead and open source

**Comment by pdettori** [comment]
Repo has been open sourced at https://github.com/kubestellar/ocm-status-addon
