### ISSUE TITLE
bug: multi-cluster-deployment e2e test is flaky

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#1610]
### Describe the bug

test/e2e/multi-cluster-deployment does not _wait_ for the ManifestWork objects to appear, it just looks once and fails if they are not present at that time.

The causes the GitHub workflow pr-test-multicluster.yml to flake.

### Steps To Reproduce

Look at the history of that workflow, see many failures for PRs prior to #1603 (which is not merged yet and fixes this problem). For example, https://github.com/kubestellar/kubestellar/actions/runs/7592862229/job/20682698792

### Expected Behavior

A test does not insist that any controller get its job done in a very short amount of time.

**Comment by effi-ofer** [comment]
Now that PR #1603 is merged, can we close this issue?

**Comment by MikeSpreitzer** [comment]
Oh, I see I had a typo on the line that would do the close automatically.
