### ISSUE TITLE
feature: choose a testing framework for the e2e tests

### ISSUE THREAD

**Issue by effi-ofer** [kubestellar/kubestellar#1612]
### Feature Description

We are currently using shell scripts for end to end testing.  Is that the best approach?  Should we switch to something else?

### Proposed Solution

Choose a testing framework.

### Want to contribute?

- [X] I would like to work on this issue.

**Comment by effi-ofer** [comment]
Ginkgo is a widely used BDD framework.  It is used by kubevirt and OCM for e2e testing.  I am looking at it as a contender to replace the shell scripts.

**Comment by pdettori** [comment]
@effi-ofer do you have a pointer to a e2e test written with Ginkgo for one of the two projects mentioned, just to get a feel of how it would look like?

**Comment by MikeSpreitzer** [comment]
We need documentation for contributors showing a few scenarios of exercising the version of the repo that they are working on (not a previous release). The current bash-based E2E tests do that (contributors can be presumed to be able to read and understand bash). I have no objection to adding tests written in other ways, but we should retain instructions for contributors and these instructions must be tested in CI. Having E2E tests written in bash accomplishes that.

**Comment by effi-ofer** [comment]
> @effi-ofer do you have a pointer to a e2e test written with Ginkgo for one of the two projects mentioned, just to get a feel of how it would look like?

Sorry @pdettori for replying only now.  Check out the PR associated with this issue.

**Comment by effi-ofer** [comment]
> We need documentation for contributors showing a few scenarios of exercising the version of the repo that they are working on (not a previous release). The current bash-based E2E tests do that (contributors can be presumed to be able to read and understand bash). I have no objection to adding tests written in other ways, but we should retain instructions for contributors and these instructions must be tested in CI. Having E2E tests written in bash accomplishes that.

Once the pluggable transporter is fully online, we expect the examples in the associated PR will pass and then we can revisit this.

**Comment by effi-ofer** [comment]
We choose ginkgo for e2e and the tests will be delivered in PR #1713.  Another issue (#1865) has been opened to add bash based examples.  I am therefore closing this issue.

**Comment by MikeSpreitzer** [comment]
I will also comment in #1865. I think that it is important to retain at least one example of how a contributor would issue shell commands to exercise their own local copy/version of the system.
