### ISSUE TITLE
feature: add resiliency testing

### ISSUE THREAD

**Issue by effi-ofer** [kubestellar/kubestellar#1617]
### Feature Description

Add resilience testing. 

### Proposed Solution

https://github.com/kubestellar/kubestellar/blob/main/docs/content/v0.20/examples.md#scenario-5---resiliency-testing

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by ezrasilvera** [comment]
@effi-ofer I guess it's not the proposed solution but rather the proposed flow that will be implemented as CICD workflow ?

**Comment by effi-ofer** [comment]
Handled by PR #1713
