### ISSUE TITLE
Fix a typo on the pre-reqs documentation page

### ISSUE THREAD

**Issue by cwiklik** [kubestellar/kubestellar#1626]
### Describe the bug

There is a typo on the pre-reqs page
Typo:  % instead of $

### Steps To Reproduce

Go to:  https://github.com/kubestellar/kubestellar/blob/main/docs/content/v0.20/pre-reqs.md

Section describing ocm installation

Its says: export PATH=%PWD/ocm:$PATH

### Expected Behavior

Should be: export PATH=$PWD/ocm:$PATH

**Comment by effi-ofer** [comment]
https://github.com/kubestellar/kubestellar/pull/1647 created.

**Comment by effi-ofer** [comment]
Fixed by #1647
