### ISSUE TITLE
Documentation improvement for step 3 on page example-wecs.md 

### ISSUE THREAD

**Issue by cwiklik** [kubestellar/kubestellar#1634]
### Describe the bug

When following steps on example-wecs.md it was not clear to me on step 3 what status of Pending means. Is it Pending creation or Pending approval? It actually means Pending approval but this should more explicit.  

### Steps To Reproduce

Go to: https://github.com/kubestellar/kubestellar/blob/main/docs/content/v0.20/example-wecs.md

In step 3 it says to issue a command:  watch kubectl --context imbs1 get csr
and wait until the certificate signing requests (CSR) for both cluster1 and cluster2 are created, then ctrl+C.

What you see is that both CSRs are in Pending state

### Expected Behavior

Explain that pending means pending approval in the next step. Perhaps something like, CSRs are pending until you approve them in step 4

**Comment by andreyod** [comment]
Fixed by https://github.com/kubestellar/kubestellar/pull/1668
