### ISSUE TITLE
feature: Add more automated tests to CI/CD

### ISSUE THREAD

**Issue by pdettori** [kubestellar/kubestellar#1655]
### Feature Description

Currently we have two automated tests (multi-cluster-deployment and singleton-status) that test core features of KubeStellar. This is a good start but we need to test also other usage scenarios. 

### Proposed Solution

We can think of other tests as variations built as extensions of multi-cluster-deployment. These tests are designed to exercise different parts of the code:

0. Test update of an object - deliver a deployment, increase the number of replicas from 1 to 2, verify they are updated on the WEC.

1. Create object 1 with label A and label B, object 2 with label B, and a Placement that matches labels A AND B, and verify that only object 1 matches and is delivered.

2. Create object 1 with label A, object 2 with label B, and a Placement with 2 object selectors, one with label A and one with label B, and verify both objects get delivered.

3. Similar to 2, but test also specifying other criteria for selection of objects: namespace, api group, resource, name

4. Start from `multi-cluster-deployment` scenario, delete the placement and verify that the object is deleted from the WECs.

5. Start from `multi-cluster-deployment` scenario, change the placement objectSelector to no longer match and verify that the object is deleted from the WECs.

6. Start from  `multi-cluster-deployment` scenario, delete the object and verify it is deleted from the WECs.

7. Create an object and two placements that match the object (overlapping placements). Verify that by deleting one of the placements the object stays in the WEC, but when the second placement is deleted the object is deleted from the WEC.

8. Create an object and a placement that does not match,  change the placement to match, then verify that the object gets delivered.

9. Write a test for https://github.com/kubestellar/kubestellar/issues/1541 (which has been fixed)

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by pdettori** [comment]
@ezrasilvera note that test 0 is particularly important in light of the discussion in https://github.com/kubestellar/kubestellar/pull/1667

**Comment by andreyod** [comment]
I think that the second part of test 7 is the same test case as test 4. 
So we can drop test 4, or change test 7 to be: Create an object and two placements that match the object (overlapping placements). Verify that by deleting one of the placements the object stays in the WEC.

**Comment by nirrozenbaum** [comment]
adding more to Paolo's list:
10. label cluster1 with `env:dev` and cluster2 with `env:dev`. create a placement that selects some objects and in the cluster selectors use `env:dev`. verify that selected objects were received in both clusters. now remove/change the label in cluster2 (e.g, `env:prod`). verify selected objects are removed from cluster2.

**Comment by pdettori** [comment]
> So we can drop test 4, or change test 7 to be: Create an object and two placements that match the object (overlapping placements). Verify that by deleting one of the placements the object stays in the WEC.

@andreyod, yes, but then we need also to make sure that by deleting also the second placement the object is deleted by the WEC, otherwise we are not testing what 4. is testing (delete placement deletes the object in the WEC)

**Comment by pdettori** [comment]
@nirrozenbaum good point, we need also tests for changes in the cluster selectors labels.

**Comment by ezrasilvera** [comment]
@pdettori Yes we are looking on how to section it so it will be optimal in terms of creating the environment.

**Comment by nirrozenbaum** [comment]
@ezrasilvera @pdettori please have a look also on points @MikeSpreitzer raised in issue #1674.
it's worth automating tests that cover those as well.

**Comment by pdettori** [comment]
@nirrozenbaum - right, we should definitely have tests to cover some of those scenarios in #1674 - let's try to prioritize and start with the scenarios that might be more important for our initial use case - for example 6 (adding/removing clusters after the kubestellar controller is started) seems at the top of the list to me.

**Comment by nirrozenbaum** [comment]
@pdettori yes, I agree. I created an issue #1679 earlier today and assigned Ezra who will take solve that point.

**Comment by MikeSpreitzer** [comment]
(A) I see an attempt to list all the input deltas to consider. I also see _some_ recognition of the importance of testing a given delta in different frames (other bits of state) but not a thorough plan.  What would be a thorough plan, anyway? I think maybe a randomized test would be the best approach here.

(B) All the above discussion focuses on completely sequential scenarios. But a Kubernetes controller generally has concurrent workers and concurrent changes coming in. Such scenarios are also a concern. And very hard to test thoroughly.

(C) None of the above scenarios include process or node crashes or transient failures. These are also concerns.

**Comment by andreyod** [comment]
Partially implemented by https://github.com/kubestellar/kubestellar/pull/1678

**Comment by effi-ofer** [comment]
@nirrozenbaum I added a flavour of your (10) and (11) to PR #1713 except I haven't added tests that test changes following changes to the OCM's managedcluster objects.  It can be argued whether we want to test OCM's CRDs.
