### ISSUE TITLE
Architecture document for the status adds on

### ISSUE THREAD

**Issue by ezrasilvera** [kubestellar/kubestellar#1670]
We need to have  an architecture document for the status adds on that will include:
1. High level diagram of the participating controllers and objects
   * Description of the policy (what is updated, on which condition)
   * Dependency on external packages/solutions (e.g., is it OCM only ? ) 
3. Relation to the clusters (hubcluster, wec cluster, etc..) 
4.

**Comment by pdettori** [comment]
@ezrasilvera all of the above is currently in the #1669 PR - there is a section on the status add on and a diagram & description of the interaction with the other modules - hub cluster, wec cluster etc. Please have a look at the PR and let's decide if we need to extract that part into a separate doc.

**Comment by ezrasilvera** [comment]
@pdettori Thanks. Added my comments there + will add a link in the PR to this issue so it is closed when the PR is merged.
