### ISSUE TITLE
feature: handle update to an object that was selected by a placement

### ISSUE THREAD

**Issue by nirrozenbaum** [kubestellar/kubestellar#1671]
### Feature Description

Suppose you create a deployment in the WDS. The placement controller writes the placement decision, the transport controller sees there is a new (or updated) placement decision, it wraps it up and deliver it to the mailbox namespace. Perhaps there are also other objects in that placement decision that are targeted by the placement. 
At this point, assume that the deployment is updated - e.g., changing the number of replicas from 1 to 3, or added an annotation/label. How is the transport informed of the change in the deployment in spec/annotations/labels? 

### Proposed Solution

There are several options to tackle this issue:
Option (1) - the placementdecision might have a `revision` field for every object that exists in the `ClusterScope` and `NamespaceScope` lists. this way, when placement controller gets an event, if something has changed in the specific object the placement controller increments the revision field of the changed object. This triggers an event in transport controller that will wrap up the objects and take if from there to the WECs.
(suggested by Nir & Maroon)

Option (2) - same as option (1), but instead of having a `revision` field per object, we have a single `revision` field per the two lists (ClusterScope + NamespaceScope). if any object in those lists has changed, placement controller increments the revision field which in turn triggers an event in transport controller, continues the same as in option (1).
(suggested by Nir&Maroon)

Option (3) - the placement controller is only responsible for maintaining correct lists in the PlacementDecision, and the transport controller is responsible for maintaining the correct relationships between workload objects and wrapped-up contents in the mailboxes.
(suggested by Mike)

Option (4) - implement the go interface defined for transport based on the work API and for every pluggable transport implement the code in a separate go project / package and import that code/package in KubeStellar controller manager. Assuming we have other transport plugins, the selection of one or the other would be based on some flag on the KS controller manager. We may think this approach may make more difficult to add other plugins, but after all, how many do we expect. Most likely we will have the OCM-based one and the KS syncer-based one.
(suggested by Paolo)

Option (5) - Expose the go transport interface as a gRPC interface. The transport would run in a separate container in the same pod as the placement controller or in a separate pod and exposed as a service. Whenever the placement controller sees an update on the tracked objects, it runs all the placement matching logic for objects and clusters and invokes the gRPC transport service which takes care of the transport part.
(suggested by Paolo)

 

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by nirrozenbaum** [comment]
I would like to add my two cents on some of the points:
my opinion on option (3) - 
in our pluggable-transport design there is a clear separation of responsibilities between the placement controller and the transport controller.
placement controller is responsible for watching placement and all objects that are included in any of the placements. the placement controller should maintain the list of objects to distribute and list of destinations. upon any change in the objects or destinations, this controller should handle the change.

the transport controller is responsible for watching placement decision, fetch the objects as listed in the decision and distribute it to the destinations as listed in the decision object.

option (3) as suggested above violates this separation of concerns. it's the placement controller responsibility to handle any change in placement or any of the objects the are selected by a placement.
how would you trigger reconciliation of the transport controller upon a change in a deployment as described in problem statement? If I understand correctly this suggestion, that means transport will need to watch all objects, but that is what placement controller does.
so now do you expect both controllers will watch all objects? it doesn't sound reasonable to me.

**Comment by nirrozenbaum** [comment]
adding my opinion on option (4):
first point, I'm not sure I got the whole idea so I'd be happy to get more explanation. 
second point which was mentioned by Paolo - Paolo mentioned we may think it makes it harder to add more plugins. I think this approach not only makea it harder to add other plugins, but in fact kills the pluggability.
if we need to add an option to a flag when we want to add another option, this is not pluggable.
pluggability in the open community means that others from the community can implement the transport interface and plug in their favorite transport without touching KS code.

**Comment by nirrozenbaum** [comment]
adding my opinion on option (5):
In current design and implementation transport controller has two infromers.
the first one is the placement decision. the second one is the wrapped object (in the transport space).
This allows us to watch if there was any change in the wrapped object (e.g., a mistake done manually) and overwrite it by the controller back to the values we want/need.
In addition, one of the basic things we wanted to do in next PRs is to add status of the distribution that is listed in the placementdecision.
the basic fields we thought are valid are - 
- was object written in the mailbox namespace (true/false).
- was the wrapped object propagated to the WEC (true/false)
- were all the objects in the wrapped object applied successfully in the WEC(true/false).
the first one in the list is something transport controller knows by itself and can update.
the other two fields should be taken from the wrapped object and propagated back up. since we have the informer on wrapped object we get the status events and can update the status. 
how would you handle these points using this option @pdettori ?

**Comment by ezrasilvera** [comment]
Just general comment - as far as I understand this flag impact the underlying implementation but is not directly used by the user. This means it doesn't impact on the actual API and user behavior.  This means that the final decision is not very critical as long as it doesn't have major faults/issues. I suggest we first try to remove the options we all think are unacceptable or have major issues and then if we have more than one final options we leave it to the team (@nirrozenbaum ) to decide.

**Comment by nirrozenbaum** [comment]
> Just general comment - as far as I understand this flag impact the underlying implementation but is not directly used by the user. This means it doesn't impact on the actual API and user behavior. This means that the final decision is not very critical as long as it doesn't have major faults/issues. I suggest we first try to remove the options we all think are unacceptable or have major issues and then if we have more than one final options we leave it to the team (@nirrozenbaum ) to decide.

@ezrasilvera you are correct. this is internally used but has no impact on users/API.

another very important aspect I think we should all consider is simplicity. and when I say simplicity I mean - 
what is the simplest option that works simply and straight forward that is also **aligned with current design and will not trigger major changes.** if someone suggests a solution to this issue that requires changing the whole code, that is not simple :)

**Comment by MikeSpreitzer** [comment]
I really do not like building all the plugins into a binary under central control (option 4); that is not very pluggable.

I also do not like option 5; that makes a very expensive (chatty) interface, and once you think through concurrency and failure scenarios and handle the all correctly you get very complicated (expensive in development and maintenance costs) code.

**Comment by MikeSpreitzer** [comment]
The difference between option (3) and options (1&2) is where certain responsibilities lie. Each one violates the other's assignment of responsibilities.

**Comment by MikeSpreitzer** [comment]
If I understand correctly, the point of doing option (1) or (2) instead of (3) is to avoid the memory costs of the transport controller caching the workload objects in its memory. To save this memory cost, instead the transport controller re-reads every workload object referenced in a PlacementDecision every time any of those objects changes and also on every startup of either the placement or transport controller; this imposes CPU and network and memory (serialization and deserialization thrash the heap) costs on the transport controller and workload apiserver(s). I am not sure this is a net win. Apart from performance, I think options (1) and (2) can function correctly. So I can accept either.

I see little performance difference for the transport controller between options (1) and (2); for both of them, all the objects referenced by a PlacementDecision have to be read whenever there is any change in the PlacementDecision.

**Comment by pdettori** [comment]
I think that for 0.20 we can live with option 1 or 2. It should allow us to deliver within the February timeframe. Since this is not UX but is more like an internal implementation detail we can defer to after 0.20 how to improve / optimize / the design and implementation. As long as we are test and data driven and we have enough test coverage for the usage pattern that matter for the key use cases we should be able to refactor without fear.

**Comment by nirrozenbaum** [comment]
@MikeSpreitzer @pdettori @ezrasilvera thank you for quick response and comments.
To summarize the thread, I think for now we will go with option (2) just due to simplicity, having one revision field instead of one per object. There is not a big difference between (1) and (2) as Mike explained.
I will modify the current PR and rename the field to `revision` in order to be less confusing.

**Comment by vMaroon** [comment]
@MikeSpreitzer regarding last point, the optimization you refer to under option 3 can be maintained under option 1 (transport can read objects with changed versions only).

But I support Nir in going for the simple option (opt 2), since optimizations talk can be relevant when optimizations are planned for implementation.
