### ISSUE TITLE
bug: Things the placement controller does not do (right)

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#1674]
### Describe the bug

In reviewing #1669 I noticed the following problems with the placement controller. Caution: this is based on reviewing the textual description, not the actual code.

1. An update to a workload object that removes some Placements from the matching set is not handled correctly. (covered by #1694)
2. If a workload object is deleted, or changed to remove some Placements from the matching set, while the controller is down this will not be handled correctly. (covered by #1694)
3. A Placement update that (a) removes workload objects or clusters from their respective matching sets and (b) happens while the controller is not running, is not handled correctly. (covered by #1694)
4. A cluster update that (a) removes Placements from its matching set and (b) happens while the controller is not running, is not handled correctly. (covered by #1679 )
5. An update to the labels of a Namespace object does not trigger reconsideration of the workload objects in that namespace (even though matching can depend on Namespace labels --- this one is my bad, introduced in #1525).  (covered by #1682 )
6. The placement controller does not react to add/change/delete of clusters. (covered by #1679 )
7. Nothing ensures that only one worker is working on a given ManifestWork at a time. This is a problem because different concurrent workers are not guaranteed to all be working with the same version of all the relevant objects, so there is no guarantee about what the outcome will be. This controller is full of dead reckoning about what it did in the past, rather than getting that information from the ManifestWork objects themselves. (covered by #1695)

### Steps To Reproduce

Read #1669 

### Expected Behavior

A design that works in the presence of concurrent activity with failures and retries.

**Comment by nirrozenbaum** [comment]
@MikeSpreitzer excellent points. 
I think it's important to add test cases that cover all these points.
can you add or reference this issue in #1655?

**Comment by vMaroon** [comment]
I opened an issue #1682 and assigned to @ezrasilvera.
After introducing this fix, point (5) should be solved.

**Comment by ezrasilvera** [comment]
@MikeSpreitzer if you agree that 4,5,6 are covered by the linked issues, feel free to remove them from the list in this issue.

**Comment by MikeSpreitzer** [comment]
@ezrasilvera : since we have taken to referring to the OP's items by number, I am loathe to change the numbers. It looks like we have started on the path of enhancing each item with a reference to the issue that covers it, when there is such an issue.

**Comment by ezrasilvera** [comment]
> @ezrasilvera : since we have taken to referring to the OP's items by number, I am loathe to change the numbers. It looks like we have started on the path of enhancing each item with a reference to the issue that covers it, when there is such an issue.

Sounds OK to me.  I like to have focused issues with 1-2 PRs that cover them, rather then a large general issue with many unrelated issues.

**Comment by MikeSpreitzer** [comment]
Closing this in favor of the various smaller issues now referenced in the (edited) OP.
