### ISSUE TITLE
feature: all returned errors should be wrapped and not returned as is 

### ISSUE THREAD

**Issue by nirrozenbaum** [kubestellar/kubestellar#1677]
### Feature Description

in all the code that was pulled from KS light into KubeStellar - the errors are returned as is instead of wrapping them.
This is against best practices and also in many of the cases doesn't explain the problem.

### Proposed Solution

we should fix this by wrapping all errors in all existing code.
we should also pay attention in PRs that add new code that errors are wrapped.
example for wrapping errors can be seen here:
https://github.com/kubestellar/kubestellar/blob/main/pkg/transport/generic_transport_controller.go#L360

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by vMaroon** [comment]
after my placement-decision logic is in, I'll refactor the full placement code.

**Comment by MikeSpreitzer** [comment]
I do not think that all errors have to necessarily be wrapped. If the error already has sufficient explanatory value, I do not see a need to wrap it.

**Comment by nirrozenbaum** [comment]
@vMaroon @MikeSpreitzer can we close this issue?
is it done?

**Comment by vMaroon** [comment]
@nirrozenbaum not all in code are wrapped, but I'd say most are wrapped (and some of the kept direct forwarding instances are fine). I think we can close this, it will be finalized as part of future refactoring work.
