### ISSUE TITLE
feature: missing informer on cluster CR

### ISSUE THREAD

**Issue by nirrozenbaum** [kubestellar/kubestellar#1679]
### Feature Description

current placement code is missing informer on managed cluster CR.
as a result of this issue, changes on labels of MCs are not triggering recalculation of placement and distribution/removal of objects from WECs 

### Proposed Solution

we should add informer on ManagedCluster CR in the placement code to fix this probelm.

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by ezrasilvera** [comment]
Thanks @nirrozenbaum Will look into it

**Comment by ezrasilvera** [comment]
We need to be carful here as this is a global controller so it will impact the scalability of number of managed clusters. Need to keep in mind possible sharding approaches in the future.

**Comment by effi-ofer** [comment]
This is what I am implementing to resolve this issue: an informer that monitors changes in the labels of the managedcluster objects on the imbs. The placement controller will need to listen on this informer and recalculate the PlacementDecisions (once Maroon delivers) or re-evaluate the Placements (under the existing pre- PR #1681).

Scalability wise, the informer shares the scalability issues of the imbs.  When we shard for wecs we will have multiple imbs-es which means the placement controller will need to know which imbs-es to use.  The wec scalability requires some thought and is beyond the scope of this issue.
