### ISSUE TITLE
 Instrumentation of data collection for KubeStellar

### ISSUE THREAD

**Issue by dumb0002** [kubestellar/kubestellar#168]
### Feature Description

To add instrumentation to collect metrics for kcp-edge deployments

### Proposed Solution

1.  Build an automation to deploy and configure instrumentations (e.g., Prometheus, Grafana, etc ) to collect metrics for edge-mc deployment

2. Build an automation that is easy to extend to collect any additional metric required in the future

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by dumb0002** [comment]
**Metrics Collection:** 

1. Syncer throughput: 
   - assuming that in each direction the syncer transports desired/reported state in chunks that each contain all it has to read/write about a single object
   - compute histogram vector of observations of chunk size indexed by APIGroup, APIVersion, and Resource or Kind

2. Syncer communication with the APIserver (e.g., create/update/delete objects, etc.)

3. Latency: 
    - how long from write at origin server to successful corresponding write to the other copy by the syncer?

**Comment by ezrasilvera** [comment]
@dumb0002 for latency we probably need both down-syncer and up-syncer.  Need to define exactly what are the two events that you want to measure latency (what exactly you mean by "write" on server)

**Comment by dumb0002** [comment]
IRIS instrumentation is now being used to collect metrics for KubeStellar. Hence, this issue can be closed
