### ISSUE TITLE
feature: singleton status support under multi-object wrapping

### ISSUE THREAD

**Issue by vMaroon** [kubestellar/kubestellar#1680]
### Feature Description

Currently, the status addon handles creating WorkStatus objects that are watched for propagating object statuses in the WDS.

Need to check if it handles multi-wrapped objects correctly, therefore this should be checked and updated.

### Proposed Solution

Update the status addon to generate individual WorkStatuses for multiple-objects in ManifestWorks.

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by andreyod** [comment]
Today the status addon is already iterate over the list of workload objects in the manifestwork, but a workstatus object is created with the same name as the manifestwork, so only 1 workstatus is created. To support multi-wrapped objects we have to change the naming and also need to validate the update/delete flows.

**Comment by andreyod** [comment]
PR https://github.com/kubestellar/ocm-status-addon/pull/7 fixed the naming.
Follow up issue for the update flow: https://github.com/kubestellar/kubestellar/issues/1724
