### ISSUE TITLE
bug: object, referenced from work queue, not found should not be reported as an error

### ISSUE THREAD

**Issue by pdettori** [kubestellar/kubestellar#1683]
### Describe the bug

Current code in:

https://github.com/kubestellar/kubestellar/blob/e516d75cc05dcfe16b041d8616381ceaaaea4f1a/pkg/placement/controller.go#L390-L402

Reports object not found as an error. See conversation in https://github.com/kubestellar/kubestellar/pull/1669#pullrequestreview-1851912129 for more details

### Steps To Reproduce

Look at the code

### Expected Behavior

Should not log as an error

**Comment by nirrozenbaum** [comment]
should be fixed as part of placement code changes for transport
