### ISSUE TITLE
bug: clarify what happens with placement labels when WantSingletonReportedState is used

### ISSUE THREAD

**Issue by pdettori** [kubestellar/kubestellar#1688]
### Describe the bug

From @MikeSpreitzer (see comment https://github.com/kubestellar/kubestellar/pull/1669#pullrequestreview-1852771689 )

The text that I am commenting on here says unequivocally that there is a label added for every matching Placement. Is this really true even if some of those matching Placements have WantSingletonReportedState == true ? Also, the following bullet speaks simply of "each cluster". Is that really each cluster matching any Placement that matches the object, regardless of WantSingletonReportedState ? I doubt it. I think these pieces of text need updating. Is anything undone in the WantSingletonReportedState == true case for clusters that match a Placement that matches the object but are not selected for delivery? The text should say.

### Steps To Reproduce

Check arch doc after merging.

### Expected Behavior

Should clarify better what happens with placement labels when `WantSingletonReportedState` is used.

**Comment by vMaroon** [comment]
@pdettori is this still relevant?

Currently, when that field is set, the selected workload objects receive a label:
`managed-by.kubestellar.io/singletonstatus = $(binding-policy-name)`

And this is both documented and implemented.
