### ISSUE TITLE
bug: add a section to docs with known limitations

### ISSUE THREAD

**Issue by pdettori** [kubestellar/kubestellar#1691]
### Describe the bug

We are aware of a number of [limitations](https://github.com/kubestellar/kubestellar/issues/1674) in the current code, and should warn users.

### Steps To Reproduce

Look at https://github.com/kubestellar/kubestellar/issues/1674

### Expected Behavior

Should inform the users on what to expect with the most current snapshots/releases

**Comment by pdettori** [comment]
@ezrasilvera don't we have already this in https://github.com/kubestellar/kubestellar/blob/main/docs/content/direct/release-notes.md ? can we close this issue ?

**Comment by ezrasilvera** [comment]
Yes. we have release notes for this
