### ISSUE TITLE
bug: incorrect handling of Placement and workload objects in placement controller

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#1694]
### Describe the bug

From reviewing the architecture document, and first noted in #1674, problems in that controller include the following.

1. An update to a workload object that removes some Placements from the matching set is not handled correctly.
2. If a workload object is deleted, or changed to remove some Placements from the matching set, while the controller is down this will not be handled correctly.
3. A Placement update that (a) removes workload objects or clusters from their respective matching sets and (b) happens while the controller is not running, is not handled correctly.

### Steps To Reproduce

This was from based on reviewing the architecture document.

### Expected Behavior

Controller maintains intended eventually consistent relations between input and output objects.

**Comment by waltforme** [comment]
I'm reading https://github.com/kubestellar/kubestellar/pull/1669#discussion_r1472208727 and tracking to this issue. I'm so curious about the "change/deletion happens while the controller is down" case. How are we going to solve this?

**Comment by nirrozenbaum** [comment]
@MikeSpreitzer now that pluggable transport was merged, can we check which of the points still happen and which is fixed?
/cc @vMaroon 
/cc @ezrasilvera

**Comment by vMaroon** [comment]
@MikeSpreitzer I think this is fixed, right?
