### ISSUE TITLE
bug: placement controller may do concurrent work on one wrapped object

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#1695]
### Describe the bug

From review of the architecture document, I noticed that the placement controller may have concurrent goroutines working on the same ManifestWork --- and not necessarily with the same versions of their inputs. Also, the controller makes too many assumptions about the current state of a given ManifestWork object rather than reading it from the apiserver (or a local cache of that).

### Steps To Reproduce

A reliable procedure to demonstrate the problem would require more fine-grained and precise control over timing than the technology offers.

### Expected Behavior

Only one goroutine should work on a given output object at a time, using the latest inputs.

**Comment by ezrasilvera** [comment]
@MikeSpreitzer Is this still valid?

**Comment by MikeSpreitzer** [comment]
Yes, this is still valid. The problem is in the older part of the binding controller, of course, the part that is creating/updating/deleting ManifestWork objects.

**Comment by MikeSpreitzer** [comment]
Here is the code analysis. For a given workload objects, there are two different items that can appear in the workqueue and cause work to be done on that object's ManifestWork. One is a Key that refers to the object. Another is a Key that refers to a BindingPolicy, where the Key's DeletedObject is non-nil. Look at `func (c *Controller) handleBindingPolicy` and see where it calls `c.handleBindingPolicyFinalizer` and `c.cleanUpObjectsNoLongerMatching`. Both of those will delete ManifestWork objects. Also: inquiring minds want to know why there are two paths to delete those objects for the same reason.
