### ISSUE TITLE
bug: The Kubestellar Controller Manager is crashing on OCP for CP of type "host"

### ISSUE THREAD

**Issue by cwiklik** [kubestellar/kubestellar#1697]
### Describe the bug

While trying to test Scenario#2 on OCP, I'd noticed that neither the AppWrapper CRD nor the CR were being downsynced to the WECs. This scenario involves a control plane of type host. On closer inspection the controller manager is crashing:

k get pods -n wds2-system
NAME                                              READY   STATUS             RESTARTS       AGE
kubestellar-controller-manager-675ffffd74-9kvch   1/2     CrashLoopBackOff   40 (36s ago)   3h24m

In the log, there are a bunch these:

I0201 20:15:55.356108       1 trace.go:236] Trace[1503902376]: "Reflector ListAndWatch" name:k8s.io/client-go@v0.28.2/tools/cache/reflector.go:229 (01-Feb-2024 20:15:38.046) (total time: 17309ms):
Trace[1503902376]: ---"Objects listed" error:<nil> 17309ms (20:15:55.356)

### Steps To Reproduce

Install kubeflex and kubestellar on OCP
Onboard WEC(s)
Follow setup for Scenario#2 described here: https://github.com/kubestellar/kubestellar/blob/main/docs/content/v0.20/examples.md

### Expected Behavior

Both the AppWrapper CRD and the CR should be down synced to the WEC(s). 

### Additional Context

Paolo's explanation:
"
in a CP of type k8s there are about 40 resource types. In this OCP I found about 395. Since the controller starts an informer for each,the api server does throttling and the informers never complete loading the caches. I need to give an option for running in OCP host to specify the resource to track rather than all
"

**Comment by pdettori** [comment]
Changed the title to reflect that this problem is specific to a control plane type "host" as WDS, where the hosting cluster is OpenShift.

**Comment by pdettori** [comment]
A simple approach that does not change the current UX for Placement (or BindingPolicy) is to allow to specific a list of GVRs at startup. If the list is present, only informers for the GVRs in the list are started. If the list is not present (which is the default) and is what works for the "denatured" k8s CP, then most informers for server preferred resources are started as it's done today.

**Comment by pdettori** [comment]
the startup option may have the form:

```
--resources="appwrappers.mcad.ibm.com/v1beta1, inferenceservices.serving.kserve.io/v1beta1"
```

When this flag is present, and if the selected resources are available as server preferred resources, only informers for those resources are started.

**Comment by pdettori** [comment]
This makes sense in scenarios where the hosting clusters has the WDS role as there are many resources that may not make sense anyway to track as there are active controllers on the hosting cluster already for those resources.

**Comment by MikeSpreitzer** [comment]
Is the throttling really by the apiserver, or is it client-side self-restraint?

What do you mean by "the informers never complete loading the caches"? Slowing throttling does not explain "never".

Asking the user to do more configuration is a painful UX.

**Comment by pdettori** [comment]
> Asking the user to do more configuration is a painful UX
That is true, but still, look at how many api resources are available on a stock OCP:
```
$ kubectl api-resources | wc -l
     395
```

versus KubeFlex's stock k8s API server:

```
$ kubectl api-resources | wc -l
      56
```

There are definitely too many in the OCP hosting cluster case that we would have a need to track.

**Comment by pdettori** [comment]
> Is the throttling really by the apiserver, or is it client-side self-restraint?

How can you tell? I am including the complete log if that helps.

[wds2-system-kubestellar-controller-manager-675ffffd74-9kvch.log](https://github.com/kubestellar/kubestellar/files/14131761/wds2-system-kubestellar-controller-manager-675ffffd74-9kvch.log)

> What do you mean by "the informers never complete loading the caches"? Slowing down does not explain "never".

The message "All caches synced" never shows up. The controller crashes before that happens (could be OOM Killed)

**Comment by MikeSpreitzer** [comment]
I four "Waited for 8.597854136s due to client-side throttling..." in that log, with increasingly long delays reported.

I see 49 reports of a LIST operation taking a long time, with the time increasing from about 10 to about 19 seconds.

It would be worth knowing why the controller crashes.

Asking the user to provide a list of GVRs sounds just too painful to me. Surely the user should not have to specify the Version part. I suspect that just taking a list of API Groups would enable enough filtering.

I still have not seen any real quantification of "enough" or "too much".

**Comment by ezrasilvera** [comment]
@pdettori I think this is not related to OCP , it's related to using the HOST as a CP where that host has many build in resources. I assume this can also happen with "external" mode depending on which external space you import into KF. 
I think it's not only an issue of wait time but also wasted resources in terms of memory & CPU.  
In addition,  when using the host (or other k8s clusters that also have additional controllers) - the user can't use that space to deploy resources that are not denatured in that space into the WECs (i.e., resources that that "space" may be acting upon) , this means that for theses resources there is no point in bringing up informers in the first place. 
I'm not sure that any of the solutions suggested in this thread are acceptable from UX perspective :(

**Comment by ezrasilvera** [comment]
To add to that - what will happen if a user creates WDS of type "host" and tries to deploy k8s resources into the WEC (Pods, deployment, etc..)  This obviously will be a bad thing - but do we actively prohibit it today and print some error/warning ?

**Comment by pdettori** [comment]
@MikeSpreitzer 

> Asking the user to provide a list of GVRs sounds just too painful to me. Surely the user should not have to specify the Version part. I suspect that just taking a list of API Groups would enable enough filtering, if we were to go that way.

Yes, I agree, but see my comments above, the most common scenario for "host" is a wrapper CRD. The value of KS here is "bring your own wrapper". It is clear that the most value would come when using the `k8s` CP, as that is something that can be controlled and there are no restrictions or need to provide such list of resources.

**Comment by nirrozenbaum** [comment]
I don't think this is the correct way to handle the issue. users should not be specifying list of allowed resources.
this list obviously might change over time in a long running environment and we don't want to require controller restart for updating this list.

a better solution might be the following -
at startup we DO NOT create informers for all CRDs. we create informer only for Placement (or with the new name - BindingPolicy), so upon startup of placement controller it is started only with informer on BindingPolicy.
during runtime, we create informers dynamically for resources that appear in at least one BindingPolicy.
so all other informers should be created by demand and not upfront.

by doing this, users of the system do not need to tell the system which resource to watch, but instead users should use KS regular APIs to let the system which objects they want to distribute to WECs. the placement controller should implicitly understand and create only the required informers dynamically.
