### ISSUE TITLE
bug: convertLabelSelectorsToMap is broken two ways

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#1699]
### Describe the bug

`pkg/ocm/ocm.go:convertLabelSelectorsToMap` is broken in three ways.

1. The return type can not represent the OR functionality that is the semantics in https://github.com/kubestellar/kubestellar/blob/ad2f86d60cf5b27a88a16839d419d152b346ff5a/api/edge/v1alpha1/types.go#L26-L27
2. https://github.com/kubestellar/kubestellar/blob/ad2f86d60cf5b27a88a16839d419d152b346ff5a/pkg/ocm/ocm.go#L190 will fail for a selector that is not simply an AND of key=value pairs. There are indeed more complex label selectors. See https://v1-28.docs.kubernetes.io/docs/concepts/overview/working-with-objects/labels/#label-selectors .

### Steps To Reproduce

This bug report comes from code inspection.

### Expected Behavior

Any valid user input can be handled.

**Comment by effi-ofer** [comment]
@MikeSpreitzer you mentioned pkg/ocm/ocm.go:convertLabelSelectorsToMap is broken in two ways, but I only see two listed.  Please let me know if I am missing anything.
