### ISSUE TITLE
Remember to update the API group (in KS/KS) for WorkStatus

### ISSUE THREAD

**Issue by waltforme** [kubestellar/kubestellar#1701]
The WorkStatus API is defined in the status addon repo. Then in the KS/KS repo, the KubeStellar controller manager uses its GVR to conditionally start the status controller.

However, because of a [documented difficulty](https://github.com/kubestellar/kubestellar/blob/71e77d281d86741b05a46f3e5ae5c0a08940a398/pkg/util/unstructured.go#L48-L51), the GVR of WorkStatus is explicitly coded today in KS/KS, not imported.

So, if we change the API group of WorkStatus from `edge.kubestellar.io` to something else in the status addon repo, we should remember to make changes in the KS/KS repo accordingly.

**Comment by pdettori** [comment]
we have completed the open sourcing of ocm-status-addon, so we should be able now to work on that part of refactoring

**Comment by pdettori** [comment]
https://github.com/kubestellar/ocm-status-addon/pull/24 is ready for review. As soon as it is merged and a new release for ocm-status-addon is published this task can be completed.
