### ISSUE TITLE
bug: `make ko-build-local` is not completely 'local'

### ISSUE THREAD

**Issue by waltforme** [kubestellar/kubestellar#1706]
### Describe the bug

In the sense that the built image may not fit the build platform. There is an example in the 'Steps To Reproduce' section.

### Steps To Reproduce

1. On a linux/arm64 platform, in the root dir of the KubeStellar repository, do the following.
```
. test/e2e/common/setup-shell.sh
test/e2e/common/setup-kubestellar.sh
```
2. Check the log of the KS controller manager.
```
kubectl --context kind-kubeflex -n wds1-system logs deploy/kubestellar-controller-manager
```
The output should be similar to
```
exec /ko-app/kubestellar-operator: exec format error
```

### Expected Behavior

`make ko-build-local` produces image for the local platform.

### Additional Context

Looks like 'ko build' defaults to amd64. We may specify `--platform` to override the default.

**Comment by MikeSpreitzer** [comment]
I do not have that problem.  Attached is a log of my success (I eventually ran into a problem with a pre-existing kubeconfig context, but that was after starting the kubestellar controller manager).

[ks-setup-success.log](https://github.com/kubestellar/kubestellar/files/14168251/ks-setup-success.log)

**Comment by MikeSpreitzer** [comment]
However, on closer inspection, I see that the built image is indeed for amd64 even though my laptop is arm64. Apparently my container runtime pulls in the ability to run amd64 on arm64.

**Comment by pdettori** [comment]
Yes, Mac M* have the rosetta translation by default -  https://www.makeuseof.com/what-is-rosetta-2-mac/

**Comment by MikeSpreitzer** [comment]
So why does @waltforme have a problem?

But the main surprise is that `ko build` does not seem to build for the host platform by default.

**Comment by waltforme** [comment]
I think I saw the problem but others do not is that I have a arm based system, which doesn't do emulation. And others probably were running amd64 images on mac, which does the emulation.

**Comment by waltforme** [comment]
@MikeSpreitzer There was 1714 BTW.
