### ISSUE TITLE
Design & implement infrastructure for large scale testing of KubeStellar

### ISSUE THREAD

**Issue by dumb0002** [kubestellar/kubestellar#171]
### Feature Description

To design & implement an scalable infrastructure to test and experiment with KubeStella at scale

### Proposed Solution

1. Use AWS to build and implement the scalable infrastructure
2. Use Ansible automation to design and implement automation for an scalable infrastructure with the following features:
   a) easily tunable (e.g., scale up & down, etc)
   b) ease to destroy & replicate
   c) infrastructure similar to clients deployments.
   d) optimal in terms of cost so that we can easily carry out large scale experiments (e.g, simulation of 1M+ devices)

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by dumb0002** [comment]
<img width="1413" alt="kcp-edge-architecture-aws" src="https://user-images.githubusercontent.com/25727844/226696877-b7bca1c0-77aa-4a49-9346-a8540b70a7e2.png">

**Comment by ezrasilvera** [comment]
@dumb0002 I think it's important to understand which components are going to be tested. If it's the core region than you probably want to have some "mock" or "virtual" representative of edge regions so you can have a very large scale tests with very low cost and effort.

**Comment by dumb0002** [comment]
@ezrasilvera for PoC2023q1 were are targeting a relatively small scale for the edge region. We have plans to simulate or virtualize the edge regions for the large scale experiments with ~1M+ edge endpoints.

**Comment by clubanderson** [comment]
@dumb0002 is this 'closed' or 'done'?  Closed means work has stopped, done means it is completed.

**Comment by clubanderson** [comment]
no longer valid
