### ISSUE TITLE
feature: Finish harmonizing on "kubestellar controller-manager"

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#1727]
### Feature Description

We still have references to "kubestellar-operator".  For example, in the container image and Helm chart names.

### Proposed Solution

Consistently use "kubestellar operator" or consistently use "kubestellar controller-manager". Do not use a mixture of the two.

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by MikeSpreitzer** [comment]
I think we should do this as we put the new release process into place, so that we do not suffer unnecessarily from ghcr.io ownership conflicts.

**Comment by pdettori** [comment]
working on this, with the intent to make then the new snapshot with the new naming scheme.
