### ISSUE TITLE
feature: Rename two Kinds in our API

### ISSUE THREAD

**Issue by waltforme** [kubestellar/kubestellar#1729]
### Feature Description

We decided by a [vote](https://kubernetes.slack.com/archives/C058SUSL5AA/p1707155424985459?thread_ts=1706903581.862249&cid=C058SUSL5AA) to rename two Kinds in our API so that
- `Placement` becomes `BindingPolicy`;
- `PlacementDecision` becomes `Binding`.

Right now (immediately after merging of #1681), there are 1728 occurrences of 'placement', including 492 occurrences of 'placementdecisions', case insensitive.

I was suggested to create an issue to specifically track the renaming so here it is.

### Proposed Solution

We have a two-step plan for the renaming.

1. (Small and hard part) Update everything in api/ and test/, plus whatever necessary code changes, to get the new API code available and controllers passing the e2e tests. So that others can begin to contribute their new code growing on the fresh APIs.
2. (Big and easy part) Update everything left: variable names, file/directory names, (go) docs, etc. Also make sure we don't touch things that should not be renamed.

I'll create two PRs, one for each of the two steps, to complete the plan. If there are any (transient) inconsistencies between code and doc in the middle, we should make explicit statements about those inconsistencies.

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by waltforme** [comment]
We have a two-step plan for the renaming.
1. (Small and hard part) Update everything in api/ and test/, plus whatever necessary code changes, to get the new API code available and controllers passing the e2e tests. So that others can begin to contribute their new code growing on the fresh APIs.
2. (Big and easy part) Update everything left: variable names, file/directory names, (go) docs, etc. Also make sure we don't touch things that should not be renamed.

I'll create two PRs, one for each of the two steps, to complete the plan. If there are any (transient) inconsistencies between code and doc in the middle, we should make explicit statements about those inconsistencies.

**Comment by vMaroon** [comment]
@waltforme please note that you must also lookup "decision" on its own.
