### ISSUE TITLE
feature: finalize documentation, build and testing for transport controller

### ISSUE THREAD

**Issue by nirrozenbaum** [kubestellar/kubestellar#1731]
### Feature Description

in order to run transport controller it should use a specific transport plugin implementation.
- we need to document how to run the ocm based transport controller and what it is (how is it working, what it does), 
- how to build the images of ocm based transport controller. 
- change all flows (including tests) to use the transport controller 

### Proposed Solution

do the above

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by MikeSpreitzer** [comment]
So the title of this PR should not only speak of "document", since changing the E2E tests is also required.

**Comment by nirrozenbaum** [comment]
> So the title of this PR should not only speak of "document", since changing the E2E tests is also required.

done
