### ISSUE TITLE
feature: design and document procedure for making KS releases and snapshots

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#1732]
### Feature Description

We need to be able to make KubeStellar snapshots and releases, and do so without breaking users of previous ones. Other repositories in the kubestellar org should also have their own release processes.

What is a snapshot? Maybe it is a release that we do not advertise widely because it does not have all the user-visible features that we want in the next release. Maybe it is a git tag and equal "image" (published container and published Helm chart(s)) tag with instructions.

One part of the problem is just defining the criteria that a release process should meet.

### Proposed Solution

I do not have a proposal yet.

### Want to contribute?

- [x] I would like to work on this issue.

**Comment by MikeSpreitzer** [comment]
Here is one thing giving us grief: IF we distribute a Helm chart through an OCI "image" repository then the OCI "image" tag has to equal the "version" in the Chart.yaml (https://helm.sh/docs/topics/registries/#oci-feature-deprecation-and-behavior-changes-with-v370). This means, for example, that we can not tell users to refer to such an "image" using a branch release tag UNLESS the chart also declares the branch release to be its "version" --- which would mean that as we advance along a release branch (make new patch releases) the chart gets overwritten.

**Comment by MikeSpreitzer** [comment]
Here is an initial draft of the criteria for a release process. Note that this set of criteria is not internally consistent.

- MUST HAVE: A user of a given snapshot or release does not get perturbed by our work on later snapshots or releases. Not even if they restart something. Not even if they tear their environment all the way down and re-create it using the instructions for the old release that they are using. This includes having stable instructions and other documentation on the web somewhere.
- STRONGLY DESIRED: The contents of a release or snapshot come from one git commit, tagged with a git tag that is identical to the release identifier.
- STRONGLY DESIRED: A git tag is immutable: once it is associated with a given git commit, the tag is not later re-associated with a different commit.
- STRONGLY DESIRED: Use [semantic versions](https://semver.org) for release identifiers.
- DESIRED: have a concept of release branch. That is a series of patch releases that share the same major.minor version number.
- DESIRED: The user-visible container image references (and possibly others) use a tag that identifies a release branch (e.g., `release-0.20`) rather than one specific release. This makes it easier to deliver bug fixes, for example. This does _NOT_ mean that there are no additional container image tags; indeed it would probably be positively good to have additional tags that identify specific builds, for example.

**Comment by MikeSpreitzer** [comment]
The above draft is not internally consistent: sometimes it speaks about a user locking onto an individual release, sometimes it speaks of a user using a release branch. I think the latter is more important. Hence the second draft below.

This draft focuses only on releases, supposing that a snapshot is either not-highly-advertised release or something that needs a distinct set of its own goals.

- MUST HAVE: have a concept of release branch. That is a series of releases that share the same major.minor version number.
- MUST HAVE: A user of a given release release branch does not get perturbed by our work on other release branches. Not even if the user restarts something. Not even if they tear their environment all the way down and re-create it using the same instructions that they have been using. This includes having stable instructions and other documentation on the web somewhere.
- MUST HAVE: the contents of `main` always work, including having accurate instructions for users and developers. This does not mean that `main` documents all release branches; quite the opposite, I think.
- STRONGLY DESIRED: The contents of a particular release come from one git commit, tagged with a git tag that is identical to the release identifier.
- STRONGLY DESIRED: A git tag is immutable: once it is associated with a given git commit, the tag is not later re-associated with a different commit.
- STRONGLY DESIRED: Use [semantic versions](https://semver.org) for release identifiers.
- DESIRED: The user-visible container image references (and possibly others) use a tag that identifies a release branch (e.g., `release-0.20`) rather than one specific release. This does _NOT_ mean that there are no additional container image tags; indeed it would probably be positively good to have additional tags that identify specific builds, for example.

**Comment by MikeSpreitzer** [comment]
- DESIRED: the process of adding a new patch release to a release branch includes testing in-place migration from an earlier release in that branch to the new release.

**Comment by MikeSpreitzer** [comment]
There is useful background information in `docs/content/v0.20/packaging.md`. And an expansion of it in #1723 .

**Comment by eaepstein** [comment]
I think that "reliable" snapshots could be useful for delivering advanced function to selected users. But there are practical issues: all the work necessary to have a fully working and correctly documented snapshot and creating all the snapshot artifacts.  Perhaps if creating artifacts could be ~fully automated with only limited reliability, e.g. no guarantees that all documentation was correct, the effort of creating snapshots could be small enough.

A similar alternative that other projects use is to simply update artifacts tagged "latest" and be discriminating about when these artifacts are updated.

Ideally the release process would require little manual effort so that releases can be created as needed.

**Comment by eaepstein** [comment]
Comments with regards the list started in  https://github.com/kubestellar/kubestellar/issues/1732#issuecomment-1934680370

1. MUST HAVE: have a concept of release branch. That is a series of releases that share the same major.minor version number.
=> meaning: Minimal effort to create patch releases?
2. MUST HAVE: A user of a given release release branch does not get perturbed by our work on other release branches...
=> meaning: All release artifacts required for a running system are immutable, and all 3rd party artifacts are referenced by version?
3. MUST HAVE: the contents of main always work, ...
=> I agree that this is invalid, i.e. NOT REQUIRED
4. STRONGLY DESIRED: The contents of a particular release come from one git commit ...
=> why isn't this MUST HAVE?
5. STRONGLY DESIRED: A git tag is immutable: once it is associated with a given git commit ...
=> agree but only after the associated release is made
6. STRONGLY DESIRED: Use semantic versions for release identifiers.
=> meaning major.minor.patch?
7. DESIRED: we can test a release before making it an actual release.
=> should be MUST HAVE
8. DESIRED: The user-visible container image references ...
=> no can grok
9. DESIRED: the process of adding a new patch release to a release branch includes testing in-place migration ...
=> does "in-place migration" mean support for updating a running system?

**Comment by MikeSpreitzer** [comment]
@eaepstein:

I would say that keeping down the effort needed to create a release is a criterion on its own. I should have written it down as such.

The main part of my thinking behind wanting a concept of release branch is so that we can both (a) say that a release is an immutable thing and (b) get bug fixes into users' hands without making a new minor release (that is, fix bugs by making patch releases). With users latched onto release branches rather than particular releases, that threads this needle.

> All release artifacts required for a running system are immutable, and all 3rd party artifacts are referenced by version?

That would be my preference, but there is a problem with achieving that and also letting a user focus on a release branch. For a Helm chart being published through an OCI registry, a user wanting to use that chart has to fully specify the exact release to use, not a release branch.

> the contents of main always work ... NOT REQUIRED

Why not?

Regarding semantic versions: they are described at [semver.org](https://semver.org/) , which allows more stuff after the patch.

**Comment by MikeSpreitzer** [comment]
Fans of goreleaser are going to be disappointed by saying the git tag is applied after making the release, because goreleaser requires applying the git tag first. I do not consider using goreleaser to be a requirement.

**Comment by eaepstein** [comment]
@MikeSpreitzer
> > the contents of main always work ... NOT REQUIRED
> 
> Why not?

Because of the potential extra burden of any manual testing required. Agree that it is a good idea if comprehensive release testing can be automatically run on PRs.

> in-place migration

Now this is an important subject! Does OCM support in-place migration? What support does OCM have for managed cluster migration? Or even OCM support for managed clusters running different versions of k8s?

**Comment by ezrasilvera** [comment]
for goreleaser I think you can create a fake tag to initiate the release process and then re-tag. Also what the issue in tagging first (and remove if the release creation fails) ?

**Comment by MikeSpreitzer** [comment]
Helm charts are particularly difficult with respect to versioning, because each version of a chart is distinct. You can not have two versions (e.g., `0.20.1` and `0.20`) that refer to the same chart. That is because _inside_ the chart, in Chart.yaml, is an assertion of the chart's version!

Helm charts simply do not support a concept of a release branch that is a series of immutable things. You either use immutable un-aliased chart versions, or a mutable "version".

**Comment by MikeSpreitzer** [comment]
@eaepstein , regarding "DESIRED: The user-visible container image references (and possibly others) use a tag that identifies a release branch (e.g., release-0.20) rather than one specific release". What I am trying to talk about there is instructions for a user about how to use a release branch. Such instructions need to refer a user to a git and/or container image and/or published Helm chart _version_, and the thought is that we would direct the user at a release branch rather than an individual release. The verbiage about the tags appearing in such instructions not being the only tags is so that there can _also_ be tags for individual releases.

Sadly, as noted above, Helm does not play nice here.

**Comment by eaepstein** [comment]
> (a) instructions for how to use the latest stable release, and (b) instructions for how to use the current contents of main.

Contributors may also try to validate function with private applications, and they rely on current usage instructions. But it is OK to make a change that invalidates current usage instructions?  Is the same OK for architecture documentation?

>  What I am trying to talk about there is instructions for a user about how to use a release branch.

I thought a release branch is a mechanism to apply bug fixes to a previous release as a patch release. A patch could be to fix a performance problem that was affecting latency or utilization.  If a user wants to reproduce a previous result they cannot depend on an artifact tagged 'latest'.

**Comment by MikeSpreitzer** [comment]
I agree that the tag `latest` is just an invitation to a bunch of pain.

I was thinking that a tag like `release-0.20` could be useful for a user to use. Even though individual releases in that branch would be identified as `0.20.0`, `0.20.1`, and so on --- and the next release branch would be `release-0.21`.

**Comment by eaepstein** [comment]
> I was thinking that a tag like release-0.20 could be useful for a user to use.

Agreed, except for example, someone doing performance tests on things peripheral to KS and doesn't want changes due to a new patch level to affect measurements.

I was also confused by the reference to a branch rather than a semantic version, as runtime usage accesses release artifacts not source branches.

But assuming the team adheres to the expectation that all minor versions > 0.20 are backwards compatible, then specifying only major version 0 should be more useful than pinning to a specific minor version. This also assumes that the artifacts tagged with just major version=0 are always updated to the latest released version 0.*.*

**Comment by MikeSpreitzer** [comment]
Major version 0 is special in that it explicitly denies the usual backward-compatibility in its progression of minor versions.

I agree that a user should be able to lock onto a specific release. That would mean that picking up a bug fix involves explicitly moving to another release (presumably a later patch release of the same major.minor version). This is a bit of change in the goals, let me try to compose a new set.

**Comment by MikeSpreitzer** [comment]
Latest draft of criteria.

- MUST HAVE: A user selects an individual release to use.
- STRONGLY DESIRED: Use [semantic versions](https://semver.org) for release identifiers.
- MUST HAVE: A user of a given release release does not get perturbed by our work on other releases. Not even if the user restarts something. Not even if they tear their environment all the way down and re-create it using the same instructions that they have been using. This includes having stable instructions and other documentation on the web somewhere.
- - MUST HAVE: have a concept of release branch. That is a series of releases that share the same major.minor version number. This means that contributors can contribute bug fixes to existing release branches, and new patch releases in those branches can be made.
- MUST HAVE: the contents of `main` always work. This includes passing CI tests. This means that the instructions in `main` are always accurate. This does not mean that `main` documents all release branches; quite the opposite, I think. The instructions in `main` might document how a contributor works with `main`. The instructions in `main` might document what is the latest stable release and how a user can use it.
- STRONGLY DESIRED: The contents of a particular release come from one git commit, tagged with a git tag that is "v" + the release identifier.
- STRONGLY DESIRED: A git tag is immutable: once it is associated with a given git commit, the tag is not later re-associated with a different commit.
- DESIRED: we can test a release before making it an actual release.

**Comment by MikeSpreitzer** [comment]
Let me illustrate the self-reference difficulties we have been giving ourselves. Look at the picture in https://github.com/kubestellar/kubestellar/blob/main/docs/content/v0.20/packaging.md#outline-of-publishing and the release process goals above . To be fully concrete, one of the things I would expect is that the contents of release 1.2.3 are built from the git commit tagged `v1.2.3`.

1. Suppose we have a commit XXX... that we want to make into a release.
2. Build container image(s) from commit XXX... and tag them `1.2.3` or `v1.2.3`.
3. Test them. Oops, what test refers to images tagged `1.2.3`? None. OK, suppose we somehow have tests that take the tag as a parameter, somebody/something somehow is responsible for carefully invoking the tests with the right tag parameter.
4. Supposing the container images pass their tests, now we need to update the Helm chart(s) so that their defaults for image references use tag `1.2.3`.  Oops, now we made a new git commit, it is now YYY... rather than XXX....
5. Supposing that somehow the previous "oops" is not a problem, test the new Helm chart(s). What tests the chart(s) with version `1.2.3`? Nothing in commit XXX... or YYY... unless those tests take the chart version as a parameter. Suppose we do that, and something/somebody is somehow responsible for invoking these tests correctly.
6. Update the user-facing instructions to refer to Helm chart(s) version `1.2.3`. Oops, now we made another change in git, creating commit ZZZ...

**Comment by MikeSpreitzer** [comment]
Suppose we have some document in this git repository that says "the latest stable release is X.Y.Z". Well, suppose that is what the document says in the git branch named `main`. What does that document say in a release branch? Suppose it is a release branch for a major.minor that has not yet been tested enough for us to know whether or not to call it "stable". We want to continue testing that release branch. Thus I conclude that testing of a release can not be directed by a file that declares the latest stable release.

**Comment by MikeSpreitzer** [comment]
FYI, here is a way to find the latest tag applied to any commit in a given branch.

```
mspreitz@mjs13 kubestellar % git checkout main #demonstrate querying different branch
Switched to branch 'main'
Your branch is up to date with 'upstream/main'.

mspreitz@mjs13 kubestellar % git for-each-ref --count=1 --sort=-creatordate 'refs/tags/*' --format='%(refname)' --merged=release-0.14
refs/tags/v0.14.2
```

**Comment by eaepstein** [comment]
> Suppose it is a release branch for a major.minor that has not yet been tested enough ...

One approach: assume the tag for the new release has been chosen, and that the image and helm chart artifacts will include that tag info in their identifier. Release testing uses artifacts with the correct identifier. If an error is found and git must be updated, a new git tag is be created, affected artifacts with correct identifiers created and used to overwrite the previous. This iterates until testing succeeds, at which point a git tag with the desired ID is then be associated with the working git tag.

If there is another approach, the steps should be describable in a similar fashion.

**Comment by MikeSpreitzer** [comment]
@eaepstein: If I understand you correctly, you are suggesting that for some git tags, the associate commit changes over time. I would prefer to avoid that. I think that we can avoid that with no comparative disadvantage. I think your suggestion involves creating a release before testing it, and the alternatives do too. As long as we can identify a release with an identifier like `0.20.0-rc1` and then, if testing is successful, add the identifier `0.20.0`. I think the textual format of those tags makes it immediately obvious what the quality and implications of them are.

**Comment by eaepstein** [comment]
@MikeSpreitzer   OK, that sounds fine. What about the artifacts? For pre-release testing, what container image and helm chart names are used? Are they pointing at artifacts with 0.20.1-rc1?

**Comment by MikeSpreitzer** [comment]
This also connects to the website, since that also has specific technology for release branches.

**Comment by MikeSpreitzer** [comment]
@eaepstein : #1758 proposes naming test releases `$something-rc$number`. I think the meaning of that is immediately clear to everyone.

**Comment by eaepstein** [comment]
@MikeSpreitzer Sorry I was not clear on the issue. For example, release testing will use release helm charts that reference container images. The helm charts are in the git repo. If the charts reference test image tags, how will they be changed to use the official release image tags without updating git and requiring a new git tag?

I'm confused about the ordering of steps: git release tag, image building, release testing, updating helm charts, etc.

**Comment by MikeSpreitzer** [comment]
@eaepstein : Let's pursue this in #1758 . I think that you should already find there an answer about how the _published_ Helm chart of release 1.2.3 references the published image of release 1.2.3. I will review and may add some emphasis. As for step-by-step instructions, it is simple: add a git tag --- that is all that a contributor needs to do in order to trigger publishing of release artifacts.

**Comment by MikeSpreitzer** [comment]
@eaepstein : I have updated #1758

**Comment by MikeSpreitzer** [comment]
Another part of the problem is divergence/convergence between `main` and a new release branch as that new minor release is first being created and debugged. Generally there will be bugs found and fixed during the release process (`-rc1` will have bugs, fixed in `-rc21, and so on). How do these fixes appear in `main` too? The simplest would be to only create the new release branch after release testing and bug fixing have reached a successful conclusion with creation of new release `X.Y.Z` (sans `-rc$N`). Another approach would involve creating the release branch earlier, but (somehow; manually?) keep it pointing to the same commit as `main` until after `X.Y.Z` is anointed. Yet another approach, with even more manual chores, would be to cherry-pick from one branch to the other. This last is what has to happen anyway with fixes made after `X.Y.Z` is anointed --- but we have historically had less of these than fixes done during the test/fix cycle leading up to release `0.Y.0`.
