### ISSUE TITLE
bug: E2E tests put new content under old container image tag

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#1740]
### Describe the bug

https://github.com/kubestellar/kubestellar/blob/79f0aecda1fad14b08297d809d5853e637fb170e/test/e2e/common/setup-kubestellar.sh#L64 makes my local docker hold an image name:tagged `ghcr.io/kubestellar/kubestellar/kubestellar-operator:0.20.0-alpha.1` . But the contents of that image result from a local build of the local copy of the repo, which normally (e.g., when working with `main`) are different from the contents of the container image that you would get from `docker pull ghcr.io/kubestellar/kubestellar/kubestellar-operator:0.20.0-alpha.1` (i.e., what was built from the git commit tagged `v0.20.0-alpha.1`).

### Steps To Reproduce

1. `git checkout main`
2. `test/e2e/multi-cluster-deployment/run-test.sh`
3. `docker images`
4. Note the "IMAGE ID" (which is a prefix of the SHA256 digest) associated with `ghcr.io/kubestellar/kubestellar/kubestellar-operator:0.20.0-alpha.1`; when I tried it just now I got c7db62e7b814
5. Note the "CREATED" of that image; when I tried it just now I saw "8 hours ago".
6. `docker pull ghcr.io/kubestellar/kubestellar/kubestellar-operator:0.20.0-alpha.1`
7. `docker images`
8. Note that `ko.local/kubestellar-operator:0.20.0-alpha.1` now has a different "IMAGE ID" and an older build date; when I tried it just now I saw "0e86f9c16de2" and "4 weeks ago"

### Expected Behavior

Building `main` does not overwrite, even locally, an image name:tag that is supposed to identify an old snapshot or release.

**Comment by MikeSpreitzer** [comment]
@pdettori 
@francostellari

**Comment by MikeSpreitzer** [comment]
Correction: The "image ID" is not necessarily a prefix of the SHA256 digest. But still, you can see from inspection of the makefile and E2E test scripts that they will build current contents and put them under the old image name:tag.

**Comment by ezrasilvera** [comment]
There is an issue where the image is built on the fly from code, however the image reference in the helm is hardcoded to kubestellar-operator:0.20.0-alpha.1 , the make local shouldn't tag the image with 0.20.0-alpha.1  as obviously that tag corresponds to a different commit. 
In general we need to do some re-design around our Makefile, is seems that some of the tasks we perform today through Makefile phony targets, should probably be moved to scripts + parameters in hack. (cc: @MikeSpreitzer @pdettori )

**Comment by effi-ofer** [comment]
KS 0.14 Makefile was using a temp tag for the local images used in the tests.  We should switch to a similar model.

**Comment by pdettori** [comment]
I had a similar issue in ocm-status-addon and I have been using a git short commit for that (see https://github.com/kubestellar/ocm-status-addon/blob/8036909019c13263ad4045792b38d8f8e6cc60fa/Makefile#L17 ).
