### ISSUE TITLE
bug: pluggable transport attempts to wrap empty workloads

### ISSUE THREAD

**Issue by vMaroon** [kubestellar/kubestellar#1745]
### Describe the bug

currently the transport tries to produce empty wrapped objects when reconciling a binding with empty workload. this leads to errors in OCM's case, since a manifestwork cannot be created while wrapping no resources.

### Steps To Reproduce

read above

### Expected Behavior

syncing bindings with empty workloads should be checking and enforcing that no relevant wrapped object exists.

**Comment by nirrozenbaum** [comment]
this bug may happen in the following scenario (putting here only one example):
a user creates object with label X (e.g., a deployment) and a BindingPolicy that selects objects with label X.
at some point the the user may delete the deployment but BindingPolicy is still there, which results in re-evaluation of the BindingPolicy and the creation of Binding with empty workload section.
This is a valid scenario.

The solution:
transport controller should check if workload section is empty and if yes it should not distribute anything to any cluster. it should remove all existing manifest work from all destinations (empty binding should remove the manifest work).

**Comment by nirrozenbaum** [comment]
fixed in PR #1747
