### ISSUE TITLE
bug: scripts/add-helm-code.sh issues

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#1756]
### Describe the bug

(1) The script named "add-helm-code.sh" in `scripts/` is badly named. It does not add code; it tweaks some names in `operator.yaml`.

(2) The comments suggest that it takes one command line argument that can be either "add" or "remove". But it only does something if that argument is "add".

A better name would be something like `specialize-names.sh`.

(3) This script is designed to ONLY be used in one place --- the Makefile recipe for target `chart` --- but does not say so.

(4) A script for development-time use belongs in `hack/` not `scripts/` (the latter is for users not contributors).

(5) The script does some very fragile text search-and-replace operations. Since it is really an amendment to `$(KUSTOMIZE) build config/default`, it would be more robust to adjust the kustomization to also do this work.

### Steps To Reproduce

See above.

### Expected Behavior

See above.

**Comment by ezrasilvera** [comment]
@francostellari is this still a valid issue?  Are you working on it ?

**Comment by francostellari** [comment]
> @francostellari is this still a valid issue? Are you working on it ?

@ezrasilvera (/cc @MikeSpreitzer ) indeed, I was learning a bit more about YQ to implement a solution with it.
Please see #2036

**Comment by MikeSpreitzer** [comment]
I think that this issue has been resolved by #2036 .
