### ISSUE TITLE
bug: Incomplete workload object matching

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#1788]
### Describe the bug

While testing #1769 I noticed the new integration test reporting some failures that looked like real failures. Following is one I got while using commit 6eff71c795d9413af2d1f268a45bb8eba5358d33.

I ran the test with this command:

```
CONTROLLER_TEST_NUM_OBJECTS=30 go test -v ./test/integration/controller-manager -args -v=5 &> /tmp/test2.log
```

Here is the log file that produced:
[test2.log](https://github.com/kubestellar/kubestellar/files/14355630/test2.log)

The results quickly settled down to a Binding that lacked one workload object reference, which should indeed have been in the Binding.

### Steps To Reproduce

Using that commit, run that command several times. It is flaky. Sometimes you will get a pass, sometimes a failure.

### Expected Behavior

Always pass.

**Comment by nirrozenbaum** [comment]
@vMaroon looks like a serious bug. 
can you have check this?

**Comment by vMaroon** [comment]
@MikeSpreitzer can you attach other log runs?

**Comment by MikeSpreitzer** [comment]
I force-pushed, so that commit may not stick around. Here is an example using the current commit, 2602b73034ba68ecadec487718ba12de96d59c0d:

[test5.log](https://github.com/kubestellar/kubestellar/files/14356635/test5.log)

**Comment by MikeSpreitzer** [comment]
It is also interesting to consider the dynamics. Soon after test5, I produced test6 with the same parameters, and this one passed.

[test6.log](https://github.com/kubestellar/kubestellar/files/14356744/test6.log)

Now, try applying `grep "httplog.go.*matching-tester"` to test5.log, and then to test6.log, and compare the results.  There are many more PUTs in test6.log.

**Comment by MikeSpreitzer** [comment]
I rebased #1769, creating commit d7cc593cfa632dcf4eb40e82006190a678f49f81 (equivalent to 2602b7303).

**Comment by vMaroon** [comment]
I will investigate this after #1765

**Comment by MikeSpreitzer** [comment]
While working on #1784 I noticed that the behavior has gotten flakier. With 18 objects (created; 6 expected) it reliably fails now. I tried 12 objects (created; 3 expected) instead, and that reliably succeeds.

**Comment by MikeSpreitzer** [comment]
The bug is in `func (resolution *bindingPolicyResolution) toBindingSpec`; when I replace the code there with the simpler code in pkg/transport/generic_tranpsort_controller_test.go, the failures go away.

**Comment by vMaroon** [comment]
@MikeSpreitzer that code will be significantly simplified when the binding API flattening PR is open. Changes to Binding controller can be seen [here](https://github.com/kubestellar/kubestellar/commit/aa17f0731d1c0e82eae9cd39732dc46ed7bd7da6).
