### ISSUE TITLE
bug: Overview vs. Areas of exploration in README.md

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#180]
### Describe the bug

The Overview section and the Areas of exploration section of [the README](README.md) have no clear distinction.  Both describe aspects of the problem.
 The Overview says it is going to list use cases, but then it actually lists aspects of the general problem.

Also: the scheduling/syncing interface is not like the other aspects, which are about the interface that the platform user uses.

Also, there are some aspects that we consider important and are not currently mentioned in either section.
- the customer decides on the hierarchy, not the platform provider.
- resource constraints in the edge locations.
- Complex Arrangement of Roles and Responsibilities.

Also, I would add a bit of organization: one root cause, the one-to-many relation between workload description and running copies, leads to many sub-problems:
- the user needs an API for saying what goes where.
- the user may want some degree of imprecision, to allow for local autonomy in certain details of desired state.
- the user may need a way to specify how the workload is customized to each edge cluster.
- the platform needs a broadly usable sort of container for workload descriptions.
- the user may want reported state from associated objects.
- the user needs a way to specify how the reported state is summarized --- at least functionally, and perhaps also how that function is placed in the hierarchy.
- the platform needs a way to represent reported state summaries.

### Steps To Reproduce

See above.

### Expected Behaviour

The same kinds of things should not be in two different sections.

**Comment by MikeSpreitzer** [comment]
You might also want to review https://clubanderson.medium.com/navigating-the-edge-overcoming-multi-cloud-challenges-in-edge-computing-182e13255e29 with these thoughts in mind.

**Comment by clubanderson** [comment]
@MikeSpreitzer is this still a valid issue?

**Comment by MikeSpreitzer** [comment]
Yes, this is still valid.

**Comment by MikeSpreitzer** [comment]
This has been addressed.
