### ISSUE TITLE
feature: deploy transport controller in a pod

### ISSUE THREAD

**Issue by nirrozenbaum** [kubestellar/kubestellar#1809]
### Feature Description

it should be possible to deploy transport controller in a pod. ideally using helm

### Proposed Solution

the above.

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by pdettori** [comment]
@nirrozenbaum I would start by looking at the Kubebuilder scaffolding we use in https://github.com/kubestellar/kubestellar/tree/main/config - we can probably remove many unused files/dirs from there but a lot of the infrastructure can be still useful. Then we can use the same process to `make chart` as in kubestellar and ocm-status-add on and same approach for publishing the chart.
