### ISSUE TITLE
bug: Missing workstatus objects for successfully executed workloads in the WECs

### ISSUE THREAD

**Issue by dumb0002** [kubestellar/kubestellar#1820]
### Describe the bug

While testing ks-v0.20 I observed a very strange behavior:  if I run back to back tests the number of workstatus objects created in the second experiments decreases significantly.  For example:  53 workstatus objects created for 500 pods deployed in the WEC. What is even weird is that 478 have successful status completion in the WDS - it seems that some workstatus objects are somehow being deleted from the IMBS. 

Here is the produced log file for the status agent: 
[status-agent-ccd7fbb4f-nbxvt-ks-v020-log.txt](https://github.com/kubestellar/kubestellar/files/14426468/status-agent-ccd7fbb4f-nbxvt-ks-v020-log.txt)

### Steps To Reproduce

Run two back to back stress tests generating a large number of objects (e.g., 500 pods) - deleting all the pods before running the second experiment

### Expected Behavior

A workstatus object should be created for every workload object deployed in the WEC

### Additional Context

The hypothesis is that there is a bug in the status agent logic that tracks objects. Need to filter out the objects that are not relevant.

```
rtified-operators-t6w4m" not found, requeuing
2024-02-27T22:54:05Z	INFO	going to update status:	{"object": "[openshift-marketplace] pod/certified-operators-t6w4m"}
E0227 22:54:05.510429       1 agent.go:280] error syncing key 'util.Key{GvkKey:"v1/Pod", NamespaceNameKey:"openshift-marketplace/certified-operators-t6w4m", DeletedObject:(*runtime.Object)(0xc002a1e4b0)}': workstatuses.control.kubestellar.io "v1-pod-openshift-marketplace-certified-operators-t6w4m" not found, requeuing
2024-02-27T22:54:10Z	INFO	going to update status:	{"object": "[openshift-marketplace] pod/certified-operators-t6w4m"}
E0227 22:54:10.640487       1 agent.go:280] error syncing key 'util.Key{GvkKey:"v1/Pod", NamespaceNameKey:"openshift-marketplace/certified-operators-t6w4m", DeletedObject:(*runtime.Object)(0xc002a1e4b0)}': workstatuses.control.kubestellar.io "v1-pod-openshift-marketplace-certified-operators-t6w4m" not found, requeuing
2024-02-27T22:54:10Z	INFO	going to update status:	{"object": "[openshift-marketplace] pod/redhat-marketplace-nfp2h"}
E0227 22:54:10.718833       1 agent.go:280] error syncing key 'util.Key{GvkKey:"v1/Pod", NamespaceNameKey:"openshift-marketplace/redhat-marketplace-nfp2h", DeletedObject:(*runtime.Object)(0xc005bbe4a0)}': workstatuses.control.kubestellar.io "v1-pod-openshift-marketplace-redhat-marketplace-nfp2h" not found, requeuing
2024-02-27T22:54:20Z	INFO	going to update status:	{"object": "[openshift-marketplace] pod/certified-operators-t6w4m"}
E0227 22:54:20.889714       1 agent.go:280] error syncing key 'util.Key{GvkKey:"v1/Pod", NamespaceNameKey:"openshift-marketplace/certified-operators-t6w4m", DeletedObject:(*runtime.Object)(0xc002a1e4b0)}': workstatuses.control.kubestellar.io "v1-pod-openshift-marketplace-certified-operators-t6w4m" not found, requeuing
2024-02-27T22:54:25Z	INFO	going to update status:	{"object": "[openshift-marketplace] pod/certified-operators-gw9vv"}
E0227 22:54:25.533098       1 agent.go:280] error syncing key 'util.Key{GvkKey:"v1/Pod", NamespaceNameKey:"openshift-marketplace/certified-operators-gw9vv", DeletedObject:(*runtime.Object)(0xc004fe8800)}': workstatuses.control.kubestellar.io "v1-pod-openshift-marketplace-certified-operators-gw9vv" not found, requeuing
```

**Comment by pdettori** [comment]
The bug related to re-queing and concurrent maps access has been fixed in 0.2.0-rc4, but now there are several errors like the following:

```
StorageError: invalid object, Code: 4, Key: /registry/control.kubestellar.io/workstatuses/wec1/v1-pod-stress-test-sleep-20-sec-4, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: b3fdaded-f25c-4161-8bae-95318ce5a251, UID in object meta:
```

**Comment by ezrasilvera** [comment]
@pdettori  @dumb0002 is this still valid? Is there a simple way to reproduce ?

**Comment by pdettori** [comment]
I think we can close this. I added a short stress test in the status add-on that re-created the issue and fixed it. @dumb0002 was able to validate afterwards the rc6 build was no longer showing the issue.
