### ISSUE TITLE
feature: e2e test code is duplicated for every test.

### ISSUE THREAD

**Issue by nirrozenbaum** [kubestellar/kubestellar#1821]
### Feature Description

when I wanted to write a new e2e test, I noticed some of the e2e test is duplicated for each e2e.
this is not a good practice and might become a pain once we have many tests. 
for example, if we have 10 tests and find a bug in the testing setup code - we will need to fix the same bug in 10 places.

### Proposed Solution

implement once use many 

### Want to contribute?

- [ ] I would like to work on this issue.

### Additional Context

duplication examples - 
- https://github.com/kubestellar/kubestellar/blob/main/test/e2e/singleton-status/run-test.sh and https://github.com/kubestellar/kubestellar/blob/main/test/e2e/multi-cluster-deployment/run-test.sh
the only difference is one calling update-delete and the other is not. this might be passed as argument or alternatively integrated into `use-kubestellar.sh`.  
- https://github.com/kubestellar/kubestellar/blob/main/.github/workflows/pr-test-multicluster.yml and https://github.com/kubestellar/kubestellar/blob/main/.github/workflows/pr-test-singleton-status.yml
the only difference is the path to the e2e `run-test.sh` file.

**Comment by effi-ofer** [comment]
@nirrozenbaum I am not saying the tests are perfect, and perhaps some refactoring would be beneficial.  But note that in the examples you give, these are the test drivers rather than the tests themselves.  Can you give other examples?

**Comment by ezrasilvera** [comment]
@effi-ofer I agree, and when we find a good way to "cleanup" our environment we plan to have a single e2e test that will run all of th etests.

**Comment by nirrozenbaum** [comment]
@effi-ofer yes, my intention was for the e2e test drivers.
the tests internals are of course different.

I think we need to have one place with code to drive test.
code duplication is never a good practice :)

**Comment by effi-ofer** [comment]
I might argue that in testing, readability, reliability, and reproducibility are more important than avoiding code duplications, but in almost all cases (testing and code) you are absolutely right.  Longer term I would prefer to have a single e2e test driver with multiple test units.  I am actually moving into this model with PR #1713 and the resiliency testing.

**Comment by nirrozenbaum** [comment]
in #1713 removes the duplication of test drivers code, that's another good reason to switch :)

**Comment by nirrozenbaum** [comment]
@effi-ofer @ezrasilvera see the following example - #1824 
the test content is 70 code lines, while the whole PR is 230 code lines.
that means that for each new e2e test, we add duplication of 160 lines.

**Comment by ezrasilvera** [comment]
Tests are moving to ginkgo without duplication

**Comment by effi-ofer** [comment]
Handled by PR #1713
