### ISSUE TITLE
bug: singleton status does not change when wantSingletonReportedState changes

### ISSUE THREAD

**Issue by effi-ofer** [kubestellar/kubestellar#1838]
### Describe the bug

To set the singleton status, the wantSingletonReportedState flag needs to be set to true in the spec of the BindingPolicy.  When this flag changes from true to false, the singleton status does not changes and the status is still reported.

### Steps To Reproduce

Create a singleton deployment and bindpolicy.  This can be done by running the e2e singleton test.  Then patch the wantSingletonReportedState to false as follows:
`kubectl --context wds1 patch bindingpolicy nginx-singleton --type=merge -p '{"spec": {"wantSingletonReportedState": false}}'`

Here's what I do:
```
2216  kubectl --context wds1 create -f bp.yaml
 2217  kubectl --context wds1 create -f d.yaml
 2218  kubectl --context wds1 get deployment -n nginx nginx-singleton -o yaml
 2219  kubectl --context wds1 get bindingpolicies  nginx-singleton -o yaml
 2220  kubectl --context wds1 patch bindingpolicy nginx-singleton --type=merge -p '{"spec": {"wantSingletonReportedState": false}}'
 2221  kubectl --context wds1 get bindingpolicies  nginx-singleton -o yaml
 2222  kubectl --context wds1 get deployment -n nginx nginx-singleton -o yaml
```
Where bp.yaml is
```
apiVersion: control.kubestellar.io/v1alpha1
kind: BindingPolicy
metadata:
  creationTimestamp: "2024-02-29T17:12:47Z"
  finalizers:
  - bindingpolicy.kubestellar.io/kscontroller
  generation: 2
  name: nginx-singleton
  resourceVersion: "5006"
  uid: 2be0aad0-0cc4-4985-a6c7-0cbd6244b2f4
spec:
  clusterSelectors:
  - matchLabels:
      name: cluster1
  downsync:
  - objectSelectors:
    - matchLabels:
        app.kubernetes.io/name: nginx-singleton
  wantSingletonReportedState: true
```
And d.yaml is
```
apiVersion: control.kubestellar.io/v1alpha1
kind: BindingPolicy
metadata:
  creationTimestamp: "2024-02-29T17:12:47Z"
  finalizers:
  - bindingpolicy.kubestellar.io/kscontroller
  generation: 2
  name: nginx-singleton
  resourceVersion: "5006"
  uid: 2be0aad0-0cc4-4985-a6c7-0cbd6244b2f4
spec:
  clusterSelectors:
  - matchLabels:
      name: cluster1
  downsync:
  - objectSelectors:
    - matchLabels:
        app.kubernetes.io/name: nginx-singleton
  wantSingletonReportedState: true
effi@fortress:~/edge-mc/test/e2e/singleton-status$ cat d.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2024-02-29T17:12:47Z"
  generation: 1
  labels:
    app.kubernetes.io/name: nginx-singleton
  name: nginx-singleton
  namespace: nginx
  resourceVersion: "5002"
  uid: bf70a975-9a4d-44c8-bf05-33b63b86e0f2
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx-singleton
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-singleton
    spec:
      containers:
      - image: public.ecr.aws/nginx/nginx:latest
        imagePullPolicy: Always
        name: nginx-singleton
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
```

### Expected Behavior

Singleton status respect the value of the wantSingletonReportedState flag.

**Comment by effi-ofer** [comment]
This can also be reproduced with the "sets singleton status when a singleton bindingpolicy/deployment is created" test case in the new tests included in PR #1713

**Comment by effi-ofer** [comment]
I am guessing but haven't checked the code that the bindingpolicies informer only checks changes to the clusterselectors spec fields?

**Comment by vMaroon** [comment]
This is not a binding controller bug, but a status controller bug. I have followed the steps, and the singleton label is correctly removed off the deployment object after updating the binding-policy.

This is a status controller bug.

**Comment by andreyod** [comment]
Correct. Both the status addon and the status controller don't support this scenario today. Changing from false to true is supported.
Is this a valid scenario? Should we remove the status from the object in WDS?

**Comment by effi-ofer** [comment]
@vMaroon I don't see the label removed when I run the scenario I outlined in slack.

**Comment by pdettori** [comment]
could this be related to https://github.com/kubestellar/kubestellar/issues/1580 ? In that case it was the opposite I think - start from a bindingpolicy that has wantSingletonReportedState initially false and then changing to to true was not triggering the status update.

**Comment by effi-ofer** [comment]
> @vMaroon I don't see the label removed when I run the scenario I outlined in slack.

Correction - once I moved up to the latest version of main I can see the label is removed.  This issue is then about cleaning up the status fields.

**Comment by andreyod** [comment]
It looks like we hit an OCM bug here: When a label is removed from wrapped object it is not removed from the object on the WEC. Add label and update the label value works, so as a workaround we can update the singletonstatus label value in the wrapped object instead of removing this label.

**Comment by andreyod** [comment]
> can we verify that is an OCM bug not related to KS? this should be easy, create manifestwork with kubectl directly to imbs. work only with imbs as ocm-hub to do the same scenario and see if the same issue happens. if yes, we can fix the issue in OCM quickly (I'm sure they will be happy).

I get the same issue. 
Also opened a separate git issue for this: https://github.com/kubestellar/kubestellar/issues/1856 .

**Comment by andreyod** [comment]
Following the comments on #1900 , we need to decide what should be the value for the singleton status label.

**Comment by ezrasilvera** [comment]
@andreyod So what is the summary of this issue?  Do we close it and track the OCM one (#1856 ) ?  Is there a workaround here ?  Is there another issue overlapping this one ?
