### ISSUE TITLE
bug: after killing the vcluster pod in the imbs we lose wec deployments

### ISSUE THREAD

**Issue by effi-ofer** [kubestellar/kubestellar#1850]
### Describe the bug

When killing the vcluster pod in the imbs, we lose the deployments in the wec.  

### Steps To Reproduce

This can be reproduced using the following test unit in PR #1713.  Note that ValidateNumDeployments retries for 500 seconds.
```
ginkgo.It("survives IMBS vcluster coming down", func() {
	util.DeletePod(ctx, coreCluster, "imbs1-system", "vcluster")
	util.ValidateNumDeployments(ctx, wec1, ns, 1)
	util.ValidateNumDeployments(ctx, wec2, ns, 1)
})
```

### Expected Behavior

The vcluster will come back up and everything will work as usual.

**Comment by nirrozenbaum** [comment]
@effi-ofer have you tried to do the same manually and not through ginkgo?
you might find interesting findings in logs

**Comment by effi-ofer** [comment]
> @effi-ofer have you tried to do the same manually and not through ginkgo? you might find interesting findings in logs

The difficulty is in reproducing this and not with getting access to the logs.  When ginkgo fails, it leaves the system at the point of failure and I can check the logs.

**Comment by effi-ofer** [comment]
I managed to reproduce this locally.  Woohoo!  After the vcluster pod is killed, it comes back up, but the deployments from the WECs (both wec1 and wec2) are gone!  Here's the state of the system.  Note that the binding object is created properly, but the manifestwork objects are not. 
```
$ kubectl --context kind-kubeflex get pods -A
NAMESPACE            NAME                                                              READY   STATUS      RESTARTS      AGE
imbs1-system         addon-status-controller-f9df8bf44-vt6sm-x-open-clust-bd7d1c3301   1/1     Running     0             18h
imbs1-system         cluster-manager-6ddf9dc5bc-sp7p6-x-open-cluster-mana-fd4bd9f1a6   1/1     Running     0             18h
imbs1-system         cluster-manager-addon-manager-controller-8469c8b65b--e3446b1ec0   1/1     Running     0             18h
imbs1-system         cluster-manager-placement-controller-6455668ff8-sxp9-44a7fe336d   1/1     Running     0             18h
imbs1-system         cluster-manager-registration-controller-8665f67c46-g-1ac72a5469   1/1     Running     0             18h
imbs1-system         cluster-manager-registration-webhook-59f5b7c779-7xsv-c15bf435b3   1/1     Running     0             18h
imbs1-system         cluster-manager-work-webhook-78955486dd-6w2zd-x-open-f1a73c1b4d   1/1     Running     0             18h
imbs1-system         coredns-68559449b6-rmlkx-x-kube-system-x-vcluster                 1/1     Running     0             18h
imbs1-system         ocm-mxlll                                                         0/1     Completed   0             18h
imbs1-system         update-cluster-info-j7ctx                                         0/1     Completed   0             18h
imbs1-system         vcluster-0                                                        2/2     Running     0             3m26s
ingress-nginx        ingress-nginx-admission-create-zbh8w                              0/1     Completed   0             18h
ingress-nginx        ingress-nginx-admission-patch-zws5f                               0/1     Completed   0             18h
ingress-nginx        ingress-nginx-controller-7f6d7fb87b-zzlv9                         1/1     Running     0             18h
kube-system          coredns-565d847f94-h7xzr                                          1/1     Running     0             18h
kube-system          coredns-565d847f94-ncpkr                                          1/1     Running     0             18h
kube-system          etcd-kubeflex-control-plane                                       1/1     Running     0             18h
kube-system          kindnet-7g7xr                                                     1/1     Running     0             18h
kube-system          kube-apiserver-kubeflex-control-plane                             1/1     Running     0             18h
kube-system          kube-controller-manager-kubeflex-control-plane                    1/1     Running     0             18h
kube-system          kube-proxy-2k9c6                                                  1/1     Running     0             18h
kube-system          kube-scheduler-kubeflex-control-plane                             1/1     Running     0             18h
kubeflex-system      kubeflex-controller-manager-5dd85b86d5-sbrjv                      2/2     Running     0             14m
kubeflex-system      postgres-postgresql-0                                             1/1     Running     0             14m
local-path-storage   local-path-provisioner-684f458cdd-f2rv9                           1/1     Running     0             18h
wds1-system          kube-apiserver-5c555547b-cc5tw                                    2/2     Running     0             18h
wds1-system          kube-controller-manager-5b84697bdd-n9xcf                          1/1     Running     2 (14m ago)   18h
wds1-system          kubestellar-controller-manager-6db75d7b8-d4hn2                    2/2     Running     2 (14m ago)   14m

effi@fortress:~/edge-mc/test/e2e/ginkgo$ kubectl --context cluster1 get deployments -n nginx
No resources found in nginx namespace.
effi@fortress:~/edge-mc/test/e2e/ginkgo$ kubectl --context cluster2 get deployments -n nginx
No resources found in nginx namespace.
effi@fortress:~/edge-mc/test/e2e/ginkgo$ kubectl --context wds1 get deployments -n nginx
NAME    READY   UP-TO-DATE   AVAILABLE   AGE
nginx   0/1     0            0           7m
effi@fortress:~/edge-mc/test/e2e/ginkgo$ kubectl --context imbs1 get manifestworks -A
NAMESPACE   NAME                          AGE
cluster1    addon-addon-status-deploy-0   18h
cluster2    addon-addon-status-deploy-0   18h
effi@fortress:~/edge-mc/test/e2e/ginkgo$ kubectl --context wds1 get bindingpolicies -A
NAME    SYNCED   READY   TYPE   AGE
nginx                           7m22s
effi@fortress:~/edge-mc/test/e2e/ginkgo$ kubectl --context wds1 get bindings.control -A
NAME    AGE
nginx   7m27s
effi@fortress:~/edge-mc/test/e2e/ginkgo$ kubectl --context wds1 get bindings.control -A -o yaml
apiVersion: v1
items:
- apiVersion: control.kubestellar.io/v1alpha1
  kind: Binding
  metadata:
    creationTimestamp: "2024-03-04T10:02:54Z"
    generation: 1
    name: nginx
    ownerReferences:
    - apiVersion: control.kubestellar.io/v1alpha1
      blockOwnerDeletion: false
      controller: true
      kind: BindingPolicy
      name: nginx
      uid: 64c4281a-2c25-48c4-adbe-47bdd22cc1dd
    resourceVersion: "42552"
    uid: cdd961c5-f3af-4598-a017-bc2a76d409b4
  spec:
    destinations:
    - clusterId: cluster1
    - clusterId: cluster2
    workload:
      clusterScope:
      - group: ""
        objectNames:
        - nginx
        resource: namespaces
        version: v1
      namespaceScope:
      - group: apps
        objectsByNamespace:
        - names:
          - nginx
          namespace: nginx
        resource: deployments
        version: v1
      workloadGeneration: 1
kind: List
metadata:
  resourceVersion: ""
```
Next I'll be checking the logs.

**Comment by effi-ofer** [comment]
The OTP paniced.  
```
I0304 11:52:12.177286  392696 reflector.go:325] Listing and watching work.open-cluster-management.io/v1, Resource=manifestworks from pkg/mod/k8s.io/client-go@v0.28.2/tools/cache/reflector.go:229                                                                                                                          I0304 11:52:12.186085  392696 generic_transport_controller.go:189] "failed to extract binding key from wrapped object" logger="transport-controller" Name="addon-addon-status-deploy-0" Namespace="cluster1"                                                                                                                I0304 11:52:12.186182  392696 generic_transport_controller.go:189] "failed to extract binding key from wrapped object" logger="transport-controller" Name="addon-addon-status-deploy-0" Namespace="cluster2"                                                                                                                E0304 11:52:12.187650  392696 runtime.go:79] Observed a panic: &runtime.TypeAssertionError{_interface:(*runtime._type)(nil), concrete:(*runtime._type)(0x176d560), asserted:(*runtime._type)(0x1831f60), missingMethod:"GetAnnotations"} (interface conversion: cache.DeletedFinalStateUnknown is not v1.Object: missing method GetAnnotations)
goroutine 73 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x1705380?, 0xc0007938c0})
    /home/effi/go/pkg/mod/k8s.io/apimachinery@v0.28.2/pkg/util/runtime/runtime.go:75 +0x99
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x0?})
    /home/effi/go/pkg/mod/k8s.io/apimachinery@v0.28.2/pkg/util/runtime/runtime.go:49 +0x75
panic({0x1705380, 0xc0007938c0})
    /usr/local/go/src/runtime/panic.go:884 +0x213
github.com/kubestellar/kubestellar/pkg/transport.(*genericTransportController).handleWrappedObject(0xc000121c70, {0x176d560?, 0xc0001db900})
    /home/effi/edge-mc/pkg/transport/generic_transport_controller.go:186 +0x39
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnDelete(...)
    /home/effi/go/pkg/mod/k8s.io/client-go@v0.28.2/tools/cache/controller.go:253
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
    /home/effi/go/pkg/mod/k8s.io/client-go@v0.28.2/tools/cache/shared_informer.go:979 +0xaf
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x30?)
    /home/effi/go/pkg/mod/k8s.io/apimachinery@v0.28.2/pkg/util/wait/backoff.go:226 +0x3e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000489738?, {0x1b15d60, 0xc0004380c0}, 0x1, 0xc0003480c0)
    /home/effi/go/pkg/mod/k8s.io/apimachinery@v0.28.2/pkg/util/wait/backoff.go:227 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0?, 0x3b9aca00, 0x0, 0x0?, 0xc000489788?)
    /home/effi/go/pkg/mod/k8s.io/apimachinery@v0.28.2/pkg/util/wait/backoff.go:204 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(...)
    /home/effi/go/pkg/mod/k8s.io/apimachinery@v0.28.2/pkg/util/wait/backoff.go:161
k8s.io/client-go/tools/cache.(*processorListener).run(0xc00049e240)
    /home/effi/go/pkg/mod/k8s.io/client-go@v0.28.2/tools/cache/shared_informer.go:968 +0x6b
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
    /home/effi/go/pkg/mod/k8s.io/apimachinery@v0.28.2/pkg/util/wait/wait.go:72 +0x5a
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
    /home/effi/go/pkg/mod/k8s.io/apimachinery@v0.28.2/pkg/util/wait/wait.go:70 +0x85
panic: interface conversion: cache.DeletedFinalStateUnknown is not v1.Object: missing method GetAnnotations [recovered]
    panic: interface conversion: cache.DeletedFinalStateUnknown is not v1.Object: missing method GetAnnotations

goroutine 73 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x0?})
    /home/effi/go/pkg/mod/k8s.io/apimachinery@v0.28.2/pkg/util/runtime/runtime.go:56 +0xd7
panic({0x1705380, 0xc0007938c0})
    /usr/local/go/src/runtime/panic.go:884 +0x213
github.com/kubestellar/kubestellar/pkg/transport.(*genericTransportController).handleWrappedObject(0xc000121c70, {0x176d560?, 0xc0001db900})
    /home/effi/edge-mc/pkg/transport/generic_transport_controller.go:186 +0x39
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnDelete(...)
    /home/effi/go/pkg/mod/k8s.io/client-go@v0.28.2/tools/cache/controller.go:253
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
    /home/effi/go/pkg/mod/k8s.io/client-go@v0.28.2/tools/cache/shared_informer.go:979 +0xaf
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x30?)
    /home/effi/go/pkg/mod/k8s.io/apimachinery@v0.28.2/pkg/util/wait/backoff.go:226 +0x3e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000489738?, {0x1b15d60, 0xc0004380c0}, 0x1, 0xc0003480c0)
    /home/effi/go/pkg/mod/k8s.io/apimachinery@v0.28.2/pkg/util/wait/backoff.go:227 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0?, 0x3b9aca00, 0x0, 0x0?, 0xc000489788?)
    /home/effi/go/pkg/mod/k8s.io/apimachinery@v0.28.2/pkg/util/wait/backoff.go:204 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(...)
    /home/effi/go/pkg/mod/k8s.io/apimachinery@v0.28.2/pkg/util/wait/backoff.go:161
k8s.io/client-go/tools/cache.(*processorListener).run(0xc00049e240)
    /home/effi/go/pkg/mod/k8s.io/client-go@v0.28.2/tools/cache/shared_informer.go:968 +0x6b
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
    /home/effi/go/pkg/mod/k8s.io/apimachinery@v0.28.2/pkg/util/wait/wait.go:72 +0x5a
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
    /home/effi/go/pkg/mod/k8s.io/apimachinery@v0.28.2/pkg/util/wait/wait.go:70 +0x85
```

**Comment by effi-ofer** [comment]
@nirrozenbaum @vMaroon I am assigning to you.

**Comment by effi-ofer** [comment]
```
        jm, err := runtime.DefaultUnstructuredConverter.ToUnstructured(obj.MRObject)
	if err != nil {
		panic(err)
	}
```
Should we ever panic?

**Comment by nirrozenbaum** [comment]
@effi-ofer @vMaroon from what I see in the logs - 
it seems to me that killing the vcluster pod in the imbs tries to do graceful shutdown. that is, it tries to delete the existing objects. the hint for this can be seen in the log with the panic:
```
panic({0x1705380, 0xc0007938c0})
    /usr/local/go/src/runtime/panic.go:884 +0x213
github.com/kubestellar/kubestellar/pkg/transport.(*genericTransportController).handleWrappedObject(0xc000121c70, {0x176d560?, 0xc0001db900})
    /home/effi/edge-mc/pkg/transport/generic_transport_controller.go:186 +0x39
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnDelete(...)
```

so we can see that:
the transport controller code that tried to call function `handleWrappedObject` had panic as a result of line 186.
and - we can see also that it was as result of a `Delete` event.

an obvious fix must be that transport controller shouldn't crash if imbs is down.
having said that, I'm not sure if that is enough to bring the system back to the desired state. 
once imbs is up again - if all manifest work objects were deleted, there is no event that will cause reconcile.
we will have eventual consistency cause all objects are reconciled by default once every 10 hours. but that's not good enough.
as an initial step, I will look into fixing the first point. then we'll be able to re-test and see the results.

**Comment by nirrozenbaum** [comment]
the bug is - transport controller line 186 should handle `cache.DeletedFinalStateUnknown` and not cast to metav1.Object without checking.

**Comment by nirrozenbaum** [comment]
@effi-ofer I will fix after completing the containerization of transport controller.

**Comment by effi-ofer** [comment]
> it seems to me that killing the vcluster pod in the imbs tries to do graceful shutdown. that is, it tries to delete the existing objects.

Are you saying that if the vcluster goes down then it deletes existing objects?  Deletion of these objects then trigger their removal via ocm from the wec?  Does it ever makes sense to delete wec objects if the vcluster or other pods go down, expectedly or unexpectedly?

**Comment by nirrozenbaum** [comment]
@effi-ofer
```
Are you saying that if the vcluster goes down then it deletes existing objects?
```
yes, this is what it looks like from the logs. you killed the pod, as a result we see failure in the event `OnDelete` of manifestwork. I might be wrong but that's my interpretation of this log.

```
Deletion of these objects then trigger their removal via ocm from the wec?
```
yup, that's bad.

```
Does it ever makes sense to delete wec objects if the vcluster or other pods go down, expectedly or unexpectedly? Does it ever makes sense to delete wec objects if the vcluster or other pods go down, expectedly or unexpectedly?
```
I don't think it makes sense to delete objects from wec unless it was explicitly requested by the user. crash of a pod shouldn't cause deletion of anything.

I'm not very well familiar with vcluster, but maybe graceful shutdown is configurable in vcluster.

orthogonal to all of the above, you found a bug in transport controller that should (and will) be fixed.

**Comment by effi-ofer** [comment]
@nirrozenbaum which log are you looking at?
@pdettori Nir is going to fix the transport panic, but orthogonally we also observe objects in the WEC getting deleted. Why is that?

**Comment by nirrozenbaum** [comment]
> The OTP paniced.
> 
> ```
> I0304 11:52:12.177286  392696 reflector.go:325] Listing and watching work.open-cluster-management.io/v1, Resource=manifestworks from pkg/mod/k8s.io/client-go@v0.28.2/tools/cache/reflector.go:229                                                                                                                          I0304 11:52:12.186085  392696 generic_transport_controller.go:189] "failed to extract binding key from wrapped object" logger="transport-controller" Name="addon-addon-status-deploy-0" Namespace="cluster1"                                                                                                                I0304 11:52:12.186182  392696 generic_transport_controller.go:189] "failed to extract binding key from wrapped object" logger="transport-controller" Name="addon-addon-status-deploy-0" Namespace="cluster2"                                                                                                                E0304 11:52:12.187650  392696 runtime.go:79] Observed a panic: &runtime.TypeAssertionError{_interface:(*runtime._type)(nil), concrete:(*runtime._type)(0x176d560), asserted:(*runtime._type)(0x1831f60), missingMethod:"GetAnnotations"} (interface conversion: cache.DeletedFinalStateUnknown is not v1.Object: missing method GetAnnotations)
> goroutine 73 [running]:
> k8s.io/apimachinery/pkg/util/runtime.logPanic({0x1705380?, 0xc0007938c0})
>     /home/effi/go/pkg/mod/k8s.io/apimachinery@v0.28.2/pkg/util/runtime/runtime.go:75 +0x99
> k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x0?})
>     /home/effi/go/pkg/mod/k8s.io/apimachinery@v0.28.2/pkg/util/runtime/runtime.go:49 +0x75
> panic({0x1705380, 0xc0007938c0})
>     /usr/local/go/src/runtime/panic.go:884 +0x213
> github.com/kubestellar/kubestellar/pkg/transport.(*genericTransportController).handleWrappedObject(0xc000121c70, {0x176d560?, 0xc0001db900})
>     /home/effi/edge-mc/pkg/transport/generic_transport_controller.go:186 +0x39
> k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnDelete(...)
>     /home/effi/go/pkg/mod/k8s.io/client-go@v0.28.2/tools/cache/controller.go:253
> k8s.io/client-go/tools/cache.(*processorListener).run.func1()
>     /home/effi/go/pkg/mod/k8s.io/client-go@v0.28.2/tools/cache/shared_informer.go:979 +0xaf
> k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x30?)
>     /home/effi/go/pkg/mod/k8s.io/apimachinery@v0.28.2/pkg/util/wait/backoff.go:226 +0x3e
> k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000489738?, {0x1b15d60, 0xc0004380c0}, 0x1, 0xc0003480c0)
>     /home/effi/go/pkg/mod/k8s.io/apimachinery@v0.28.2/pkg/util/wait/backoff.go:227 +0xb6
> k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0?, 0x3b9aca00, 0x0, 0x0?, 0xc000489788?)
>     /home/effi/go/pkg/mod/k8s.io/apimachinery@v0.28.2/pkg/util/wait/backoff.go:204 +0x89
> k8s.io/apimachinery/pkg/util/wait.Until(...)
>     /home/effi/go/pkg/mod/k8s.io/apimachinery@v0.28.2/pkg/util/wait/backoff.go:161
> k8s.io/client-go/tools/cache.(*processorListener).run(0xc00049e240)
>     /home/effi/go/pkg/mod/k8s.io/client-go@v0.28.2/tools/cache/shared_informer.go:968 +0x6b
> k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
>     /home/effi/go/pkg/mod/k8s.io/apimachinery@v0.28.2/pkg/util/wait/wait.go:72 +0x5a
> created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
>     /home/effi/go/pkg/mod/k8s.io/apimachinery@v0.28.2/pkg/util/wait/wait.go:70 +0x85
> panic: interface conversion: cache.DeletedFinalStateUnknown is not v1.Object: missing method GetAnnotations [recovered]
>     panic: interface conversion: cache.DeletedFinalStateUnknown is not v1.Object: missing method GetAnnotations
> 
> goroutine 73 [running]:
> k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x0?})
>     /home/effi/go/pkg/mod/k8s.io/apimachinery@v0.28.2/pkg/util/runtime/runtime.go:56 +0xd7
> panic({0x1705380, 0xc0007938c0})
>     /usr/local/go/src/runtime/panic.go:884 +0x213
> github.com/kubestellar/kubestellar/pkg/transport.(*genericTransportController).handleWrappedObject(0xc000121c70, {0x176d560?, 0xc0001db900})
>     /home/effi/edge-mc/pkg/transport/generic_transport_controller.go:186 +0x39
> k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnDelete(...)
>     /home/effi/go/pkg/mod/k8s.io/client-go@v0.28.2/tools/cache/controller.go:253
> k8s.io/client-go/tools/cache.(*processorListener).run.func1()
>     /home/effi/go/pkg/mod/k8s.io/client-go@v0.28.2/tools/cache/shared_informer.go:979 +0xaf
> k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x30?)
>     /home/effi/go/pkg/mod/k8s.io/apimachinery@v0.28.2/pkg/util/wait/backoff.go:226 +0x3e
> k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000489738?, {0x1b15d60, 0xc0004380c0}, 0x1, 0xc0003480c0)
>     /home/effi/go/pkg/mod/k8s.io/apimachinery@v0.28.2/pkg/util/wait/backoff.go:227 +0xb6
> k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0?, 0x3b9aca00, 0x0, 0x0?, 0xc000489788?)
>     /home/effi/go/pkg/mod/k8s.io/apimachinery@v0.28.2/pkg/util/wait/backoff.go:204 +0x89
> k8s.io/apimachinery/pkg/util/wait.Until(...)
>     /home/effi/go/pkg/mod/k8s.io/apimachinery@v0.28.2/pkg/util/wait/backoff.go:161
> k8s.io/client-go/tools/cache.(*processorListener).run(0xc00049e240)
>     /home/effi/go/pkg/mod/k8s.io/client-go@v0.28.2/tools/cache/shared_informer.go:968 +0x6b
> k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
>     /home/effi/go/pkg/mod/k8s.io/apimachinery@v0.28.2/pkg/util/wait/wait.go:72 +0x5a
> created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
>     /home/effi/go/pkg/mod/k8s.io/apimachinery@v0.28.2/pkg/util/wait/wait.go:70 +0x85
> ```

@effi-ofer see the log you attached. more specifically the following lines:
```
github.com/kubestellar/kubestellar/pkg/transport.(*genericTransportController).handleWrappedObject(0xc000121c70, {0x176d560?, 0xc0001db900})
    /home/effi/edge-mc/pkg/transport/generic_transport_controller.go:186 +0x39
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnDelete(...)
```

that means that handleWrappedObject handler function was called as a result of a delete event for manifestwork object.

**Comment by effi-ofer** [comment]
Thanks Nir for the explanation.  The question then becomes, why do we have a delete event for a manifestwork object?  Any idea @pdettori ?

**Comment by pdettori** [comment]
Also, I cannot reproduce this issue with a manual delete of the vcluster0 pod:

```shell
(base) (⎈|kind-kubeflex:N/A)$ k  -n imbs1-system delete pod vcluster-0 
pod "vcluster-0" deleted
(base) (⎈|kind-kubeflex:N/A)$ k --context imbs1 -n cluster1 get manifestwork
NAME                                 AGE
nginx-singleton-bindingpolicy-wds1   40m
addon-addon-status-deploy-0          40m
(base) (⎈|kind-kubeflex:N/A)$ k --context cluster1 get deployments.apps -A
NAMESPACE                             NAME                     READY   UP-TO-DATE   AVAILABLE   AGE
kube-system                           coredns                  2/2     2            2           42m
local-path-storage                    local-path-provisioner   1/1     1            1           42m
nginx                                 nginx-deployment         1/1     1            1           41m
open-cluster-management-agent-addon   status-agent             1/1     1            1           41m
open-cluster-management-agent         klusterlet-agent         1/1     1            1           41m
open-cluster-management               klusterlet               1/1     1            1           42m
```

**Comment by vMaroon** [comment]
@nirrozenbaum @effi-ofer what's the status of this issue?

**Comment by nirrozenbaum** [comment]
there is a bug in transport controller that I need to fix in this line - https://github.com/kubestellar/kubestellar/blob/main/pkg/transport/generic_transport_controller.go#L186

I'm working on other priorities so didn't fix it yet.
will probably get to it in a day or two.

**Comment by effi-ofer** [comment]
@vMaroon There are two issues here.  Issue #1: the panic Nir mentioned.  Issue #2: The question of the WEC objects being deleted.  We observed this in the original failure but Paolo was not able to reproduce when running independent of the test.  I need to revisit this and confirm this is still reproducible.

**Comment by ezrasilvera** [comment]
@nirrozenbaum  @vMaroon anyone is actively working on this?

**Comment by nirrozenbaum** [comment]
me :)

**Comment by effi-ofer** [comment]
I am not longer able to reproduce either the panic or the missing wec deployments using the test script.  I went back to the original test since it got modified in the past month but I am still not able to reproduce.  I should be able to reproduce manually and fix the panic, but as for the missing wec objects I am going to treat the issue as fixed.
