### ISSUE TITLE
bug: race condition observed when a large number of objects is consecutively deleted and re-created 

### ISSUE THREAD

**Issue by pdettori** [kubestellar/kubestellar#1853]
### Describe the bug

When a large number of objects  (~85 in the test scenario) is first deleted and then re-created, it has been observed that some manifestwork is not present on the IMBS, therefore the final state is not what expected (all 85 objects should be present in the IMBS).

This behavior has been observed with v0.20.0

### Steps To Reproduce

1. Create a large number of objects
2. Delete and then consecutively re-create the same objects 

### Expected Behavior

Final state should be equal to desired state (all matched objects present in manifestworks on the IMBS)

### Additional Context

The current hypothesis is that since due the nature of async processing, some previously enqueued delete operation for objects happens right after object has been created, therefore the final state is `object not present` rather than `object present` on the IMBS.

**Comment by MikeSpreitzer** [comment]
I think this has been fixed in `main`. Can you please test with `main`?

**Comment by pdettori** [comment]
@MikeSpreitzer we do not have a release from main that can be easily deployed on the openshift clusters @clubanderson is testing. I am finding however that is quite possible to replicate these type of race conditions by writing a test driver in go or python that asynchronously creates, deletes and create a batch of objects. I think that would be a good test here.

**Comment by nirrozenbaum** [comment]
we should have 0.21 release soon (I assume in the next few days). let's re-test this bug after the release.

**Comment by MikeSpreitzer** [comment]
See also #1859 . While the driver is not asynchronous, remember that the controller has concurrent workers --- so the controller itself introduces asynchrony.

**Comment by MikeSpreitzer** [comment]
BTW, I have updated #1859 to do parallel as well as serial thrashing of objects.

**Comment by ezrasilvera** [comment]
@pdettori is this still valid ?

**Comment by pdettori** [comment]
I ran a e2e stress test (attached here) with 200 objects that does a fast create, delete and re-create and verified that all expected objects are present at the end in both clusters. 
[load-driver.go.zip](https://github.com/kubestellar/kubestellar/files/14808441/load-driver.go.zip)
