### ISSUE TITLE
feature: enable shell based bash multi-cluster testing

### ISSUE THREAD

**Issue by effi-ofer** [kubestellar/kubestellar#1865]
### Feature Description

Now that we are switching to ginkgo based e2e tests, we still need to keep a shell script based test.  This is going to be it.  We'll keep only the basic multi cluster test without all the extensions made in the update-delete.sh script.

### Proposed Solution

See feature description.

### Want to contribute?

- [X] I would like to work on this issue.

**Comment by ezrasilvera** [comment]
@effi-ofer I want to try doing this a little differently. Can I take it ?

**Comment by effi-ofer** [comment]
> @effi-ofer I want to try doing this a little differently. Can I take it ?

It's all yours @ezrasilvera .

**Comment by MikeSpreitzer** [comment]
We need to retain at least one example of how a contributor issues shell commands to exercise their own local copy and version of the system (this is importantly different from documenting how a user uses a release). That is what we have now: there remains just one E2E test written in bash, the basic multi-cluster distribution test. We should keep that.

I think this issue has been addressed.
