### ISSUE TITLE
feature: deploy transport controller through a helm chart

### ISSUE THREAD

**Issue by nirrozenbaum** [kubestellar/kubestellar#1866]
### Feature Description

up until now pluggable transport controller was running as an executable. 
we've made some work to run it in a pod and deploy it using a script.
we would like to have transport controller deployed in a pod through a helm chart.

### Proposed Solution

either add transport to the existing kubestellar helm chart (the preffered approach)
or create new helm chart for transport.

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by francostellari** [comment]
Kubestellar documentation will be updated when OTP provides the first release of the new helm chart

**Comment by francostellari** [comment]
@nirrozenbaum can you work on a new release with the OTP chart , when you have time?

**Comment by nirrozenbaum** [comment]
@francostellari created release v0.1.0
