### ISSUE TITLE
The documentation link in README.md at https://github.com/kubestellar/kubestellar is broken

### ISSUE THREAD

**Issue by eaepstein** [kubestellar/kubestellar#1908]
### Describe the bug

The documentation link to https://github.com/kubestellar/kubestellar/blob/main/kubestellar.io returns a 404.

### Steps To Reproduce

Point browser at https://github.com/kubestellar/kubestellar, scroll down to README and click on the link in the first line:
NOTE: Some of our documentation is on the website [kubestellar.io](https://github.com/kubestellar/kubestellar/blob/main/kubestellar.io), some is here.

### Expected Behavior

kubestellar.io should take one to current active documentation at https://docs.kubestellar.io/main/

**Comment by MikeSpreitzer** [comment]
The problem is the first sentence, "NOTE: Some of our documentation is on the website [kubestellar.io](https://github.com/kubestellar/kubestellar/blob/main/kubestellar.io), some is here." in https://github.com/kubestellar/kubestellar/blob/main/README.md
