### ISSUE TITLE
bug: step numbers are messed up on website

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#1928]
### Describe the bug

See the multiple step 1 in these screenshots.

<img width="828" alt="Screenshot 2024-03-19 at 4 00 30 PM" src="https://github.com/kubestellar/kubestellar/assets/14296719/38ef6690-a9fc-490e-9ff2-01c4249351df">

<img width="614" alt="Screenshot 2024-03-19 at 4 00 44 PM" src="https://github.com/kubestellar/kubestellar/assets/14296719/faddf22b-9822-4ffd-821c-7033cc865f5c">

### Steps To Reproduce

See above

### Expected Behavior

Steps numbered sequentially.

### Additional Context

The step numbers are not messed up when the markdown files are viewed directly through GitHub.

**Comment by pdettori** [comment]
It appears we are using a GitHub markdown feature "You can also just use 1. for all items, and Markdown will automatically increment the numbers for you" - unfortunately this feature does not seem to work with the website which means we will have to go back to manual numbering.

**Comment by MikeSpreitzer** [comment]
@pdettori : it is not that simple. Look at the first screenshot. The first three list members get increasing numbers. The ones after that are numbered "1". The problem is that something is not recognizing that the indendent displays are part of the list item contents.

**Comment by MikeSpreitzer** [comment]
@pdettori : I tried #1934 , but it does not change the rendered GitHub pages.

**Comment by MikeSpreitzer** [comment]
https://github.com/facelessuser/pymdown-extensions/issues/2340

**Comment by pdettori** [comment]
@MikeSpreitzer thanks, sounds good
