### ISSUE TITLE
bug: Kubestellar Controller Manager v0.21.0 log message "Successfully synced" should be less ambiguous 

### ISSUE THREAD

**Issue by cwiklik** [kubestellar/kubestellar#1932]
### Describe the bug

The controller manager (v0.21.0) logs many msgs like this: 

I0320 02:26:01.845908       1 controller.go:515] "Successfully synced" logger="Binding.worker-0" objectIdentifier={"GVK":{"Group":"apiextensions.k8s.io","Version":"v1","Kind":"CustomResourceDefinition"},"Resource":"customresourcedefinitions","ObjectName":{"Namespace":"","Name":"csisnapshotcontrollers.operator.openshift.io"}}

The "Successfully synced" may suggest to uninformed (me) that the object was synced to the spoke/wec. My understanding is that the "synced" in this case, actually means that the object was reconciled. Perhaps "reconciled" is less ambiguous.

Sourcecode in question: https://github.com/kubestellar/kubestellar/blob/755304114a53a09cc26c23148e7e39ba0afad8c6/pkg/binding/controller.go#L520
[controller.go](https://github.com/kubestellar/kubestellar/blob/755304114a53a09cc26c23148e7e39ba0afad8c6/pkg/binding/controller.go)

...

 `logger.V(2).Info("Successfully synced", "objectIdentifier", objIdentifier)`

### Steps To Reproduce

Install controller manager and view its log. In my case I am deploying on OpenShift and there are hundreds of CRDs there.

### Expected Behavior

The message logged for each CRD found should be less ambiguous. Also, does this have to be logged at level=2?

**Comment by pdettori** [comment]
I agree @cwiklik , I think we should rename that "synced" to "reconciled". And I think too that logging that at V(2) is too verbose, perhaps it should be V(4)
