### ISSUE TITLE
OCM ManifestWork resources size limit

### ISSUE THREAD

**Issue by vMaroon** [kubestellar/kubestellar#2006]
As seen in a log file shared by @clubanderson:

> E0402 13:39:29.737793       1 generic_transport_controller.go:248] "failed to process Binding object" err="failed to process object with key 'kuberay-bindingpolicy' - failed to propagate wrapped object 'kuberay-bindingpolicy-wds1' to all required WECs - failed to propagate wrapped object to cluster mailbox namespace 'edgeplatform-test-wec1' - failed to create wrapped object 'kuberay-bindingpolicy-wds1' in destination WEC mailbox namespace 'edgeplatform-test-wec1' - admission webhook \"manifestworkvalidators.admission.work.open-cluster-management.io\" denied the request: the size of manifests is 1042259 bytes which exceeds the 512000 limit" logger="transport-controller" objectKey="kuberay-bindingpolicy" workerID=4

We can see that the cap on manifests size is `512000 bytes`, which is smaller than the kubernetes resource size cap (`1MiB`).

**Comment by ezrasilvera** [comment]
@vMaroon For now let's add it to the docs in our limitations section
