### ISSUE TITLE
🐛  stress-testing CRUD for BindingPolicies

### ISSUE THREAD

**Issue by clubanderson** [kubestellar/kubestellar#2007]
### Feature Description

I witnessed a WDS api server go unresponsive while creating 5 binding policies in quick succession

this is from stacker:

working on ***** wec-kuberay-bindingpolicy for wds1 - git clone and apply *****
   🗑️ deleting Repository from git@github.ibm.com:MCC/MCC.git from /Users/andan02/projects/MCC/stacker/bin/gitRepos/MCC
   🛠️ [rm -rf /Users/andan02/projects/MCC/stacker/bin/gitRepos/MCC]
      🗑️ deleted local local git repository '/Users/andan02/projects/MCC/stacker/bin/gitRepos/MCC'
   🌱 cloning Repository from ks2 git@github.ibm.com:MCC/MCC.git to /Users/andan02/projects/MCC/stacker/bin/gitRepos/MCC
Enumerating objects: 279, done.
Counting objects: 100% (279/279), done.
Compressing objects: 100% (234/234), done.
Total 279 (delta 75), reused 158 (delta 34), pack-reused 0
   🌱 cloned repository
   REPO name: MCC.git
   REPO directory: gitRepos/MCC/cicd/stars/wec-kuberay-bindingpolicy
   📁files containing 'kind: Kustomization':
       none
   📁files containing 'kind: Namespace':
       none
   📁files containing 'kind: CustomResourceDefinition':
       none
   📁non-crd and non-ns files found:
     📄kuberay-bindingpolicy1.yml
     📄kuberay-bindingpolicy2.yml
     📄kuberay-bindingpolicy3.yml
     📄kuberay-bindingpolicy4.yml
     📄kuberay-bindingpolicy5.yml
   ✨ creating objects from files above:
       ℹ️ BindingPolicy/kuberay-bindingpolicy-1 object not detected, attempting creation
          ✨ created object control.kubestellar.io/v1alpha1/bindingpolicies kuberay-bindingpolicy-1
       ℹ️ BindingPolicy/kuberay-bindingpolicy-2 object not detected, attempting creation
          ✨ created object control.kubestellar.io/v1alpha1/bindingpolicies kuberay-bindingpolicy-2
       ℹ️ BindingPolicy/kuberay-bindingpolicy-3 object not detected, attempting creation
          ✨ created object control.kubestellar.io/v1alpha1/bindingpolicies kuberay-bindingpolicy-3
       ℹ️ BindingPolicy/kuberay-bindingpolicy-4 object not detected, attempting creation
          ✨ created object control.kubestellar.io/v1alpha1/bindingpolicies kuberay-bindingpolicy-4
       ℹ️ BindingPolicy/kuberay-bindingpolicy-5 object not detected, attempting creation
          ℹ️ object kuberay-bindingpolicy-5 is being created (if error, namespace might be missing from resource definition). Retrying in 5 seconds: control.kubestellar.io/v1alpha1/bindingpolicies: the server could not find the requested resource
          ℹ️ object kuberay-bindingpolicy-5 is being created (if error, namespace might be missing from resource definition). Retrying in 5 seconds: control.kubestellar.io/v1alpha1/bindingpolicies: the server could not find the requested resource
          ℹ️ object kuberay-bindingpolicy-5 is being created (if error, namespace might be missing from resource definition). Retrying in 5 seconds: control.kubestellar.io/v1alpha1/bindingpolicies: the server could not find the requested resource
          ℹ️ object kuberay-bindingpolicy-5 is being created (if error, namespace might be missing from resource definition). Retrying in 5 seconds: control.kubestellar.io/v1alpha1/bindingpolicies: the server could not find the requested resource
          ℹ️ object kuberay-bindingpolicy-5 is being created (if error, namespace might be missing from resource definition). Retrying in 5 seconds: control.kubestellar.io/v1alpha1/bindingpolicies: the server could not find the requested resource
          ℹ️ object kuberay-bindingpolicy-5 is being created (if error, namespace might be missing from resource definition). Retrying in 5 seconds: control.kubestellar.io/v1alpha1/bindingpolicies: the server could not find the requested resource
          ℹ️ object kuberay-bindingpolicy-5 is being created (if error, namespace might be missing from resource definition). Retrying in 5 seconds: control.kubestellar.io/v1alpha1/bindingpolicies: the server could not find the requested resource
          ℹ️ object kuberay-bindingpolicy-5 is being created (if error, namespace might be missing from resource definition). Retrying in 5 seconds: control.kubestellar.io/v1alpha1/bindingpolicies: the server could not find the requested resource
          ℹ️ object kuberay-bindingpolicy-5 is being created (if error, namespace might be missing from resource definition). Retrying in 5 seconds: control.kubestellar.io/v1alpha1/bindingpolicies: the server could not find the requested resource
          ℹ️ object kuberay-bindingpolicy-5 is being created (if error, namespace might be missing from resource definition). Retrying in 5 seconds: control.kubestellar.io/v1alpha1/bindingpolicies: the server could not find the requested resource
       🟡 error creating object control.kubestellar.io/v1alpha1/bindingpolicies kuberay-bindingpolicy-5 in default: the server could not find the requested resource
   ✅ git clone and kubectl apply successful

### Proposed Solution

just apply a few dozen bp in a row, delete them, re-create them, etc.

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by MikeSpreitzer** [comment]
To test he hypothesis that the kube-apiserver restarted, get a pod listing that includes the kube-apiserver. If it shows some container restarts, use `kubectl logs -p` to get the log from the last container run that crashed.

**Comment by ezrasilvera** [comment]
@clubanderson Can you please add some info so we can try to reproduce?  Did you already have objects that need to be downsynced or did you create a BP before the objects are in WDS ?  
Any additional info on the env will be helpful (kind?  OCP ?  number of WECs?  wds==host ?  etc..)

**Comment by clubanderson** [comment]
objects existed, bp was added after

**Comment by effi-ofer** [comment]
@clubanderson have you seen it since?  Any hints on how to go about reproducing?  I tried creating 10 bindingpolicies after creating a few objects, but perhaps I am not creating enough objects or something similar.
