### ISSUE TITLE
bug: cannot install OTP for multiple different WDS

### ISSUE THREAD

**Issue by clubanderson** [kubestellar/kubestellar#2021]
### Describe the bug

can only install one OTP per environment - here is what happens when you try for more than 1

install OTP for wds1

`helm --kube-context=wds0 install ocm-transport-plugin oci://ghcr.io/kubestellar/ocm-transport-plugin/chart/ocm-transport-plugin --namespace default --create-namespace --version 0.1.2 --set transport_cp_name=its1 --set wds_cp_name=wds1
`

install OTP for wds0
```
helm --kube-context=wds0 install ocm-transport-plugin1 oci://ghcr.io/kubestellar/ocm-transport-plugin/chart/ocm-transport-plugin --namespace default --create-namespace --version 0.1.2 --set transport_cp_name=its1 --set wds_cp_name=wds0
Pulled: ghcr.io/kubestellar/ocm-transport-plugin/chart/ocm-transport-plugin:0.1.2
Digest: sha256:e58fb2882d2e3c39de6959b2a02490b537622a6f93e011ed5a298c52c5f11a8e
Error: INSTALLATION FAILED: Unable to continue with install: ClusterRole "transport-controller-role" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "ocm-transport-plugin1": current value is "ocm-transport-plugin"

```

as you can see, I changed the name of the release here. context is wds0 (the host)

(not supposed to work I guess - but for completeness) if I try to install in context of wds1 for wds1, I get this
```
helm --kube-context=wds1 install ocm-transport-plugin oci://ghcr.io/kubestellar/ocm-transport-plugin/chart/ocm-transport-plugin --namespace default --create-namespace --version 0.1.2 --set transport_cp_name=its1 --set wds_cp_name=wds1
Pulled: ghcr.io/kubestellar/ocm-transport-plugin/chart/ocm-transport-plugin:0.1.2
Digest: sha256:e58fb2882d2e3c39de6959b2a02490b537622a6f93e011ed5a298c52c5f11a8e
Error: INSTALLATION FAILED: 3 errors occurred:
        * namespaces "wds1-system" not found
        * namespaces "wds1-system" not found
        * namespaces "wds1-system" not found
```

please advise - unable to proceed with MCAD and MCC due to this bug

### Steps To Reproduce

can only install one OTP per environment - here is what happens when you try for more than 1

install OTP for wds1

`helm --kube-context=wds0 install ocm-transport-plugin oci://ghcr.io/kubestellar/ocm-transport-plugin/chart/ocm-transport-plugin --namespace default --create-namespace --version 0.1.2 --set transport_cp_name=its1 --set wds_cp_name=wds1
`

install OTP for wds0
```
helm --kube-context=wds0 install ocm-transport-plugin1 oci://ghcr.io/kubestellar/ocm-transport-plugin/chart/ocm-transport-plugin --namespace default --create-namespace --version 0.1.2 --set transport_cp_name=its1 --set wds_cp_name=wds0
Pulled: ghcr.io/kubestellar/ocm-transport-plugin/chart/ocm-transport-plugin:0.1.2
Digest: sha256:e58fb2882d2e3c39de6959b2a02490b537622a6f93e011ed5a298c52c5f11a8e
Error: INSTALLATION FAILED: Unable to continue with install: ClusterRole "transport-controller-role" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "ocm-transport-plugin1": current value is "ocm-transport-plugin"

```

as you can see, I changed the name of the release here. context is wds0 (the host)

please advise

### Expected Behavior

OTP helm install should work for multiple

**Comment by francostellari** [comment]
@clubanderson PR https://github.com/kubestellar/ocm-transport-plugin/pull/10 fixes a bug in naming conflicts for cluster-level resources when using multiple WDS

**Comment by francostellari** [comment]
@clubanderson I believe there is also a usage issue. The 2 heml command should
1. target the same `--kube-context`, e.g. kubeflex-kind or the root OCP context, not the wds0 and wds1 CPs
2. the 2 helm chatys should be named differently
3. the namespace can be shared and left as default asn you are already doing

In summery, once the PR above is implemented, your new commands should be:

```shell
helm --kube-context=<cluster context, not CP> upgrade --install wds0-ocm-transport-plugin ocm-transport-plugin oci://ghcr.io/kubestellar/ocm-transport-plugin/chart/ocm-transport-plugin --version 0.1.x --set transport_cp_name=its1 --set wds_cp_name=wds0 

helm --kube-context=<cluster context, not CP> upgrade --install wds1-ocm-transport-plugin ocm-transport-plugin oci://ghcr.io/kubestellar/ocm-transport-plugin/chart/ocm-transport-plugin --version 0.1.x --set transport_cp_name=its1 --set wds_cp_name=wds1
```

**Comment by clubanderson** [comment]
wds0 is the core/hub, so it is interchangeable.

I can do the different names, but it requires more customization on my part.

I hope this fix covers the clusterscoped - it looks like it will with the unique naming.

Thank you

**Comment by nirrozenbaum** [comment]
@francostellari fix is merged and a new OTP with the updated chart was released - v0.1.3.

**Comment by francostellari** [comment]
@clubanderson if you don't want to keep track of the additional naming of the charts, you can use `--generate-name` instead of giving a name to the charts

**Comment by MikeSpreitzer** [comment]
Scenario 2 should also exercise this. I will try it.

**Comment by MikeSpreitzer** [comment]
I succeeded in running Scenarios 1 and 2 in https://github.com/kubestellar/kubestellar/blob/233f8dde6250e7ff0e10fd778a7d5cbaa9850896/docs/content/direct/examples.md , modified to say `export OCM_TRANSPORT_PLUGIN=0.1.3`.

**Comment by clubanderson** [comment]
yes, I did as well - thank you. The '--generate-name' does not allow me to track the exact instance and therefore makes it impossible to delete or upgrade this chart.

Need another way to install the OTP. I would have hoped the OTP would have somehow been installed in the WDS itself and not in the core. I understand why this is not possible, but the OTP is "owned by" or "associated with" the WDS.

**Comment by MikeSpreitzer** [comment]
Oh! Scenario 2 does not test that wds1 is still functional after creating wds2. I see that indeed there is just one chart instance ("release").

```shell
bash-3.2$ helm --kube-context kind-kubeflex list -A
NAME                	NAMESPACE      	REVISION	UPDATED                                	STATUS  	CHART                          	APP VERSION
kubeflex-operator   	kubeflex-system	1       	2024-04-04 16:24:38.800388 -0400 EDT   	deployed	kubeflex-operator-v0.5.0       	v0.5.0     
kubestellar         	wds1-system    	1       	2024-04-04 20:29:24.394069838 +0000 UTC	deployed	controller-manager-chart-0.21.2	0.21.2     
kubestellar         	wds2-system    	1       	2024-04-04 16:43:17.253156 -0400 EDT   	deployed	controller-manager-chart-0.21.2	0.21.2     
ocm-transport-plugin	default        	2       	2024-04-04 16:42:03.080885 -0400 EDT   	deployed	ocm-transport-plugin-0.1.3     	0.1.3      
postgres            	kubeflex-system	1       	2024-04-04 16:23:47.848258 -0400 EDT   	deployed	postgresql-13.1.5              	16.0.0     
vcluster            	imbs1-system   	1       	2024-04-04 20:26:20.25819501 +0000 UTC 	deployed	vcluster-0.16.4                	0.16.4     
```

I am surprised that the chart instance is going into the namespace named `default`.

**Comment by MikeSpreitzer** [comment]
If I understand correctly, @clubanderson was able to have two instances of this chart, one for each of two WDSes, by adding `--namespace ${wds_name}-system` to his `helm` commands. The chart itself qualifies every object's namespace/name with the WDS name, the only problem was the collision of the Helm "release" objects.

**Comment by MikeSpreitzer** [comment]
I wondered what would go wrong if https://github.com/kubestellar/ocm-transport-plugin/blob/main/chart/templates/controller.yaml#L20 were updated by replacing every occurrence of `{{.Values.wds_cp_name}}` with `{{.Release.Namespace}}`.

I found two potentially troubling uses of `wds_cp_name`:
- https://github.com/kubestellar/ocm-transport-plugin/blob/7a69bcd1d7d8f9fb933a9bf4acaa94821b9144dc/chart/templates/controller.yaml#L116 and
- https://github.com/kubestellar/ocm-transport-plugin/blob/7a69bcd1d7d8f9fb933a9bf4acaa94821b9144dc/chart/templates/controller.yaml#L138

It turns out that the transport controller uses the `--wds-name` only as a source of strings that distinguish controllers for different WDSes; these strings can be anything (that does not violate name length, character set, or syntax concerns) that varies from WDS to WDS, it does not actually have to be the WDS name.

The use in the call to the get-kubeconfig.sh script is more troubling. It actually needs to be the _name_ of the WDS. This chart currently asserts that the relevant host cluster namespace for a given WDS is `<WDS name>-system`. If we can take that as fixed, then we can write a bit of template logic that extracts the WDS name from that namespace name.

**Comment by francostellari** [comment]
@clubanderson can you please clarify if this was closed by my explanation of helm usage and the fix introduced to chart 0.1.3 by PR https://github.com/kubestellar/ocm-transport-plugin/pull/10

**Comment by francostellari** [comment]
@clubanderson this step will not be needed anymore when I have a chance to update kubestellar PCH

**Comment by clubanderson** [comment]
@francostellari before 0.1.3, OTP would not install. Since 0.1.3, installation succeeds, but the issue here remains.

**Comment by pdettori** [comment]
@clubanderson can we close this issue since #2038 is resolved ?

**Comment by clubanderson** [comment]
All set here I think
