### ISSUE TITLE
Finish renaming "IMBS" to "ITS"

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#2024]
We agreed long ago to use the term "Inventory and Transport Space (ITS)" in place of "Inventory and MailBox Space (IMBS)". But we have not updated all our docs and examples. This should be done.

**Comment by MikeSpreitzer** [comment]
@clubanderson

**Comment by effi-ofer** [comment]
There are also a couple of files in ocm-transport-plugin (chart/values.yaml, chart/templates/controller.yaml) that need updating.
