### ISSUE TITLE
feature: Easy release testing for KS on OCP

### ISSUE THREAD

**Issue by ezrasilvera** [kubestellar/kubestellar#2037]
1. Configure an OCP environment for KCP (hub + 2 WECs)
2. Script(s) based procedure for release testing
   - Download KS release sources to get the testing scripts 
   - Download all release artifacts (KS, OTP, etc..)
   - Install KS environment (KS components, WECs, agents , etc.._)
   - Run the KS e2e tests (deployment t multiple clusters + ginkgo)
  
Goal:  Have a very simple procedure, preferably using 1-2 scripts that automatically will perform the needed configuration and launch the tests.

**Comment by effi-ofer** [comment]
Thanks Braulio for delivering #2046.  As discussed, this issue will also contain the method of access to the OCP cluster.

**Comment by dumb0002** [comment]
A simple procedure to automatically run our e2e tests in a OCP env has be implemented in this PR: https://github.com/kubestellar/kubestellar/pull/2046
