### ISSUE TITLE
bug: OTP complains of "rpc error: code = Unknown desc = database is locked" logger="transport-controller" objectKey="appwrapper-sample-default" workerID=1

### ISSUE THREAD

**Issue by clubanderson** [kubestellar/kubestellar#2050]
### Describe the bug

E0412 17:16:21.778987       1 generic_transport_controller.go:248] "failed to process Binding object" err="failed to process object with key 'appwrapper-sample-default' - failed to propagate wrapped object 'appwrapper-sample-default-wds0' to all required WECs - failed to propagate wrapped object to cluster mailbox namespace 'edgeplatform-test-wec1' - failed to create wrapped object 'appwrapper-sample-default-wds0' in destination WEC mailbox namespace 'edgeplatform-test-wec1' - rpc error: code = Unknown desc = database is locked" logger="transport-controller" objectKey="appwrapper-sample-default" workerID=1

while attempting to sync an MCAD appwrapper to a remote wec.

clusters:
edgeplatform-test-kscore, edgeplatform-test-wec1

ks environment:
its1, wds0 (hosted), wds1 (k8s)

edgeplatform-test-wec1 is connected to wds1

managedcluster:
```
kubectl --context its1 get managedclusters -o yaml                              edgeplatform-test-kscore/default ⎈
apiVersion: v1
items:
- apiVersion: cluster.open-cluster-management.io/v1
  kind: ManagedCluster
  metadata:
    annotations:
      remoteLokiURL: https://logging-loki-openshift-logging.edgeplatform-test-kscore-9ca4d14d48413d18ce61b80811ba4308-0000.us-south.containers.appdomain.cloud/api/logs/v1/application
      remoteWriteURL: http://thanos-receiver-router-monitoring.edgeplatform-test-kscore-9ca4d14d48413d18ce61b80811ba4308-0000.us-south.containers.appdomain.cloud/api/v1/receive
    creationTimestamp: "2024-04-11T19:02:52Z"
    finalizers:
    - cluster.open-cluster-management.io/api-resource-cleanup
    generation: 4
    labels:
      cluster.open-cluster-management.io/clusterset: default
      feature.open-cluster-management.io/addon-addon-status: available
      location-group: edge
      name: edgeplatform-test-wec1
    name: edgeplatform-test-wec1
    resourceVersion: "820"
    uid: 7e545b9f-423d-4a62-8d40-4fde64837ea3
  spec:
    hubAcceptsClient: true
    leaseDurationSeconds: 60
```

bindingpolicies:
```
kubectl --context wds0 get bindingpolicies  -o yaml 
apiVersion: v1
items:
- apiVersion: control.kubestellar.io/v1alpha1
  kind: BindingPolicy
  metadata:
    creationTimestamp: "2024-04-12T17:16:06Z"
    finalizers:
    - bindingpolicy.kubestellar.io/kscontroller
    generation: 1
    name: appwrapper-sample-default
    resourceVersion: "165195261"
    uid: 8f105e39-fb8f-48c4-be43-964cb8fbf526
  spec:
    clusterSelectors:
    - matchLabels:
        location-group: edge
        name: edgeplatform-test-wec1
    downsync:
    - namespaces:
      - default
      objectNames:
      - appwrapper-sample
      objectSelectors:
      - matchLabels:
          appwrapper.mcad.ibm.com/assignedCluster: edgeplatform-test-wec1
    wantSingletonReportedState: true
- apiVersion: control.kubestellar.io/v1alpha1
  kind: BindingPolicy
  metadata:
    creationTimestamp: "2024-04-03T20:51:43Z"
    finalizers:
    - bindingpolicy.kubestellar.io/kscontroller
    generation: 1
    name: edgeplatform-test-wec1-hosted-mcad-bp
    resourceVersion: "150814756"
    uid: 06d0d22f-e3b2-48a5-ac61-a4fdecdd04d2
  spec:
    clusterSelectors:
    - matchLabels:
        location-group: edge
        name: edgeplatform-test-wec1
    downsync:
    - objectSelectors:
      - matchLabels:
          app.kubernetes.io/cluster: edgeplatform-test-wec1
    wantSingletonReportedState: true
kind: List
metadata:
  resourceVersion: ""
```

the bindings:
```
kubectl --context wds0 get bdg -o yaml  
apiVersion: v1
items:
- apiVersion: control.kubestellar.io/v1alpha1
  kind: Binding
  metadata:
    creationTimestamp: "2024-04-12T17:16:11Z"
    finalizers:
    - transport.kubestellar.io/object-cleanup
    generation: 1
    name: appwrapper-sample-default
    ownerReferences:
    - apiVersion: control.kubestellar.io/v1alpha1
      blockOwnerDeletion: false
      controller: true
      kind: BindingPolicy
      name: appwrapper-sample-default
      uid: 8f105e39-fb8f-48c4-be43-964cb8fbf526
    resourceVersion: "165195353"
    uid: 7bdb9802-8832-4306-8d75-e26b60c49c2a
  spec:
    destinations:
    - clusterId: edgeplatform-test-wec1
    workload:
      namespaceScope:
      - group: workload.codeflare.dev
        name: appwrapper-sample
        namespace: default
        resource: appwrappers
        resourceVersion: "165195282"
        version: v1beta1
- apiVersion: control.kubestellar.io/v1alpha1
  kind: Binding
  metadata:
    creationTimestamp: "2024-04-03T20:52:42Z"
    finalizers:
    - transport.kubestellar.io/object-cleanup
    generation: 1196
    name: edgeplatform-test-wec1-hosted-mcad-bp
    ownerReferences:
    - apiVersion: control.kubestellar.io/v1alpha1
      blockOwnerDeletion: false
      controller: true
      kind: BindingPolicy
      name: edgeplatform-test-wec1-hosted-mcad-bp
      uid: 06d0d22f-e3b2-48a5-ac61-a4fdecdd04d2
    resourceVersion: "165232125"
    uid: 8e8d6f27-4529-4bbc-8579-e289d87f519b
  spec:
    destinations:
    - clusterId: edgeplatform-test-wec1
    workload:
      namespaceScope:
      - group: workload.codeflare.dev
        name: edgeplatform-test-wec1
        namespace: mcad
        resource: clusterinfo
        resourceVersion: "165232094"
        version: v1beta1
kind: List
metadata:
  resourceVersion: ""
```

manifestworks:
```
kubectl --context its1 get manifestworks edgeplatform-test-wec1-hosted-mcad-bp-wds0 -n edgeplatform-test-wec1 -o yaml

apiVersion: work.open-cluster-management.io/v1
kind: ManifestWork
metadata:
  annotations:
    transport.kubestellar.io/originOwnerReferenceBindingGeneration: "1198"
  creationTimestamp: "2024-04-12T17:15:12Z"
  finalizers:
  - cluster.open-cluster-management.io/manifest-work-cleanup
  generation: 1
  labels:
    transport.kubestellar.io/originOwnerReferenceBindingKey: edgeplatform-test-wec1-hosted-mcad-bp
    transport.kubestellar.io/originWdsName: wds0
  name: edgeplatform-test-wec1-hosted-mcad-bp-wds0
  namespace: edgeplatform-test-wec1
  resourceVersion: "154014"
  uid: 9083acb9-d120-48d3-8f29-daf38cafe620
spec:
  workload:
    manifests:
    - apiVersion: workload.codeflare.dev/v1beta1
      kind: ClusterInfo
      metadata:
        annotations:
          meta.helm.sh/release-name: mcad-controller
          meta.helm.sh/release-namespace: mcad
        creationTimestamp: "2024-04-12T16:56:34Z"
        labels:
          app.kubernetes.io/cluster: edgeplatform-test-wec1
          app.kubernetes.io/managed-by: Helm
          managed-by.kubestellar.io/singletonstatus: "true"
        name: edgeplatform-test-wec1
        namespace: mcad
status:
  conditions:
  - lastTransitionTime: "2024-04-12T17:15:14Z"
    message: Apply manifest work complete
    observedGeneration: 1
    reason: AppliedManifestWorkComplete
    status: "True"
    type: Applied
  - lastTransitionTime: "2024-04-12T17:15:14Z"
    message: All resources are available
    observedGeneration: 1
    reason: ResourcesAvailable
    status: "True"
    type: Available
  resourceStatus:
    manifests:
    - conditions:
      - lastTransitionTime: "2024-04-12T17:15:14Z"
        message: Apply manifest complete
        reason: AppliedManifestComplete
        status: "True"
        type: Applied
      - lastTransitionTime: "2024-04-12T17:15:14Z"
        message: Resource is available
        reason: ResourceAvailable
        status: "True"
        type: Available
      - lastTransitionTime: "2024-04-12T17:15:14Z"
        message: ""
        reason: NoStatusFeedbackSynced
        status: "True"
        type: StatusFeedbackSynced
      resourceMeta:
        group: workload.codeflare.dev
        kind: ClusterInfo
        name: edgeplatform-test-wec1
        namespace: mcad
        ordinal: 0
        resource: clusterinfo
        version: v1beta1
      statusFeedback: {}
```

```
kubectl --context its1 get manifestworks appwrapper-sample-default-wds0 -n edgeplatform-test-wec1 -o yaml
apiVersion: work.open-cluster-management.io/v1
kind: ManifestWork
metadata:
  annotations:
    transport.kubestellar.io/originOwnerReferenceBindingGeneration: "1"
  creationTimestamp: "2024-04-12T17:16:21Z"
  finalizers:
  - cluster.open-cluster-management.io/manifest-work-cleanup
  generation: 1
  labels:
    transport.kubestellar.io/originOwnerReferenceBindingKey: appwrapper-sample-default
    transport.kubestellar.io/originWdsName: wds0
  name: appwrapper-sample-default-wds0
  namespace: edgeplatform-test-wec1
  resourceVersion: "150436"
  uid: b7f9a638-a732-4fac-8702-e45a798d6466
spec:
  workload:
    manifests:
    - apiVersion: workload.codeflare.dev/v1beta1
      kind: AppWrapper
      metadata:
        annotations:
          appwrapper.mcad.ibm.com/serializedStatus: '{"state":"Running","step":"dispatching","dispatchTimestamp":null,"requeueTimestamp":null,"restarts":0,"transitions":[{"time":"2024-04-12T17:16:06Z","controller":"Dispatcher","state":"Pending"},{"time":"2024-04-12T17:16:06Z","controller":"Dispatcher","state":"Running","step":"dispatching"}],"transitionCount":2,"conditions":[{"type":"Pending","status":"False","lastTransitionTime":"2024-04-12T17:16:06Z","reason":"Dispatched","message":"Selected
            for dispatch"}]}'
        creationTimestamp: "2024-04-12T17:16:06Z"
        labels:
          appwrapper.mcad.ibm.com/assignedCluster: edgeplatform-test-wec1
          managed-by.kubestellar.io/singletonstatus: "true"
        name: appwrapper-sample
        namespace: default
      spec:
        priority: 5
        priorityslope: "0"
        resources:
          GenericItems:
          - custompodresources:
            - replicas: 1
              requests:
                cpu: 10m
                memory: 10Mi
            generictemplate:
              apiVersion: v1
              kind: Pod
              metadata:
                name: appwrapper-sample-1
              spec:
                containers:
                - command:
                  - sh
                  - -c
                  - sleep 5
                  image: quay.io/project-codeflare/busybox
                  name: busybox
                  resources:
                    requests:
                      cpu: 10m
                      memory: 10Mi
                restartPolicy: Never
            priorityslope: "0"
        schedulingSpec:
          dispatchDuration: {}
          minAvailable: 2
          requeuing:
            forceDeletionTimeInSeconds: 570
            growthType: exponential
            maxNumRequeuings: 5
            maxTimeInSeconds: 0
            numRequeuings: 0
            pauseTimeInSeconds: 90
            timeInSeconds: 270
        service:
          spec: {}
status:
  conditions:
  - lastTransitionTime: "2024-04-12T17:16:23Z"
    message: Apply manifest work complete
    observedGeneration: 1
    reason: AppliedManifestWorkComplete
    status: "True"
    type: Applied
  - lastTransitionTime: "2024-04-12T17:16:23Z"
    message: All resources are available
    observedGeneration: 1
    reason: ResourcesAvailable
    status: "True"
    type: Available
  resourceStatus:
    manifests:
    - conditions:
      - lastTransitionTime: "2024-04-12T17:16:23Z"
        message: Apply manifest complete
        reason: AppliedManifestComplete
        status: "True"
        type: Applied
      - lastTransitionTime: "2024-04-12T17:16:23Z"
        message: Resource is available
        reason: ResourceAvailable
        status: "True"
        type: Available
      - lastTransitionTime: "2024-04-12T17:16:23Z"
        message: ""
        reason: NoStatusFeedbackSynced
        status: "True"
        type: StatusFeedbackSynced
      resourceMeta:
        group: workload.codeflare.dev
        kind: AppWrapper
        name: appwrapper-sample
        namespace: default
        ordinal: 0
        resource: appwrappers
        version: v1beta1
      statusFeedback: {}
```

### Steps To Reproduce

1. setup kubestellar with its1, wds0, wds1
2. install MCAD dispatcher on wds0, and MCAD runner on wds1
3. attempt to synchronize appwrapper

### Expected Behavior

appwrapper should sync to remote wec and execute

**Comment by clubanderson** [comment]
development team has access to edgeplatform-test-kscore to investigate further

**Comment by MikeSpreitzer** [comment]
Some of us have that access, I lack it temporarily.

Software version? Pod statuses?

**Comment by MikeSpreitzer** [comment]
Looking at the timestamps, it appears that the intended ManifestWork object was successfully created during the same second as the error message was logged --- quite possibly on a retry after the error message was logged. The status of that ManifestWork seems to be saying that the requested workload has happily camping on the WEC. Is that so? Is this just a too-alarming message about a transient problem?

**Comment by cwiklik** [comment]
Andy deployed the latest. The transport controller log attached. Not much there except for the two errors shown above. 

Controller Manager deployed:

kc get pod transport-controller-fc44cc5b8-wb2hp -n wds0-system -o yaml                                                                                                                                                                          ─╯
apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: a1adb5f9419ecc6f8b056db875da80ba1eb2d764ffe0f2bd5580409f5330730e
    cni.projectcalico.org/podIP: 172.30.204.167/32
    cni.projectcalico.org/podIPs: 172.30.204.167/32
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "k8s-pod-network",
          "ips": [
              "172.30.204.167"
          ],
          "default": true,
          "dns": {}
      }]
    openshift.io/scc: restricted-v2
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
  creationTimestamp: "2024-04-12T16:55:43Z"
  generateName: transport-controller-fc44cc5b8-
  labels:
    name: transport-controller
    pod-template-hash: fc44cc5b8
  name: transport-controller-fc44cc5b8-wb2hp
  namespace: wds0-system
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: transport-controller-fc44cc5b8
    uid: a32f895b-5f74-4ea3-a39a-9bd5e50b1689
  resourceVersion: "165168919"
  uid: cdf0fb4d-1dba-47ab-bc37-c8b208da591e
spec:
  containers:
  - args:
    - --transport-kubeconfig=/mnt/shared/transport-kubeconfig
    - --wds-kubeconfig=/mnt/shared/wds-kubeconfig
    - --wds-name=wds0
    - -v=4
    image: ghcr.io/kubestellar/ocm-transport-plugin/transport-controller:0.1.3
    imagePullPolicy: IfNotPresent
    name: transport-controller
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      runAsNonRoot: true
      runAsUser: 1000790000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /mnt/shared
      name: shared-volume
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-pjjl5
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: transport-controller-sa-dockercfg-wtbmp
  initContainers:
  - command:
    - bin/sh
    - -c
    - sh /mnt/config/get-kubeconfig.sh wds0 true | base64 -d > /mnt/shared/wds-kubeconfig
    image: quay.io/kubestellar/kubectl:1.27.8
    imagePullPolicy: Always
    name: setup-wds-kubeconfig
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      runAsNonRoot: true
      runAsUser: 1000790000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /mnt/config
      name: config-volume
    - mountPath: /mnt/shared
      name: shared-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-pjjl5
      readOnly: true
  - command:
    - bin/sh
    - -c
    - sh /mnt/config/get-kubeconfig.sh its1 true | base64 -d > /mnt/shared/transport-kubeconfig
    image: quay.io/kubestellar/kubectl:1.27.8
    imagePullPolicy: Always
    name: setup-imbs-kubeconfig
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      runAsNonRoot: true
      runAsUser: 1000790000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /mnt/config
      name: config-volume
    - mountPath: /mnt/shared
      name: shared-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-pjjl5
      readOnly: true
  nodeName: 10.176.37.202
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000790000
    seLinuxOptions:
      level: s0:c28,c17
    seccompProfile:
      type: RuntimeDefault
  serviceAccount: transport-controller-sa
  serviceAccountName: transport-controller-sa
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - emptyDir: {}
    name: shared-volume
  - configMap:
      defaultMode: 484
      name: transport-controller-config
    name: config-volume
  - name: kube-api-access-pjjl5
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
      - configMap:
          items:
          - key: service-ca.crt
            path: service-ca.crt
          name: openshift-service-ca.crt
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-04-12T16:55:48Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-04-12T16:55:49Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-04-12T16:55:49Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-04-12T16:55:43Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: cri-o://4b094751061fbd853c94e3f557a8de15014e2d7d4c6341716469beee936776f6
    image: ghcr.io/kubestellar/ocm-transport-plugin/transport-controller:0.1.3
    imageID: ghcr.io/kubestellar/ocm-transport-plugin/transport-controller@sha256:2532ff27fb3b7ac0af2f259f3e37a25c3df7e0e12b603213fe9a9e04fcd23b62
    lastState: {}
    name: transport-controller
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-04-12T16:55:48Z"
  hostIP: 10.176.37.202
  initContainerStatuses:
  - containerID: cri-o://f12ee95877cd1571da042bfcfb4693c0a8fe60ff46ead3c15e3ebe30f02721cb
    image: quay.io/kubestellar/kubectl:1.27.8
    imageID: quay.io/kubestellar/kubectl@sha256:126dd8c147bf171d1a3ecebc7e31e866c7efbbc2cf1267c62f817a1a2256a0c8
    lastState: {}
    name: setup-wds-kubeconfig
    ready: true
    restartCount: 0
    state:
      terminated:
        containerID: cri-o://f12ee95877cd1571da042bfcfb4693c0a8fe60ff46ead3c15e3ebe30f02721cb
        exitCode: 0
        finishedAt: "2024-04-12T16:55:46Z"
        reason: Completed
        startedAt: "2024-04-12T16:55:45Z"
  - containerID: cri-o://77dce19118d0b6794d5008651c60aeb901ced225e73c66735b3b3342fdbca18d
    image: quay.io/kubestellar/kubectl:1.27.8
    imageID: quay.io/kubestellar/kubectl@sha256:126dd8c147bf171d1a3ecebc7e31e866c7efbbc2cf1267c62f817a1a2256a0c8
    lastState: {}
    name: setup-imbs-kubeconfig
    ready: true
    restartCount: 0
    state:
      terminated:
        containerID: cri-o://77dce19118d0b6794d5008651c60aeb901ced225e73c66735b3b3342fdbca18d
        exitCode: 0
        finishedAt: "2024-04-12T16:55:48Z"
        reason: Completed
        startedAt: "2024-04-12T16:55:47Z"
  phase: Running
  podIP: 172.30.204.167
  podIPs:
  - ip: 172.30.204.167
  qosClass: BestEffort
  startTime: "2024-04-12T16:55:43Z"



[tc.log](https://github.com/kubestellar/kubestellar/files/14962341/tc.log)

**Comment by clubanderson** [comment]
[log-wds0.txt](https://github.com/kubestellar/kubestellar/files/14962372/log-wds0.txt)
[log-wds1.txt](https://github.com/kubestellar/kubestellar/files/14962373/log-wds1.txt)

**Comment by cwiklik** [comment]
The appwrapper is not on the WEC

**Comment by MikeSpreitzer** [comment]
But the ManifestWork is in the ITS, as @andreyod showed above. If OCM is not transporting from the ManifestWork to the WEC, then that is where the actual problem is. The log posted recently shows successful handling of the relevant Binding shortly after the error messages.  Here is an excerpt (blank lines added for clarity):

```
...
I0412 17:15:58.890433       1 generic_transport_controller.go:250] "synced Binding object successfully." logger="transport-controller" objectKey="iris-bindingpolicy" workerID=3

E0412 17:16:16.656324       1 generic_transport_controller.go:248] "failed to process Binding object" err="failed to process object with key 'appwrapper-sample-default' - failed to propagate wrapped object 'appwrapper-sample-default-wds0' to all required WECs - failed to propagate wrapped object to cluster mailbox namespace 'edgeplatform-test-wec1' - failed to create wrapped object 'appwrapper-sample-default-wds0' in destination WEC mailbox namespace 'edgeplatform-test-wec1' - rpc error: code = Unknown desc = database is locked" logger="transport-controller" objectKey="appwrapper-sample-default" workerID=1

E0412 17:16:21.778987       1 generic_transport_controller.go:248] "failed to process Binding object" err="failed to process object with key 'appwrapper-sample-default' - failed to propagate wrapped object 'appwrapper-sample-default-wds0' to all required WECs - failed to propagate wrapped object to cluster mailbox namespace 'edgeplatform-test-wec1' - failed to create wrapped object 'appwrapper-sample-default-wds0' in destination WEC mailbox namespace 'edgeplatform-test-wec1' - rpc error: code = Unknown desc = database is locked" logger="transport-controller" objectKey="appwrapper-sample-default" workerID=1
I0412 17:16:23.595473       1 generic_transport_controller.go:250] "synced Binding object successfully." 

logger="transport-controller" objectKey="appwrapper-sample-default" workerID=1
...

**Comment by cwiklik** [comment]
Attached is controller manager log from wds0. It's complaining about lack of status but I think that is normal given that the object does not exist on the WEC. The AW name is: test-appwrapper-2

[cm-new.log](https://github.com/kubestellar/kubestellar/files/14962845/cm-new.log)

**Comment by pdettori** [comment]
After some investigation on the WEC, I determined that the error in the issue is transient, the ManifestWork is correctly created in the ITS and the AppWrappers are created in the WEC, however there are 2 CRDs for the same appwrapper resource name, with different API groups:

```
$ k get appwrappers.workload.codeflare.dev
NAME                STATUS   RESTARTS   AGE
appwrapper-sample                       34m
test-appwrapper-2                       16m
$ k get appwrappers.mcad.ibm.com
No resources found in default namespace. 
```

The default for non-qualified resource name is based on the first applied CRD:

```
$ k get appwrappers
No resources found in default namespace.
```

so since you were syncing `appwrappers.workload.codeflare.dev` the default `appwrappers.mcad.ibm.com` seems to find nothing.

I recommend removing the CRD for `appwrappers.mcad.ibm.com` unless it is required.

**Comment by pdettori** [comment]
Also, @clubanderson @cwiklik - since this is not a KS issue, and the error in the log is of transient nature and had no bearing on the syncing of the objects, can we close this issue ?

**Comment by clubanderson** [comment]
found the error - wrong version of CRD was on the remote. Perhaps it would be good to soften the tone of the error in this issue.

**Comment by MikeSpreitzer** [comment]
@clubanderson: no maybe about it. #2053
