### ISSUE TITLE
bug: Service resources have their clusterIP field removed even if the value is None

### ISSUE THREAD

**Issue by shmuelk** [kubestellar/kubestellar#2064]
### Describe the bug

**Original service object:**
```
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-04-21T08:58:51Z"
  name: dummy-world-m7fzlb45wh-inf-server
  namespace: default
  ownerReferences:
  - apiVersion: control.kubestellar.io/v1alpha1
    kind: BindingPolicy
    name: dummy-world-m7fzlb45wh
    uid: afa9b94c-bfee-43af-be59-5a640a8c8b30
  resourceVersion: "9358"
  uid: 6b3b1000-1ffc-43fe-8a20-c59a4f55b1d5
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 50061
    protocol: TCP
    targetPort: 50060
  selector:
    app: dummy-world-m7fzlb45wh-inf-server
  sessionAffinity: None
  type: ClusterIP
```
**Service on WEC:**
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    operator.openshift.io/spec-hash: 6cba97d7f0c77d03cd71295590cef6695b005427b35280d9546968ba3bcba70d
  creationTimestamp: "2024-04-21T08:58:53Z"
  name: dummy-world-m7fzlb45wh-inf-server
  namespace: default
  ownerReferences:
  - apiVersion: work.open-cluster-management.io/v1
    kind: AppliedManifestWork
    name: 870f419f0221a1388cd9b155c11a89b759a86068db794ec8b7a9cdfbce20786e-dummy-world-m7fzlb45wh-wds1
    uid: f35c79b2-74b9-4210-8393-dd1730f7d823
  resourceVersion: "17995"
  uid: a5acf9b1-2adf-4d90-9215-2388580fc8b4
spec:
  clusterIP: 10.96.155.67
  clusterIPs:
  - 10.96.155.67
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 50061
    protocol: TCP
    targetPort: 50060
  selector:
    app: dummy-world-m7fzlb45wh-inf-server
  sessionAffinity: None
  type: ClusterIP
```
Note that a clusterIP has been assigned.

Here is the appropriate snippet from the appropriate ManifestWork object:
```
- apiVersion: v1
      kind: Service
      metadata:
        creationTimestamp: "2024-04-21T08:58:51Z"
        name: dummy-world-m7fzlb45wh-inf-server
        namespace: default
      spec:
        ports:
        - nodePort: null
          port: 50061
          protocol: TCP
          targetPort: 50060
        selector:
          app: dummy-world-m7fzlb45wh-inf-server
        type: ClusterIP
      status:
        loadBalancer: {}
```

### Steps To Reproduce

Create a service with an appropriate BindingPolicy object

### Expected Behavior

The Service should be the same as it was on the WDS. That is with clusterIP set to None.

clusterIP is one of the fields that are deleted when denaturing Service objects. This needs to be done only if the value of the clusterIP field isn't **None**

**Comment by vMaroon** [comment]
@ezrasilvera @pdettori @MikeSpreitzer @nirrozenbaum perhaps once the transformation feature is in, it should be expanded to allow the overriding of default denaturing behavior. (Not referring to how to actually implement that / API)

**Comment by MikeSpreitzer** [comment]
I am not sure I understand the problem here. Don't we want the WEC to assign the IP address? What is going wrong here?

If there _is_ something going wrong here, then I think it needs to be recorded in #1976 or wherever else we are accumulating user stories for this feature.

**Comment by shmuelk** [comment]
Theer are applications that don't want K8S to assign an address to the service. Instead when they do a DNS lookup on the service they get the address(es) of the Pod(s). They typically have a background thread that periodically checks the addresses of the PODs in case a Pod was restarted for some reason or other.

The FMAAS Router from IBM, now open sourced functions this way.

**Comment by pdettori** [comment]
@shmuelk perhaps then this use case would require a [Headless service](https://kubernetes.io/docs/concepts/services-networking/service/#headless-services), not a ClusterIP service. I am confused that the examples above show a ClusterIP.

**Comment by MikeSpreitzer** [comment]
I think that @shmuelk is describing a headless Service. That is the answer to my question. The user specified a headless Service in the WDS, but KubeStellar made it non-headless (headful?) on the way to the WEC.

**Comment by MikeSpreitzer** [comment]
Right, that is what #2070 is for.

**Comment by ezrasilvera** [comment]
@MikeSpreitzer But as @vMaroon mentioned - why can't the Transform override the default denature behavior ? I thought that this was one of the main use cases of the Transform. 
The current "default" behavior was dictated by some examples @pdettori worked on, other use cases may require different "default filtering"

**Comment by MikeSpreitzer** [comment]
@ezrasilvera: I think that is making things more complicated than necessary. I think that the examples that @pdettori cited did _not_ involve headless Services. So making the built-in behavior preserve headless-ness should work for both @pdettori and @shmuelk .

**Comment by pdettori** [comment]
I think we should keep this simple. For service, it should be simple enough just to support the headless Services with the built-in behavior as @MikeSpreitzer suggested. For all other use cases with CRDs, we can use CustomTransform.
