### ISSUE TITLE
Should we recommend only one CustomTransform per GroupResource?

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#2067]
This issue is about a detail of the feature of Issue #1976 .

I got the idea that we were thinking that there would be at most one `CustomTransform` for a given `metav1.GroupResource`, but I do not recall explicitly discussing the question.

This question is about the mental model that users should have; it is not driven by implementation concerns (the implementation in #2060 supports multiple and logs an error when there are more than one).

It makes sense to me to recommend just one `CustomTransform` per `GroupResource` because there are not independent consequences if there are multiple: the effects of all of them get added together and applied to the same workload objects. If some user is writing and reading only a subset of those effects, then that user is not seeing and, more importantly, not thinking about the other `CustomTransform`(s) that apply to the same workload objects. If there were multiple independent users writing `CustomTransform` objects that apply to the same workload object, one user might put something in her `CustomTransform` that other users do not want. By recommending a single `CustomTransform` for a given GroupResource, we recommend that users act as coherently as the feature effectively supposes they are.

**Comment by vMaroon** [comment]
I think it makes sense to support chaining CustomTransforms (with importance to order). If not unlimited chaining, at the very least a 2-levels chain.

E.g., one CustomTransform can be thought of as cluster-wide, and one can be user specific. I understand that currently CustomTransforms are non-namespaced objects, and under this PoV it might make sense to change that.

In all cases, unless there is a concrete use-case such as implementing denaturing and allowing the user to override default behavior through the above, this wouldn't be high priority.

**Comment by MikeSpreitzer** [comment]
We do not have a use case that requires changing the binding semantics. With the current binding semantics, there is no differentiation among the CustomTransform objects that apply to a given kind of workload object.

**Comment by ezrasilvera** [comment]
@MikeSpreitzer I suggest we go forward with the simple approach (single) that we have now, we can change in that future if there is a concrete use case for that

**Comment by pdettori** [comment]
+1

**Comment by MikeSpreitzer** [comment]
This has been settled in the affirmative.
