### ISSUE TITLE
bug: test/e2e/multi-cluster-deployment/run-test.sh does not support testing a contributor's work on OCP

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#2071]
### Describe the bug

`test/e2e/multi-cluster-deployment/run-test.sh`, in the OCP case, can only test a release; it can _not_ test a contributor's modified version of the repo. This fails to meet a critical requirement on the E2E tests.

### Steps To Reproduce

Look at the script or read the special case for OCP in the README.md.

### Expected Behavior

As for `kind`, when using OCP this test can test a contributor's modified version of the repo.

**Comment by MikeSpreitzer** [comment]
@effi-ofer 
@dumb0002

**Comment by ezrasilvera** [comment]
@MikeSpreitzer Until we have automatic OCP tests hooked into our CICD, we defined OCP testing as required only for release.  On-going developer work is tested only through the CICD github workflows.

**Comment by MikeSpreitzer** [comment]
>  On-going developer work is tested only through the CICD github workflows.

That may be the only automated testing, but we been making it possible for a contributor to run the end-to-end tests on their work (in their own environment). The Issue at hand is an unnecessary failure to do that.
