### ISSUE TITLE
bug: example Scenario 2 will fail if context wds2 already exists

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#2096]
### Describe the bug

`kflex create wds2 -t host` will not achieve the desired result if the kubeconfig context named "wds2" already exists --- but still exits with status 0 (indicating success). Users can easily overlook the one line error message amongst the many lines printed at that step, and proceed along in the scenario --- getting an error later with no obvious cause.

### Steps To Reproduce

See above.

### Expected Behavior

The scenario either crashes with a complaint about the pre-existing context or something has the user ensure that there is no "wds2" context at first.

**Comment by pdettori** [comment]
yes, we can.
