### ISSUE TITLE
bug: No E2E test of most relevant versions of the transport controller

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#2125]
### Describe the bug

This is just one pain point that is part of #1786 ; I am calling it out separately because I think that it can be addressed without a major overhaul.

We are currently following the "staggered release" approach to coping with the dependency cycle between ks/ks and ks/OTP.

For a contributor working on ks/ks (NOT a user trying to use the latest release of ks/ks), the most interesting E2E test of ks/ks is a test of what the next release of ks/ks would contain if it were made from the current ks/ks code. That upcoming release of ks/ks would use the transport controller from the latest release of ks/OTP.

For a contributor working on ks/OTP (NOT a user trying to use the latest releases), the most interesting E2E test of ks/OTP is a test of what the next release of ks/OTP would contain if it were made from the current ks/OTP code. That upcoming release of ks/OTP would have a transport controller that is built from a combination of (a) the current plugin in ks/OTP and (b) the generic transport controller code in the latest release of ks/ks.

The existing ks/ks E2E test (when NOT given `--released`) does not do either of the above. Instead it builds a transport controller from the combination of the current ks/ks generic transport controller code and the plugin from the latest release of ks/OTP.

### Steps To Reproduce

This is from inspection. See above.

### Expected Behavior

The two E2E use cases described above should be available.

**Comment by MikeSpreitzer** [comment]
@nirrozenbaum 
@ezrasilvera 
@pdettori

**Comment by effi-ofer** [comment]
The e2e tests used to support building OTP separately and making the path available via an env variable. But rather then reinvent that mechanism or something like it, it would be nice to resolve #1786 and avoid introducing additional complexity to the tests.

**Comment by ezrasilvera** [comment]
@MikeSpreitzer I think that the KS e2e is doing what need to be tested taking into account the dependency we have.  That dependency means that the expected KS developer experience  you mentioned doesn't practically exist and as soon as a new KS code is introduced a new OTP must be created as well. So in a sense it's basically acts as if it resides in the same repo and every time you have a new KS code you need to build both of them .

**Comment by MikeSpreitzer** [comment]
@ezrasilvera: apart from this testing snafu, the devloper experience that I described _is_ what exists. We _are_ following the staggered release approach (except when we overlook something).

You described another scenario, a contributor who is looking ahead to both the next ks/ks release and the following ks/OTP release. And that _also_ is _not_ what our current E2E test supports. Such a contributor would want to test the current ks/ks code with the current ks/OTP code.

Let me summarize with a table.

| ks/ks vintage excl transport ctlr | ks/ks vintage in transport ctlr | ks/OTP vintage | scenario |
| ------------- | --------------- | --------- | ----- |
| current | last release | last release | working on upcoming ks/ks release |
| last release | last release | current | working on upcoming ks/OTP release |
| current | current | current | working on coming ks/ks; ks/OTP release sequence |
| current | current | last release | what our E2E actually tests |

**Comment by MikeSpreitzer** [comment]
This has been resolved by merging the contents of the ocm-transport-plugin repo into the kubestellar repo.
