### ISSUE TITLE
bug: labelKey ignored in GetWDSKubeconfig

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#2133]
### Describe the bug

https://github.com/kubestellar/kubestellar/blob/223360a38d01b5405c0056573c730ca846ca76d7/pkg/util/kubeconfig.go#L73-L156 uses the given `labelKey` in log and error messages but not in the actual query.

### Steps To Reproduce

Look at the code.

### Expected Behavior

Either the parameter makes a difference or does not exist.

**Comment by MikeSpreitzer** [comment]
@pdettori 
@vMaroon 
@francostellari

**Comment by pdettori** [comment]
@MikeSpreitzer  - For simplicity, I would prefer that we just use the default  `ControlPlaneTypeLabel` and remove labelKey, but if you have preferences for actually allowing users to pass and use their own labelKey I am fine with that as well.

**Comment by MikeSpreitzer** [comment]
Currently that `labelKey` parameter is only exposed through the `wds-label` command line flag of the kubestellar controller-manager. None of our instructions, PostCreateHooks, or Helm charts actually uses that command line flag. So I think that we can safely remove it.
