### ISSUE TITLE
E2E test re-org

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#2160]
We currently have a confusing organization. The `test/e2e/` directory has two scenario-specific subdirectories (ginkgo, multi-cluster-deployment) plus one (common) for common stuff. Except that is no longer true; `test/e2e/multi-cluster-deployment/run-test.sh` can also run the ginkgo scenario. Also, `test/e2e/ginkgo` directly supports only using freshly-created `kind` clusters, while `test/e2e/multi-cluster-deployment/run-test.sh` allows using pre-existing OCP clusters. In fact, that generality is why that script was further generalized so that it can run the ginkgo scenario.

We should untangle this.

Following is a proposal.

Recognize that `test/e2e/multi-cluster-deployment/run-test.sh` is a general E2E test-runner, able to run either scenario.

Move `test/e2e/multi-cluster-deployment/run-test.sh` and `test/e2e/multi-cluster-deployment/README.md` up one level, to become `test/e2e/run-test.sh` and `test/e2e/README.md`. Adapt the contents of the new `test/e2e/README.md` to be the appropriate readme for all of E2E testing.

Remove the support from `test/e2e/ginkgo` for invoking the cleanup and setup steps; let `test/e2e/ginkgo` rely on the fact that it is run in the context of `test/e2e/run-test.sh` (or anything else that provides the necessary environment).

**Comment by MikeSpreitzer** [comment]
@dumb0002 
@effi-ofer

**Comment by dumb0002** [comment]
@effi-ofer, I agree with @MikeSpreitzer's proposal above. Furthermore, we could create a new directory for the bash tests and have the following directory structure: 

```
 — e2e
     — common
     — ginkgo
     — bash 
     README.md
     run-test.sh
```

The new `bash` directory will host the file: [use-kubestellar.sh](https://github.com/kubestellar/kubestellar/blob/main/test/e2e/multi-cluster-deployment/use-kubestellar.sh)

**Comment by ezrasilvera** [comment]
@dumb0002 @effi-ofer I don't mind a re-org, but I would like to maintain the ability to run each of them separately without depending on a previous "state" . 
Also I want us to limit our platform support to only OCP and KIND at this point (e.g., not include k3d) till we have a better helm/automation that supports multiple platform. I prefer we don't complicate our testing setup script beyond reasonable limit,.

**Comment by effi-ofer** [comment]
Re-iterating Ezra's comments - this is a good change, but lets keep the ability to run each independently. If you prefer, you can change the default for ginkgo's -skip-setup to true. I also agree we shouldn't support automated testing of additional platforms at this point in time until we have catchers (users) that require it.

**Comment by MikeSpreitzer** [comment]
To be clear (and some PR titles were NOT clear on this): what we have now is scripting to run just one of the two scenarios per invocation. What was changed recently was to make one of the run-test.sh scripts able to run _either_ (not _both_) scenario in one invocation.

@dumb0002: I do not think it is necessary to rename `multi-cluster-deployment` to `bash`. It is currently identifying the scenario that it runs. OTOH, I also think that the renaming is acceptable, it just amounts to a change in the naming strategy: a shift from naming by scenario to a naming by technology (which was already half done with the creation of the `ginkgo` directory).
