### ISSUE TITLE
bug: fix/update sudo command and fix 404::command not found error 

### ISSUE THREAD

**Issue by rchen-devv** [kubestellar/kubestellar#2178]
### Describe the bug

Here after running these lines of commands, I get a 404:: command not found error 
<img width="1176" alt="Screenshot 2024-05-28 at 1 41 13 PM" src="https://github.com/kubestellar/kubestellar/assets/169481903/3d8f88c1-c054-4af2-84d6-00c3ab503eae">

### Steps To Reproduce

1. Go to this part of the GitHub page  -> https://github.com/kubestellar/kubestellar/blob/main/docs/content/direct/common-setup-core-chart.md
2. Put this command into the terminal ` export KUBESTELLAR_VERSION=0.23.0-alpha.2 ` followed by this command `bash <(curl -s https://raw.githubusercontent.com/kubestellar/kubestellar/v${KUBESTELLAR_VERSION}/scripts/create-kind-cluster-with-SSL-passthrough.sh) --name kubeflex --port 9443`
3. After running the command it will produce this error `/dev/fd/13: line 1: 404:: command not found`

### Expected Behavior

This command is supposed to create a kind cluster but gave me this error instead.

**Comment by clubanderson** [comment]
@rchen-devv please test with 

`export KUBESTELLAR_VERSION=0.23.0-alpha.2`
