### ISSUE TITLE
Instructions missing for kubestellar installation on Kind and OCP

### ISSUE THREAD

**Issue by benzha14** [kubestellar/kubestellar#2213]
### Describe the bug: Missing instructions for kubestellar installation on Kind and OCP

<img width="1680" alt="Screenshot 2024-06-18 at 2 31 30 PM" src="https://github.com/kubestellar/kubestellar/assets/93015397/81c49a7c-c713-4f07-b78b-934d484f38a3">

### Steps To Reproduce

1. https://docs.kubestellar.io/release-0.23.0/
2. documentation
3. Getting started
4. Setting up Kubestellar
5. Kubestellar on KIND and Kubestellar on OCP

### Expected Behavior

The instructions for kubestellar installation on Kind and OCP should be similar to the instructions provided for K3D.

**Comment by ezrasilvera** [comment]
Thanks, we are redesigning the web site , and this will be addressed as part of it.

**Comment by ezrasilvera** [comment]
Overlap with #2163 
Addressed by #2183

**Comment by KPRoche** [comment]
In particular, check out #2163 for the current discussion and links to a couple of staged versions of proposed changes.

**Comment by MikeSpreitzer** [comment]
I think that this complaint is valid and should be fixed quickly without waiting for a grand redesign. In the meantime there is an example of setup using new kind clusters in https://docs.kubestellar.io/release-0.23.0/direct/examples/

**Comment by MikeSpreitzer** [comment]
For contributors, see the end-to-end tests for a broader illustration of setup. You will find bash scripting that can either make and use three new kind clusters or use three pre-existing OCP clusters.
