### ISSUE TITLE
Keeping github link separate from KubeStellar documentations

### ISSUE THREAD

**Issue by rchen-devv** [kubestellar/kubestellar#2214]
### Feature Description

When looking through documentation on KubeStellar I found that some links are not up to date to the GitHub page. I found this as a common issue since the link will direct me to a KubeStellar GitHub page that is either not existing or not up to date. I know that the issue 2163 is working on new UI design for the new KubeStellar documentation page so I am not sure if this is a separate issue from that. @KPRoche, can you look into this and see if this issue can be integrated into one issue, or it can be a different issue from itself. 

### Proposed Solution

I think it's better to keep GitHub documentations separate from KubeStellar documentations as much as possible since the GitHub Page undergoes many changes so the link to page might be broken, deleted, moved, etc. So, it is much better to keep these documentations separate.  

### Want to contribute?

- [X] I would like to work on this issue.

**Comment by KPRoche** [comment]
Can you point me at an example?
The kubestellar.io pages are actually generated via mkdocs from the markdown files in kubestellar/docs, so they are part of the repository.

I know @MikeSpreitzer was looking for internal references in some md files that were problematic.

**Comment by rchen-devv** [comment]
that makes more sense now but for example in this link 
[https://docs.kubestellar.io/release-0.23.0/direct/examples/#common-setup](https://docs.kubestellar.io/release-0.23.0/direct/examples/#common-setup)
when you scroll down to common setup, there are multiple text "common setup" hyperlinked but doesn't bring me to a new page but instead it just brings me to the section of common setup. I am wondering if there is a better way to do this since there are a bunch of information on one page about the setup process.

**Comment by KPRoche** [comment]
> that makes more sense now but for example in this link
> https://docs.kubestellar.io/release-0.23.0/direct/examples/#common-setup
> when you scroll down to common setup, there are multiple text "common setup" hyperlinked but doesn't bring me to a new page but instead it just brings me to the section of common setup. I am wondering if there is a better way to do this since there are a bunch of information on one page about the setup process.

Ah! Those are anchor links *intended* to bring you back up to the section on creating the "common setup" configuration, and the current behavior is an artifact of an earlier version. Before the "step-by-step manual setup" vs "using Kubestellar Core chart" dichotomy existed, that section was all part of this file and much longer, so having a simple link from each scenario that popped back to it as a starting point was perhaps less confusing.
The organization of the installation instructions is indeed a big part of the redesign conversation

**Comment by ezrasilvera** [comment]
I think this issue is a simple broken links issues that should be resolved in the redesign. github docs shouldn't be separate from the web docs.

**Comment by MikeSpreitzer** [comment]
@rchen-devv: I am not sure I understand the general complaint. I see that you cited one example. I agree with @KPRoche , there are several places that are intended to link back to the "Common Setup" section. @ezrasilvera, this is not a matter of broken links. @rchen-devv: can you suggest a change that would make the intent clearer? Can you cite other examples? I do not understand what "Keeping github link separate from KubeStellar documentations" (the current title of this Issue) means.

**Comment by rchen-devv** [comment]
@MikeSpreitzer I apologize for the confusing title. I should have done a better job of making my issue much clearer. 
I have made an issue about this site right here [https://helm.kubestellar.io](https://helm.kubestellar.io) where the GitHub repo is [https://github.com/kubestellar/helm](https://github.com/kubestellar/helm). In the GitHub repo there is a link to a page not found error which makes finding material for helm/kubestellar installations difficult. I was thinking if we keep our in-progress documentations separate from final documentations it would lead to less confusion but thanks to @KPRoche explanation of how the page was built, I understand that page is part of the repository. Also this page [https://github.com/kubestellar/kubestellar/blob/release-0.23.0/docs/content/direct/common-setup-core-chart.md](https://github.com/kubestellar/kubestellar/blob/release-0.23.0/docs/content/direct/common-setup-core-chart.md) has underwent many changes in the past few weeks so I want to find a solution to keep only the most up to date documentation on the final documentation page since there are still some wrong instructions in those GitHub pages. For example, the closed issue #2178 had incorrect code to get KubeStellar Core Chart to run. I am just afraid that if we have links in the KubeStellar documentations that is connected to a GitHub page that is incorrect, it would be hard for the user to use the product.

**Comment by MikeSpreitzer** [comment]
Thanks for the clarification.

The first and most important answer is that both https://helm.kubestellar.io/ and https://github.com/kubestellar/helm are outdated junk. They should be withdrawn. Do not bother trying to use them. Follow the links from https://kubestellar.io/ .

**Comment by clubanderson** [comment]
Why not replace the content instead of removing it?  Do you know what it takes to get SEO to rank a page?  Just update the content.

**Comment by clubanderson** [comment]
@rchen-devv  maybe you could create a PR that updates the helm page. This would qualify as 1 of the 2 PRs you complete. Happy to help you with this.

**Comment by MikeSpreitzer** [comment]
It would be fairly easy to update https://github.com/kubestellar/helm so that it is nothing but pointers into the current documentation.

Not so sure about https://helm.kubestellar.io/ . Tracing the plumbing now...

**Comment by rchen-devv** [comment]
@clubanderson sounds good, thank you for your help.

**Comment by MikeSpreitzer** [comment]
https://github.com/kubestellar/helm/settings/pages shows that http://helm.kubestellar.io/ is a GitHub pages site that is based on the branch named `main` of the github.com/kubestellar/helm repo.

**Comment by MikeSpreitzer** [comment]
So a PR that completely replaced the contents of github.com/kubestellar/helm with pointers into the current system would do it.

**Comment by clubanderson** [comment]
resolved - helm.kubestellar.io content was torn down and replaced with links
