### ISSUE TITLE
bug: Kubernetes spelled wrong 

### ISSUE THREAD

**Issue by rchen-devv** [kubestellar/kubestellar#2222]
### Describe the bug

![Screenshot 2024-06-20 at 10 34 30 AM](https://github.com/kubestellar/kubestellar/assets/169481903/0de6c2ca-9a86-4b79-834a-23ab54492a50)
In this above image, under the subsection "Size considerations" the second instance of Kubernetes is incorrectly spelled. 

### Steps To Reproduce

[https://docs.kubestellar.io/release-0.23.0/direct/best-practices/](https://docs.kubestellar.io/release-0.23.0/direct/best-practices/)
this is the website with the incorrect spelling

### Expected Behavior

Kuberentes should be spelled Kubernetes

**Comment by clubanderson** [comment]
@rchen-devv can you open a PR with a fix for this? If you click on the "Edit this page" icon on the top of the page https://docs.kubestellar.io/release-0.23.0/direct/best-practices/ a page will open in GitHub that allows you to edit the content, correct the spelling mistake, and then 'propose' a fix.

**Comment by rchen-devv** [comment]
Issue is fixed with a PR and the new site is updated. Closing this issue with this comment.
