### ISSUE TITLE
bug: Bug template still has references to outdated components such as Syncer and kcp

### ISSUE THREAD

**Issue by JonathanWentaoBao** [kubestellar/kubestellar#2224]
### Describe the bug

Section c and d in the template above makes references to outdated components such as kcp and syncer. These sections should be updated.

### Steps To Reproduce

Open an issue on the kubestellar github and open bug report (template is shown on the page)

### Expected Behavior

Bug template should reflect the most recent components of Kubestellar

**Comment by clubanderson** [comment]
bug template has been updated to remove old instructions. Please double check and close this issue if you no longer see the old info referenced.

/assign @JonathanWentaoBao

**Comment by JonathanWentaoBao** [comment]
template has been updated
