### ISSUE TITLE
:bug: Misspelling of Kubestellar on website

### ISSUE THREAD

**Issue by benzha14** [kubestellar/kubestellar#2228]
### Describe the bug

<img width="1680" alt="Screenshot 2024-06-20 at 1 22 31 PM" src="https://github.com/kubestellar/kubestellar/assets/93015397/4091423d-ecb8-4a97-a031-312948634bcc">

Kubestellar is misspelled as kubestellat 

### Steps To Reproduce

https://docs.kubestellar.io/release-0.23.0/direct/examples/ -> CTRL + f "In this example, we use the helm chart method to install the kubestellat controller manager for the hosting cluster so that we can pass additional startup options."

### Expected Behavior

kubestellar instead of kubestellat

**Comment by clubanderson** [comment]
also not correctly capitalized - good find @benzha14 - feel free to PR a fix for this.

**Comment by clubanderson** [comment]
looks like this is no longer an issue as the doc was moved and the spelling issue was resolved. @benzha14 can you please check and close this if it is no longer an issue.

/assign @benzha14
