### ISSUE TITLE
:bug: old version referenced by k3d instructions

### ISSUE THREAD

**Issue by clubanderson** [kubestellar/kubestellar#2230]
### Describe the bug

https://docs.kubestellar.io/release-0.23.0/direct/deploy-on-k3d/ references 0.22 of KS

### Steps To Reproduce

1. go to https://docs.kubestellar.io/release-0.23.0/direct/deploy-on-k3d/
2. observe 0.22 ks is referenced

not sure if other references are correct either.

### Expected Behavior

0.23 doc should point to 0.23 ks components

**Comment by MikeSpreitzer** [comment]
That doc says right up front in the introductory material:

> This is a point-in-time statement that worked with KubeStellar release v0.22.0.

Maybe it could be worded more clearly. It is trying to say that that particular document is not about the latest release but rather an older one. It is trying to say that we do not intend to update that document with every release. That was the outcome of a discussion about testing, in which it was asserted with some vehemence that we would not have the capacity to do that much manual testing.

**Comment by clubanderson** [comment]
Ugg. What a mess. Close if you prefer. I don't know what else to do. This has become untenable.

**Comment by MikeSpreitzer** [comment]
I think that the re-org should remove the need for this file. In the meantime I will offer a PR to make the warning more explicit.

**Comment by clubanderson** [comment]
documentation no longer exists. closing
