### ISSUE TITLE
:bug: Misspelling of "needed"

### ISSUE THREAD

**Issue by algoritmoalex** [kubestellar/kubestellar#2231]
### Describe the bug

Wording needs to be fixed. In pre-reqs.md "eeded" should be "needed" in the link below.

https://github.com/kubestellar/kubestellar/blob/release-0.23.0/docs/content/direct/pre-reqs.md

### Steps To Reproduce

1. Go to link: https://github.com/kubestellar/kubestellar/blob/release-0.23.0/docs/content/direct/pre-reqs.md
2. Go to **Check pre-requisites for KubeStellar** section.
3. The first sentence has a spelling error of "needed".

### Expected Behavior

Correct spelling.

**Comment by clubanderson** [comment]
looks like this was resolved. Can you double check on the latest unreleased version of the documents to see if this is still an issue? If no longer an issue, please close.

**Comment by algoritmoalex** [comment]
Issue resolved in unreleased documentation.
