### ISSUE TITLE
bug: Incorrect spelling of KubeStellar in Architecture page

### ISSUE THREAD

**Issue by aishwarya-mathew** [kubestellar/kubestellar#2255]
### Describe the bug

![Spelling_Screenshot ](https://github.com/kubestellar/kubestellar/assets/46677213/72d40ce9-529f-470a-9b45-6d427890fe67)
The spelling of KubeStellar is incorrect

### Steps To Reproduce

1. Click on this link: https://docs.kubestellar.io/release-0.23.0/direct/architecture/
2. Search the page for the term "KubeSteller" OR "currently prereqs KubeFlex"

### Expected Behavior

KubeSteller should be KubeStellar

**Comment by clubanderson** [comment]
@aishwarya-mathew good find. Make sure to use https://docs.kubestellar.io/unreleased-development to find these items in the future. Unreleased-development is the most recent docs for the purpose of development. You bug find exists in both 0.23 and unreleased-development versions of the doc - so you are good to go here. Consider adding a PR to fix this.

**Comment by clubanderson** [comment]
/assign @aishwarya-mathew 

@aishwarya-mathew please see if this is still an issue in unreleased-development. I no longer see this spelling mistake in the documentation. If no longer an issue, please close.

**Comment by aishwarya-mathew** [comment]
I don't see the issue in the unreleased development anymore.
https://docs.kubestellar.io/unreleased-development/direct/architecture/
Closing the issue!
