### ISSUE TITLE
bug: Misspelling of “uninstalled” on core helm chart usage page

### ISSUE THREAD

**Issue by JonathanWentaoBao** [kubestellar/kubestellar#2260]
### Describe the bug

“uninstalled” misspelled as “uninsitalled” (highlighted in the picture)
![IMG_7608](https://github.com/kubestellar/kubestellar/assets/171893847/8545df3a-6b5f-440c-a982-1f65ccb2325f)

### Steps To Reproduce

1. Open docs.kubestellar.io
2.  Navigate to the drop down bar
3. Navigate to the Getting Started tab
4.  From Getting Started, navigate to Core Helm chart page
5.  Scroll to the uninstallation section at the bottom of the page

### Expected Behavior

“uninsitalled” should be spelled as “uninstalled”

**Comment by clubanderson** [comment]
@JonathanWentaoBao please check if this is still an issue. If it has been resolved, please close this issue.
