### ISSUE TITLE
bug: incorrect spelling in documentation

### ISSUE THREAD

**Issue by benzha14** [kubestellar/kubestellar#2264]
### Describe the bug

requies should be requires 

### Steps To Reproduce

1. got to https://docs.kubestellar.io/unreleased-development/direct/core-chart/ 
2. ctrl+f "Install a new chart with a different name. This choice does not requires to relist the existing control planes, but requies to disable the reinstallation of KubeFlex and PCHs:"
3. The second "requies" should be requires 

### Expected Behavior

The second "requies" should be requires

**Comment by clubanderson** [comment]
@benzha14 I dont see this spelling issue any more, please check and close this if no longer present.

**Comment by MikeSpreitzer** [comment]
I fixed this one in #2279
