### ISSUE TITLE
bug: Mispelling of KubeStelllar in docuemntation

### ISSUE THREAD

**Issue by benzha14** [kubestellar/kubestellar#2265]
### Describe the bug

Kubestellar is misspelled as KubeStelalr

### Steps To Reproduce

1.  go to "https://docs.kubestellar.io/unreleased-development/direct/core-chart/"
2. ctrl+f "By default the KubeStelalr Core chart uses a test domain localtest.me, which is ok for testing on a single host machine. However, scenarios that span more than one machine, it is necessary to set --set "kubeflex-controller.domain=<domain>" to a more appropriate <domain> that can be reached from Workload Execution CLusters (WECs)."

### Expected Behavior

Kubestelalr should be spelled as Kubestellar

**Comment by MikeSpreitzer** [comment]
There is also a speling misteak in the title of this Issue.

**Comment by clubanderson** [comment]
fixed @MikeSpreitzer

**Comment by MikeSpreitzer** [comment]
Yes, fixed.
