### ISSUE TITLE
bug: Misspelling of vcluster

### ISSUE THREAD

**Issue by benzha14** [kubestellar/kubestellar#2266]
### Describe the bug

vcluster is misspelled as vlcuster

### Steps To Reproduce

1. got to https://docs.kubestellar.io/unreleased-development/direct/core-chart/
2. ctrl+f vlcuster 

### Expected Behavior

vlcuster should be spelled as vcluster

**Comment by clubanderson** [comment]
@benzha14 I no longer see this as an issue in the link you provided, please check and close this issue if it is no longer present.
