### ISSUE TITLE
Kubestellar helm chart out of date

### ISSUE THREAD

**Issue by rayoazul777** [kubestellar/kubestellar#2284]
### Describe the bug

Error: chart "kubestellar-core" matching v0.14.0 not found in kubestellar index. (try 'helm repo update'): no chart version found for kubestellar-core-v0.14.0
I tried to install the latest release for kube stellar
and i got that same error
i searched the repo and only these showed up as available
NAME                            CHART VERSION   APP VERSION     DESCRIPTION
kubestellar/kubestellar-core    7               v0.14.0         A Helm chart for KubeStellar Core deployment as...
kubestellar/kubestellar-core    6               v0.13.0         A Helm chart for KubeStellar Core deployment as...
kubestellar/kubestellar-core    5               v0.12.0         A Helm chart for KubeStellar Core deployment as...
kubestellar/kubestellar-core    4               v0.11.0         A Helm chart for KubeStellar Core deployment as...
kubestellar/kubestellar-core    3               v0.10.0         A Helm chart for KubeStellar Core deployment as...
kubestellar/kubestellar-core    1               v0.9.0          A Helm chart for KubeStellar Core deployment as...

chart for the helm repo is out of date and not showing v0.23

### Steps To Reproduce

We should get updated instructions on installing Ks core using helm since the repo is out of date

### Expected Behavior

should done this 
Release "ks-core" does not exist. Installing it now.
Pulled: ghcr.io/kubestellar/kubestellar/core-chart:0.23.0
Digest: sha256:550047534d8cca78020c7cb9907e760909a62021097183c6df277478bfa0d2bc
NAME: ks-core
LAST DEPLOYED: Wed Jun 26 16:09:31 2024
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:

but instead I got this

 $KUBESTELLAR_VERSION="v0.23.0"
>>
>> helm upgrade --install ks-core kubestellar/core-chart `
>>   --version $KUBESTELLAR_VERSION `
>>   --set-json='ITSes=[{"name":"its1"}]' `
>>   --set-json='WDSes=[{"name":"wds1"}]'
>>
Release "ks-core" does not exist. Installing it now.
Error: chart "core-chart" matching v0.23.0 not found in kubestellar index. (try 'helm repo update'): no chart name found

### Want to contribute?

- [X] I would like to work on this issue.

**Comment by rayoazul777** [comment]
i went inside the helm install page instructions here 

https://github.com/kubestellar/helm/blob/main/README.md

when I looked in charts it had all the old stuff

**Comment by clubanderson** [comment]
@rayoazul777 check out https://helm.kubestellar.io/ in incognito browser (chrome private browsing). I have updated it to reflect working instructions.

**Comment by MikeSpreitzer** [comment]
Or see https://docs.kubestellar.io/unreleased-development/direct/core-chart/ for the copy in its native context, and see https://docs.kubestellar.io/unreleased-development/direct/get-started/ for complete example setup instructions.
