### ISSUE TITLE
bug: view and edit git source from mkdocs no longer working

### ISSUE THREAD

**Issue by clubanderson** [kubestellar/kubestellar#2286]
### Describe the bug

clicking the 'view' and 'edit' icons should take you to the GitHub page that is underlying the doc site. This allows you to grab/view the source or edit it for PR.

### Steps To Reproduce

1. go to https://docs.kubestellar.io/release-0.23.0/direct/common-setup-core-chart/

2. click on the 'view' or 'edit' icons in the top right of the page

3. receive 404 error 

### Expected Behavior

should be able to view or edit the source for the page you clicked on 'edit' or 'view'

### Want to contribute?

- [ ] I would like to work on this issue.

### Additional Context

the url prefix is wrong, and this is controlled by the mkdocs manifest - the prefix for 0.23 is pointing at 'main'

**Comment by MikeSpreitzer** [comment]
For a file that exists in both the `main` branch and the `release-0.23.0` branch, these icons "work" --- they take the user to view or edit the doc on the `main` branch.

When viewing the `release-0.23.0` version of the website, should these icons take the user to the file in the `release-0.23.0` branch or to the file (if it still exists) in the `main` branch?

**Comment by MikeSpreitzer** [comment]
If I understand correctly, the latest version of the website does not have this problem on any page.

The root cause, however, has not been fixed; the symptom will re-appear as soon as any file used in the latest version of the website is deleted or renamed in `main`.

**Comment by clubanderson** [comment]
appears to be working again - closing for now
