### ISSUE TITLE
Additional links for help with installation

### ISSUE THREAD

**Issue by aishwarya-mathew** [kubestellar/kubestellar#2290]
### Describe the bug

![image](https://github.com/kubestellar/kubestellar/assets/46677213/43d78a66-2cc4-46eb-8ce2-7bf7d187d076)

The prerequisites includes some additional software like go, make, ko for which reference links to their installation or official website could be included.

### Steps To Reproduce

1. Go to: https://docs.kubestellar.io/release-0.23.1/direct/pre-reqs/
2. Go to the sections of "Additional Software for..."

### Expected Behavior

Could include links to help with their installation

### Want to contribute?

- [X] I would like to work on this issue.

**Comment by clubanderson** [comment]
@aishwarya-mathew assigning this to you for PR
