### ISSUE TITLE
Incorrect sentence and link

### ISSUE THREAD

**Issue by aishwarya-mathew** [kubestellar/kubestellar#2294]
### Describe the bug

This sentence is incorrect and the examples hyperlink leads to a 404 error

![image](https://github.com/kubestellar/kubestellar/assets/46677213/d044610e-3b7c-4d43-b07b-9c564775b989)

### Steps To Reproduce

1. Go to: https://helm.kubestellar.io/
2. Search for the section "Create a Kind cluster"

### Expected Behavior

The sentence was probably meant to be:
"For convenience, a new local Kind cluster that satisfies the requirements for KubeStellar setup and that can be used for the exercises in the examples can be created with the following command"

The link for examples: https://docs.kubestellar.io/release-0.23.0/direct/examples/

### Want to contribute?

- [X] I would like to work on this issue.

**Comment by MikeSpreitzer** [comment]
I think that the contents of that README should be entirely replaced; see https://github.com/kubestellar/helm/pull/2 .

**Comment by clubanderson** [comment]
@aishwarya-mathew the team tore down the instructions on helm.kubestellar.io - this issue no longer applies.
