### ISSUE TITLE
bug: "First" misspelled as "fist" in Prerequisites documentation

### ISSUE THREAD

**Issue by JonathanWentaoBao** [kubestellar/kubestellar#2307]
### Describe the bug

Upon navigating to the supported flags section of the prerequisites page in kubestellar documentation, the first flag description has a typo where "first missing prerequisite" is written as "fist missing prerequisite"

### Steps To Reproduce

1. go to kubestellar.io documentation
2. go to the Prerequisites page 
3. scroll down to the first flag description in the Supported flags section 

### Expected Behavior

"fist missing prerequisite" should read as "first missing prerequisite"

### Want to contribute?

- [X] I would like to work on this issue.

**Comment by clubanderson** [comment]
this was fixed by #2312 - closing
