### ISSUE TITLE
bug: Rename "Documentation" to "User Guide" on Landing Page

### ISSUE THREAD

**Issue by algoritmoalex** [kubestellar/kubestellar#2319]
### Describe the bug

Kubestellar users can be referred to the documentation or the user guides without knowing they are the same. Using a search engine with these different terms will lead to different results.

@KPRoche 

### Steps To Reproduce

1. Go to Landing preview page [https://kproche.github.io/kubestellar/doc-nav-emphasis/](https://kproche.github.io/kubestellar/doc-nav-emphasis/)
2. View and click "Documentation" button.
3. Wait for redirect to Kubestellar "User Guide".

### Expected Behavior

Documentation titles should match.

![image](https://github.com/kubestellar/kubestellar/assets/9136079/4f06b1a8-33fc-437c-bdc6-9486cb97a4aa)
![image](https://github.com/kubestellar/kubestellar/assets/9136079/5db005b6-e527-4f0a-b25a-c31b242727ea)

OR

![image](https://github.com/kubestellar/kubestellar/assets/9136079/ba9d5647-48b2-405a-a387-7c9877474b03)
![image](https://github.com/kubestellar/kubestellar/assets/9136079/d808bb64-aff7-467f-aa3e-e579d952f74b)

### Want to contribute?

- [ ] I would like to work on this issue.

### Additional Context

The alt text should match the button text or provide a description for those users using screen readers.

**Comment by KPRoche** [comment]
To my knowledge the mkdocs engine does not allow us to add alt-text to the navigation links.

The home (landing) page, however does. Those buttons are a legacy from our original landing page, and I agree their text, or at very least their alt-text, should be brought in line with the new web structure.

**Comment by MikeSpreitzer** [comment]
Remember also that we have the freedom to choose what that button links to. Perhaps https://kproche.github.io/kubestellar/doc-nav-emphasis/readme/ would be a better choice?

**Comment by MikeSpreitzer** [comment]
To my taste it would be odd if the landing page had only buttons named "User Guide" and "Join Us". That would leave me, if I did not already know better, where to find the rest of the documentation.

**Comment by KPRoche** [comment]
Did more digging. The button hover text that appears (which is currently "overview" for both buttons) is generated from the title for the menu link page in the mkdocs.yml navigation tree. Knowing that, we do need to give them distinctive link titles (in an earlier discussion I didn't think that necessary; I was mistaken).

Now that we have more options in the top menu of the landing page, having the "Documentation" button go to the architecture overview (readme.md) would work ok. I'm also trying some experiments to see what I can get the styling in home.html to do for us.

**Comment by KPRoche** [comment]
@clubanderson I note that the Join Us links in the landing page point to kubestellar.io/joinus which redirects out of kubestellar.io to the googlegroup. Should they perhaps instead point to the Community page which has links to the googlegroup, slack, etc?

**Comment by clubanderson** [comment]
@KPRoche the link was intended to be used as a way to get people access to our documents in google and get an invite for the bi-weekly meetings. Perhaps the shortcut should be called "community meeting access"

**Comment by KPRoche** [comment]
@clubanderson Thank you for explaining! Yes, I think a re-label is in order. Also, the embedded code for the button title does not appear to be rendering properly.
I think I can build a mockup for inspection now, if not actually a PR yet

**Comment by KPRoche** [comment]
@clubanderson @algoritmoalex 
OK, here is a mockup of an improved (I hope) landing page for the site. (I had to do a little research to get the additional text to center below each button). The links in the masthead menu now have title attributes, too.
https://kproche.github.io/kubestellar/doc-alttext/

**Comment by clubanderson** [comment]
@KPRoche I like the doc-alttext version - is it in PR form?

**Comment by KPRoche** [comment]
@clubanderson not just yet. It needs a couple of tweaks, I think (considering the search engine question)

**Comment by KPRoche** [comment]
@clubanderson @MikeSpreitzer @algoritmoalex I've made some additional tweaks to add missing alt text and element titles.
https://kproche.github.io/kubestellar/doc-alttext/
(One note -- the Documentation button references docs.kubestellar.io; obviously on the above rendering it's going to my version)
I think it might be ready for a PR

**Comment by KPRoche** [comment]
> Just noticed the Contribute on Github button does not have a title attribute. Diving back in.

OK, *now* I think it's ready.
