### ISSUE TITLE
bug: bash 2 curl not using exported var

### ISSUE THREAD

**Issue by clubanderson** [kubestellar/kubestellar#2323]
### Describe the bug

the instructions on https://docs.kubestellar.io/unreleased-development/direct/get-started/ give a bash2curl to create a kind cluster. The instruction uses hardcoded 0.23.0

`bash <(curl -s https://raw.githubusercontent.com/kubestellar/kubestellar/v0.23.0/scripts/create-kind-cluster-with-SSL-passthrough.sh) --name kubeflex --port 9443
`

the page is part of the 0.23.1 release though and the exported var is 0.23.1 just above it.

### Steps To Reproduce

go to https://docs.kubestellar.io/unreleased-development/direct/get-started/
observe bash 2 curl including hardcoded 0.23.0

### Expected Behavior

bash 2 curl should use exported var instead

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by MikeSpreitzer** [comment]
This has been resolved.
