### ISSUE TITLE
bug: Misspelling of 'Release Testing' under 'Contribution Notes' dropdown on kubestellar.io

### ISSUE THREAD

**Issue by JonathanWentaoBao** [kubestellar/kubestellar#2333]
### Describe the bug

Release Testing misspelled as "Releaes Testing" under the contribution notes dropdown in the Contributing tab for unreleased version of kubestellar.io documentation
![image](https://github.com/user-attachments/assets/bfa9b279-9606-4f80-b41c-014bdae96aaf)

### Steps To Reproduce

1. go to kubestellar.io documentation
2. navigate to the Contributing tab (at the top of the page)
3. open the dropdown bar for Contribution Notes at the left side of the page
4. misspelling should be the third dropdown option

### Expected Behavior

third dropdown option under Contribution Notes should be spelled as "Release Testing"

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by clubanderson** [comment]
fixed by #2334
