### ISSUE TITLE
feature: named ports on KubeStellar controller-manager Pod

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#2360]
### Feature Description

A user (such as @dumb0002) who wants access to the ports at which `/metrics` and `/debug/pprof` can be reached finds it easier if the Pod object declares named ports for these.

### Proposed Solution

Declare those in the sources of the PodSpec.

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by francostellari** [comment]
@MikeSpreitzer @dumb0002 would adding something like below to https://github.com/kubestellar/kubestellar/blob/main/config/default/manager_auth_proxy_patch.yaml go in the right direction of what you want?

```yaml
- containerPort: 8080
   protocol: TCP
   name: metrics
```

**Comment by dumb0002** [comment]
@francostellari,  only the port 8082 needs to be named in the manager container for my use-case. 

@MikeSpreitzer, fyi, prometheus also have a PodMonitor object that can be used to configure the scraping targets. I haven't be able to successful use it to scrape our controllers yet.

**Comment by MikeSpreitzer** [comment]
@dumb0002: why not the debug port too?

I have recently been saying that using ServiceMonitor is preferable to using PodMonitor. My reasoning was that the former only requires tweaking the Service object's labels/annotations, while the latter requires tweaking the Pod's labels/annotations and that requires changing more stuff that we maintain (PostCreateHooks and Helm charts).

However, today remembered a more important reason for preferring PodMonitor. It concerns what happens when multiple matching Pods are running concurrently. Even for a Deployment for which `replicas == 1`, we get multiple concurrent Pods during the transition period if ever there is a change in the PodSpec in the Deployment. Also: even if there is never more than 1 matching Pod at any given time, the scraped metric labels in a PodMonitor make it clear when there is a Pod termination and replacement.

**Comment by dumb0002** [comment]
@MikeSpreitzer, yes we also need the debug port. 

I don't clearly understand your statement above: you're saying that using `PodMonitor` is better than `ServiceMonitor'?

**Comment by MikeSpreitzer** [comment]
Yes, I am saying that using PodMonitor is better that using ServiceMonitor.

**Comment by dumb0002** [comment]
Understood. I suggested the following (cc: @MikeSpreitzer @francostellari ):
        1) Let's keep this issue on hold for now because we can use port number with `PodMonitor`
       2) For now, let's use `ServiceMonitor` and we can use the current script on my PR to name the needed ports
       3) In the later PR (feature improvement) we can transition from using `ServiceMonitor` to `PodMonitor` given that I don't have the configuration with PodMonitor working properly yet

**Comment by francostellari** [comment]
@MikeSpreitzer as I mentioned in the meeting, I'm not very familiar with the metrics, and did not work with pod port myself.
Can you help by clarifying which pod should have which port open with what name?
Also, is https://github.com/kubestellar/kubestellar/issues/2360#issuecomment-2252683251 the right direction? assuming that I got the right pod and I figure out which ports to open.

**Comment by MikeSpreitzer** [comment]
Here are details regarding the KubeStellar controller-manager.

`docker run --rm ghcr.io/kubestellar/kubestellar/controller-manager:0.24.0-alpha.2 -h` lists the command-line help for it, which includes the following two entries.

```
      --metrics-bind-address string        The [host]:port from which /metrics is served. (default ":8080")
      --pprof-bind-address string          The [host]:port fron which /debug/pprof is served. (default ":8082")
```

Looking at a running system, I see the following `Deployment` of that.

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: kubestellar
    meta.helm.sh/release-namespace: wds1-system
  creationTimestamp: "2024-08-01T17:55:09Z"
  generation: 1
  labels:
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: kubestellar
    app.kubernetes.io/instance: controller-manager
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: deployment
    app.kubernetes.io/part-of: kubestellar
    control-plane: controller-manager
  name: kubestellar-controller-manager
  namespace: wds1-system
  resourceVersion: "1990"
  uid: 544da03c-331f-4f77-939f-acd2ba280bf8
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      control-plane: controller-manager
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      creationTimestamp: null
      labels:
        control-plane: controller-manager
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
                - ppc64le
                - s390x
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
      containers:
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=0
        image: gcr.io/kubebuilder/kube-rbac-proxy:v0.13.1
        imagePullPolicy: IfNotPresent
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 5m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - args:
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=127.0.0.1:8080
        - --leader-elect
        - --wds-name=wds1
        - --its-name=
        - --api-groups=
        - -v=2
        image: ghcr.io/kubestellar/kubestellar/controller-manager:0.24.0-alpha.2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 1
        name: manager
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readyz
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 10m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
      serviceAccount: kubestellar-controller-manager
      serviceAccountName: kubestellar-controller-manager
      terminationGracePeriodSeconds: 10
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-08-01T17:56:19Z"
    lastUpdateTime: "2024-08-01T17:56:19Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-08-01T17:55:09Z"
    lastUpdateTime: "2024-08-01T17:56:19Z"
    message: ReplicaSet "kubestellar-controller-manager-5ff645946f" has successfully
      progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
```

So, there are two layers to think about, thanks to the kube-rbac-proxy container. The point of this container is that it can be used to engage RBAC-based control over clients of what would otherwise be a plain HTTP port. In the configuration above, you see this being done for the metrics port. The manager container is configured to listen for HTTP connections to TCP port 8080 at IP address 127.0.0.1 --- and that IP address is not reachable from outside the Pod. The kube-rbac-proxy container is configured to listen for HTTPS connections to TCP port 8443 at any/every IP address, and clients outside the pod can thus connect using the Pod's "cluster IP" address. The proxy uses the client's TLS certificate to get an identity and then asks the kube-apiserver whether that client is authorized. If so, the HTTP requests are delegated to the proxy's `--upstream`, the aforementioned TCP port 8080 at IP address 127.0.0.1. With this configuration in place, what clients want is a port declaration on the container with port number 8443, protocol TCP, and an informative name such as "metrics". That is already there, albeit with the less informative name "https".

At present there is no corresponding proxying configured for the `/debug/pprof` port. You see above that the default behavior of the manager container is to listen for HTTP connections to TCP port 8082 at any/every IP address. And the `Deployment` does not change this behavior. So what would serve clients is a port declaration on the manager container, with protocol TCP, port number 8082, and an informative name such as "debug-pprof".
