### ISSUE TITLE
:bug:  Diagram image does not render well on dark backrgound

### ISSUE THREAD

**Issue by francostellari** [kubestellar/kubestellar#2386]
### Describe the bug

Main diagram image referenced in the README.md is not legible in dark background browsers

### Steps To Reproduce

![image](https://github.com/user-attachments/assets/3a3f1c59-2c19-4d7c-b9f8-61c3b5c7a703)

### Expected Behavior

I would suggest to remove transparency and use a defined light background

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by KPRoche** [comment]
I've created PR #2411 to properly enable dark/light mode toggling, with updates to the image file backgrounds as necessary

**Comment by MikeSpreitzer** [comment]
@francostellari: What URL shows the problem?

**Comment by MikeSpreitzer** [comment]
I switched my Mac's theme to dark and visited https://docs.kubestellar.io/release-0.23.1/readme/ , the web page content still looks light.

<img width="913" alt="Screenshot 2024-08-23 at 4 15 41 PM" src="https://github.com/user-attachments/assets/9edfdd35-afb6-4829-a0fe-88ee42db8705">

**Comment by MikeSpreitzer** [comment]
I am using Firefox. I switched its "theme" to "dark", and still see light background.

<img width="1085" alt="Screenshot 2024-08-23 at 4 19 19 PM" src="https://github.com/user-attachments/assets/401bbd73-6ce4-44c1-845b-be1c7b3bc110">

**Comment by KPRoche** [comment]
You have to switch to the doc-darklight version!

**Comment by francostellari** [comment]
I looked at it in GH dark mode

**Comment by MikeSpreitzer** [comment]
@francostellari: What is "GH dark mode"?

**Comment by MikeSpreitzer** [comment]
I launched Chrome, put it in dark mode, then visited kubestellar.io, navigated to https://docs.kubestellar.io/release-0.23.1/readme/, and took the attached snapshot.
<img width="950" alt="Screenshot 2024-08-23 at 4 56 36 PM" src="https://github.com/user-attachments/assets/120fef3d-bcab-4bf0-837a-cc515eb8d625">

**Comment by francostellari** [comment]
> @francostellari: What is "GH dark mode"?

IN dark mode

**Comment by francostellari** [comment]
![Screenshot_20240823_230032_GitHub.jpg](https://github.com/user-attachments/assets/07c17c9d-19e2-4178-955d-622ddd0dfb6f)

**Comment by MikeSpreitzer** [comment]
@francostellari: what URL are you looking at?

**Comment by MikeSpreitzer** [comment]
@francostellari: I have tried Firefox and Chrome in dark mode, and still see no problem. But maybe I am not looking at the same URL as you?

**Comment by MikeSpreitzer** [comment]
I have Firefox in dark mode and here is what I see at https://docs.kubestellar.io/release-0.23.1/readme/.

<img width="876" alt="Screenshot 2024-08-23 at 5 23 28 PM" src="https://github.com/user-attachments/assets/b23059de-9571-4cad-bcdb-5490dbfe6c6c">

**Comment by KPRoche** [comment]
To simplify the conversation, I've made a branch that does NOT have the SVG background corrections.
https://kproche.github.io/kubestellar/doc-darkerror/direct/architecture/ is an example of a page that does not render well if you use the toggle icon next to the search bar to rotate into dark mode.

**Comment by MikeSpreitzer** [comment]
@KPRoche: thank you for that diagnostic. I am looking at it on my Mac at night with Firefox in dark mode. The attached screen snapshot is what I see.

<img width="1727" alt="Screenshot 2024-08-25 at 1 29 42 AM" src="https://github.com/user-attachments/assets/6e33f53e-0e71-4dbe-b904-bf2aab867404">

**Comment by MikeSpreitzer** [comment]
Is there a problem with what is merged right now? Can someone say what URL, what browser, what settings show the problem?

**Comment by KPRoche** [comment]
I am not sure exactly how @francostellari invoked dark mode to trigger the problem; our default scheme in the current merged repo forces light mode. However, once you **do** get the browser to render the site in dark mode, the defects in the graphics and the default color scheme are readily apparent. 
The modifications to mkdocs.yml and the image files in the PR are simple, and only affect how the site renders in dark mode, but they do fix the problem.

**Comment by MikeSpreitzer** [comment]
Using Firefox on Mac OS 14.6.1, with Firefox in dark mode, I went to https://docs.kubestellar.io/release-0.23.1/readme/ and saw no problem. The attached screenshot shows this situation: what I see from the ks website, and the setting in Firefox.

<img width="1693" alt="Screenshot 2024-08-26 at 1 18 17 PM" src="https://github.com/user-attachments/assets/4dea2ec2-aaaf-4b32-bcbc-166eae8299c7">

**Comment by KPRoche** [comment]
> Using Firefox on Mac OS 14.6.1, with Firefox in dark mode, I went to https://docs.kubestellar.io/release-0.23.1/readme/ and saw no problem. The attached screenshot shows this situation: what I see from the ks website, and the setting in Firefox.
> 
As I said above, I'm not sure how Franco got the website to switch and render in dark mode.  It may be that you have to switch your whole desktop to dark mode to actually trigger the shift.

The [doc-darkerror](https://kproche.github.io/kubestellar/doc-darkerror/) branch I created allows you to manually toggle to dark mode to see the problems, 
in comparison to[ doc-darklight ](https://kproche.github.io/kubestellar/doc-darklight/) branch which has the fixes in the PR applied.

Note that the landing (splash) page is rendered from a completely independent html file and the mode change does not affect it. You need to enter via the documentation button to explore the problems. [The architecture page is a great example](https://kproche.github.io/kubestellar/doc-darkerror/direct/architecture/).

Use the toggle icon next to the search bar to flip to the dark theme, then switch between the doc-darkerror and doc-darklight versions and you can see the issue.

**Comment by MikeSpreitzer** [comment]
@KPRoche: Yes, I reported on my own look at `doc-darkerror` above. But my concern is this: if I can not see the problem then I can not test the fix. You have added some functionality, but until I see what the OP complained about, I can not check whether the original problem has been fixed.

**Comment by MikeSpreitzer** [comment]
Below is a snapshot of my looking at https://docs.kubestellar.io/release-0.23.1/direct/architecture/ with Firefox in dark mode and my desktop in dark mode.

<img width="1728" alt="Screenshot 2024-08-26 at 2 25 42 PM" src="https://github.com/user-attachments/assets/a61a76fd-c66f-4eb3-9ca9-23d272ecb65d">

**Comment by KPRoche** [comment]
OK, I have found a way to illustrate the problem in the existing site. It involves setting an override in Firefox in addition to the dark theme. (and for the record, I do know people who do this to their browsers)
In the Firefox appearance settings, click on Manage Colors, then in the popup check "always use system colors" and "Always" in the override options:
![Screenshot 2024-08-26 114157](https://github.com/user-attachments/assets/46578154-f293-43b6-88b4-6999b11ac436)

Now if you visit kubstellar.io and look at the architecture page you'll see the problem. If you look at the doc-darklight preview you'll see that the modified SVG files still render with a usable background, because the SVG background is specifically set.

**Comment by MikeSpreitzer** [comment]
Thanks, @KPRoche , now I can see a problem. On to the PR!

**Comment by MikeSpreitzer** [comment]
If I understand correctly, @KPRoche intended to say that this Issue was resolved by #2411 .
