### ISSUE TITLE
feature: Helm chart control over bundling parameters

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#2425]
### Feature Description

The transport controller has recently gained two parameters that control the bundling of workload objects into ManifestWork objects. These should be exposed to users of the Helm charts.

```shell
mspreitz@mjs13 kubestellar % docker run --rm ko.local/ocm-transport-controller:8cd940eb82ad9913dba5498791b13a3d33d0f19b46f6b84b4d172b1ab2b5fb03 -h
pflag: help requested
Usage of transport-controller:
...
      --max-num-wrapped int                Max number of objects inside the wrapped object (default 9223372036854775807)
      --max-size-wrapped int               Max size of the wrapped object in bytes (default 512000)
...
```

### Proposed Solution

Add "values" to the charts that let these parameters be conveyed.

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by francostellari** [comment]
@MikeSpreitzer 

1. should I keep the same default values?
2. I propose to add the following values to the OTP chart: `max_num_wrapped: 9223372036854775807` and `max_size_wrapped: 512000`
3.  I propose to bring those values out to KS-core-chart as 

```yaml
transport_controller:
    max_num_wrapped: 9223372036854775807
    max_size_wrapped: 512000
```

**Comment by MikeSpreitzer** [comment]
I think it looks silly to have a max_num_wrapped that is greater than max_size_wrapped; each wrapped object is going to occupy at least 1 byte!

The rest of what you proposed looks OK to me.

**Comment by MikeSpreitzer** [comment]
I suggest fixing the default in the controller too. See #2431 .
