### ISSUE TITLE
bug: Workload not deleted from a WEC after its label (matching BP) is deleted in WDS

### ISSUE THREAD

**Issue by cwiklik** [kubestellar/kubestellar#2469]
### Describe the bug

My environment:
K3D 
Client Version: v1.31.0
Kustomize Version: v5.4.2
Server Version: v1.30.4+k3s1
Kubestallar version: 0.24.0 

I've configured  a job with a label matching BP of specific WEC. I've created it in WDS (type=host) and the job was pulled to the WEC and ran. On WDS, I've edited the job and removed the label matching BP. My expectation was that the job would be removed from the WEC. Instead, the job lingers and eventually after several minutes is cleaned up. The amount of time before the cleanup is done varies.

Another side effect of the problem is that any subsequent jobs created in WDS are not pulled to the WEC. 

The workaround is to use BP per workload which is not optimal. The BP deletion does cleanup the WEC.

### Steps To Reproduce

Create BP for a WEC (add   wantSingletonReportedState: true )
Add a label to a job which matches the BP
Create a job in WDS and observe its running and completing on the WEC
Edit the job in WDS (kubectl edit job ..) and delete the label that matches BP
Observe the job lingering on the WEC

### Expected Behavior

After deletion of the label, I expect the workload to be deleted in a timely manner (not several minutes) and subsequent jobs should be pulled and run on the WEC.

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by MikeSpreitzer** [comment]
I tried this, and could not reproduce the problem.
I used the Getting Started setup but modified to set `"type":"host"` for the WDS.

@cwiklik : can you reproduce the problem and report:
- `kubectl --context <one that gets to your ITS> get manifestworks -A --show-managed-fields -o yaml`
- `kubectl --context <one that gets to your KubeFlex hosting cluster> get pods -A`
- `kubectl --context <one that gets to your KubeFlex hosting cluster> logs -n <wds1-system or whatever is right for your WDS> deploy/kubestellar-controller-manager`
- `kubectl --context <one that gets to your WEC> get pods -A`
- logs from the klusterlet and klusterlet-agent and status-agent in the WEC

**Comment by cwiklik** [comment]
Yes, I can reproduce every time using steps outlined above. Perhaps you were lucky the one time you tried. I am using k3d. Perhaps that has something to do with the problem. Attached find the data you've requested.

[manifestworks.txt](https://github.com/user-attachments/files/17259614/manifestworks.txt)
[podlistwds.txt](https://github.com/user-attachments/files/17259615/podlistwds.txt)
[wds-kubestellar-controller-mgr.log](https://github.com/user-attachments/files/17259616/wds-kubestellar-controller-mgr.log)
[wec-cluster-pods.txt](https://github.com/user-attachments/files/17259617/wec-cluster-pods.txt)
[wec-klusterlet.log](https://github.com/user-attachments/files/17259618/wec-klusterlet.log)
[wec-klusterlet-agent.log](https://github.com/user-attachments/files/17259619/wec-klusterlet-agent.log)
[podlistwec.txt](https://github.com/user-attachments/files/17259620/podlistwec.txt)

**Comment by MikeSpreitzer** [comment]
Is this using your wds1 or is it wds2?

**Comment by MikeSpreitzer** [comment]
What was the name of the Job? The BindingPolicy?

**Comment by MikeSpreitzer** [comment]
I just realized that we still have not updated the wrapping code to implement the create-only bit properly. That would explain wedging the kubelet.

**Comment by MikeSpreitzer** [comment]
Also, that listing of pods shows that two are missing for wds2. Compare the pods listed for wds1 vs wds1.

```
NAMESPACE                             NAME                                                 READY   STATUS      RESTARTS   AGE
...
wds1-system       kube-apiserver-74cc855d5b-dbk2m                                   2/2     Running     0          3d23h
wds1-system       kube-controller-manager-ffdb6b8bc-rk945                           1/1     Running     0          3d23h
wds1-system       kubestellar-controller-manager-76f9f97b78-d8rmq                   2/2     Running     0          3d23h
wds1-system       transport-controller-8555c6cf8d-xls5h                             1/1     Running     0          3d23h
wds1-system       wds-29nlb                                                         0/2     Completed   0          3d23h

wds2-system       kubestellar-controller-manager-85bc96bcdf-wbt6s                   2/2     Running     0          3d23h
wds2-system       transport-controller-7d54f6b684-bk2vz                             1/1     Running     0          3d23h
wds2-system       wds-h72nn                                                         0/2     Completed   0          3d23h
```

**Comment by cwiklik** [comment]
I submitted a single job on wds2 of type _host_. I think this is the reason why some pods are not in wds2-system.  The job's name is h100-job-wxv78. Its the only job in the manifestworkls. The binding policy for it should have job's name prefix. This job was cleaned some time ago so I dont have access to any more relevant data. I can recreate the problem at will so if need be I can get new set of files for you to look at. Label was deleted as soon as the job completed (dont have timestamp).
