### ISSUE TITLE
bug: installing kubestellar getting started on kind with rancher desktop

### ISSUE THREAD

**Issue by clubanderson** [kubestellar/kubestellar#2487]
### Describe the bug

I get an error when I try to install kubestellar on kind. Kind is runner with dockerd from rancher desktop. The error I get is from Kind when our getting started script (or automated demo environment bash script) is trying to create the second cluster (cluster 2). The error looks like this...

```
Have a question, bug, or feature request? Let us know! https://kind.sigs.k8s.io/#community 🙂
Context "kind-cluster1" renamed to "cluster1".
Error: hub oriented command should not running against non-hub cluster
Creating cluster "cluster2" ...
 ✓ Ensuring node image (kindest/node:v1.27.1) 🖼
 ✓ Preparing nodes 📦
 ✓ Writing configuration 📜
 ✗ Starting control-plane 🕹️
Deleted nodes: ["cluster2-control-plane"]
ERROR: failed to create cluster: failed to init node with kubeadm: command "docker exec --privileged cluster2-control-plane kubeadm init --skip-phases=preflight --config=/kind/kubeadm.conf --skip-token-print --v=6" failed with error: exit status 1
Command Output: I1008 16:11:20.743111     134 initconfiguration.go:255] loading configuration from "/kind/kubeadm.conf"
W1008 16:11:20.743835     134 initconfiguration.go:332] [config] WARNING: Ignored YAML document with GroupVersionKind kubeadm.k8s.io/v1beta3, Kind=JoinConfiguration
[init] Using Kubernetes version: v1.27.1
[certs] Using certificateDir folder "/etc/kubernetes/pki"
I1008 16:11:20.748175     134 certs.go:112] creating a new certificate authority for ca
[certs] Generating "ca" certificate and key
I1008 16:11:20.789452     134 certs.go:519] validating certificate period for ca certificate
[certs] Generating "apiserver" certificate and key
[certs] apiserver serving cert is signed for DNS names [cluster2-control-plane kubernetes kubernetes.default kubernetes.default.svc kubernetes.default.svc.cluster.local localhost] and IPs [10.96.0.1 172.18.0.4 127.0.0.1]
[certs] Generating "apiserver-kubelet-client" certificate and key
I1008 16:11:21.009079     134 certs.go:112] creating a new certificate authority for front-proxy-ca
```

### Steps To Reproduce

to reproduce this
1) install rancher desktop
2) install kind
3) install all other kubestellar pre-reqs
4) run through kubestellar getting started (or run the kubestellar demo environment setup bash script)
5) observe completed kubeflex installation
6) observe wait for ITS1 and WDS1 creation
7) observe creation of cluster1 remote cluster
8) wait for cluster2 remote cluster to create successfully

fail...

### Expected Behavior

cluster 2 should create successfully

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by clubanderson** [comment]
Rancher desktop runs a virtual machine where all the dockerd bits execute. This VM has relatively low settings for certain sysctl parameters. 

fs.inotify.max_user_watches
fs.inotify.max_user_instances

to see the values for these first use 'rdctl shell' to login to the rancher desktop virtual machine and then run sysctl to see the values of these 2 parms:

```
sysctl fs.inotify.max_user_watches
    fs.inotify.max_user_watches = 155696
sysctl fs.inotify.max_user_instances
    fs.inotify.max_user_instances = 128
```

These should be, according to Kind, equal to or higher than 524288 and 512 respectively.

attempting to set these 2 parms with sysctl will succeed at first, but you must then restart rancher desktop for the changes to take effect. When you do this, the new parm values will have disappeared - they are not persisted as a normal linux box would persist them. To stop this idempotent behavior, you must change the settings in an overlay file on your host.

on my Mac I created a new file with VI

```
vi ~/Library/Application\ Support/rancher-desktop/lima/_config/override.yaml
```

then I entered the following:
```
provision:
- mode: system
  script: |
    #!/bin/sh
    echo "fs.inotify.max_user_watches=524288" > /etc/sysctl.d/fs.inotify.conf
    echo "fs.inotify.max_user_instances=512" >> /etc/sysctl.d/fs.inotify.conf
    sysctl -p /etc/sysctl.d/fs.inotify.conf
```

write and save this file. Then restart rancher desktop.

delete the last set of clusters you created for KubeStellar and re-run the getting started guide or the automated demo environment shell script.

you should be good to go.

Thanks @MikeSpreitzer for your help debugging and correcting this.

**Comment by MikeSpreitzer** [comment]
Is this closed Issue intended as documentation for other readers to see? If so then I think it would be better to add into the troubleshooting page of the website. Note that PR #2486 --- currently in flight --- also makes a relevant update.

**Comment by MikeSpreitzer** [comment]
> attempting to set these 2 parms with sysctl will succeed at first, but you must then restart rancher desktop for the changes to take effect.

As far as I know, that is not true.

BTW, I have an `override.yaml` file with the same contents as you exhibited except that mine does not have the `sysctl -p /etc/sysctl.d/fs.inotify.conf` at the end, and mine still has the desired effect.
