### ISSUE TITLE
feature: dependency checking script should check version

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#2492]
### Feature Description

It is a problem when the dependency checking script (hack/check_pre_req.sh) claims success but the dependency is at too old of a version.

### Proposed Solution

Make the dependency checking script check the versions.

### Want to contribute?

- [ ] I would like to work on this issue.

### Additional Context

If this feature had been present then issue #2491 would not have been raised (the user would have been told that they have too old a version of kflex).

**Comment by francostellari** [comment]
It's not trivial to make it work in general
