### ISSUE TITLE
bug: "Generate and Push Docs" action appears to fail on fork branches named "main"

### ISSUE THREAD

**Issue by KPRoche** [kubestellar/kubestellar#2504]
### Describe the bug

This is a problem which I've observed on several occasions, where the the action to create (preview) webpages from a fork of the repository appears to fail if the branch of that fork is "main"
If a branch of that fork is created named something else, the action works.

### Steps To Reproduce

1. Create a fork of kubestellar main in your own account.
2. Go to that fork. (switch to your copy of the repo in github.com)
3. Leave the branch in your copy of the repo named main.
4. Go to Actions and select **Generate and Push Docs**
5. Click the **Run Workflow** button. Select the main branch and click the second **Run Workflow** button in the dialog
6. Workflow runs with errors, and the preview site (https://youraccount.github.io/kubestellar/main) is not generated

### Expected Behavior

The webpages should be generated and the preview website should be available.

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by MikeSpreitzer** [comment]
Re step 1: one does not create a "fork" of a "branch"; one creates a "fork" of a "repository".

**Comment by MikeSpreitzer** [comment]
Please show logs from a failing case.

IIRC, it is also necessary for your fork to have a copy of the branch named "gh-pages". Remember that the GitHub web UI for creating a fork has an option for whether to copy _only_ the default branch, and this option is engaged unless you explicitly say to copy all branches.

**Comment by MikeSpreitzer** [comment]
Perhaps we should have a doc about how to enable a contributor's fork for docs rendering.

**Comment by KPRoche** [comment]
> Re step 1: one does not create a "fork" of a "branch"; one creates a "fork" of a "repository".

You are correct, I was sloppy in my phrasing. When you create a fork of a repository, you can specify the branch name for it *in your github account* and that defaults to main in my experience.

I don't have logs to hand at the moment from the last time I tried and failed -- however you may have put your finger on the problem with the gh-pages observation.

**Comment by KPRoche** [comment]
> Perhaps we should have a doc about how to enable a contributor's fork for docs rendering.

AGREED!

**Comment by MikeSpreitzer** [comment]
Here is an example of what I see when creating a fork using the GitHub web UI. I do not get to create any new branches or rename any branches. My only choice is whether to copy all the branches or only the one that is marked as "the default" (which is the one named `main` in this case). The name that I _do_ get to choose is the repository name, within the scope of my "organization". The repository name is a completely separate concept from a branch name. I can choose any name for my repository, and it makes no difference to anything, as far as I know.

<img width="822" alt="image" src="https://github.com/user-attachments/assets/ab9e1892-5e7b-4943-9531-1cbfd82bb4b6">

**Comment by KPRoche** [comment]
@MikeSpreitzer I am 99% sure at this point that the issue is the default behavior of creating a fork only copying the main branch and not including the gh-pages branch, as opposed to my presumption that it was the name of the branch in the forked repository.

I did discover a related quirk -- unlike on kubestellar.io, where updates to the branch "main" are rendered as the "unreleased-development" version of the documentation on the site, running the action on a branch named "main" in one's fork of the repository will create a "main" version of the web pages in your_account.github.io/kubestellar

We **do** need to update the documentation on the steps on how to enable previewing the website in one's own github account, as previewing file changes only as markdown misses key visual components of the render.

**Comment by KPRoche** [comment]
@MikeSpreitzer I have attempted to update the README.md file for the docs (which is pulled into the website contribution page via an include directive) to describe how to create and render previews from a fork.
I also made a minor change to the first sentence of the Testing website PRs file.
You can preview the website rendering at 
https://kproche.github.io/kubestellar/doc-addweb/Contribution%20guidelines/operations/document-management/
And in the repo at https://github.com/KPRoche/kubestellar/blob/doc-addweb/docs/README.md

If this looks right, I can make it an actual PR.

**Comment by KPRoche** [comment]
Note the URL for the preview of that page has changed ever so slightly (I've updated the link in my comment)
Otherwise, start at https://kproche.github.io/kubestellar/doc-addweb/readme/  and navigate to the website section of Contributing
