### ISSUE TITLE
bug: "Was this page useful" feedback buttons data inaccessible

### ISSUE THREAD

**Issue by KPRoche** [kubestellar/kubestellar#2533]
### Describe the bug

In the footer of every page on the kubestellar.io site there is a pair of feedback icons (happy and sad emoticons) 
![image](https://github.com/user-attachments/assets/eb775938-1df2-40db-942f-269310241d8b)
If you click on one of the icons, a "Thanks for your feedback" message appears, but that feedback is not currently available to the KubeStellar Team.

### Steps To Reproduce

1. Go to any page inside kubestellar.io other than the landing page.
2. Scroll to the bottom
3. Click on one of the feedback icons in the footer
4. Message saying "Thanks for your Feedback!" appears.
5. The feedback does not actually come back to the KubeStellar team.

### Expected Behavior

Apparently this feature was added to mkdocs, but the data must be accessed via Google Analytics.
https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-analytics/#was-this-page-helpful
It would be worth investigating whether we can access it, or how mkdocs.yml has to be configured to make it more useful.

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by KPRoche** [comment]
Looking at the mkdocs.yml file, we are indeed sending it to a google analytics handler (I've redacted the ID code):

```
analytics:
    provider: google
    property: X-XXXXXXXXX
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="https://github.com/kubestellar/kubestellar/issues/new?assignees=&labels=kind%2Fbug&projects=&template=bug_report.yaml&title=bug%3A+" target="_blank" rel="noopener">feedback form</a>.
```
Also, it seems the URL for the feedback form does not appear when the "note" is triggered.

**Comment by clubanderson** [comment]
fyi, the following people have access to GA for feedback

<img width="1331" alt="Screenshot 2024-10-30 at 8 05 34 AM" src="https://github.com/user-attachments/assets/128aaf5c-12d0-4fdf-aaba-aa533556c52e">

**Comment by KPRoche** [comment]
> fyi, the following people have access to GA for feedback

It appears I do indeed have view access but not the authority to create the custom metrics described at https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-analytics/

**Comment by KPRoche** [comment]
I have created an "exploration" in Google Analytics logging events of the "was this page useful" clicks. It should be visible to all authorized users for our GA stats.
I'm going to close this issue; we may want to revisit whether we want more options in the feedback buttons at a future date.
