### ISSUE TITLE
feature: Automate the deployment of KubeStellar using Ansible (cloud-env)

### ISSUE THREAD

**Issue by dumb0002** [kubestellar/kubestellar#260]
### Feature Description

To build Ansible automation to deploy KubeStellar and deploy TMC Syncer in edge pclusters

### Proposed Solution

To build Ansible playbooks to deploy KCP and all the components for KubeStellar. 
To build Ansible playbooks to deploy the TMC Syncer

### Want to contribute?

- [ ] Deploy KCP server in the center (https://github.com/aknochow/install-kcp)
- [ ] Create KubeStella workspaces (e.g., inventory management, edge service provider workspace, etc)
- [ ] Create KubeStella objects in the Inventory Management workspace
- [ ] Create KubeStella objects in the Workload Management workspace
- [ ] Deploy KubeStella controllers (e.g., mailbox controller, edge scheduler, placement translator, etc.) in the Edge Service Provider workspace
- [ ] Deploy the TMC Syncer in the edge pclusters

### Additional Context
 
Assumptions:
     - Mailbox controller creates the mailbox workspaces
     -  Placement translator controller creates all the KubeStella objects in the Mailbox workspaces

**Comment by clubanderson** [comment]
@dumb0002 this looks great.  Lets get Adam into kcp-dev.

**Comment by clubanderson** [comment]
@dumb0002 can this issue be re-used to capture the information you are gathering for the use case environment?
