### ISSUE TITLE
bug: Pods for a completed Job start again

### ISSUE THREAD

**Issue by cwiklik** [kubestellar/kubestellar#2634]
### Describe the bug

My environment:
k3d version v5.7.4
k3s version v1.30.4-k3s1 (default)
KubeStellar: 0.25.1 

I create a job in the mgmt cluster, it gets pulled to a WEC  and runs to completion. When the job completes I start another ( same job spec). I create multiple jobs this way. What I notice eventually on the WEC is that pods for a job, which previously completed, start again. This happens with KS v.0.25.0 and 0.25.1. In testing I've removed Kueue and my Kueue-KS integration controllers so its just KS in the picture. Below are two images, one showing all pods in completed state; and another showing the previously completed pods as running again.

![image](https://github.com/user-attachments/assets/3b476a23-b7e1-43aa-bd54-abb23f69c218)

I start a new job: sample-job-8qksl. Note that previously completed pods for a job sample-job-fmfzw are in Running state.

![image](https://github.com/user-attachments/assets/8a9858cf-3041-404b-8278-2cfe5e394328)

Below are manifestworks, bp, binding, and my job spec:
[mw1.txt](https://github.com/user-attachments/files/17937453/mw1.txt)
[mw3.txt](https://github.com/user-attachments/files/17937454/mw3.txt)
[mw4.txt](https://github.com/user-attachments/files/17937455/mw4.txt)
[mw5.txt](https://github.com/user-attachments/files/17937456/mw5.txt)
[wec-klusterlet.log](https://github.com/user-attachments/files/17937457/wec-klusterlet.log)

Job:
```
apiVersion: batch/v1
kind: Job
metadata:
  generateName: sample-job-
  namespace: default
  labels:
    kueue.x-k8s.io/queue-name: user-queue-ks
    kubestellar.io/cluster: cluster2
spec:
  parallelism: 3
  completions: 3
  suspend: true
  template:
    spec:
      containers:
      - name: dummy-job
        image: gcr.io/k8s-staging-perf-tests/sleep:v0.1.0
        args: ["50s"]
        resources:
          requests:
            cpu: 1
            memory: "200Mi"
          limits:
            memory: "200Mi"
            cpu: 1
      restartPolicy: Never
```
BP:
```
apiVersion: control.kubestellar.io/v1alpha1
kind: BindingPolicy
metadata:
  creationTimestamp: "2024-11-27T16:01:04Z"
  finalizers:
  - bindingpolicy.kubestellar.io/kscontroller
  generation: 1
  name: cluster2
  resourceVersion: "1636"
  uid: 44627ace-a2b4-490d-aba4-d6bb3418b299
spec:
  clusterSelectors:
  - matchLabels:
      location-group: edge
      name: cluster2
  downsync:
  - createOnly: true
    objectSelectors:
    - matchLabels:
        kubestellar.io/cluster: cluster2
  wantSingletonReportedState: true
status:
  observedGeneration: 1
```
Binding:
```
apiVersion: control.kubestellar.io/v1alpha1
kind: Binding
metadata:
  creationTimestamp: "2024-11-27T16:01:06Z"
  finalizers:
  - transport.kubestellar.io/object-cleanup
  generation: 120
  name: cluster2
  ownerReferences:
  - apiVersion: control.kubestellar.io/v1alpha1
    blockOwnerDeletion: false
    controller: true
    kind: BindingPolicy
    name: cluster2
    uid: 44627ace-a2b4-490d-aba4-d6bb3418b299
  resourceVersion: "4013"
  uid: 0d1a89a8-9868-4de6-8a3a-007ef2c1db7b
spec:
  destinations:
  - clusterId: cluster2
  workload:
    clusterScope:
    - createOnly: true
      group: galaxy.kubestellar.io
      name: cluster2
      resource: clustermetrics
      resourceVersion: "4009"
      version: v1alpha1
    namespaceScope:
    - createOnly: true
      group: batch
      name: sample-job-4z8jx
      namespace: default
      resource: jobs
      resourceVersion: "2384"
      version: v1
    - createOnly: true
      group: batch
      name: sample-job-8qksl
      namespace: default
      resource: jobs
      resourceVersion: "3087"
      version: v1
    - createOnly: true
      group: batch
      name: sample-job-d7bgf
      namespace: default
      resource: jobs
      resourceVersion: "2729"
      version: v1
    - createOnly: true
      group: batch
      name: sample-job-fmfzw
      namespace: default
      resource: jobs
      resourceVersion: "3085"
      version: v1
status:
  observedGeneration: 120
```

### Steps To Reproduce

See above

### Expected Behavior

Pods with Completed state should not restart.

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by MikeSpreitzer** [comment]
What I see in the opening comment is that new pods are created for Job `sample-job-fmfzw` after the first three pods are created and complete.

**Comment by MikeSpreitzer** [comment]
The "mw?.txt" files attached to the opening comment only hold a tabular listing, not the YAML or JSON content of the relevant object.

More importantly, since the problem is behavior over time, listings of the ManifestWorks at cardinal points in time is what would be helpful. Something like `kubeget --context its1 get manifestworks -A -o yaml` at those points in time. Such as: when the Job's pod first complete, and then soon after new pods have been created.

**Comment by MikeSpreitzer** [comment]
In the opening comment, the file named "wec-klusterlet.log" is from the Deployment named "klusterlet". However, that is merely a higher level manager that manages the thing that does the work, which is the Deployment named "klusterlet-agent". It is the log from the latter that would be helpful.

**Comment by MikeSpreitzer** [comment]
I have a hypothesis of what is going wrong. @cwiklik, I assume that your system uses the KubeStellar core Helm chart, and in particular with a "values" setting of `transport_controller.max_num_wrapped` to 1 (which is the default). In this case, as matching Job objects are created and/or deleted in the WDS, a given Job will appear in different ManifestWork object over the Job's lifetime. I suspect that OCM may not recognize this as one continuous request to propagate one Job with create-only. KubeStellar's OCM based transport-controller, when working on one Binding, makes new ManifestWork objects before deleting undesired ones. Also, this controller updates the desired ManifestWork objects one at a time. So there may be brief periods of time when no ManifestWork contains a given Job, or when two ManifestWork objects contain a given Job.

This failure mode would be avoided by setting `transport_controller.max_num_wrapped` in the "values" of the KubeStellar core Helm chart to a value that is at least as large as the number of object references that ever appears in the Binding.

**Comment by cwiklik** [comment]
@MikeSpreitzer, I do use the helm chart with defaults.  Do you want me to rerun the scenario and provide you with new data as requested above? You seem to figured out what may be the reason for the issue so not sure if you need additional info.

**Comment by cwiklik** [comment]
@MikeSpreitzer, with  `max_num_wrapped: 3 ` I can run multiple jobs and old pods remain `Completed`

**Comment by MikeSpreitzer** [comment]
@cwiklik: It is not clear to me what @eaepstein reported, as I remarked in the Slack conversation where he reported.

If you only ever have 3 workload object references in your Binding at one time then you have done the test I wanted. That would probably be one Namespace plus two Job objects.
