### ISSUE TITLE
bug: create-kubestellar-demo-env.sh does not insist on prereqs

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#2656]
### Describe the bug

`scripts/create-kubestellar-demo-env.sh` invokes `hack/check_pre_req.sh` _without_ `--assert` and so does not stop if some prereqs are missing.

### Steps To Reproduce

While lacking some prereq(s), invoke scripts/create-kubestellar-demo-env.sh

### Expected Behavior

Complaint about missing prereq and then halt.

### Want to contribute?

- [x] I would like to work on this issue.

**Comment by clubanderson** [comment]
Got it. Will work on it today
