### ISSUE TITLE
docs: scenario 2 why the need for ClusterRoleBinding

### ISSUE THREAD

**Issue by csantanapr** [kubestellar/kubestellar#2659]
In the docs in https://docs.kubestellar.io/release-0.25.1/direct/example-scenarios/#scenario-2-out-of-tree-workload

Can you provide more explanation why suddenly I need to make the service account kubeflex-controller-manager cluster-admin to be able to deploy custom CRs to WECs.

**Comment by MikeSpreitzer** [comment]
This is related to #2658 .
