### ISSUE TITLE
CNCF (Sandbox) TAG-Runtime Discussion/Presentation

### ISSUE THREAD

**Issue by nikhita** [kubestellar/kubestellar#283]
Hi KCP Edge maintainers,

I'm part of [CNCF TAG Runtime](https://github.com/cncf/tag-runtime). I think it would be great for you to present/discuss KCP Edge at one of our meetings, especially also since you've applied for Sandbox (https://github.com/cncf/sandbox/issues/32).

For example, it would be great to learn things like the roadmap, tech, community and the general overview of the project.

Let me know if this is something you'd be interested in doing. If yes, please feel free to add it to our [agenda](https://bit.ly/cncf-tag-runtime-meeting-notes) or reach out to us in the [#tag-runtime](https://cloud-native.slack.com/messages/tag-runtime) channel on the CNCF slack.

Thanks!

cc @raravena80 @helayoty

**Comment by nikhita** [comment]
@clubanderson We try not to have more than 1-2 projects per meeting due to time constraints. I've moved the KCP Edge presentation from May 4th to May 18th. Hope that works!

**Comment by clubanderson** [comment]
Works for us. See you then.

**Comment by clubanderson** [comment]
Presentation was completed today - thank you.  We hope to hear from you soon re: our sandbox application's status.

**Comment by clubanderson** [comment]
Next meeting of TAG-Runtime is on Dec 12th.  Voting will open after this meeting. Fingers-crossed

**Comment by clubanderson** [comment]
KubeStellar has now been accepted to the CNCF Sandbox project!  Looking forward to what is ahead!

checkout the vote: https://github.com/cncf/sandbox/issues/32

**Comment by raravena80** [comment]
Congrats @clubanderson !
