### ISSUE TITLE
feature: Improve kcpe-dev-env with additional features (Bring Your Own Cluster & Workloads )

### ISSUE THREAD

**Issue by dumb0002** [kubestellar/kubestellar#289]
### Feature Description

To improve with kcpe-dev-env with additional features:
   a) refactor a copy of current automation to allow user to add their own workload
   b) add instructions on how to Bring Your Own Cluster (location, synctarget, etc)

### Proposed Solution

List of required features:
1) Automation that provides example infrastructure (kind clusters) for the following to use.
2) Automation that deploys the edge-mc platform, consuming given infrastructure.  Pointer to documentation of how the platform deployment is told what infrastructure to consume.  The quickstart shows the platform consuming the infrastructure from (1).
3) A walk-through for users using the deployed platform and infrastructure, including showing the contents of key objects.

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by clubanderson** [comment]
I think this is completed now, no?

**Comment by clubanderson** [comment]
is this done @dumb0002  - please close if so.
