### ISSUE TITLE
bug: remove-kubestellar is a very sharp edge

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#398]
### Describe the bug

This script invites being invoked with no parameters, and in this case it can wreak havoc if the current working directory is not what it expects.  Havoc can also happen if the user mistakenly specifies the wrong directory.

### Steps To Reproduce

See above.

### Expected Behaviour

Such a fragile and disruptive script should be more careful.

It should be possible for this script to find where it is located, rather than needing to be told.

**Comment by clubanderson** [comment]
👍

**Comment by MikeSpreitzer** [comment]
I hope this is moot now.
