### ISSUE TITLE
bug: bootstrap-kubestellar should report which version is running

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#400]
### Describe the bug

It would be helpful to get version information in the output.

### Steps To Reproduce

See doc

### Expected Behaviour

More information

**Comment by MikeSpreitzer** [comment]
@francostellari 
@dumb0002 
@clubanderson

**Comment by clubanderson** [comment]
@MikeSpreitzer how should this be done?

**Comment by MikeSpreitzer** [comment]
Moot now.
