### ISSUE TITLE
bug: ESPW create/delete should be bundled with install/uninstall not start/stop

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#401]
### Describe the bug

In common Uniix/Linux packages, starting and stopping the daemons does not create/delete the supporting state (e.g., files in /etc).  We should follow the usual pattern.

### Steps To Reproduce

read the doc or experiment

### Expected Behaviour

Unsurprising bundling of behavior

**Comment by MikeSpreitzer** [comment]
@dumb0002 
@francostellari 
@clubanderson

**Comment by clubanderson** [comment]
we have a kubestellar init command now and this relieves some of the pressure on this issue.

does this ripple through the documentation for examples?

**Comment by clubanderson** [comment]
should this change be incorporated into the bootstrap @francostellari

**Comment by MikeSpreitzer** [comment]
The ESPW create is now available in `kubestellar init` (while also done in `kubestellar start` if needed) and the ESPW deletion has been removed from `kubestellar stop`.

I think the docs are OK with the possible exception of the bootstrap script viewed as a doc; we can revisit that if/when we are more decisive about whether to sweep that content into a different script/program.
