### ISSUE TITLE
bug: No established way to test bootstrap script before release

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#407]
### Describe the bug

We need to up our before-release testing game.  We should have a way to test building a release and bootstrapping it without making a release.

### Steps To Reproduce

Think about it.

### Expected Behaviour

We have a way and a practice of testing before making an actual release.

**Comment by MikeSpreitzer** [comment]
@dumb0002 
@francostellari 
@clubanderson 
@waltforme 
@yana1205 
@ezrasilvera 
@pdettori

**Comment by MikeSpreitzer** [comment]
Yes, we have a way of testing a release, whether it is considered a "pre-release" or not.  What I am asking for here is something lighter weight that creating a pre-release type of release.  A developer and our CI should be able to test without making a release.

**Comment by clubanderson** [comment]
potentially make the bootstrap script functionality, as minimal as possible (post kcpdependency), and/or build a test case and/or port that functionality into the kubestellar command.
