### ISSUE TITLE
feature: the kubectl plugins should be based on proper arg parsing

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#414]
### Feature Description

The kubectl plugins, aside from the syncer-gen one, are currently bash scripts that do some generic parsing of kubectl flags.  This is more complex programming than should be done in bash and, more importantly, is ignorant of what kubectl flags really are.  

### Proposed Solution

These should be rewritten to rely on a standard library that actually understands kubectl flags, such as https://github.com/kubernetes/cli-runtime .

### Alternative Solutions

🤷 

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by clubanderson** [comment]
@MikeSpreitzer can you point me at an example plugin that uses https://github.com/kubernetes/cli-runtime?  I need to learn by example before trying to modify any of our plugins.

**Comment by clubanderson** [comment]
I am working on converting the get_log script first.  I hope to have something working shortly.

**Comment by clubanderson** [comment]
the scripts I am targeting for conversion, in no particular order, are:

kubectl-kubestellar-deploy
kubectl-kubestellar-ensure-location
kubectl-kubestellar-ensure_wmw
kubectl-kubestellar-get_external_kubeconfig
kubectl-kubestellar-get_internal_kubeconfig
kubectl-kubestellar-get_log
kubectl-kubestellar-prep_for_cluster
kubectl-kubestellar-prep_for_syncer
kubectl-kubestellar-remove-location
kubectl-kubestellar-remove-wmw

I am not sure if there is a need to support:
kubectl-workspace-ensure

**Comment by MikeSpreitzer** [comment]
For example, the KubeStellar scripts do not know which flags take an argument vs. which do not.

**Comment by clubanderson** [comment]
@namasl is covering this starting with #1294

**Comment by clubanderson** [comment]
we will pick this up in the new year

**Comment by namasl** [comment]
With the recent architecture change to use the space framework, PR #1294 has been closed, and a new PR will contain similar Bash script to Go conversions for the latest kubectl-kubestellar* commands.

As this issue's description is generic enough to cover the requisite changes under the new architecture, I figured I'd add this comment here rather than make a new issue.
