### ISSUE TITLE
feature: version coordination between the syncer container image and the default reference to it

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#422]
### Feature Description

Currently the `kubectl kubestellar syncer-gen` plugin does not have a usable default value for the syncer image reference, the `kubectl kubestellar prep-for-syncer` plugin has the meaningful default.  Currently that default value, in each commit tagged as a release, references the previous release --- which is not great.  The feature is to somehow get the default syncer image in each release commit to reference that same commit.

This is the remainder of #395 

### Proposed Solution

Take care for this in the process of creating a release.  When preparing for release X.Y.Z, make a commit in which the default value for the syncer image reference is tagged vX.Y.Z.  This commit can even be pushed to the shared repository in a branch, but should not be merged into `main` yet.  With the commit in place, the syncer container image can be built with the tag vX.Y.Z.  The commit can be tested.  If it passes, then the commit can be tagged as release vX.Y.Z and then the branch containing that merged into `main`.

### Alternative Solutions

The `kubectl kubestellar syncer-gen` plugin (and the ones that call it) should be able to generate YAML that specifies a syncer built from the same commit as the plugin.

Make the default for the syncer image ref be computed from characteristics captured at build time in https://github.com/kubernetes/client-go/tree/master/pkg/version .  Specifically, GitCommit and GitTreeState.

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by clubanderson** [comment]
build of syncer image is now reproducible.  need to make part of the building process - editing the script so that default is to reference the image just built (goreleaser potentially).

**Comment by MikeSpreitzer** [comment]
Moot now.
