### ISSUE TITLE
feature: something should restart crashed controllers

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#450]
### Feature Description

In every reasonably mature system with background processes, there is something that restarts them when they crash.  KubeStellar should have this too.

### Proposed Solution

I think the most likely next step is to containerize the controllers, with the containers set to restart on crash.

### Alternative Solutions

We could make the controllers into systemd services.  I disfavor that approach because (a) it is more dependent on the OS and (b) it is less helpful in getting where I expect we will later go (which is putting the controllers in one or more pods in a kube cluster).

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by clubanderson** [comment]
Is a statefulset (if containers)overkill here?  Or is Systemd enough (if processes)

**Comment by MikeSpreitzer** [comment]
I expect that eventually the KubeStellar controllers will run in one or several `Pod`s in a Kubernetes cluster.  A `Deployment` is the usual higher-level construct to manage one `Pod` or an undifferentiated set of `Pod`s.  For sharding, last year we used `StatefulSet` objects but that is not the only possible design.

**Comment by ezrasilvera** [comment]
Agree. I don't think there is a point in trying to add such restart mechanism on top of our exes

**Comment by clubanderson** [comment]
Closing as cared for in helm effort that uses separate pods for each controller and KCP
