### ISSUE TITLE
Prepare submission for KubeCon China

### ISSUE THREAD

**Issue by waltforme** [kubestellar/kubestellar#502]
https://www.lfasiallc.com/kubecon-cloudnativecon-open-source-summit-china/

Important dates:
- CFP Closes: Sunday, June 18 at 11:59 pm China Standard Time (UTC +8)
- CFP Notifications: Monday, July 31
- Schedule Announcement: Wednesday, August 2
- Slide upload deadline to Sched.com: Wednesday, September 20
- Event Date: September 26-28

**Comment by clubanderson** [comment]
what are your next steps here @waltforme and @yana1205 ?

**Comment by waltforme** [comment]
Will draft the presentation within this week.

**Comment by yana1205** [comment]
I'm still in registration step. Before submitting, I need to make sure whether I can travel on business. I am working on the pre-approval process with the latest rule of trip abroad between China and Japan.

**Comment by waltforme** [comment]
I'm revisiting the CFP, just want to confirm: Looks like the CFP doesn't require slides and doesn't have a place to upload slides?

**Comment by clubanderson** [comment]
correct, the CFP is call for proposal.  You wait for your proposal to be accepted after the deadline for CFP closes.  Then you prepare slides when (and if) your proposal is accepted.

**Comment by waltforme** [comment]
> correct, the CFP is call for proposal. You wait for your proposal to be accepted after the deadline for CFP closes. Then you prepare slides when (and if) your proposal is accepted.

Thanks Andy!

**Comment by clubanderson** [comment]
@waltforme did we get notification of inclusion or exclusion of our 2 proposed talks today?
@yana1205 did you get any notifications?

**Comment by waltforme** [comment]
Haven't heard anything yet from my side.

**Comment by yana1205** [comment]
@clubanderson 
I received the notification today's morning. It seems that my submission was added to waitlisted. Waitlisted speakers will be reached out to if speakers’ circumstances change and they can no longer speak.
I will wait for a while.

**Comment by yana1205** [comment]
I need sufficient time to process the visa. If I don't here back from them about the inclusion of my submission within a couple of weeks, I will remove my submission from the waitlist.

**Comment by clubanderson** [comment]
Ok. Jun is going to Kubecon CN to attend. He can present on your behalf now that he has no other obligations. Maybe it makes better sense for Jun to present and for you to support him from home.

**Comment by clubanderson** [comment]
moving to sprint 3 to track progress on presentation.

**Comment by clubanderson** [comment]
@yana1205 please contact the KubeCon CN to swap Jun into the presentation that is waitlisted, and you can be removed.

**Comment by yuji-watanabe-jp** [comment]
@yana1205 is going to give his talk on site if it is picked from the waitlist. He will get visa once noticed within a couple of weeks.

**Comment by clubanderson** [comment]
lets prepare a presentation (30 minutes, 8 slides and a title page) just in case we need it for CN or NA.

**Comment by clubanderson** [comment]
@waltforme you have t-shirts today.  Great job!  Please report about your experience at the conference.  We are all eager to hear how it goes, who you meet, and what you learn.

**Comment by clubanderson** [comment]
lets close this issue out after your playback when you return.  Good luck!

**Comment by waltforme** [comment]
> lets close this issue out after your playback when you return. Good luck!

Thanks! Heading to today's sessions now.
