### ISSUE TITLE
feature: Add a tutorial on using Turbonomic with KubeStellar

### ISSUE THREAD

**Issue by clubanderson** [kubestellar/kubestellar#513]
### Feature Description

I would like to demonstrate to our community that Turbonomic works with KubeStellar.

### Proposed Solution

Create a doc that can be attached to the doc site under a new 'partner' section

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by clubanderson** [comment]
you can place this information here - https://docs.kubestellar.io/main/Community/partners/turbonomic/

**Comment by clubanderson** [comment]
@dumb0002 needs this for work he is doing with MCAD

**Comment by waltforme** [comment]
Maybe we may need help from Turbo folks for this issue? In the Turbo + KubeStellar collaboration, scheduling decision is passed from Turbo to KubeStellar in two steps:
Turbo -> GitHub -> KubeStellar.

For Github -> KubeStlellar, we use Argo CD and this step is recently documented.
For Turbo -> Github, Turbo team owns some controllers to access GitHub, and some temporary workarounds to change the behavior of Turbo services (in the center).

**Comment by clubanderson** [comment]
sounds like a good plan - lets make incremental progress on the calls with Turbo.

**Comment by clubanderson** [comment]
you can use the doc-ecutable method for this to install kubestellar/kcp and configure it.  Now that would be cool

**Comment by clubanderson** [comment]
need help from turbo on cross-cluster mechanics

**Comment by waltforme** [comment]
@chlam4 Here is where we need help from you and your team.

As far as I know
- there is some tweak on the Turbo service side to enable the 'pod move action' cross clusters;
- there is some controller which writes scheduling decisions to GitHub by creating PRs.

We need your help to show the tutorial for KubeStellar users, if possible. Thanks!

**Comment by chlam4** [comment]
Hi @waltforme and @clubanderson, sure let's work on the doc together!
1. The "tweak" has now been part of the Kubeturbo code.  Just configuration change from the default; here is the related config parameter: https://github.com/turbonomic/kubeturbo/blob/master/cmd/kubeturbo/app/kubeturbo_builder.go#L204
2. The controller that creates PR is called "change reconciler": https://github.com/irfanurrehman/change-reconciler
3. There's also the part that intercepts Turbo actions and creates CRs to the above change reconciler to create PRs. Here is the code: https://github.com/edge-experiments/turbonomic-integrations

**Comment by clubanderson** [comment]
closing per @waltforme
