### ISSUE TITLE
feature: experimentation with MCAD

### ISSUE THREAD

**Issue by clubanderson** [kubestellar/kubestellar#516]
### Feature Description

I would like to use MCAD as one of the options for the job queuing and scheduling interface for KubeStellar.

### Proposed Solution

It may be possible to use the appWrapper resource type to complete this task.

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by clubanderson** [comment]
@dumb0002 has MCAD agent deployed, and example of appWrapper working.

**Comment by clubanderson** [comment]
@dumb0002 is working on video to demonstrate MCAD deployment using KubeStellar

**Comment by clubanderson** [comment]
keep going in next sprint

**Comment by dumb0002** [comment]
MCAD and KubeStellar integration work has been completed. We are now working on the v2 of this integration and we have another issue tracking this work: https://github.com/kubestellar/kubestellar/issues/1684. Hence, this issue can be closed
