### ISSUE TITLE
blog: KubeStellar as the preferred control plane for distributed observability projects

### ISSUE THREAD

**Issue by clubanderson** [kubestellar/kubestellar#518]
### Feature Description

I would like to use KubeStellar as the control plane to distribute, configure, and collect status from distributed observability projects like prometheus and others.

### Proposed Solution

Identify some distributed observability partners and determine the best pattern for deploying, configuring, and collecting status from them. 

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by clubanderson** [comment]
issue with API export/bind identified.  Issue to be opened in kcp.

**Comment by dumb0002** [comment]
Status:

-    KubeStellar integration with an application that support distributed observability using an Hub-and-Spoke Approach (**completed**)
-    Blog on KubeStellar support for a Hub-and-Spoke application architecture (**on-going**)

**Comment by clubanderson** [comment]
Blog is being revised and polished

**Comment by clubanderson** [comment]
ETA for posting on Medium.com is August 15th

**Comment by clubanderson** [comment]
@dumb0002 is there a new ETA for this?

**Comment by dumb0002** [comment]
@clubanderson, the new ETA is September 7th.

**Comment by clubanderson** [comment]
Looks great - thank you for this tremendous achievement.  Closing now.
