### ISSUE TITLE
feature: support the other containerized workload resources

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#522]
### Feature Description

As you can see in https://github.com/kcp-dev/kcp/tree/v0.11.0/config/rootcompute/kube-1.24 , currently kcp's APIExport of Kubernetes resources from the `root:compute` workspace only has four resources (kinds of objects): deployments, pods, ingresses, and services.  KubeStellar should also support use of the other containerized workload resources from Kubernetes.

### Proposed Solution

Do like kcp did for the first four, but for all the others.  I think that involved using https://github.com/kcp-dev/kcp/tree/v0.11.0/cmd/crd-puller .

### Want to contribute?

- [x] I would like to work on this issue.

**Comment by MikeSpreitzer** [comment]
Considering https://github.com/kcp-dev/edge-mc/discussions/582 , we might want to segregate these resources into two groups: namespaced and not.

**Comment by clubanderson** [comment]
pushing back 1 sprint.  @MikeSpreitzer is this referenced by the q4 roadmap?

**Comment by clubanderson** [comment]
namespaces API is supported by KubeStellar today.  Cluster-scoped (non-namespaced) Is under investigation.

**Comment by clubanderson** [comment]
pending issue https://github.com/kube-bind/kube-bind/pull/175

**Comment by MikeSpreitzer** [comment]
We added the others.
And this is moot now.
