### ISSUE TITLE
feature: Develop an initial version of  logical cluster provider framework

### ISSUE THREAD

**Issue by ezrasilvera** [kubestellar/kubestellar#526]
Build a logical cluster provider framework that allows arbitrary cluster providers to supply "logical clusters".
In the scope of KubeStellar, KubeStellar should be able to consume and use those logical clusters similar to how it uses KCP's workspaces today. 
The framework should support managing the life cycle of logical clusters but also discover and import capabilities

**Comment by clubanderson** [comment]
provider is under development. Kind is targeted.  KubeFlex may be next to test/dev against
