### ISSUE TITLE
feature: Develop an initial version for a cluster aware go-client client

### ISSUE THREAD

**Issue by ezrasilvera** [kubestellar/kubestellar#527]
The goal is to develop a cluster aware client that will work together with the logical cluster provider framework developed under #526 

- Be able to help connecting to any logical-cluster

**Comment by clubanderson** [comment]
initial version of cluster-aware client is complete. Initial provider is under development (kind). 

Code does not need to be merged - codegen is a different story.  Merge is planned for week of 6/18/23
