### ISSUE TITLE
moving: Moving to GitHub.com/kubestellar/kubestellar

### ISSUE THREAD

**Issue by clubanderson** [kubestellar/kubestellar#539]
Lets write down what we need to care for upon a move to our new repo.

- [x] PROW reconfiguration @clubanderson 
- [x] sonarcube reconfiguration @clubanderson 
- [x] doc reconfiguration @clubanderson (mkdocs update for main and release)
- [x] GH project transfer (kanban stuff) @clubanderson (this can be done in the GH projects settings)
- [x] The entire GH repo can be transferred - this might be the thing that does all the above (except for PROW)

**Comment by clubanderson** [comment]
@francostellari @KPRoche @fileppb

**Comment by francostellari** [comment]
* release transfer
* update bootstrap to point to the new repo for KubeStellar download

**Comment by clubanderson** [comment]
suggested steps to proceed - we will use the GH transfer method.  Which will allow discussions, PRs, issues, projects (kanban), releases, and etc to be migrated all at once.

To prepare for this we can:
1) use the private mirror in kubestellar/kubestellar to create a PR that will get the code/package names, and etc. ready for the transition from kcp-dev/edge-mc to kubestellar/kubestellar.
2) once the PR is reviewed and looks comprehensive enough to complete the task of transition, we re-create the same PR from kubestellar/kubestellar in kcp-dev/edge-mc.
3) Once the PR has been duplicated into edge-mc, we can delete the kubestellar/kubestellar mirror
4) Once the kubestellar/kubestellar mirror is deleted, we can transfer the kcp-dev/edge-mc to kubestellar/kubestellar
5) once transferred, we can approve the PR and test the outcome with the creation of a new release branch and tag

**Comment by clubanderson** [comment]
I test tested GitHub transfer of a fake project from kcp-dev to kubestellar.  PR, Issue, Label, Milestones,Discussions, docs, branch protection, and etc. all transferred successfully, except for projects (kanban).  However, I was able to 'copy' this separately and then remove the original from kcp-dev. 

I am waiting on @xrstf to enumerate the changes for PROW, and @MikeSpreitzer @pdettori @ezrasilvera to PR the changes needed in code.

**Comment by clubanderson** [comment]
I will take care of sonarcube reconfiguration

**Comment by clubanderson** [comment]
reminder, we will be cutting over to the new GH org/repo tomorrow morning (8am ET).  I will be executing the following steps:

0. Delete the private repo kubestellar in the kubestellar GH org.
1. Github transfer initiation - source, PRs, issues, branches, tags, releases, settings, milestones, discussions, docs, and etc will all be transferred to our new home
2. Github project transfer - our GH project (kanban) is transferred separately.
3. Updates to documentation - changes to configuration files to point at the new repo will be made where needed.
4. PROW - I will be working to re-establish PROW configuration by the afternoon or sooner (thats my goal, we will see if it happens)
5. Promote the transition to our slack, linkedin, reddit, and other channels (as well as notify the CNCF.

What do I need from you?  Please prepare your changes in the form of a PR in the current edge-mc repo source code.  @MikeSpreitzer I think that you and @ezrasilvera had this in the private kubestellar/kubestellar repo.  Now is the time to bring it over to edge-mc (if you have not done so already).

**Comment by clubanderson** [comment]
Thank you @MikeSpreitzer https://github.com/kcp-dev/edge-mc/pull/659

**Comment by clubanderson** [comment]
thank you @francostellari https://github.com/kcp-dev/edge-mc/pull/657

we are ready to start first thing in the morning

**Comment by clubanderson** [comment]
and https://github.com/kcp-dev/edge-mc/pull/660 - thank you @francostellari.  @MikeSpreitzer do you need other PRs related to #659 for other branches?

**Comment by clubanderson** [comment]
Completed transition.
