### ISSUE TITLE
feature: add a shell command that waits for the curl of the http server to succeed within some time period

### ISSUE THREAD

**Issue by clubanderson** [kubestellar/kubestellar#553]
### Feature Description

I am frustrated when I get a 'curl(5x)' error when I follow the QS documentation at https://kubestellar.io/quickstart

### Proposed Solution

create a single line command, that works on Mac and linux, that waits for the http pod to be ready before trying to curl the http port for the 'hello world' response.

### Want to contribute?

- [ ] I would like to work on this issue.

### Additional Context

checkout the output from the automated testing of the QS.  It fails on the curl commands - and it should not fail here to ensure a great experience for our users.

https://github.com/kcp-dev/edge-mc/actions/runs/5161593851/jobs/9298703329

**Comment by clubanderson** [comment]
I added this to main

while [[ $(kubectl --context kind-florin get pod commond -n commonstuff -o jsonpath='{.status.phase}') != "Running" ]]; do sleep 5; done;curl http://localhost:8094

while [[ $(kubectl --context kind-guilder get pod commond -n commonstuff -o jsonpath='{.status.phase}') != "Running" ]]; do sleep 5; done;curl http://localhost:8094


appears to work fine - https://github.com/kcp-dev/edge-mc/actions/runs/5163990372

**Comment by clubanderson** [comment]
this command spits out an error each time it fails, before the pod is running.  Maybe we just pipe the stderr>/dev/null ">/dev/null 2>&1" and give a 'waiting' string instead.

error: error executing jsonpath "{.items[0].status.phase}": Error executing template: array index out of bounds: index 0, length 0. Printing more information for debugging the template:
	template was:
		{.items[0].status.phase}
	object given to jsonpath engine was:
		map[string]interface {}{"apiVersion":"v1", "items":[]interface {}{}, "kind":"List", "metadata":map[string]interface {}{"resourceVersion":""}}

**Comment by clubanderson** [comment]
@MikeSpreitzer did you complete this on your recent refactor?

**Comment by MikeSpreitzer** [comment]
@clubanderson : yes, example1 now has waits in two places.  It waits for the "commonstuff" namespace to appear in the florin cluster and it waits for each of the three curl commands to succeed.  This doc is consistently succeeding.
