### ISSUE TITLE
feature: Name of placement translator and mailbox do not have kubestellar in process name, scheduler does

### ISSUE THREAD

**Issue by clubanderson** [kubestellar/kubestellar#554]
### Feature Description

I see processes from kubestellar that are not prefixed with 'kubestellar'

### Proposed Solution

update process names for kubestellar to include 'kubestellar' in their name

### Want to contribute?

- [ ] I would like to work on this issue.

### Additional Context

Output from PS in QS

Finished populate the espw with kubestellar crds and apiexports
 mailbox-controller is running (log file: /home/runner/work/edge-mc/edge-mc/docs/scripts/kubestellar-logs/mailbox-controller-log.txt)
 scheduler is running (log file: /home/runner/work/edge-mc/edge-mc/docs/scripts/kubestellar-logs/kubestellar-scheduler-log.txt)
 placement translator is running (log file: /home/runner/work/edge-mc/edge-mc/docs/scripts/kubestellar-logs/placement-translator-log.txt)

**Comment by MikeSpreitzer** [comment]
This will probably become moot due to #654 or something like it.

**Comment by ezrasilvera** [comment]
Why is this related to decoupling from KCP ?
