### ISSUE TITLE
feature: Stop using KCP's SyncTarget API resource

### ISSUE THREAD

**Issue by ezrasilvera** [kubestellar/kubestellar#559]
A new resources should be defined within KubeStellar repository. We don't want to simply copy this resource from KCP as there are fields we don't need. We also need to define the apigroup for this new resource. 
The work on cluster-aware-client (#527) depends on this as we  want to avoid adding ClientSet for KCP resources

**Comment by clubanderson** [comment]
@fileppb something for you?

**Comment by fileppb** [comment]
I experimented using a Virtualbox VM running Ubuntu. I tried the kubebind mangodb example, using two kind clusters, kubebind-consumer and kubebind-producer and was able to create the apibinding in that example, as seen in the following extract from the kubebind-consumer terminal. I haven't tried to integrate this with KCP yet. 
--------------------------------------------------------------------------
Start a terminal session for the Kubebind Consumer

C:\Users\RobertFilepp\kube-bind>vagrant ssh

vagrant@vagrant:~$ kubectl config use-context kind-kubebind-
consumer
Switched to context "kind-kubebind-consumer".
vagrant@vagrant:~$ cd /vagrant/kube-bind/
vagrant@vagrant:/vagrant/kube-bind$ kubectl apply -f deploy/crd
customresourcedefinition.apiextensions.k8s.io/apiservicebindings.kube-bind.io created
customresourcedefinition.apiextensions.k8s.io/apiserviceexportrequests.kube-bind.io created
customresourcedefinition.apiextensions.k8s.io/apiserviceexports.kube-bind.io created
customresourcedefinition.apiextensions.k8s.io/apiservicenamespaces.kube-bind.io created
customresourcedefinition.apiextensions.k8s.io/apiservices.kube-bind.io created
customresourcedefinition.apiextensions.k8s.io/clusterbindings.kube-bind.io created
vagrant@vagrant:/vagrant/kube-bind$ kubectl apply -f deploy/examples/crd-mangodb.yaml
customresourcedefinition.apiextensions.k8s.io/mangodbs.mangodb.com created

vagrant@vagrant:/vagrant/kube-bind$ export PATH="${PATH}:${HOME}/.krew/bin"
vagrant@vagrant:/vagrant/kube-bind$ kubectl bind http://127.0.0.1:8081/export
DISCLAIMER: This is a prototype. It will change in incompatible ways at any time.


To authenticate, visit in your browser:

        http://127.0.0.1:8081/authorize?c=1GNKq9&p=39343&s=4cgpcyhttp://127.0.0.1:8081/authorize?c=1GNKq9&p=39343&s=4cgpcy

🔑 Successfully authenticated to http://127.0.0.1:8081/export
🔒 Created secret kube-bind/kubeconfig-gg4th for host https://127.0.0.1:34867, namespace kube-bind-wmkmj
🚀 Executing: kubectl bind apiservice --remote-kubeconfig-namespace kube-bind --remote-kubeconfig-name kubeconfig-gg4th -f -
✨ Use "-o yaml" and "--dry-run" to get the APIServiceExportRequest and pass it to "kubectl bind apiservice" directly. Great for automation.
🚀 Deploying konnector v0.3.0 to namespace kube-bind.
✅ Created APIServiceBinding mangodbs.mangodb.com

NAME                                                  PROVIDER   READY   MESSAGE   AGE
apiservicebinding.kube-bind.io/mangodbs.mangodb.com
     False   Pending   0s

vagrant@vagrant:/vagrant/kube-bind$ kubectl get namespaces
NAME                 STATUS   AGE
default              Active   8h
kube-bind            Active   2m50s
kube-node-lease      Active   8h
kube-public          Active   8h
kube-system          Active   8h
local-path-storage   Active   8h


vagrant@vagrant:/vagrant/kube-bind$ kubectl get APIServiceBi
ndings
NAME                   PROVIDER   READY   MESSAGE   AGE
mangodbs.mangodb.com              True              94s

vagrant@vagrant:/vagrant/kube-bind$ kubectl describe APIServ
iceBinding mangodbs.mangodb.com
Name:         mangodbs.mangodb.com
Namespace:
Labels:       <none>
Annotations:  <none>
API Version:  kube-bind.io/v1alpha1
Kind:         APIServiceBinding
Metadata:
  Creation Timestamp:  2023-05-31T17:53:37Z
  Generation:          1
  Managed Fields:
    API Version:  kube-bind.io/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:spec:
        .:
        f:kubeconfigSecretRef:
          .:
          f:key:
          f:name:
          f:namespace:
    Manager:      kubectl-bind
    Operation:    Update
    Time:         2023-05-31T17:53:37Z
    API Version:  kube-bind.io/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
    Manager:      kubectl-bind
    Operation:    Update
    Subresource:  status
    Time:         2023-05-31T17:53:37Z
    API Version:  kube-bind.io/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
    Manager:         konnector
    Operation:       Update
    Subresource:     status
    Time:            2023-05-31T17:53:55Z
  Resource Version:  37264
  UID:               933f140a-4958-46f3-b1ae-70d2e38cb9e6
Spec:
  Kubeconfig Secret Ref:
    Key:        kubeconfig
    Name:       kubeconfig-gg4th
    Namespace:  kube-bind
Status:
  Conditions:
    Last Transition Time:  2023-05-31T17:53:55Z
    Status:                True
    Type:                  Ready
    Last Transition Time:  2023-05-31T17:53:55Z
    Status:                True
    Type:                  SecretValid
Events:                    <none>
vagrant@vagrant:/vagrant/kube-bind$ kubectl config current-c
ontext
kind-kubebind-consumer

**Comment by fileppb** [comment]
As per the discussion we had this morning in our 9am scrum, it was agreed that removing the dependency on the kcp SyncTarget would be done in a few phases. The first phase would be to copy the SyncTarget from kcp into kubestellar and adjust the imports. It remains to be seen whether the SyncTarget is dependent upon other kcp resources. Future phases would include re-writing and trimming the SyncTarget object, and providing for more complex relationships of SyncTargets and locations than the current 1:1 relationship. @ezrasilvera @MikeSpreitzer @clubanderson, please correct me if I'm mistaken.

**Comment by clubanderson** [comment]
progress is being made, @fileppb needs some help on GO.

**Comment by fileppb** [comment]
Made changes to create the SyncTarget api resource in Kubestellar using edge-mc main and kcp release 0.11. Now in process of replacing the references to the kcp api with references to the new kubestellar api.
