### ISSUE TITLE
feature: Stop using KCP's Location API resource

### ISSUE THREAD

**Issue by ezrasilvera** [kubestellar/kubestellar#560]
A new resources should be defined within KubeStellar repository. We don't want to simply copy this resource from KCP as there are fields we don't need. We also need to define the apigroup for this new resource. 
The work on cluster-aware-client (#527) depends on this as we  want to avoid adding ClientSet for KCP resources

This issue can be done together with  with #559

**Comment by clubanderson** [comment]
@fileppb something for you?
