### ISSUE TITLE
feature: ArgoCD - phase 2 - KubeStellar enables ArgoCD deployment architectures

### ISSUE THREAD

**Issue by clubanderson** [kubestellar/kubestellar#605]
### Feature Description

ArgoCD does not have to take on the role of orchestration engine AND configuration deployment/config/status collector.  Why not use KubeStellar for the latter.

### Proposed Solution

Lets attend the ArgoCD community calls and propose KubeStellar as a key integration point for ArgoCD and work towards a proposed use-model for users of ArgoCD in complex multicluster distribution use-cases.

### Success Criteria
- [ ] reference architecture (image in the form of jpg/png)
- [ ] tutorial that shows how to use ArgoCD and KubeStellar for a continuous deployment scenario
- [ ] use this material in a conference with an ArgoCD member co-presenting

### gaps
- [ ] #703 covered in 772
- [x] #772 mandatory
- [ ] #567 optional
- [x] #886 
- [x] #884 needed before 772 is completed

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by waltforme** [comment]
Watched Nicholas Morey's talk on Argo CD Multi-Cluster Architectures: https://www.youtube.com/watch?v=6Pqbks-SZfE. Put the link here for revisiting later.

**Comment by waltforme** [comment]
KubeCon EU '23 talk on Argo CD core: https://www.youtube.com/watch?v=nXEb1yZ580E
KubeCon NA '21 talk on Argo CD ApplicationSet: https://www.youtube.com/watch?v=GcvHKc2IHi8

**Comment by clubanderson** [comment]
#567 #703 #772 have been identified as required for this issue to complete.

**Comment by clubanderson** [comment]
I have added the issues to the roadmap

**Comment by waltforme** [comment]
Added a [reference architecture](https://docs.google.com/presentation/d/16ZYx3BQQk2-HzSuHrh0gCsho2D5eruBmqW9fwEFItj0/edit#slide=id.g296c1995688_1_75) for Argo CD + KubeStellar multi-cluster into the KubeStellar shared Google Drive folder.

**Comment by waltforme** [comment]
@clubanderson Just wanted to confirm that you to got the reference arch posted above last week.

**Comment by clubanderson** [comment]
@clubanderson to attend Argo community meeting
