### ISSUE TITLE
Demo: logical clusters

### ISSUE THREAD

**Issue by ezrasilvera** [kubestellar/kubestellar#615]
### Goal
This issue is used to track the tasks needed for an initial demo for the logical cluster provider framework and the cluster aware client.

**Comment by clubanderson** [comment]
@pdettori do you want to follow this work to see how kflex can become a client some day?

**Comment by ezrasilvera** [comment]
Demo completed. Demo auto script can be found here 
https://github.com/kubestellar/kubestellar/blob/main/cmd/mc-client-test/lcdemo.sh
