### ISSUE TITLE
feature: addition of a KubeStellar-controller-manager to run all processes required to run KubeStellar

### ISSUE THREAD

**Issue by clubanderson** [kubestellar/kubestellar#654]
### Feature Description

I am frustrated when I have to run multiple processes in different windows to run KubeStellar.

### Proposed Solution

I want a single controller-manager to run all the processes necessary for KubeStellar

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by clubanderson** [comment]
queued up for discussion here.  The multiple commands and 'sleeps' needed for our demo should be removed and replaced with something that is KubeStellar consolidated into 1 command or controller-manager

**Comment by MikeSpreitzer** [comment]
We have several choices for how we group things.
- One process can run multiple controllers.
- One container can run multiple processes.
- One k8s Pod can run multiple containers.
- One k8s cluster can run multiple Pods.

To inform my recommendation on which approach to pursue, I want a better sense of how we plan to scale out.

**Comment by clubanderson** [comment]
Closing this as cared for as part of helm effort
