### ISSUE TITLE
Try kube-bind + kubeflex

### ISSUE THREAD

**Issue by waltforme** [kubestellar/kubestellar#656]
If we want to support kubeflex as one of the logical cluster providers, we may need kubeflex to be able to work together with kube-bind.

Let's try to use kubeflux's controlplanes/apiservers as kube-bind's providers and consumers.

**Comment by pdettori** [comment]
This sounds like an interesting experiment. We can look at what does it take to run the Konnector controller on the consumer API Server side and what does it take on the provider.

**Comment by clubanderson** [comment]
are we looking to complete this by August 1st?  @pdettori @waltforme ?

**Comment by waltforme** [comment]
Yes let me try to do this by August 1st @clubanderson .

**Comment by waltforme** [comment]
I tried two types of KubeFlex controlplanes (CPs).

## Type 'k8s'
Kube-bind needs its agent 'konnector' to be running as a deployment in each consumer cluster. Right now we can't run pods directly in a k8s type controlplane. There is extra work (1/3) to be done to address this.

## Type 'vcluster'
I tried two scenarios for type 'vcluster'.
### Scenario 1
A CP as the consumer, a regular k8s cluster on AWS as the provider.

This scenario works without any issue. The konnector runs inside the CP as a deployment.

### Scenario 2
One CP as the consumer, another CP as the provider.

To make it work, I ran the konnector as a local process.
<img width="1329" alt="image" src="https://github.com/kubestellar/kubestellar/assets/8633434/3d89665e-5ec3-41f0-a3ac-336b07db899f">

When run as pods, the konnector couldn't reach the provider.

It turns out the apisever of a vcluster control plane is exposed by a service `vcluster`. But `vcluster` lives in the host cluster (`--context kind-kubeflex`):
```console
👉 Downloads $ kc --context kind-kubeflex -n provider-system get svc vcluster -oyaml | yq
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: vcluster
    meta.helm.sh/release-namespace: provider-system
  creationTimestamp: "2023-07-27T16:22:22Z"
  labels:
    app: vcluster
    app.kubernetes.io/managed-by: Helm
    chart: vcluster-0.15.2
    heritage: Helm
    release: vcluster
  name: vcluster
  namespace: provider-system
  resourceVersion: "790"
  uid: 9f97b7d7-4742-4268-acea-f99df1adfe01
spec:
  clusterIP: 10.96.12.193
  clusterIPs:
    - 10.96.12.193
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8443
    - name: kubelet
      port: 10250
      protocol: TCP
      targetPort: 8443
  selector:
    app: vcluster
    release: vcluster
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```
I tried this service but it seems that this service is not addressable from inside a CP. We need to do some work (2/3) figure this out.

Also, the kubeconfig for the konnector is generated on the fly upon binding, by the example-backend code. After we figured the networking between the consumer CP and the provider CP, how do we make the example-backend aware of such network settings and generate a working kubeconfig? This is another piece of work to be done (3/3).

**Comment by clubanderson** [comment]
This issue looks to be dependent on information/discussion with @pdettori at KubeFlex.  Pushing to Sprint 4 when Paolo returns.

**Comment by clubanderson** [comment]
@pdettori can you comment here on continuing or closing this effort?

**Comment by clubanderson** [comment]
@pdettori do we continue here or close this?

**Comment by ezrasilvera** [comment]
@waltforme So if we run both backend and kconnector as processes inside the kubeflex pod/container this should work ?

**Comment by waltforme** [comment]
@ezrasilvera I tried to reorg the comments [above](https://github.com/kubestellar/kubestellar/issues/656#issuecomment-1659267307) trying to make it less messy. So I guess what you described is the 2a scenario, where the konnector coundn't reach the provider.

**Comment by clubanderson** [comment]
@waltforme is this issue still necessary?  Or is this now covered by kcp-decoup?

**Comment by clubanderson** [comment]
closed per @waltforme
