### ISSUE TITLE
bug: PT logs spurious errors wrt unused resources in mailbox workspaces

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#671]
### Describe the bug

The placement translator spams its log with entries like the following.

```
W0623 14:12:51.408739   73139 reflector.go:376] k8s.io/client-go@v0.0.0-20230210192259-aaa28aa88b2d/tools/cache/reflector.go:215: failed to list batch/v1, Resource=jobs: the server could not find the requested resource
E0623 14:12:51.408766   73139 reflector.go:138] k8s.io/client-go@v0.0.0-20230210192259-aaa28aa88b2d/tools/cache/reflector.go:215: Failed to watch batch/v1, Resource=jobs: failed to list batch/v1, Resource=jobs: the server could not find the requested resource
```

The corresponding request was as follows.

```
I0623 14:12:51.407355   73139 round_trippers.go:463] GET https://192.168.58.124:6443/clusters/322w5fjq8cm0umxz/apis/batch/v1/jobs?labelSelector=edge.kcp.io%2Fprojected%3Dyes&limit=500&resourceVersion=0
```

The cluster involved is one of the mailbox workspaces.  It has no Job objects.  In fact, it does not even have an APIBinding that defines `jobs`.  The PT currently relies on the EdgePlacement to say which APIBinding objects to propagate, and the EdgePlacement in question does not list all of the kube APIBindings.

### Steps To Reproduce

See above.

### Expected Behavior

No continual spam of error messages under normal circumstances.

**Comment by MikeSpreitzer** [comment]
Here is how this is happening.  For downsynced namespaced resources, the placement translator characterizes the resolved "what" as the cross product of (selected namespaces) X (all the namespaced resources in the relevant workspace).  For every mailbox workspace, the PT maintains informers on all the namespaced resources from the (resolved "where", resolved "what") bindings, so that the PT can delete objects that it put there previously but no longer wants there.  This set of informers is more than needed because not every namespaced resource defined in a WMW is even defined in a given MBW.

**Comment by MikeSpreitzer** [comment]
I suspect this may be giving the edge syncer indigestion too, because the placement translator is also putting the same cross product in the SyncerConfig.

@yana1205

**Comment by MikeSpreitzer** [comment]
Following are few approaches to doing better.

1. Make the part of the placement translator that resolves the "what" predicates look for actual existing objects and only put their kinds (resources) in the cross product.
2. Make the placement translator aware of how resources are defined --- and there are three ways: CustomResourceDefinition, APIBinding, and being built into the workspace --- and monitor and interpret those, filtering the cross products to only include resources defined in the mailbox workspace.
3. Make the placement translator directly monitor (using pkg/apiwatch) the resources defined in each mailbox workspace and only include those in the cross products.

**Comment by clubanderson** [comment]
ii. looks like a good option to me.

**Comment by clubanderson** [comment]
Mike will review run-time costs between ii. and iii.

**Comment by MikeSpreitzer** [comment]
Approach 3 will add more runtime costs.  But it will be a smaller development effort, which I think is the higher priority concern right now.  So I currently favor approach 3.

**Comment by MikeSpreitzer** [comment]
@yana1205 : does the edge syncer also have this problem?

If the edge syncer also has this problem then I think we should look at injecting the filtering upstream of both the SyncerConfig generation and the monitoring of projected objects.

**Comment by yana1205** [comment]
@MikeSpreitzer 
Yes. Edge syncer should also print error logs when getting objects from downstream/upstream that are written in SyncerConfig but are not defined in API Resource in the edge cluster/mailbox workspace.

When this happens, Syncer catches the error from k8s client-go, dumps the error as log, skips syncing the erroneous resources, and continues syncing the next candidate resources. This kind of error handling continues to happen every iteration of syncing until the resource is defined.

> injecting the filtering upstream of both the SyncerConfig generation and the monitoring of projected objects.

PT will detect unready resources and filter them out at generating SyncerConfig. It would be helpful for Syncer to reduce the above error handling. Though, I'm not sure how it's easy to detect such resources.

**Comment by MikeSpreitzer** [comment]
#884 greatly mitigated this problem, at least for the example and test usage.  That PR changed the placement translator to focus only on resources (kinds of objects) that the user explicitly asked to downsync, rather than all the the resources defined in the WDS.  This focus includes what is put into the SyncerConfig, so it mitigates what happens to the syncer too.
