### ISSUE TITLE
bug: commingled logs painful in example1

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#686]
### Describe the bug

Currently someone running example1 gets all the controller logs mixed together on the terminal.  This is messy, and difficult to debug when something goes wrong.  #671 makes this particularly bad.

### Steps To Reproduce

Try it.

### Expected Behavior

The user's terminal does not get spammed with an endless stream of messages.

Sending controller-specific logs to controller-specific files under `/tmp` would work fine here.

**Comment by clubanderson** [comment]
we can remove xtrace again if you like.  please advise

**Comment by MikeSpreitzer** [comment]
When it comes time to debug, the xtracing is hugely helpful.
It is not bad for ordinary users in the happy case, makes it easier for them to understand what is happening.

**Comment by clubanderson** [comment]
logs are less now - removed xtrace from pre-processing and turned on in generated script.  If we get in a jam in the future, we can re-open and turn the xtrace back on for pre-processing.
