### ISSUE TITLE
bug: Unnecesary repo renaming in example1

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#687]
### Describe the bug

example1 renames the repo in the `git clone` command.  That is unusual, and does not really help anything in this case, so should be shaved off.

### Steps To Reproduce

read the doc

### Expected Behavior

Doing things the usual way when that works for us.

**Comment by clubanderson** [comment]
update all docs in main and both releases to remove renaming and updated 'cd' commands to reflect lowercase
