### ISSUE TITLE
bug: pre-req checking in example1 accepts go 1.20

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#689]
### Describe the bug

The latest version of `go` is 1.20 and that is what I normally have on my `$PATH`.  I tried to doc-execute example1 and it failed because the pre-req check was satisfied regardless of the _version_ of `go` but later `hack/verify-go-versions.sh` crashed out.

### Steps To Reproduce

See above.

### Expected Behavior

I expected the checking up front to be where problems are uncovered.

**Comment by clubanderson** [comment]
against 0.3 and main

**Comment by KPRoche** [comment]
This is likely going to interlock with the docs common-subs file problem in issue #700
