### ISSUE TITLE
bug: "schduler" is the wrong name

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#690]
### Describe the bug

Using the word "scheduler" for the controller that resolves "where predicates" to SinglePlacementSlice object collections is confusing because we are partnering with other projects that also have something they call "scheduling" and is more deserving of the name.  The KubeStellar thing should be called something like "where resolver".

### Steps To Reproduce

See above.

### Expected Behavior

No arguments over which project is doing scheduling.

**Comment by clubanderson** [comment]
vote of community yielded majority in favor of "where resolver"
