### ISSUE TITLE
bug: "get KubeStellar" misplaced in example1 and other documents

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#692]
### Describe the bug

https://docs.kubestellar.io/release-0.3/Coding%20Milestones/PoC2023q1/example1/#get-kubestellar describes "getting" KubeStellar.  But there is another instance of "getting" KubeStellar buried earlier under the "Start kcp" heading --- and that is the one that is actually executed!

### Steps To Reproduce

RTFM

### Expected Behavior

I expect only one section describing getting KubeStellar, and I expect it to not be buried under "Start kcp".

### Additional Context

Present in release-0.2 and later.

**Comment by clubanderson** [comment]
@amanroa can you PR a change that changes the order of the paragraph to match the order of the commands that run?  Needs to be PR'ed in release-0.2, 0.3 and main branches.  3 PRs total.

**Comment by amanroa** [comment]
The PR for main was approved, I just made the PRs for release-0.2 and 0.3: #758 #759

**Comment by clubanderson** [comment]
fixed - closing
