### ISSUE TITLE
bug: unversioned references from exe-docs to git repo

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#693]
### Describe the bug

For example, in release-0.2 we see https://github.com/kubestellar/kubestellar/blob/a05e6f20bdac2366c3aae8d1f9c915cb25180f87/docs/content/Coding%20Milestones/PoC2023q1/example1-subs/example1-start-kcp.md?plain=1#L20 , which does a `git clone` of the repo without specifying a branch --- and nothing later does a `git checkout` of the `release-0.2` branch.

This problem is in several docs in both release branches.

### Steps To Reproduce

RTFM

### Expected Behavior

An executable thing in a release should invoke stuff in that release.

**Comment by MikeSpreitzer** [comment]
BTW, I think it would help if these docs included usage of the `kubestellar-release` command (https://docs.kubestellar.io/main/Coding%20Milestones/PoC2023q1/commands/#kubestellar-release) to show the release that is actually being used.

**Comment by clubanderson** [comment]
fixed in all branches - "-b {{ config.ks_branch }}"
