### ISSUE TITLE
bug: v0.3.0 prep_for_syncer refs v0.2.1 syncer image

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#694]
### Describe the bug

https://github.com/kubestellar/kubestellar/blob/v0.3.0/scripts/kubectl-kubestellar-prep_for_syncer#L37

### Steps To Reproduce

See above

### Expected Behavior

The latest release should reference the latest syncer image.

**Comment by clubanderson** [comment]
@yana1205 please PR against release-0.3 only - Thank you

**Comment by clubanderson** [comment]
ahh - good point @MikeSpreitzer - yes we do
