### ISSUE TITLE
Prereq Install code for RHEL does not check for system architecture

### ISSUE THREAD

**Issue by KPRoche** [kubestellar/kubestellar#700]
### Describe the bug

The code for RHEL in docs/content/common-subs/required-packages.md presumes amd64 architecture for installing kind and kubectl. 
The commands will fail on an ARM (aarch64) system.
Specifically, the curl commands on lines 51 and 54 specifically download amd64 architecture versions.

 
![kubestellar_prereqs_code](https://github.com/kubestellar/kubestellar/assets/25445603/4750e018-9f96-43a6-90af-a3d9102bffb9)

### Steps To Reproduce

1. Go to https://docs.kubestellar.io/release-0.3/Getting-Started/quickstart/ on a browser on an aarch64 Linux system (like a Raspberry Pi)
2. Copy the command for installing kind
 `curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.14.0/kind-linux-amd64 && chmod +x ./kind && mv ./kind /usr/local/bin`
3. Paste it into a terminal window on a the aarch64 machine (like a Raspberry Pi) and hit enter; the command will execute
4. enter a kind command. The system will respond with
`bash: /usr/local/bin/kind: cannot execute binary file: Exec format error`

### Expected Behavior

The code for other operating systems reads the system architecture value and inserts that tag into the commands; the same should be done for RHEL.

**Comment by KPRoche** [comment]
The install page for kind has this code snippet on it: 

```
# For AMD64 / x86_64
[ $(uname -m) = x86_64 ] && curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64

# For ARM64
[ $(uname -m) = aarch64 ] && curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-arm64
chmod +x ./kind
sudo mv ./kind /usr/local/bin/kind
```

That should successfully install kind 0.20.0 on a Raspberry Pi running RHEL. 
Is kind version 0.14.0 specifically needed for the quickstart example to run?

**Comment by dumb0002** [comment]
@MikeSpreitzer, the release page for kind shows the default Kubernetes version for each release: https://github.com/kubernetes-sigs/kind/releases

**Comment by KPRoche** [comment]
OK, I have figured out the proper bash commands for the kind and kubectl installs and am testing the md files now.

**Comment by KPRoche** [comment]
Closing after PR 766 went through.
