### ISSUE TITLE
feature: wrapped objects in mailbox namespaces

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#706]
### Feature Description

Rather than mailbox workspaces (or whatever we are going to call the abstraction, #552) we could use wrapped objects in mailbox namespaces in one workspace/cluster.  This would remove the only place where the KubeStellar platform makes multiple workspaces for its own usage.  This is also the place where we expect the highest number of workspaces, most stressing scalability of the provider of those.  Switching the mailbox namespaces thus gets us an efficient solution without a Kubernetes fork.

### Proposed Solution

See above.

### Want to contribute?

- [ ] I would like to work on this issue.

### Additional Context

#595

**Comment by ezrasilvera** [comment]
@MikeSpreitzer just to clarify - so the syncer will unwarp downsynced object and wrap the upsync objects ?

**Comment by MikeSpreitzer** [comment]
@ezrasilvera : yes.  In particular, I think that a likely approach is to use OCM's ManifestWork and klusterlet.

**Comment by clubanderson** [comment]
We did not talk about this yes, but it's certainly not happening by next Tuesday.  Moving out by 1 sprint.

**Comment by pdettori** [comment]
how an architecture that combines OCM Manifest work & Kubelet with KubeStellar would look like? I am very interested in this topic.

**Comment by nirrozenbaum** [comment]
this was implemented as part of the transport code that was written based on KubeStellar 0.15.
since Kubestellar is transitioning to ks-0.20, a new issue was created to reflect the required changes to the existing transport code.
this issue can be closed as completed.
