### ISSUE TITLE
bug: Instructions for installing mkdocs need better clarity

### ISSUE THREAD

**Issue by KPRoche** [kubestellar/kubestellar#717]
### Describe the bug

The overview of the MKdocs as described fails to mention multiple required plugins, and the list of used plugins is scattered through the document. (notably, include-markdown is first mentioned well AFTER the overview)
The suggestion to use pip install -r requirements.txt is buried well down in the text
(in kubestellar/kubestellar/docs/README.md)

### Steps To Reproduce

1. Attempt to follow the overview description to install mkdocs on your machine.
2. change to the kubestellar/docs folder and run **mkdocs server**
3. Read the error message for plugins not found
4. find the missing plugin and install
5. Rinse and repeat until no more missing plugins message
6. apparently the i18n plugin doesn't exist for Fedora? "ERROR: No matching distribution found for mkdocs-i18n"

* notice the **pip install -r requirements.txt** command much later

### Expected Behavior

Either the instructions to install mkdocs locally via `pip install -r requirements.txt` 
should be ABOVE all the explanation about file structure, etc., 
or there should be a LINK in the overview "you can install and run mkdocs on local copies of the files" (perhaps a better solution)

**Comment by clubanderson** [comment]
Great observation. I'm happy to fix it. Thank you.
