### ISSUE TITLE
bug: mkdocs complains about a lot of broken links

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#726]
### Describe the bug

Running `cd docs; mkdocs serve` produces a lot of warning messages about broken links.  I suspect there are not really broken links, I suspect that the thing producing the warnings has gotten confused by the path of relative includes.

[mkdocs-fail.log](https://github.com/kubestellar/kubestellar/files/11932246/mkdocs-fail.log)

### Steps To Reproduce

1. git checkout main
2. cd docs
3. mkdocs serve

### Expected Behavior

No complaints based on confusion in the checker.

**Comment by MikeSpreitzer** [comment]
@clubanderson

**Comment by clubanderson** [comment]
This is normal behavior based on the plugins in use.
