### ISSUE TITLE
bug: editing for execution made inconsistencies

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#728]
### Describe the bug

In at least the example1 document, the editing to make it executable introduced some inconsistencies with the text that was there previously and remains.

In the section on starting kcp, the following picture highlights some inconsistencies.

<img width="824" alt="Screen Shot 2023-07-03 at 12 57 43 AM" src="https://github.com/kubestellar/kubestellar/assets/14296719/f1d67e0f-bdef-4665-a6a3-3fa2c0ae5c7b">

For example, in the latest content, one shell is used _both_ for running kcp and for everything else, contrary to the text that tells the reader to dedicate one shell to running kcp.

In the section on running the mailbox controller, the following picture highlights some inconsistencies.

<img width="822" alt="Screen Shot 2023-07-03 at 1 13 14 AM" src="https://github.com/kubestellar/kubestellar/assets/14296719/8dab5422-1833-4839-91f1-4a9fb101d495">

Now that the controller is in the background, it makes no sense to tell the reader to ^C it.

There are others.  Somebody needs to just read the rendered doc and pay attention to what it is saying.

### Steps To Reproduce

See above.

### Expected Behavior

The docs should not contradict themselves.

**Comment by clubanderson** [comment]
@amanroa can you fix this for us?  Thank you.

fyi @waltforme

**Comment by MikeSpreitzer** [comment]
BTW, for the sake of being user-facing documentation, I think that the option to install kcp from downloaded binaries rather than build from downloaded source should be retained.  In fact, I think the former has fewer dependencies and should be preferred for that reason.

**Comment by clubanderson** [comment]
I put the 'git clone' and 'cd kubestellar' before the 'make build' on example and syncer docs - they work properly now.   Let's leave it like this for now.  We have bigger fish to fry
