### ISSUE TITLE
bug: Inconsistent navigation links in readme and other docs

### ISSUE THREAD

**Issue by KPRoche** [kubestellar/kubestellar#735]
### Describe the bug

In several places, the documentation has hard-coded links to kubestellar.io rather than using relative links based on the info in mkdocs.yml.

This means that if you are working on docs and serving them locally to review your work, and you click on one of those hard-coded links, your browser will divert to the main documents and you will no longer be navigating your modified files.

### Steps To Reproduce

1. Follow the instructions to set up mkdocs and start the local server;
2. modify one of the doc files (say quickstart.md) in your local clone
3. open a browser and navigate to localhost:8000 to view the docs locally
4. Click on Getting Started in the masthead menu. It will _correctly_ go to your modified file and display it
5. Click on Home in the masthead. it will return to the local homepage
6. Click on "**multi-cluster down-syncing**" or "**Try our QuickStart**" links in the displayed overview
7. **_You will be sent to the master site at kubestellar.io_**

### Expected Behavior

Links in the KubeStellar docs _which go to other portions of those docs_ should be internally consistent and stay on the document server where browsing was started.

### Additional Context

This problem is observable in several of the docs files; I have had bandwidth to enumerate all the problematic links.

**Comment by clubanderson** [comment]
fixed, please test again.
