### ISSUE TITLE
What are the git fetches doing in the github workflows?

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#739]
An example is the two steps at https://github.com/kubestellar/kubestellar/blob/23fa65339793d9c9d0be077a8bbaf521f4566add/.github/workflows/docs-ecutable-example1.yml#L54-L62 that do `git fetch`.  Remember that a `git fetch` does not affect the working copy, it is not the same thing as a `git checkout`.  Note also that those `git fetch` steps are preceded by a `uses: actions/checkout@v3.5.3` --- which _does_ do the proper `git checkout` (look in the log of running one of these workflows).

**Comment by MikeSpreitzer** [comment]
I have demonstrated in the `trim-workflows` branch of my fork (e.g., https://github.com/MikeSpreitzer/kcp-edge-mc/blob/trim-workflows/.github/workflows/docs-ecutable-example1.yml) that those fetch job steps can simply be deleted.

**Comment by clubanderson** [comment]
@MikeSpreitzer did you test with push, pull, and workflow runs?

**Comment by clubanderson** [comment]
#742 is caring for this
