### ISSUE TITLE
bug: explicit token in workflows fails for plebeians

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#742]
### Describe the bug

When I try docs-ecutable GitHub actions on my fork, they fail with a complaint due to lines like https://github.com/kubestellar/kubestellar/blob/23fa65339793d9c9d0be077a8bbaf521f4566add/.github/workflows/docs-ecutable-example1.yml#L51

I find that I can simply delete those lines, and then I can run those GitHub actions on my fork.

### Steps To Reproduce

See above

### Expected Behavior

Ordinary contributors can run the CI tests.

**Comment by MikeSpreitzer** [comment]
See successful tests of docs-ecutable actions in my fork on https://github.com/MikeSpreitzer/kcp-edge-mc/tree/trim-workflows/.github/workflows

**Comment by clubanderson** [comment]
We explicitly do not allow our actions to execute in remote forks to prevent the exposure of our gh secret. If we allowed this, then we expose our repo to manipulation by bad actors. We are explicitly guarding against this

**Comment by clubanderson** [comment]
What is a plebian?

**Comment by MikeSpreitzer** [comment]
Sorry, typo; I meant plebeian.

**Comment by MikeSpreitzer** [comment]
Does the mere attempt to run a workflow expose the token, or does the successful running of yesterday's workflows pre-req exposing the token?

**Comment by MikeSpreitzer** [comment]
I am able to run the trimmed workflows in my fork without doing anything about any GitHub secret.

**Comment by MikeSpreitzer** [comment]
If your concern is https://github.com/kubestellar/kubestellar/settings/secrets/actions : what I am saying is that for the docs-ecutable actions at least, the workflows have been failing in my fork because of a reference to one of those secrets BUT that reference is not needed --- when I delete that reference, not only is the secret not exposed but the workflow succeeds too!

**Comment by clubanderson** [comment]
Ahh, ok. So it is not needed. That's a great find. I have changed this function over time and was not sure if it was still needed. Thanks for experimenting and finding this. It is a relief to know if can be removed from the doc-specific actions. I'll check it out and make the fix. Thank you.

**Comment by clubanderson** [comment]
I am going to remove these lines for push, pull, and pull_target_request.  leaving it in there for workflow_run for now.  Will also remove 'ok-to-test' label requirement for push, pull, and pull_target_request also.

**Comment by clubanderson** [comment]
all docs-ecutable workflows updated in all 3 branches.  Please have a test and re-open if there is an issue.
