### ISSUE TITLE
bug:  Functions `kcp_get_latest_version` and `kubestellar_get_latest_version` in `bootstrap-kubestellar.sh` do not work anymore

### ISSUE THREAD

**Issue by francostellari** [kubestellar/kubestellar#760]
### Describe the bug

Due to same change in GitHub pages, the two functions fail

### Steps To Reproduce

`curl -sL https://github.com/kubestellar/kubestellar/releases/latest | grep "</h1>" | head -n 1 | sed -e 's/<[^>]*>//g' | xargs`

returns garbage instead of `v0.3.1`

### Expected Behavior

`v0.3.1`

### Additional Context

Fix it by changing `head -n 1` to `tail -n 1`

**Comment by francostellari** [comment]
@dumb0002 this is fixed by pull req. #761

**Comment by clubanderson** [comment]
fixed - Thank you @francostellari
