### ISSUE TITLE
bug: Mismatch between release, tag, and quickstart

### ISSUE THREAD

**Issue by francostellari** [kubestellar/kubestellar#762]
### Describe the bug

Binary release [v0.3.1](https://github.com/kubestellar/kubestellar/releases/tag/v0.3.1) is out but there is no `release-0.3.1` tag and the [QuickStart](https://docs.kubestellar.io/release-0.3/Getting-Started/quickstart/) is still pointing users to `v0.3.0`.

### Steps To Reproduce

See above

### Expected Behavior

At minimum tag releases and binary release should always have a match.
QuickStart should point to the latest known good release to avoid having uses using old code.

**Comment by MikeSpreitzer** [comment]
The tag is `v0.3.1`, that is the usual pattern.

**Comment by MikeSpreitzer** [comment]
The attached screenshot does not show an archive for linux/s390x, unless I misunderstand something.

<img width="1010" alt="Screen Shot 2023-07-06 at 2 11 51 PM" src="https://github.com/kubestellar/kubestellar/assets/14296719/26241581-cd39-40d8-b03d-3fbfed65897b">

**Comment by francostellari** [comment]
@MikeSpreitzer there is no corresponding tag `release-0.31` or `release-0.3.1`... therefore the QuickStart is still pointing to v0.3.0
![image](https://github.com/kubestellar/kubestellar/assets/50019234/f311718f-0634-46cf-a144-07967b2d0e3a)
![image](https://github.com/kubestellar/kubestellar/assets/50019234/b02fe50a-dba0-40d5-a380-c58abbc70ad5)

**Comment by clubanderson** [comment]
please refer to #732

**Comment by clubanderson** [comment]
fixed - please retest
