### ISSUE TITLE
Special case for binding to exactly one workload execution cluster

### ISSUE THREAD

**Issue by clubanderson** [kubestellar/kubestellar#772]
### Discussed in https://github.com/kubestellar/kubestellar/discussions/703

<div type='discussions-op-text'>

<sup>Originally posted by **MikeSpreitzer** June 28, 2023</sup>
While an EdgePlacement generally binds to an arbitrary number of workload execution clusters, there is a significant body of usage in which that number is intended to be exactly 1.  In this case there is no summarization problem; the source object's status section is properly designed to handle this case and arguably the reported state should propagate back to there.</div>

**Comment by clubanderson** [comment]
pending #884

**Comment by ezrasilvera** [comment]
@MikeSpreitzer I think we need to have a common design for any N. For example we can have the sumerizer configurable so it can just copy the full copy of the statuses into the summery object if the user choose to. It will be up to the user to decide if the number of WECs is too large so a real summary function need to be apply or that it's good enough to embed the full status of all related resources. 
In the above approach the case of single WEC deployment will be just a private case of "embed the full statuses of objects across all WECs" 
There are two advantages here:
1. Users get the status on the same space no matter what's the number of deployed WECs (don't need to go to MB spaces)
2. Users get the status from the same "Summery" object , whether it's embedding a direct copy of the statuses or the result of a summery operation. 
I don't see any special case with the number "1" for deployed  WEC

**Comment by MikeSpreitzer** [comment]
I have been talking about a common design for any N, that is summarization.  I have been taking the approach that summarization should be programmable.  See #567 for my current proposal.  I think you could reasonably ask that the user be able to request a very simple form of summarization: a list of complete copies of the object in question.  As we discussed earlier, this impractical for large N, and we would point that out to users.

N=1 is special because the Kubernetes community has a standard way to represent the status from N=1 executing copy and it is so commonly expected that many people do not even think of the possibility of N other than 1.

**Comment by ezrasilvera** [comment]
I think we are a special case. The whole purpose of KS is to transparently do CM over multiple WECs.  We can dictate the user that for KS you deploy an object X and you get the status in a different object (as a vector or outcome of summarization operation). 
I think we will get many many cases in which during normal operation N will increase from 1 to a larger (very small number) , especially when WECs are scarce.  It will be pity if users that just add another WEC suddenly need to change their code that process their status as it now passed in a completely different way.

**Comment by MikeSpreitzer** [comment]
We have strong requests from users who have use cases where they know that the number of executing copies should be exactly 1.  Other users would indeed be well advised, as you said, to ask for a summarization that makes sense for any N.

**Comment by waltforme** [comment]
OK. I believe it is tracked by #605 as well.

> @waltforme ball is in your court for next rev of ArgoCD solution architecture featuring KubeStellar.
