### ISSUE TITLE
Feature: Add Auth and user access management to the space framework 

### ISSUE THREAD

**Issue by ezrasilvera** [kubestellar/kubestellar#778]
The initial version of the LC cluster framework and the LC client didn't address auth and user access requirements.

**Comment by clubanderson** [comment]
placed in sprint 3

**Comment by effi-ofer** [comment]
No update.

**Comment by clubanderson** [comment]
moving to backlog per @ezrasilvera

**Comment by ezrasilvera** [comment]
not  relevant for ks-0.20
