### ISSUE TITLE
Feature: The multi-space (MS) client should support cross-cluster operation

### ISSUE THREAD

**Issue by ezrasilvera** [kubestellar/kubestellar#779]
Need to support cross cluster List() and Watch() . 
Including:
#577

**Comment by clubanderson** [comment]
placing in sprint 3

**Comment by clubanderson** [comment]
morning to sprint 4 based on priorities.

**Comment by clubanderson** [comment]
@ezrasilvera moving this into the kcp-decouple column.  Change the sprint to your liking.

**Comment by clubanderson** [comment]
moving to sprint 5 per @ezrasilvera - this issue depends on inclusion or exclusion of kube-bind - will be re-evaluated in sprint 5.

**Comment by clubanderson** [comment]
started but not completed.  currently not needed.  moving to backlog

**Comment by ezrasilvera** [comment]
not  relevant for ks-0.20
