### ISSUE TITLE
Feature: Redesign the Space provider interface to a uniform REST interface

### ISSUE THREAD

**Issue by ezrasilvera** [kubestellar/kubestellar#780]
For phase I , the LC manager is using a specific local instance of the provider client in order to communicate with the provider. This make the LC manager aware of the concrete implementation of the LC provider. This creates dependency between the provider implementation and the LC manager. Also this require the LC manager to configure the provider.
The idea is to convert the provider interface into a pre-define set of REST APIs, so that connecting into a provider just require regular authentication without instantiating a local instance of the specific provider client code.

**Comment by clubanderson** [comment]
placing in sprint 3

**Comment by clubanderson** [comment]
streaming of watch events is a current design consideration

**Comment by effi-ofer** [comment]
Update Aug 24: Still WIP. This is not something that's critical to sprint 3 and we may push it to 4.

**Comment by ezrasilvera** [comment]
not  relevant for ks-0.20
