### ISSUE TITLE
feature: containerization: Helm chart needed for KubeStellar

### ISSUE THREAD

**Issue by clubanderson** [kubestellar/kubestellar#785]
### Feature Description

We are getting requests to produce and maintain a helm chart for KubeStellar

### Proposed Solution

1. containerize KubeStellar (https://github.com/kubestellar/kubestellar/pull/764)
2. make changes to support KubeStellar as a service based on gaps identified in containerization
    a. syncer requires a way to bind to ingress
3. get KubeStellar running in pods and accepting kubectl commands
4. create a helm chart
5. create an MD to show how to install the chart and connect to it

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by francostellari** [comment]
@clubanderson please see: 
https://github.com/francostellari/kubestellar/tree/helm-charts/helm-chart

**Comment by clubanderson** [comment]
addressed in https://github.com/kubestellar/kubestellar/pull/863
