### ISSUE TITLE
bug: SonarCloud holds up PRs due to old issues

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#796]
### Describe the bug

SonarCloud checking was introduced well after this project started, but only checks code touched in changes since then.  That means that things that SonarCloud does not like but were already present in the code before we started checking with SonarCloud (a) have not generally been reported anywhere and (b) suddenly intrude into any PR that makes any change to a file that has a pre-existing thing that SonarCloud does not like.

### Steps To Reproduce

Make a PR against code that was merged before SonarCloud checking started.

### Expected Behavior

Improvements should not be held up by old issues.

**Comment by clubanderson** [comment]
@ezrasilvera can you help with this?  I don't have extensive experience with Sonar Cloud.

**Comment by clubanderson** [comment]
@ezrasilvera can you have a look at this?

**Comment by MikeSpreitzer** [comment]
We have abandoned SonarCloud.
