### ISSUE TITLE
Docs still reference “kubestellar-scheduler” instead of new name “where-resolve”

### ISSUE THREAD

**Issue by clubanderson** [kubestellar/kubestellar#800]
### Describe the bug

QuickStart refers to KubeStellar-scheduler. Needs to be updated throughout all docs to reference “where-resolver”

### Steps To Reproduce

Go to any document in our document site
Look for kubestellar-scheduler

### Expected Behavior

Replace KubeStellar-scheduler with where-resolver

**Comment by MikeSpreitzer** [comment]
Which documents?  I looked in the latest in `main` and do not see such a reference.  I also looked at https://docs.kubestellar.io/release-0.4/Getting-Started/quickstart/ and do not see such a reference.  I suspect that Stefan Gajic was looking at the release-0.3 version of the QuickStart but somehow running something more recent.

**Comment by MikeSpreitzer** [comment]
Stefan Gajic reports that he was looking at the release-0.2 version of the quickstart, and when he looks at the latest he does not have a problem.

**Comment by waltforme** [comment]
Maybe we should change the overall arch diagram.
<img width="227" alt="image" src="https://github.com/kubestellar/kubestellar/assets/8633434/755498ee-efc6-4862-8135-e669efa15f8e">

Or, we can change it together with our recent name changes to 'space's, etc.
