### ISSUE TITLE
feature: `kubestellar` command not require co-resident `kcp` process

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#801]
### Feature Description

Today the `kubestellar` command requires that the kcp server be running as a process named `kcp` on the same "machine" (https://github.com/kubestellar/kubestellar/blob/2de44473567539ac2f4adceb32b2df4a81203d16/scripts/kubestellar#L85-L88).  This might not support the full breadth of usage scenarios that we want to support.

### Proposed Solution

Make the `kubestellar` command check instead that the needed `kubectl` behavior is available, regardless of where is the apiserver.

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by ezrasilvera** [comment]
It's not clear which behavior  of the kubectl you suggest to check. Why is this reated to decoupling?  In decoupling in any case we won't have kcp server running and we won't use the kubectl kcp extensions.

**Comment by MikeSpreitzer** [comment]
This was fix.
This is moot now.
