### ISSUE TITLE
feature:  kubectl-kubestellar-prep_for_syncer/kubectl-kubestellar-prep_for_cluster print syncer YAML to stdout

### ISSUE THREAD

**Issue by francostellari** [kubestellar/kubestellar#803]
### Feature Description

I would like an option to output the syncer YAML to stdout instead of creating a file

### Proposed Solution

I would like an option to output the syncer YAML to stdout instead of creating a file, perhaps `-o yaml`.
In this case no other output should be produced to stdout, only the generated YAML

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by clubanderson** [comment]
@MikeSpreitzer can you have a look at this?

**Comment by francostellari** [comment]
Solved by https://github.com/kubestellar/kubestellar/pull/823
