### ISSUE TITLE
bug: file references non-existent syncer container image

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#808]
### Describe the bug

https://github.com/kubestellar/kubestellar/actions/workflows/docs-ecutable-example1.yml is failing when run against the `main` branch.

When I run that locally on my development machine, the syncer Pods do not start because they reference the image `quay.io/kubestellar/syncer:v0.3.2` --- which does not exist.

Several files reference that tag.  The following shell session shows some of them.

```console
(.venv) mspreitz@mjs12 kubestellar % find * \( -path docs/.venv -prune \) -or \( -type f -exec fgrep v0.3.2 \{\} \; -print -exec echo \; \)
...

syncer_image="quay.io/kubestellar/syncer:v0.3.2"
kubestellar/bin/kubectl-kubestellar-prep_for_syncer

syncer_image="quay.io/kubestellar/syncer:v0.3.2"
kubestellar/scripts/kubectl-kubestellar-prep_for_syncer

syncer_image="quay.io/kubestellar/syncer:v0.3.2"
scripts/kubectl-kubestellar-prep_for_syncer
```

### Steps To Reproduce

See above.

### Expected Behavior

The example1 docs-ecutable succeeds.

**Comment by MikeSpreitzer** [comment]
/assign @clubanderson 
@fileppb

**Comment by clubanderson** [comment]
updated scripts/kubectl-kubestellar-prep_for_syncer in main to point at v0.4.0.  please retest

**Comment by clubanderson** [comment]
docs-ecutable for example1 on main branch is now passing.
