### ISSUE TITLE
bug: prep-for-syncer doc is wrong about default image reference

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#812]
### Describe the bug

https://docs.kubestellar.io/main/Coding%20Milestones/PoC2023q1/commands/#syncer-preparation-and-installation currently says that the default value for the syncer image reference is "" but that is incorrect.

### Steps To Reproduce

See above.

### Expected Behavior

Correct documentation

### Additional Context

The doc is wrong in release-0.4 as well.

**Comment by clubanderson** [comment]
updated 'main' version of doc to point to config.ks_tag.  The value should always be 'latest' in 'main' branch.
