### ISSUE TITLE
bug: docs instructions do not mention critical step of "mike set-default"

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#813]
### Describe the bug

I tried `make serve-docs`.  It claimed to succeed, but when I directed my browser to `http://localhost:8000/` it showed me a 404 response saying the following things in the web page.

> Error response
>
> Error code: 404
> 
> Message: File not found. Did you forget to run `mike set-default`? Alternately, you can navigate to 1.0.0.127.in-addr.arpa:8000/[some-version] to see your docs.
>
> Error code explanation: 404 - /.

Also, the shell running `mike` logged this:

> 127.0.0.1 - - [21/Jul/2023 15:49:36] code 404, message File not found. Did you forget to run `mike set-default`? Alternately, you can navigate to 1.0.0.127.in-addr.arpa:8000/[some-version] to see your docs

I tried guessing URLs that might work, such as http://localhost:8000/v0.4.0 , http://localhost:8000/release-0.4, and http://localhost:8000/main/; all rewarded me with a 404.

### Steps To Reproduce

Do the above, in a context where the default has not been set.
BTW, I do not know where the setting of the default gets stashed.

### Expected Behavior

The documented steps are sufficient.

**Comment by clubanderson** [comment]
I can't reproduce this.  I will add it to the instruction set anyway - doesn't hurt to set it locally.

I do not know where 'mike' keeps this setting.  It is not in https://github.com/kubestellar/kubestellar/blob/gh-pages/versions.json

**Comment by clubanderson** [comment]
updated doc management doc.

https://docs.kubestellar.io/main/Contribution%20guidelines/operations/document-management/

**Comment by MikeSpreitzer** [comment]
@clubanderson : 
(1) yes, you will not be able to reproduce the problem unless and until you find where `mike` stashes its default and remove that.

(2) I tried setting the default and it failed (even though I succeeded months ago when I tried it).

```
(venv) mspreitz@mjs12 docs % mike set-default main
Config value 'docs_url': Unrecognised configuration name: docs_url
Config value 'repo_raw_url': Unrecognised configuration name: repo_raw_url
Config value 'ks_tag': Unrecognised configuration name: ks_tag
Config value 'repo_default_file_path': Unrecognised configuration name: repo_default_file_path
Config value 'repo_short_name': Unrecognised configuration name: repo_short_name
Config value 'ks_branch': Unrecognised configuration name: ks_branch
error: version 'main' does not exist
```

**Comment by clubanderson** [comment]
which branch are you in when you run make serve-docs?

this is bizarre behavior.  You might look to reset your 'mike' environment - check the https://github.com/jimporter/mike site for some help.  If not, I would look for an issue that resembles your experience.

this may hold some hints - https://github.com/jimporter/mike/issues/106

**Comment by MikeSpreitzer** [comment]
This was with a fairly recent edition of `main`.
