### ISSUE TITLE
feature: Update documentation on how the syncer image is built

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#821]
### Feature Description

To the best of my knowledge, the only documentation about building the syncer image is at https://docs.kubestellar.io/main/Coding%20Milestones/PoC2023q1/kubestellar-syncer/#how-to-build-the-image-with-multiple-architectures-and-push-it-to-docker-registry .  This has three problems:

1. I am told that it is outdated (and indeed that doc does not match what I find on quay.io);
2. it does not address how the release self-reference problem is solved;
3. one normally finds instructions on how to build all collected in one place.

### Proposed Solution

Make a document on building, keep it in an easy-to-find place, and move the instructions for building the syncer image there and correct them.  Document both what someone making a release needs to do and what a developer testing a change needs to do.

### Want to contribute?

- [ ] I would like to work on this issue.

### Additional Context

The syncer image is currently referenced at https://github.com/kubestellar/kubestellar/blob/7fd7ade153114379890a726afe37d4fd9125f8ca/scripts/kubectl-kubestellar-prep_for_syncer#L37

**Comment by MikeSpreitzer** [comment]
I am told that the current technique for building the syncer image is to use `goreleaser`.  Currently, `.goreleaser.yaml` ONLY builds the syncer image, no other image or binaries.

By adding a git tag to the desired commit, I was able to use goreleaser to build the syncer image in my current commit.

```console
(venv) mspreitz@mjs12 kubestellar % git tag v0.4.1-rc2

(venv) mspreitz@mjs12 kubestellar % goreleaser release
  • starting release...
  • loading config file                              file=.goreleaser.yaml
  • loading environment variables
  • getting and validating git state
    • building...                                    commit=eae3a473ca416b88b8025477f6083ede8ec314ca latest tag=v0.4.1-rc2
  • parsing tag
  • setting defaults
  • checking distribution directory
  • loading go mod information
  • build prerequisites
  • writing effective config file
    • writing                                        config=dist/config.yaml
  • building binaries
    • skip is set                                    id=kubestellar-syncer
  • generating changelog
    • writing                                        changelog=dist/CHANGELOG.md
  • archives
  • calculating checksums
  • publishing
    • ko
2023/07/25 01:14:52 Building github.com/kubestellar/kubestellar/cmd/syncer for linux/arm64
2023/07/25 01:14:52 Building github.com/kubestellar/kubestellar/cmd/syncer for linux/s390x
2023/07/25 01:14:53 Building github.com/kubestellar/kubestellar/cmd/syncer for linux/amd64
2023/07/25 01:14:55 Publishing quay.io/kubestellar/syncer:v0.4.1-rc2
2023/07/25 01:15:46 Published quay.io/kubestellar/syncer:v0.4.1-rc2@sha256:4d3e24eeada8ccb896347c37bb44f016662366f3308ced0c7ee3ac40815be3ba
      • took: 55s
  • took: 55s
  • storing release metadata
    • writing                                        file=dist/artifacts.json
    • writing                                        file=dist/metadata.json
  • announcing
  • release succeeded after 54s
  • thanks for using goreleaser!
```

**Comment by MikeSpreitzer** [comment]
@clubanderson 
@yana1205 
@francostellari

**Comment by clubanderson** [comment]
placing in sprint 3

**Comment by clubanderson** [comment]
@MikeSpreitzer do you have any objection to using only goreleaser for the build of the syncer image?  If so, I can update the documentation to show that tagging will trigger a build.
