### ISSUE TITLE
feature: remove release self-reference problem from the prep-for-syncer script

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#822]
### Feature Description

We currently have a practice of referencing the syncer image using a tag that holds a release version.  See https://github.com/kubestellar/kubestellar/blob/7fd7ade153114379890a726afe37d4fd9125f8ca/scripts/kubectl-kubestellar-prep_for_syncer#L37 for the current choice.

This is bad because it makes it tricky to make a new release.  Remember that a git tag identifies an immutable object.  An image whose tag equals a git tag should be built from exactly the tagged commit.  Such an image would only be built _after_ that commit has been made and tagged.  Publishing a reference to something that does not exist yet is a booby-trap, if it goes someplace where users will look.  We still have not gotten the procedure right.  For example, after making the v0.4.0 release, `main` was left referring to an older release.

While it is not impossible to thread this needle if we are willing to release a tag that is on a commit in a PR, it might be better to not give ourselves a self-reference problem.

An image can be referenced by digest rather than by tag.  For example, `quay.io/kubestellar/syncer:v0.4.0` currently references the same image as `sha256:d83d3839f62494389d26e06fa4dfbc4cf6fbfe7ff9e37810af391cc8ba34e09e`.  Using a digest is considered more reliable, since those are immutable while the contents associated with a given tag can change over time.

A developer making a change is not necessarily creating a new release; requiring something that is designed as a release process and artifacts whenever there is any change is a conceptual mismatch.

### Proposed Solution

Change the prep-for-syncer plugin to reference the syncer image by digest rather than release tag.

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by MikeSpreitzer** [comment]
@clubanderson 
@yana1205 
@francostellari

**Comment by francostellari** [comment]
I personally do not like to have a tag that are not human readable.
During testing a custom image can be used anyhow since it would not be in our quay.io repo.
The correct approach is to implement `kubestelalr version` and replace the default reference with `quay.io/kubestellar/syncer:$(kubestellar version)`

**Comment by clubanderson** [comment]
I agree that a gangly uuid is not preferable. I agree it should be a version number.

**Comment by MikeSpreitzer** [comment]
Remember that using a digest in the image reference inside the `kubectl kubestellar prep-for-syncer` script does NOT mean that the image has no tag.  Every image has a tag as well as a digest.  The suggestion here is that we change what we write inside that script so that we do not have a self-reference problem.  This script is not intended for users to read, so it does not matter how pretty the default image reference is or is not.

**Comment by MikeSpreitzer** [comment]
A developer making a change is not necessarily creating a new release; requiring something that is designed as a release process and artifacts whenever there is any change is a conceptual mismatch.

**Comment by MikeSpreitzer** [comment]
Moot now.
