### ISSUE TITLE
feature:  Resilient Bilateral Reconnection

### ISSUE THREAD

**Issue by KPRoche** [kubestellar/kubestellar#824]
### Feature Description

KubeStellar lists as one of its primary use cases 
_Runtime in[ter]dependence: An edge location may need to operate independently of the center and other edge locations_

- There have been several demonstrations that Kubestellar workload management can tolerate an (edge) execution cluster disconnecting and reconnecting.
- The reverse, however, is not true. If the workload management layer(s) was restarted, a workload already running on an execution layer could not reconnect to the new instance of KubeStellar.
- This appears to be fundamentally due to the ip address of the center changing, and relying on ip address for identification

This could have dire consequences for some of the practical use cases such as space-based data centers, where the execution cluster might actually be on a satellite or probe in only periodic connectivity with the KubeStellar workload management system running on a larger installation. If KubeStellar restarted while the execution cluster was out of range, and did not recognize it on return, rebooting the satellite workload might consume all its available connection time.

### Proposed Solution

KubeStellar workload management needs to be able to support a persistent workload configuration, i.e.

- Upon spinning up and/or connecting to an execution cluster, create a persistent record of salient connection details, such as
  - hostname/ipaddress and port
  - proxy info, etc, as is being discussed in Issue 788
  - container/pod/cluster names, etc
  - other execution clusters/workloads it is known to be dependent on _[would this already be in the definition space for the edge workload?]_
  - salient connection information for those interdependencies
- On restart, using that persistent record to recreate the appropriate listeners/bindings/API (sorry for fuzzy terms) for the execution cluster to connect to
- On restart, recreate any secondary (non-edge) workloads that the execution cluster expects to interact with (e.g. an image analysis server for transmitted photos), ensure that they are up and running in the appropriate location to be ready to accept data

### Want to contribute?

- [ ] I would like to work on this issue.

### Additional Context

Starting to think now of enabling an option to create a persistent _record_ of the actual configuration created by deploying a workload managed from a definition space, with an eye to being able to recreate that configuration on restart if necessary, will make KubeStellar a much more resilient and robust workload management solution.

**Comment by MikeSpreitzer** [comment]
I am not sure I understand the problem.  As far as I know, crash and restart of any KubeStellar controller is not a problem because nothing in the workload execution cluster connects to any KubeStellar controller.  As far as I know, crash and restart of the kcp server --- and I specifically mean crash and restart with persistence of the `.kcp` data subdirectory holding the etcd contents and all the certificates and keys that the server uses --- also is not a problem because the syncer --- the only thing in the workload execution cluster --- will eventually reconnect to the restarted server and proceed happily along.

If the problem concerns stopping the kcp server and then starting a replacement that is not reachable at the same domain name(s) and/or IP address(es) as before, or using different certificates, then that is the way I would look at it.

I recognize that today we do not support the kcp server having a permanent set of domain names that it can be reached at.  Is that what this issue is really about?

**Comment by KPRoche** [comment]
I'm particularly worried about a workload that is split across locations, as in the SDC model where an execution cluster in an edge location (e.g., satellite) has an app in intermittent communication with another app (e.g., image data processing) in a cluster running in the same location as the Kubestellar control systems. 

If we have to restart, and those "local" apps have to restart, what information has to be maintained across restarts to make sure that when our edge location reconnects it finds that listening app where it expects to?

If you're telling me that the existing architecture can already do that, hurrah! 
I do seem to recall Franco described an experiment where that wasn't the case -- his edge cluster couldn't connect to the new instance of KS, however. If I'm mistaken, all for the better.

**Comment by MikeSpreitzer** [comment]
I am still not sure I understand.  The current KubeStellar design is to support independent workload execution clusters.  KubeStellar does not aim to support communication between workload components running in different workload execution clusters, and does not have a concept of running workload anywhere other than in a workload execution cluster.

**Comment by MikeSpreitzer** [comment]
KubeStellar is not saying that workload components MUST NOT communicate with stuff outside their cluster; I am just saying that KubeStellar today does not take any steps to facilitate communication between workload components (either in a cluster or between clusters).  Of course, I mean communications other than the regular stuff that KubeStellar clients can do (prescribe workloads and their placements, get some information back about that).

**Comment by clubanderson** [comment]
I may add some confusion here, but let me try...

We know that KubeStellar Syncer can survive loss of connection to an upstream KubeStellar Core.  Let's call the core KS Core A.  So KS WEC 1 and 2 call home to KS Core A and get spec and can return status.  All good.  If KS WEC 1 or 2 goes away and comes back, all is good.  

Now, if KS WEC 1 gets blown away and loses its KS Syncer, then we know we need a new KS Syncer and etc.  All bets are off in terms of what was running on KS WEC 1... that's the breaks.

But, if KS WEC 1 and 2 remain ok and connect sometimes, and then KS Core A goes away for a period of 8 hours and a new KS Core B comes online.  Can KS Core B pickup where KS Core A left off with KS WEC 1 and 2?  I don't think it can.  And this is the kind of situation that may happen if the Earth rotates while all the other platforms stay in a straight line.  

Until KS Core A comes back around, it does not have line-of-site, and therefore needs the help of other Cores located around the earth.  This could be helped along with hierarchy we are talking about, or it might be something altogether different.

**Comment by MikeSpreitzer** [comment]
Yes, do please let us be clear here.

I _think_ I hear @KPRoche talking about network communication between workload components running in different workload execution clusters.

A use case with multiple ground stations and a hierarchy of orbiting stations may call for hierarchy in the cluster configuration control plane, but I _think_ that is not what @KPRoche is trying to talk about in _this_ issue.

**Comment by KPRoche** [comment]
@MikeSpreitzer and @clubanderson --
Thanks for bringing into better focus the point I was trying to make. I'm going describe this based on the particular geometry of the space data center for the moment, and then try to generalize a bit.
(@clubanderson's question is related but somewhat orthogonal to my point; as there is a hand-wavy idea that multiple SDCs would be spaced (no pun intended) at orbital intervals allowing them to network and hence pass comms on to the correct KS Core location. That goes back to our general networking/proxy/routing questions and is not what I was focused on.)

One key concept of a SDC is that it would be in a higher orbit and able to maintain long-duration contact with a ground station, as opposed to lower orbit devices like satellites , so those (satellites) would send raw or partly processed data to the SDC, which then do more processing and then can efficiently downlink to operators on the ground. The SDC could also relay commands to those lower orbit devices.
A secondary concept is that code running in the satellite would likely be less resource-intensive and the SDC would have the computing "muscle" to do heavier duty analysis, DB operations, etc. 

If we are promoting the idea that KubeStellar can manage the apps running in those satellites as WECs, then by inference it should _also_ be managing whatever they are sending data to, which means there **must** be a WEC1(b) on the SDC to which the edge WEC1(a) is connecting. There is little point in being able to dynamically update what that edge WEC is doing if you can't also update the listener app to match.

Isn't this one of the fundamental ideas of multi-cloud computing, that you locate the components of a distributed workload in the systems best suited to that use? I clearly inferred from our earlier presentations that distributing an overall application across multiple WECs as necessary was one of the goals of KubeStellar, and I doubt I am the only one.

So -- in practical terms, if, as you say, the "engine" of KS can spin things back up, then maybe the issue I'm really raising is that we need a way to make sure that the definitions in a space are robust and complete enough that restarting a processing WEC1(b) while the edge WEC1(a) is disconnected does so in such a way that WEC1(a) can find it on reconnection.

I hope this clarifies what I was trying to say

**Comment by clubanderson** [comment]
@MikeSpreitzer is a WEC where KS Core and KS Syncer runs?  I assumed WEC is only a spoke where KS Syncer runs.  Please help me clear this up.  If WEC is where KS Syncer runs today, then WEC to WEC communication - as @KPRoche suggests, requires hierarchy?  Or, at a minimum, some concept that we do not have in KS today, correct?

**Comment by MikeSpreitzer** [comment]
Yes, a Workload Execution Cluster is where a KubeStellar syncer runs.

KubeStellar neither forbids nor assists with direct communication between workload components in different WECs.   The job of the KubeStellar syncer is to be the agent in its cluster for Kubernetes API object downsync and upsync.

@KPRoche, thanks for clarifying the usage scenario that you have in mind.  I think it raises interesting questions about how the communication between the low-orbit satellites and the higher-orbit data centers and the ground stations are organized.  I would expect this to be a separate matter from configuring the Kubernetes API objects.  It might involve direct application awareness of which peers are reachable at the moment, or it might involve something more structured (such as a storage layer that moves data along when/where possible).  But in any case, it is not a matter of configuring Kubernetes API objects.

**Comment by clubanderson** [comment]
@KPRoche update on this?

**Comment by KPRoche** [comment]
I had planned to do my experiment running Kubestellar core on a WSL machine and the WEC on a raspberry pi. I got as far as successfully getting Kubestellar core running on my WSL, with an assigned hostname, only to discover that the process of exposing the WSL machine to external network connections was particularly labyrinthine.
I have switched to trying installing core on one named raspberry pi and WEC on a second, each with their own hostname and static IP address, to take that layer out of the mix. I'm chasing my tail through our installation instructions.

**Comment by KPRoche** [comment]
This issue is unsolvable with the current implementation of Kubestellar-core, relying on the kcp-generated certificates for authentication between syncers and core. Because kcp creates new certificates when it restarts, this will break any syncers previously connected to it.

**Comment by clubanderson** [comment]
@KPRoche can you please reference the issue that was opened to specifically address this so that this issue is informed by it when it gets resolved?

**Comment by KPRoche** [comment]
It is issue https://github.com/kubestellar/kubestellar/issues/1063

**Comment by clubanderson** [comment]
ok, #1063 is now closed.  Let us know how this works for you in 0.9.0.

**Comment by KPRoche** [comment]
This issue is entirely dependent on solving the token issue described in #1120.

**Comment by clubanderson** [comment]
will tackle with SF in December

**Comment by KPRoche** [comment]
I have been pondering what may be a naive question: Could we have an API endpoint which a syncer running on a workload execution cluster could use to fetch the current ks-core kubeconfig and update its copy?

I imagine this would involve a couple of steps: 
- When a syncer is first configured and deployed, an authentication token is generated and
  -  included in the syncer deployment as a secret
  -  saved in persistent storage by the ks-core and associated with the location and workload definitions
- When a running syncer connects to ks-core, it first uses the kubeconfig file from its initial deployment
- If this fails (say because the ks-core has had to restart), it uses the token and API endpoint to pull the current kubeconfig and it updates the copy on the WEC.
- this fallback process also returns a new authentication token which must be updated in both the syncer secrets and the ks-core persistent storage.

Is this even possible? I say naive question because I don't know if it's actually possible to replace the kubeconfig used by the syncer on the fly.

**Comment by MikeSpreitzer** [comment]
@KPRoche : you are reinventing a key rotation technique. Yes, it can be done. I think it would be more work than other approaches that are either underway already or could be taken:
- @francostellari has shown that the kcp Helm chart does not have this problematic user credential, and maybe even shows how we can avoid the problem with kcp v0.11.0;
- This problem is expected to just go away when we switch to using kcp through the Space abstraction layer;
- This problem will certainly go away when we switch from kcp to KubeFlex;
- If none of the above is good enough then we can switch from the blighted user to a ServiceAccount that we construct and authorize as necessary.

**Comment by KPRoche** [comment]
@MikeSpreitzer Thank you for giving me the right vocabulary; I was absolutely certain it was not an original idea! 
I hope you are 100% right it goes away as we move away from kcp. 
As long as some persistent record of the WECs is created when they are first deployed so the ks-core can recognize them if they reconnect, we should achieve the resilience of the title :)
