### ISSUE TITLE
feature: containerization: `kubestellar start` should append to, rather than overwrite, logs

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#825]
### Feature Description

`kubestellar start` currently launches processes that overwrite their log file if it already exists.  It would be better if the older log contents were preserved.

### Proposed Solution

Make `kubestellar start` append to logs that already exist.

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by clubanderson** [comment]
placing in sprint 3

**Comment by clubanderson** [comment]
@MikeSpreitzer is this issue still open if it was fixed for the container in #764?  I am offering PR for kubestellar script now just in case.
