### ISSUE TITLE
bug: [Logical Clusters] address remaining comments in PR 783

### ISSUE THREAD

**Issue by effi-ofer** [kubestellar/kubestellar#827]
### Describe the bug

This issue is being opened so we'll have a reminder to address the remaining unaddressed comments in PR #783

### Steps To Reproduce

.

### Expected Behavior

.

**Comment by clubanderson** [comment]
placing in sprint 3

**Comment by clubanderson** [comment]
@ezrasilvera to review and determine if still relevant
