### ISSUE TITLE
bug: a few of the docs-ecutable docs are finishing with errors

### ISSUE THREAD

**Issue by clubanderson** [kubestellar/kubestellar#828]
### Describe the bug

After #814 was merged, a few of the docs-ecutable files are not running to completion without errors.

### Steps To Reproduce

run example1, placement, and syncer.  There is a sub-doc that is misconfigured and is referenced by these 3 docs.

### Expected Behavior

all docs-ecutable should run to completion without errors.

**Comment by fileppb** [comment]
fixed with https://github.com/kubestellar/kubestellar/pull/835
