### ISSUE TITLE
Does a single kube-bind konnector work for multiple providers?

### ISSUE THREAD

**Issue by waltforme** [kubestellar/kubestellar#829]
In July 27th KubeStellar community meeting, @MikeSpreitzer asked this question. Although I haven't seen any working example from in the kube-bind community (and in KubeStellar we only have one provider), it is still worth trying.

**Comment by clubanderson** [comment]
moving to sprint 3

**Comment by waltforme** [comment]
The answer is yes.

What I tried is illustrated in the diagram. More details are documented here: https://docs.google.com/document/d/1k1_Mie8TjxceWHqNt_yJj4tXMR76Be1ZfSIHtnwksFA

![use multiple providers in kube-bind](https://github.com/kubestellar/kubestellar/assets/8633434/ce55035b-8ba5-4e15-8c00-a563baa6a447)
