### ISSUE TITLE
bug: kcp.io is used on some of our api, should be kubestellar.io

### ISSUE THREAD

**Issue by clubanderson** [kubestellar/kubestellar#833]
### Describe the bug

when I look at the api used in the yaml definitions for objects in our examples, I see some of our api uses kcp.io instead of kubestellar.io

### Steps To Reproduce

1. open any example on kubestellar.io
2. view yaml definitions for objects like Customizer and edgeplacement
3. note the use of customizer.kcp.io and edgeplacement.kcp.io

### Expected Behavior

would like to move to kubestellar.io for all kubestellar related apis

**Comment by fileppb** [comment]
@clubanderson would an example of this be replacing the edge.kcp.io api-group with a new api-group named edge.kubestellar.io?

**Comment by clubanderson** [comment]
Yes indeed. That is one of them.

**Comment by fileppb** [comment]
@clubanderson That's a lot of changes then. Shouldn't this be a feature rather than a bug?

**Comment by clubanderson** [comment]
Well, at this point carrying partial KCP and partial non-KCP is a liability and might break several aspects of our project. We don't want to be in this mixed mode for very long if we can avoid it

**Comment by fileppb** [comment]
@clubanderson @MikeSpreitzer Andy yes I understand, but so far the replacements have all been assigned to the edge.kcp.io api group. It's not just my stuff. I think it's all the stuff that's distinct from KCP. So EdgePlacements, etc. @MikeSpreitzer what's your opinion, bug or feature?

**Comment by clubanderson** [comment]
I'm fine with feature. To me it isn't really a difference. Either way we have to tackle it over the coming weeks and months.

**Comment by fileppb** [comment]
@clubanderson @MikeSpreitzer Maybe I'm misinterpreting this? Do you actually mean completely severing the relationship with kcp, and replacing all xxx.kcp.io api groups with xxx.kubestellar.io api groups? Maybe I'm off base but that sounds like a very big change.

**Comment by clubanderson** [comment]
Well, that's where we are headed. Yes. We are severing our dependency and making it so Kubestellar can stand alone and can be combined with KCP as a client, but not as part of the core.

**Comment by clubanderson** [comment]
looks like there are 401 instances of '.kcp.io' in our code base across 142 files at present.  Yes, indeed, lots of work.  This is the difference between kubestellar as an opensource project that uses kcp to do interesting things that kcp could not do on its own, yet, and KubeStellar as an opensource project that does something unique and does not rely on kcp, but can use kcp, kind, kubeflex, and other kubernetes distributions in a flexible way.  I think that is the place where we want to be.  Renaming API's is not going to get us there entirely, but it is a good step in a) identifying our interdependencies, and b) replacing or renaming those dependencies over time with technology that either replaces or abstracts kcp.

**Comment by fileppb** [comment]
this was closed with PR #901
