### ISSUE TITLE
bug: pkg/placeholder/workload-projector.go needs to use Kubestellar edge.kcp.io rather than TMC scheduling.kcp.io

### ISSUE THREAD

**Issue by fileppb** [kubestellar/kubestellar#836]
### Describe the bug

pkg/placeholder/workload-projector.go needs to use Kubestellar edge.kcp.io rather than TMC scheduling.kcp.io. This should have been included in Feature 814's changes, but was overlooked.

### Steps To Reproduce

Run make MANIFEST="'docs/content/Coding Milestones/PoC2023q1/example1.md'" docs-ecutable
at the end the http returned will show something like "is running on %(loc-name)"

### Expected Behavior

Run make MANIFEST="'docs/content/Coding Milestones/PoC2023q1/example1.md'" docs-ecutable
at the end the http returned should show something like "is running on florin"

**Comment by clubanderson** [comment]
adding to sprint 3

**Comment by fileppb** [comment]
@clubanderson This was already done and merged into main. Please see https://github.com/kubestellar/kubestellar/pull/839

**Comment by clubanderson** [comment]
oh, then should this ticket be closed?  If so, please close it.

**Comment by fileppb** [comment]
fixed with https://github.com/kubestellar/kubestellar/pull/839
