### ISSUE TITLE
Epic: Convert KubeStellar to work with space provider instead of directly with KCP workspaces

### ISSUE THREAD

**Issue by ezrasilvera** [kubestellar/kubestellar#840]
This feature describes the steps needed in order to switch from using KCP workspaces directly to using spaces through the space-manager. The following plan doesn't depend on new kube-bind support for apibind, apiexport, and apiexport view. KS can continue using KCP's export/bind. 
This transition doesn't impact the interaction with KubeStellar - **no changes are needed to anyone using KS**
There are two dependent phases:

1.  Changes to the KS setup process and scripts: bring up  the space manager, create and configure a KCP space provider
2. Gradually convert the KS controllers that are interacting with Workspaces through the cluster scoped KCP go-client into using the multi-space aware client (msclien)

The plan includes the following tasks and changes to KS:
## prerequisites 
- [x] Working KCP space provider  #849 
- [x]  Merge the space framework and multi-space client library into KS

### Related features and PRs:
- [ ] #978
- [ ] #977
- [ ] #976 
- [ ] #975 
- [ ] #852 
  - [ ] #897 
- [ ] #853 
  - [ ] #904 
  - [ ] #923

**Comment by effi-ofer** [comment]
What is WS workspace?  Did you mean KS Workspace?

**Comment by clubanderson** [comment]
placing in sprint 3

**Comment by MikeSpreitzer** [comment]
I assume that in "Update the KS setup: setup the space framework", in the first bullet, the intent is to talk about the KubeStellar Core Space.  BTW, we _do_ have a glossary now, in https://docs.kubestellar.io/main/Getting-Started/user-guide/#glossary ; further improvements are solicited.

**Comment by MikeSpreitzer** [comment]
In "Update the KS setup: setup the space framework", in the last bullet, about creating the other spaces: I expect that we can start with i; obviously we need to eventually get to ii.

**Comment by ezrasilvera** [comment]
@MikeSpreitzer I have updated the flow. We now have a bootstrapping space that is used only by the space-manager and is not crated through the space-manager. (Originally the flow used the KS core space for that). 
I suggest we actually start directly with creating the spaces through the space resources  rather than letting the space manager import KCP workspaces. This way we won't need to change anything when we switch to another provider.

**Comment by ezrasilvera** [comment]
The epic moved into the following epic https://github.com/kubestellar/kubestellar/issues/524
