### ISSUE TITLE
feature: upgrade KubeStellar kcp dependency from v0.11 to v0.20

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#847]
### Feature Description

Currently KubeStellar depends on v0.11 of kcp.  This is increasingly painful, as kcp v0.11 is pinned to Kubernetes 1.24.

Release 1.28 of Kubernetes is planned for Aug 15 (https://www.kubernetes.dev/resources/release/), at which point 1.24 will drop out of the maintenance window.

Kubernetes 1.24.3 lacks a bug fix to the server's updating of the `ObjectMeta.ManagedFields`; this bug is problematic for some of our clients.

### Proposed Solution

Do the dependency upgrade.

### Want to contribute?

- [ ] I would like to work on this issue.

### Additional Context

Compared to v0.11, v.20 of kcp removes TMC and re-orgnizes some of the packages, concentrating into a new Go module `sdk` the things that clients are expected to depend on.

**Comment by fileppb** [comment]
@MikeSpreitzer do you have a feel for how widespread the fallout from this would be?
 I see that we currently require:
        github.com/kcp-dev/apimachinery/v2 v2.0.0-alpha.0
	github.com/kcp-dev/client-go v0.0.0-20230126185145-aeff170a288b
	github.com/kcp-dev/kcp v0.11.0
	github.com/kcp-dev/kcp/pkg/apis v0.11.0
	github.com/kcp-dev/logicalcluster/v3 v3.0.2

while https://github.com/kcp-dev/kcp/blob/v0.20.0/go.mod requires 
        github.com/kcp-dev/apimachinery/v2 v2.0.0-alpha.0.0.20230419125703-767ac05aebce
	github.com/kcp-dev/client-go v0.0.0-20230519100911-e16eb4c2bf18
	github.com/kcp-dev/kcp/sdk v0.0.0-00010101000000-000000000000
	github.com/kcp-dev/logicalcluster/v3 v3.0.4

**Comment by clubanderson** [comment]
@MikeSpreitzer could we revisit the priority of this issue.  I would like to finish decoupling by September 1st.
