### ISSUE TITLE
feature: Change  the KS setup create Spaces instead of workspaces

### ISSUE THREAD

**Issue by ezrasilvera** [kubestellar/kubestellar#852]
Use bootstrap space+ the space-manager to create the KS spaces ) inventory, WL, and core

**Comment by andreyod** [comment]
PR https://github.com/kubestellar/kubestellar/pull/897 . Need to address review comments.

**Comment by effi-ofer** [comment]
At this point this is still WIP because there (1) are additional scripts in the scripts directory that need to be converted from workspaces to spaces and (2) the documentation needs to be updated.

**Comment by ezrasilvera** [comment]
Replaced with https://github.com/kubestellar/kubestellar/issues/1215
