### ISSUE TITLE
feature: Change the KS controllers  to use the MS client library 

### ISSUE THREAD

**Issue by ezrasilvera** [kubestellar/kubestellar#853]
Change the code to use the MS librray instead of using the KCP workspace directly

**Comment by clubanderson** [comment]
is this slated for completion by Sept. 1st (Sprint 3 end)?

**Comment by andreyod** [comment]
PR https://github.com/kubestellar/kubestellar/pull/904 for mailbox controller changes.
Working on changes for `where-resolver` and `placement-translator`

**Comment by effi-ofer** [comment]
This issue is dependent on issue #852.

**Comment by clubanderson** [comment]
per @ezrasilvera closing - which issue replaces this?

**Comment by clubanderson** [comment]
this is completed per @ezrasilvera
