### ISSUE TITLE
Epic: continuing work on the Space abstraction framework

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#857]
This epic is about the on-going work on the abstraction framework that separates providers of space functionality from consumers of that functionality.
This epic is specifically about the framework, not its use in multi-cluster configuration management; that is companion work covered by #524 (formerly #840).

includes:
#780

**Comment by clubanderson** [comment]
need some more details in here as to which gaps are to be addressed

**Comment by effi-ofer** [comment]
The work remaining on the space framework includes 1. changing the KS code and scripts to use the space framework 2. separate the provider from the space framework 3. cross cluster operations such as list and watch. 4. review the performance implications of using kcp workspaces  and switch to kubeflex? There are already issues open for 1-3.  Is there any other gap that I missed?

**Comment by clubanderson** [comment]
I might have questions for you as I convert bash scripts to go.

**Comment by MikeSpreitzer** [comment]
Moot
