### ISSUE TITLE
Epic: codify support for more production grade deployment scenarios

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#858]
Currently the only codified deployment that we have is for dev/test using kind clusters.  We need to codify support for serious usage.

Tasks:
- [ ] Support deployment into a Kubernetes cluster (#859)
- [ ] ...

**Comment by clubanderson** [comment]
placed into "new" status.  Need to know which other items from the backlog and sprint 3 should be included here.

**Comment by clubanderson** [comment]
@MikeSpreitzer @pdettori please look to combine #990

**Comment by clubanderson** [comment]
@MikeSpreitzer @pdettori can you look to combine this with #990?

**Comment by clubanderson** [comment]
closing this ticket - will work with #990
