### ISSUE TITLE
feature: Adding support to select a subset of resources in a namespace to be synced to a workload execution cluster

### ISSUE THREAD

**Issue by dumb0002** [kubestellar/kubestellar#866]
### Feature Description

KubeStellar needs to support the use of EdgePlacement object to specify a subset of resources in a namespace to be synced to a particular workload execution cluster. 

This feature is required for some applications such as the following:

-  KubeFlow:  the entire pipeline needs to run in one namespace at the same time, but we may want to run parts of the namespace in different clusters

- MCAD: in some use-cases MCAD needs to cherry pick objects from a namespace to be shipped to a particular location.

### Proposed Solution

KubeStellar EdgePlacement object allows selection of a subset of resources in a namespace to be synced to a particular workload execution cluster.  

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by clubanderson** [comment]
@MikeSpreitzer unless you object, I think this is our next priority.

**Comment by clubanderson** [comment]
@roytman please review along with @cwiklik  - Thank you

**Comment by ezrasilvera** [comment]
Few questions: 
1. Why should this be done through EdgePlacement  ?  
2. Why can a user use multiple NS and put all resources needed to be synced in special NS ?

**Comment by roytman** [comment]
> Why can a user use multiple NS and put all resources needed to be synced in special NS ?

KFP puts all its objects in the same NS.

**Comment by cwiklik** [comment]
Current workaround for this issue requires creation of WDS for each target cluster.

**Comment by dumb0002** [comment]
Fixed in this PR: https://github.com/kubestellar/kubestellar/pull/884
