### ISSUE TITLE
feature: add space manager context flag, update logging, change kubeconfig default

### ISSUE THREAD

**Issue by effi-ofer** [kubestellar/kubestellar#868]
### Feature Description

This issue describe a number of relatively minor changes that we would like to implement as part of the kubestellar switch to using the space framework.

1. Add a space manager context flag to cmd/space-manager (space-manager -kubeconfig $KUBECONFIG -context $space_mgt_context -v=2)
2. Fix the space manager logging.  The current implementation is missing a call to klog.InitFlags() 
3. change the code that determnes the kubeconfig default to using $KUBECONFIG
4. update the defaultProviderNS to spaceprovider-default. 

### Proposed Solution

.

### Want to contribute?

- [X] I would like to work on this issue.

**Comment by clubanderson** [comment]
is this slated for completion by Sept. 1st (Sprint 3 end)?

**Comment by effi-ofer** [comment]
@clubanderson yes.

**Comment by effi-ofer** [comment]
Merged by PR #878
