### ISSUE TITLE
Automate kube-bind's binding

### ISSUE THREAD

**Issue by waltforme** [kubestellar/kubestellar#870]
We need to come up with some automation to get kube-bind's exports and bindings in place before we start KS controllers, just like the automations we have today to get kcp's exports and bindings in place. This automation may be trickier comparing to kcp, because kube-bind needs a consumer (a person) to open a link in a browser UI, and interact with the UI to finish authentication, in order to finish the binding to a provider. But in kcp we don't need this authentication between two workspaces.

**Comment by ezrasilvera** [comment]
@waltforme Can you please link the relevant PRs that implement this issue ?

**Comment by waltforme** [comment]
The initial implement of this automation lives in [the autobind branch](https://github.com/waltforme/kube-bind/tree/autobind) of my fork of kube-bind.

**Comment by ezrasilvera** [comment]
Can we consider this as done?  Maybe add a different issue of "upstream to kube-bind" ?

**Comment by waltforme** [comment]
I agree. This is done. Let me close it.
