### ISSUE TITLE
Remove kcp dependencies from Kubestellar Syncer 

### ISSUE THREAD

**Issue by fileppb** [kubestellar/kubestellar#874]
### Feature Description

Remove dependencies on KCP from Kubestellar syncer. As per Yana, "The code doesn't work if we just replace it with kubestellar logicalcluster clientset. Syncer codes depend on kcp logical cluster (core.kcp.io/v1alpha1/logicalclusters) that's created by kcp when a workspace is created. The kcp logical cluster is different from kubestellar logical cluster both syntactically and semantically. We need to remove the dependency from codes relating with Syncer/Syncer manifest generation."

### Proposed Solution

Remove dependencies on KCP from Kubestellar syncer. 

### Want to contribute?

- [ ] I would like to work on this issue.

### Additional Context

See https://github.com/kubestellar/kubestellar/issues/848#issuecomment-1669254839

**Comment by fileppb** [comment]
@MikeSpreitzer is this just a duplication of what Ezra is working on?

**Comment by clubanderson** [comment]
@yana1205 to review

related notes from scrum: can we add use of the regular kube code generator now to incrementally change over from kcp code gen to kube code gen?  Directory structure can be used to isolate the two versions
