### ISSUE TITLE
feature: containerization: Decompose KubeStellar control plane components to run in separated containers

### ISSUE THREAD

**Issue by dumb0002** [kubestellar/kubestellar#882]
### Feature Description

To decompose KubeStellar control plane components (e.g., mailbox controller, where resolver, placement translator, etc.) to run in separated containers and provide logs that can be collected by observability tools. 

### Proposed Solution

1. Decompose KubeStellar control plane to run in separated containers
2. Containers should generate logs that can be collected by observability tools

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by clubanderson** [comment]
this is complete - closing
