### ISSUE TITLE
bug: edge syncer bug(s) wrt REST mapping, downsynced object ownership

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#900]
### Describe the bug

(1) @ronenkat has observed the syncer to delete a ReplicaSet object from a workload execution cluster when that ReplicaSet was created by the Deployment controller in that cluster due to the downsync of a Deployment object.  We observed, to our surprise, that the ReplicaSet object has the following _annotations_.

```
    edge.kcp.io/downsynced: "true"
    kcp.io/cluster: 2wtbj9dfm5zqt18w
```

As shown in https://kubernetes.slack.com/archives/C18NZM5K9/p1692118887941999. this seems to be unexpected but actual behavior of the Deployment controller.

(2) In my own successful tests of our Quickstart I do not see spurious deletions of any ReplicaSet.  I also do not see log messages from the syncer about "SyncMany: downsync many" nor "setup ResourceClient" for ReplicaSet --- even though replicasets are in the downsynced namespaced resource list in the SyncerConfig.  So I suspect a failure in the inverse REST mapping.  But it must be a flaky failure, because @ronenkat reports that his syncer logs _do_ show such messages.

### Steps To Reproduce

See above.

### Expected Behavior

Do deletions of objects that should exist, actual processing of the configured resources.

**Comment by MikeSpreitzer** [comment]
/cc @yana1205 
@ronenkat

**Comment by MikeSpreitzer** [comment]
More investigation shows the following.

The problem does not occur in the quickstart because the `replicasets` resource is _not_ defined in the mailbox workspaces because the workload only uses Deployment objects.

In example1 ("extended example"), there is thrashing of the Deployment's ReplicaSet in the guilder workload execution cluster.  Every roughly 17 seconds, the syncer deletes that ReplicaSet because it has the annotation marking it as managed by the syncer and the corresponding mailbox controller has the `replicasets` resource defined but there is no object corresponding to the RS created by the Deployment controller.  Shortly after that, the Deployment controller notices that this ReplicaSet is missing and re-creates it.  Here is some shell evidence of this ReplicaSet being thrashed:

```console
(venv) %n@%m %1~ %# date; kubectl --context kind-guilder get rs -A
Tue Aug 15 22:33:20 EDT 2023
NAMESPACE                             NAME                                             DESIRED   CURRENT   READY   AGE
commonstuff                           commond                                          1         1         1       4m50s
kube-system                           coredns-5d78c9869d                               2         2         2       7m46s
kubestellar-syncer-guilder-28klyfq9   kubestellar-syncer-guilder-28klyfq9-5cf8957887   1         1         1       5m31s
local-path-storage                    local-path-provisioner-6bc4bddd6b                1         1         1       7m46s
specialstuff                          speciald-76f6fc4cfc                              1         1         1       11s
(venv) %n@%m %1~ %# date; kubectl --context kind-guilder get rs -A
Tue Aug 15 22:33:31 EDT 2023
NAMESPACE                             NAME                                             DESIRED   CURRENT   READY   AGE
commonstuff                           commond                                          1         1         1       5m1s
kube-system                           coredns-5d78c9869d                               2         2         2       7m57s
kubestellar-syncer-guilder-28klyfq9   kubestellar-syncer-guilder-28klyfq9-5cf8957887   1         1         1       5m42s
local-path-storage                    local-path-provisioner-6bc4bddd6b                1         1         1       7m57s
specialstuff                          speciald-76f6fc4cfc                              1         1         1       5s
(venv) %n@%m %1~ %# date; kubectl --context kind-guilder get rs -A
Tue Aug 15 22:33:45 EDT 2023
NAMESPACE                             NAME                                             DESIRED   CURRENT   READY   AGE
commonstuff                           commond                                          1         1         1       5m14s
kube-system                           coredns-5d78c9869d                               2         2         2       8m10s
kubestellar-syncer-guilder-28klyfq9   kubestellar-syncer-guilder-28klyfq9-5cf8957887   1         1         1       5m55s
local-path-storage                    local-path-provisioner-6bc4bddd6b                1         1         1       8m10s
specialstuff                          speciald-76f6fc4cfc                              1         1         0       1s
```

Here is an excerpt from the syncer's log showing one of the deletions:

```
I0816 02:33:44.755531       1 downsyncer.go:215] "SyncMany: downsync many" syncTargetName="guilder" resource="ReplicaSet.apps/* in specialstuff"
I0816 02:33:44.755618       1 downsyncer.go:222] "SyncMany:   list resources from upstream" syncTargetName="guilder" resource="ReplicaSet.apps/* in specialstuff"
I0816 02:33:44.772247       1 downsyncer.go:234] "SyncMany:   list resources from downstream" syncTargetName="guilder" resource="ReplicaSet.apps/* in specialstuff"
I0816 02:33:44.785943       1 downsyncer.go:241] "SyncMany:   compute diff between upstream and downstream" syncTargetName="guilder" resource="ReplicaSet.apps/* in specialstuff"
I0816 02:33:44.786780       1 common.go:201] "SyncMany:   speciald-76f6fc4cfc is added to deletedResources since annotation is set." syncTargetName="guilder" resource="ReplicaSet.apps/* in specialstuff"
I0816 02:33:44.787006       1 common.go:221] "SyncMany:   new resource names: []" syncTargetName="guilder" resource="ReplicaSet.apps/* in specialstuff"
I0816 02:33:44.787213       1 common.go:222] "SyncMany:   updated resource names: []" syncTargetName="guilder" resource="ReplicaSet.apps/* in specialstuff"
I0816 02:33:44.787255       1 common.go:223] "SyncMany:   deleted resource names: [speciald-76f6fc4cfc]" syncTargetName="guilder" resource="ReplicaSet.apps/* in specialstuff"
I0816 02:33:44.787312       1 downsyncer.go:244] "SyncMany:   create resources in downstream" syncTargetName="guilder" resource="ReplicaSet.apps/* in specialstuff"
I0816 02:33:44.787346       1 downsyncer.go:253] "SyncMany:   update resources in downstream" syncTargetName="guilder" resource="ReplicaSet.apps/* in specialstuff"
I0816 02:33:44.787383       1 downsyncer.go:262] "SyncMany:   delete resources from downstream" syncTargetName="guilder" resource="ReplicaSet.apps/* in specialstuff"
I0816 02:33:44.787434       1 downsyncer.go:265] "SyncMany:   delete speciald-76f6fc4cfc" syncTargetName="guilder" resource="ReplicaSet.apps/* in specialstuff"
```

**Comment by MikeSpreitzer** [comment]
Interestingly, the ReplicaSet controller does _not_ seem to propagate annotations to the ReplicaSet's Pod objects.

```console
(venv) %n@%m %1~ %# kubectl --context kind-guilder get pods -n specialstuff -o yaml
apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: "2023-08-16T02:49:24Z"
    generateName: speciald-76f6fc4cfc-
    labels:
      app: special
      pod-template-hash: 76f6fc4cfc
    name: speciald-76f6fc4cfc-h8bx2
    namespace: specialstuff
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: speciald-76f6fc4cfc
      uid: 2cf83ada-6f1a-428a-a9e1-2b1e433dfe24
    resourceVersion: "4896"
    uid: 765d8c9f-2ab6-4387-815a-6a10241e6d1f
  spec:
...
```

**Comment by MikeSpreitzer** [comment]
One way to avoid this thrashing would be to leverage the fact that the placement translator does not put any `metadata.ownerReferences` in the objects it manages in a mailbox workspace (see https://docs.kubestellar.io/main/Coding%20Milestones/PoC2023q1/placement-translator/#additional-design-details).  The syncer could take the presence of some ownerReferences to mean that the object is owned by a local (in the same cluster as the syncer) controller rather than the syncer.

**Comment by MikeSpreitzer** [comment]
Another way to solve this would be to make the annotation that indicates syncer ownership have content that is a function of the object kind or resource name (excluding API group should be enough, that way there is no worry about renaturing's effect on the API group); an invalid value would indicate that the syncer does not own the object.

**Comment by clubanderson** [comment]
This is the approach I was going to ask about. It seems like the easiest path to reduce the time needed to resolve the issue.

**Comment by MikeSpreitzer** [comment]
It looks like this annotation copying is a deliberate behavior of the Deployment controller, although I still do not understand why or know where it is documented.  https://github.com/kubernetes/kubernetes/pull/94858#issuecomment-1679903399

**Comment by MikeSpreitzer** [comment]
https://github.com/kubestellar/kubestellar/issues/900#issuecomment-1679891824 was written with the Deployment controller in mind, but in general the syncer has to cope with any controller that the users put in their workload execution clusters.  The safe version of this idea is to make the value of the syncer-ownership annotation be a function of the full ID of the object owned by the syncer: API group, resource or Kind, namespace, and name.

**Comment by yana1205** [comment]
@MikeSpreitzer Thanks for the deep investigation.

I didn't expect that DeploymentController propagates annotations to ReplicaSets. 
I understood and agreed with the way (https://github.com/kubestellar/kubestellar/issues/900#issuecomment-1679888165) to avoid this issue. Thanks for the PR. I will review it soon.
