### ISSUE TITLE
Should the space framework support hierarchy?

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#905]
The space framework is about providing a layer of abstraction between providers and consumers of spaces.  What should the framework tell consumers about hierarchy among spaces?  I can think of four answers, each with its own advantages and disadvantages.

A: There is no hierarchy among spaces

This is the simplest to implement. However, for a provider that _does_ have hierarchy, this answer makes that feature inaccessible.

B: There is hierarchy among spaces

This makes the hierarchy feature of providers that have it accessible, but poses a challenge for providers that do not.  There might be a way to encode hierarchy in provider space names, depending on name restrictions on both sides.

C: The availability of hierarchy depends on the choice of provider

That is, each provider would have a boolean field in its Spec that reveals whether that provider supports hierarchy.  For consumers using the default provider, this would require a way for them to discover which is the default provider.  This has the disadvantage of maximal complexity for consumers to use.

D: The consumers see no hierarchy, each provider can optionally create hierarchy based on space names

In this approach the consumer sees no features regarding hierarchy, and a provider can map the flat space namespace to the provider's native hierarchical pathspace.  This can be difficult if that hierarchical pathspace has restrictions because the consumers will not know and respect those restrictions.  With the consumers not having access to hierarchy features, this would be of little value.

**Comment by clubanderson** [comment]
@MikeSpreitzer does ignoring hierarchy now put us behind in terms of supporting it for q4?

**Comment by clubanderson** [comment]
for now, the team has select A - no support for hierarchy

@pdettori and @ezrasilvera can you weigh in with your preference?

**Comment by MikeSpreitzer** [comment]
I am reconsidering due to #913 and #914 .

**Comment by ezrasilvera** [comment]
The latest decision is to not support hierarchy + hierarchy navigation and to change KS to not use hirarchy

**Comment by clubanderson** [comment]
pushing to backlog per @ezrasilvera

**Comment by MikeSpreitzer** [comment]
Moot
