### ISSUE TITLE
feature: use Brew to install KubeStellar plugins

### ISSUE THREAD

**Issue by clubanderson** [kubestellar/kubestellar#908]
### Feature Description

I would like to be able to install KubeStellar as a container (perhaps using helm), and then install plugins for kubectl easily

### Proposed Solution

create a package for krew that automates the installation of our kubestellar plugins

### Want to contribute?

- [X] I would like to work on this issue.

**Comment by MikeSpreitzer** [comment]
(1) As long as KubeStellar has more than one kubectl plugin, there is a version consistency question.  Using a distribution mechanism that, like krew, is focused on individual plugins is not advisable while KubeStellar has multiple kubectl plugins.  We *could* consolidate all of KubeStellar's kubectl plugins to one executable.

(2) Remember that although sometimes people using "plugins" as a shorthand for all the executables of a project, that is just a misleading shorthand.  KubeStellar distributes executables that are not kubectl plugins.  As long as KubeStellar distributes multiple executables, there is a version consistency question among them.

**Comment by MikeSpreitzer** [comment]
If you look at the value proposition for krew at https://krew.sigs.k8s.io/docs/developer-guide/distributing-with-krew/ , package managers and their associated ecosystem do a better job on 3 of the 4 than krew; the exception is the multiplicity of package managers itself.  I understand the desire to make KubeStellar easy to get and track.  Perhaps focusing on one or a few package managers is the better solution.

**Comment by clubanderson** [comment]
apt, brew, choco - agreed - I think your right.  Will research

**Comment by KPRoche** [comment]
remember apt is _specific_ to the Debian family of linux. 
Whatever package manager you use needs to work on Fedora too (i.e. RHEL, Fedora, CentOS)

**Comment by clubanderson** [comment]
@KPRoche what do you recommend?

**Comment by KPRoche** [comment]
According to its docs, Brew (homebrew) will work in MacOS, multiple flavors of Linux, and Windows 10+ if it has the Windows Subsystem for Linux installed. https://docs.brew.sh/Installation

Chocolatey is aimed at Windows only, so setting up a choco package would still require another package manager for Linux/MacOS

Brew might be our best bet to examine first.

**Comment by clubanderson** [comment]
Ahh. Didn't know brew had that reach. Perfect. I'll work on it. Thank you.

**Comment by clubanderson** [comment]
Changing title to include brew and not krew
