### ISSUE TITLE
bug: meta API group is exported from ESPW

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#911]
### Describe the bug

https://github.com/kubestellar/kubestellar/blob/v0.6.0/scripts/kubestellar#L252 creates an APIExport for the `meta.kcp.io` API group, but that is not intended.  There are no objects of that API group in any apiserver.  (That is an incidental side-effect of defining the in-process API for API introspection in the same place/way as the apiserver object oriented APIs.)

### Steps To Reproduce

See above.

### Expected Behavior

No BS.

**Comment by clubanderson** [comment]
moving to backlog, not committing for sprint 3
