### ISSUE TITLE
feature: space framework supports kube-binding between producers and consumers of space functionality

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#913]
### Feature Description

kube-bind provides better isolation between consumers than the baseline Kubernetes API machinery.  It would be good if the space framework supported this better isolation between consumers of the space framework's functionality.

In other words, this is about the space manager being a kube-bind service provider.

### Proposed Solution

Do it.

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by clubanderson** [comment]
@effi-ofer is this something we 'must' address before sept 15th?

**Comment by effi-ofer** [comment]
@clubanderson I don't think so.  Adding @ezrasilvera to the discussion.

**Comment by clubanderson** [comment]
we could live with this not being implemented on Sept 15th, but it will create more debt that we want to clear up within short order thereafter.

**Comment by MikeSpreitzer** [comment]
Moot.
