### ISSUE TITLE
feature: space framework supports spaces being kube-bind service consumers

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#914]
### Feature Description

In order for a space to be a kube-bind service consumer, there needs to be a kube-bind konnector for that space.  A space is not something that can necessarily run a konnector.  We need some way for the needed konnectors to run.

### Proposed Solution

Develop a provider-independent add-on to the space framework that runs the needed konnectors.

### Want to contribute?

- [ ] I would like to work on this issue.

### Additional Context

The combination of this and #913 creates a natural hierarchy among spaces: one space (parent) can call for the creation of other spaces (children).  This gets back to #905 .

**Comment by clubanderson** [comment]
@effi-ofer is this something we "must" address before sept 15h?

**Comment by effi-ofer** [comment]
@clubanderson I don't think so.  Adding @ezrasilvera to the discussion.

**Comment by MikeSpreitzer** [comment]
This is something we need in order to switch from using kcp APIExport/APIBinding to using kube-bind.

**Comment by fileppb** [comment]
@MikeSpreitzer @effi-ofer Where you able to decide if this needs to be included in the Sept. 15 release?

**Comment by fileppb** [comment]
Sorry I meant "Were you able" not "Where".

**Comment by ezrasilvera** [comment]
@MikeSpreitzer Is this needed for bind/export on all providers or only on Kubeflex?

**Comment by ezrasilvera** [comment]
I'm not sure it's part of the space framework, it's something that is needed for bind/export. , one of the options that it will be handled by the space framework, but that's not the only option.

**Comment by MikeSpreitzer** [comment]
I recommend closing this gap as follows.

- Give the space abstraction layer the concept of a "plugin", which is defined as directions for instantiating two Helm charts.  One goes in each space, and defines only objects that can go in any space.  The other chart goes into the space management cluster, which can run containerized workload.  These charts need to have sufficient parameters that their two instantiations can communicate as necessary, and this includes getting the containerized workload authenticated and authorized as needed to get its job done.
- Create a plugin that runs a kube-bind konnector per space, with the needed authentications and authorizations.

**Comment by ezrasilvera** [comment]
We decided not to implement ar this point
