### ISSUE TITLE
Should KubeStellar have a merge instead of fetch for kubeconfig?

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#915]
In the Kubernetes milieu there are two ways for a client to manage which cluster it is focused on: (1) using different kubeconfig files or (2) using different "contexts" within one kubeconfig file.  But currently KubeStellar's commands for deploying KubeStellar as Kubernetes workload only support (1).  Perhaps it would be helpful to users to also have a command that supports (2).  This would be a command that merges the kcp+KubeStellar contexts into the user's current kubeconfig file rather than fetching a distinct kubeconfig file.

There is a potential down-side here: the `kcp ws` commands _modify_ the current kubeconfig file and so have a usage restriction: nothing else should be reading or writing that kubeconfig file concurrently.  Doing the merge means that more "contexts" are in the kubeconfig file that has that usage restriction --- it widens the usage restriction.  Of course, offering an option does not mean that users have to use it.  Offering a footgun does not mean that users will use it.

Users are already able to combine kubeconfig files if they want to.

**Comment by clubanderson** [comment]
moving to backlog, we have bigger priorities right now.
