### ISSUE TITLE
bug: quickstart test is confusing people

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#919]
### Describe the bug

The quickstart test tests a release.  But its docs-ecutable workflow gets triggered in situations besides testing a release; see https://github.com/kubestellar/kubestellar/actions/workflows/docs-ecutable-qs.yml .  For one example, it is included in https://github.com/kubestellar/kubestellar/blob/main/.github/workflows/docs-ecutable-ALL.yml --- which some developers seem to expect to test their work.

Also, the quickstart docs-ecutable seems to be a blocking check in CI, but that is not appropriate.  The quickstart text in the `main` branch can not be expected to always work with the last release.  That would prevent us from making changes like #901 .

### Steps To Reproduce

See above

### Expected Behavior

No confusion about the quickstart docs-ecutable.

**Comment by clubanderson** [comment]
1) an admin can skip the quickstart
2) quickstart will not work for main without tons of headaches
3) we should not support quickstart for main any longer
4) we should stop using bootstrap script in any example, instead we should be using brew formula

as for building images and testing in main, this can be done with all other examples except for QS.  QS should be for releases only.

**Comment by clubanderson** [comment]
I have removed the 'main' branch trigger for QS

**Comment by MikeSpreitzer** [comment]
The bootstrap script has a simple way to deliver the kcp + KubeStellar executables, and is the path that we have working so far.  I think we should continue with that in the user documentation until we have a better alternative working for all supported platforms.

**Comment by clubanderson** [comment]
Why was this reopened?  The GitHub action was edited and it no longer triggers on main branch. Please close if this is the sole purpose of your issue. It has been fixed. The other commentary will be addressed in time.

**Comment by MikeSpreitzer** [comment]
Getting the GitHub action edit was not the sole purpose here.  It was to raise awareness in general, since I have been hearing developers express the understanding that the quickstart tests their work.

**Comment by clubanderson** [comment]
The issue exists and the action was changed. We can close the issue.

**Comment by MikeSpreitzer** [comment]
What about https://github.com/kubestellar/kubestellar/blob/main/.github/workflows/docs-ecutable-ALL.yml ?  I must admit that I am not clear on the purpose of that one.  I do not see it mentioned in our documentation.

**Comment by MikeSpreitzer** [comment]
Who invokes docs-ecutable-ALL when/why?

**Comment by clubanderson** [comment]
I do. So that I can eat breakfast while I wait for some feedback.

**Comment by MikeSpreitzer** [comment]
Other contributors are also using it, but I am not clear on what they think it is for.  I suspect that including the quickstart is making this confusing.
