### ISSUE TITLE
`kubectl ws`, equivalently `kubectl ws '~'`, is harmful

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#920]
If you are using a kubeconfig file in which the server URLs of the clusters use a domain name hacked in there by https://github.com/kubestellar/kubestellar/blob/main/scripts/switch-domain (or anything else), then issuing the command `kubectl ws` --- WITHOUT any further argument --- then kcp's `kubectl ws` plugin will introduce different server URLs to your kubeconfig.  Following is a demonstration.

```console
mspreitz@mjs12 kubestellar % cp k2.kubeconfig k3.kubeconfig
mspreitz@mjs12 kubestellar % KUBECONFIG=k3.kubeconfig kubectl ws
Current workspace is "kvdk2spgmbix".
Note: 'kubectl ws' now matches 'cd' semantics: go to home workspace. 'kubectl ws -' to go back. 'kubectl ws .' to print current workspace.
mspreitz@mjs12 kubestellar % diff k2.kubeconfig k3.kubeconfig | grep server
<       server: https://yep.yep:6443
<       server: https://yep.yep:6443/clusters/root
<       server: https://yep.yep:6443/clusters/root
<       server: https://yep.yep:6443/clusters/root:compute
>     server: https://yep.yep:6443
>     server: https://yep.yep:6443/clusters/root
>     server: https://10.244.0.9:6443/clusters/kvdk2spgmbix
>     server: https://yep.yep:6443/clusters/root
mspreitz@mjs12 kubestellar % 
```

See also https://github.com/kcp-dev/kcp/issues/3011

**Comment by ezrasilvera** [comment]
Why is this related to decoupling ?  Without KCP we won't use kubectl ws at all.

**Comment by MikeSpreitzer** [comment]
@ezrasilvera : I do not understand.  I see no claim that this issue is related to kcp decoupling.

**Comment by MikeSpreitzer** [comment]
Oh, now I see there was a label.  Not sure why I couldn't see the label earlier.

Now it is true that this issue is connected to kcp, and will go away when kcp is not used, and I expect will probably even be avoided when kcp is accessed through the space abstraction layer --- so there _is_ a logical relation here with decoupling, but it runs the other way than usual: this issue is not about some parcel of work that needs to be done as part of decoupling, rather decoupling will have a natural consequence of eliminating this issue.

**Comment by clubanderson** [comment]
to be covered in #998
