### ISSUE TITLE
bug: kubectl kubestellar ensure location fails

### ISSUE THREAD

**Issue by clubanderson** [kubestellar/kubestellar#922]
### Describe the bug

Trying to use example1 after using brew install of kubestellar, kcp, and kcp_kubectl, starting kcp, and running instructions from https://docs.kubestellar.io/main/Coding%20Milestones/PoC2023q1/example1/#initialize-the-kubestellar-platform-as-bare-processes and down.

I am receiving:

```
kubectl kubestellar ensure location florin  loc-name=florin  env=prod          

--- current directory is /Users/andan02
current ws is root:imw-1
imw is .
current cwsi is root:imw-1
error: apibindings.apis.kcp.io "edge.kcp.io" is forbidden: unable to create APIBinding: no permission to bind to export root:espw:edge.kcp.io
``` 

happens with guilder instruction as well.

### Steps To Reproduce

1) I used brew to install kubestellar, kcp, and kcp_kubectl.
2) I followed the example1 doc from https://docs.kubestellar.io/main/Coding%20Milestones/PoC2023q1/example1/#initialize-the-kubestellar-platform-as-bare-processes down.
3) I receive error on:
```
kubectl kubestellar ensure location florin  loc-name=florin  env=prod          

--- current directory is /Users/andan02
current ws is root:imw-1
imw is .
current cwsi is root:imw-1
error: apibindings.apis.kcp.io "edge.kcp.io" is forbidden: unable to create APIBinding: no permission to bind to export root:espw:edge.kcp.io
``` 

### Expected Behavior

should ensure florin location.

**Comment by MikeSpreitzer** [comment]
I see that the error message says "edge.kcp.io".  That was replaced with "edge.kubestellar.io" in #901 .  I do not know what vintage you expect in that brew, but it should be consistent whatever it is.  Look at what you have got exported from the `root:espw` workspace.

**Comment by MikeSpreitzer** [comment]
This is also a little interesting; it demonstrates that the kcp ws create operation creates a broken ClusterRoleBinding or I do not understand how they work in kcp.

```console
(venv) %n@%m %1~ %# kubectl ws create fubar --enter
Workspace "fubar" (type root:organization) created. Waiting for it to be ready...
Workspace "fubar" (type root:organization) is ready to use.
Current workspace is "root:fubar" (type root:organization).

(venv) %n@%m %1~ %# kubectl get clusterrolebindings
NAME              ROLE                        AGE
workspace-admin   ClusterRole/cluster-admin   10s

(venv) %n@%m %1~ %# kubectl get clusterroles
No resources found
```

I started by looking at the ESPW in a working system, of course.

```console
(venv) %n@%m %1~ %# kubectl ws root:espw
Current workspace is "root:espw".

(venv) %n@%m %1~ %# kubectl get clusterrolebindings
NAME              ROLE                        AGE
workspace-admin   ClusterRole/cluster-admin   28m

(venv) %n@%m %1~ %# kubectl get clusterroles
No resources found
```

**Comment by clubanderson** [comment]
no longer an issue with latest core-matching brew installer of user pkgs
