### ISSUE TITLE
feature: rename space.kcp.io API group to space.kubestellar.io

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#926]
### Feature Description

This API group needs to be renamed.

### Proposed Solution

Do it.

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by MikeSpreitzer** [comment]
@fileppb 
@effi-ofer 
@andreyod 
@ezrasilvera

**Comment by effi-ofer** [comment]
Hey @MikeSpreitzer isn't it already?  https://github.com/kubestellar/kubestellar/blob/main/pkg/apis/space/register.go

**Comment by fileppb** [comment]
@MikeSpreitzer do you mean the references to workspace.kcp.io? I don't see any references to "space.kcp.io" but I do see this: ```docs/content/Community/partners/argocd.md:$ argocd cluster add --name wmw --kubeconfig ./admin.kubeconfig workspace.kcp.io/current
docs/content/Community/partners/argocd.md:WARNING: This will create a service account `argocd-manager` on the cluster referenced by context `workspace.kcp.io/current` with full cluster level privileges. Do you want to continue [y/N]? y```

**Comment by MikeSpreitzer** [comment]
Sorry, my mistake.  Looks like this is already done.
