### ISSUE TITLE
feature: use namespaces to separate space framework consumers

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#927]
### Feature Description

Absent #913 , the natural use of the _namespace_ of a Space object is to separate consumers of the space functionality.  Currently the namespace of a Space object has to be a function of the space provider name, which seems a spurious imposition on consumers (which are already indicating the provider in the Space object).

### Proposed Solution

Make the change.

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by MikeSpreitzer** [comment]
@ezrasilvera 
@effi-ofer 
@andreyod

**Comment by clubanderson** [comment]
pushing to backlog - not in plan for milestone1 per @ezrasilvera

**Comment by MikeSpreitzer** [comment]
Moot
