### ISSUE TITLE
feature: Document space framework for users of it

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#931]
### Feature Description

Users of the space framework need a document addressed to them.  I, as a reviewer of PRs changing space functionality consumers to use the space framework, need to understand how the space framework is intended to be used.

While the Go compiler does a certain amount of checking for consistency with the APIs already checked in, an author of code using the space framework needs to know much more than what is written in the Go code and checked by the compiler.

Clues can be found in my comments in my reviews of the PRs currently in flight: #897, #904, and #923.  Also the high level issues such as #905, #906, #913, #914, #928 .

Such a document will address the following issues, among others.

- Division of roles and responsibilities; who makes what decisions when, how are those decisions recorded by the decision-maker and conveyed to decision consumers.
- What needs to be configured in code that uses the space framework.
- How space names correspond to kcp workspaces paths, when the kcp provider is used.
- An architectural outline, with clear and distinct identification of process boundaries and library boundaries, boundaries between who owns/authors/maintains what.

Given the current extreme time crunch, I do not expect everything will be done to our complete satisfaction at first.  The needed document will at least be a roadmap.  It might call out forks in the road ahead, where we have decisions still to make.

### Proposed Solution

This document gets written.

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by MikeSpreitzer** [comment]
@effi-ofer 
@andreyod 
@clubanderson

**Comment by clubanderson** [comment]
pushing to backlog, not committed for milestone1 - per @ezrasilvera
