### ISSUE TITLE
bug: incorrect way of updating status of an object

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#945]
### Describe the bug

The correct way to update the `status` field of an object depends on whether that kind of object has a "status subresource".  Neither the placement-translator nor the syncer has a general way of knowing which is which.

### Steps To Reproduce

Try propagating status upward from a kind of object that the syncer does not handle correctly.

### Expected Behavior

Status propagates upward for all kinds of objects.

### Additional Context

#944 is nearby but distinct.

**Comment by clubanderson** [comment]
can we close this since it just a PSA?
