### ISSUE TITLE
Space name may not be unique if hierarchy is supported. 

### ISSUE THREAD

**Issue by ezrasilvera** [kubestellar/kubestellar#953]
Currently the space-framework consider the space name (without the hierarchy path) to be unique across a provider instance. For providers that support hierarchy this is of course not correct. 
path+name can be considered a unique identifier.

**Comment by clubanderson** [comment]
pushing to backlog at this time - decided not to support hierarchy in spaces, for now.

**Comment by ezrasilvera** [comment]
not  relevant for ks-0.20
