### ISSUE TITLE
feature: transition use of user credentials

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#955]
### Feature Description

Currently much of the multi-cluster configuration management codebase uses one of _two_ highly-privileged user identities, as mentioned in #932 .  The space framework currently plans to give a space user only one user identity.  We _might_ be able to make this transition easily, because the current distinction is that one of the two is authorized to do things with kcp Workspaces that might map to authorization to do things with Space objects in the Space Manager's cluster.

### Proposed Solution

Document the transition of user identities.

### Want to contribute?

- [ ] I would like to work on this issue.

### Additional Context

#840

**Comment by clubanderson** [comment]
pushing back 1 sprint to allow time for discussion between @ezrasilvera and @MikeSpreitzer

**Comment by MikeSpreitzer** [comment]
I think this is moot now.
