### ISSUE TITLE
bug: KCP provider stops getting events after some time

### ISSUE THREAD

**Issue by andreyod** [kubestellar/kubestellar#964]
### Describe the bug

KCP provider stops getting events from KCP server after approximately 1 hour.

### Steps To Reproduce

1. Strat KCP and space-manager
2. Create provider object for KCP
3. Run for more than 1 hour
4. Create Space object

### Expected Behavior

Provider should get create event and update the space-manager about it.

**Comment by clubanderson** [comment]
@andreyod is there an issue open in KCP (assuming this is a bug for them)?

**Comment by andreyod** [comment]
This is for our space-framework KCP provider.
Fixed by https://github.com/kubestellar/kubestellar/pull/966
Closing.
