### ISSUE TITLE
feature: take user guidance on dissecting downsynced objects

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#970]
### Feature Description

The KubeStellar design for downsynced objects it that "desired state" propagates outward and "reported state" propagates inward.  This begs the questions of which parts of a downsynced object are desired state and which parts are reported state.  A simple answer that people often suppose is that the `spec` field holds the desired state and the `status` field holds the reported state but that is only usually approximately true.  Currently the placement translator has a documented heuristic for answering this question.  When #772 is implemented it will become even more imperative to make this distinction accurately, lest desired state get overwritten.

The feature request here is to add a feature by which a user can say which parts of a downsynced object are desired state and which are reported state.

In Codeflare's MCAD there was recently introduced a new field under the `status` of an AppWrapper object that indicates the desired cluster for execution of that AppWrapper.  Treating this as reported state, together with #772, would cause that new field to be cleared when the `status` field is propagated to the center from the WEC (which would never get the value of this field as long as it is treated as reported state).  I have just suggested that this new field be moved to `spec`; I do not know if/when this will happen.

@cwiklik 
@dmatch01

### Proposed Solution

Add a kind of object that says how another kind of object is dissected.

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by clubanderson** [comment]
@dumb0002 please check if this is needed or if a change to spec/status designation in MCAD appwrapper is sufficient (preferable) - and we can close this item.

**Comment by dumb0002** [comment]
@clubanderson, @cwiklik is still working to implement the changes in MCAD appwrapper: to move cluster selection field from the status field to the spec field in AppWrapper (cc: @MikeSpreitzer ).

**Comment by clubanderson** [comment]
@dumb0002 ok - moving the selection field obviates this issue, correct?  We can close this issue since the direction they are taking is moving away from needing any changes in KS.

**Comment by dumb0002** [comment]
@clubanderson, that's correct (cc: @cwiklik @MikeSpreitzer )

**Comment by clubanderson** [comment]
closing - thank you
