### ISSUE TITLE
bug: bootstrap/install-kcp-with-plugins.sh problems

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#971]
### Describe the bug

(1) This script, which was designed for users and I thought was obsolete and should be deleted, is now used by contributors (in the Makefile target for `kcp/bin/kcp`, used by the target for `e2e-test-kubestellar-syncer`).  Do we still want to do this?  If this script is to be kept in some form then the following two items are not moot.

(2) #760 redux.

(3) The `get_arch_type` function barfs on my MacBook, where `$HOSTTYPE` is `arm64`.

### Steps To Reproduce

See above.  Try the syncer end-to-end test.  Try it on a Mac.

### Expected Behavior

The syncer end-to-end test works on my Mac.

**Comment by clubanderson** [comment]
@MikeSpreitzer please update this ticket with details for @yana1205 to have a closer look.

**Comment by clubanderson** [comment]
@francostellari to take a look at item 1

**Comment by francostellari** [comment]
@MikeSpreitzer 

I believe PR #1024 fixes (3) 
I believe (2) was fixed by PR #761 and issue #760 should have been closed... is ti still an issue for you?

**Comment by clubanderson** [comment]
This appears to be fixed.

**Comment by francostellari** [comment]
Fixed by PR #1024
