### ISSUE TITLE
feature: Restructure the space-framework code to use modules 

### ISSUE THREAD

**Issue by ezrasilvera** [kubestellar/kubestellar#977]
We are using a single git repository for both KS and the space-framework . The space-framework currently spread over several directories of KS and tightly integrated with it. 
We want to separate the space-framework into a distinct go module and use a distinct directory structure within the kubestellar repository.

**Comment by MikeSpreitzer** [comment]
I suggest putting "go" in the title of this issue.

**Comment by MikeSpreitzer** [comment]
There is an implication here for directory structure.  Each go module is headed by a directory, and a given directory can head only one go module.

**Comment by MikeSpreitzer** [comment]
I am not sure whether you want to make this a distinct issue, but the documentation should also have a clear high-level split between the MCCM and the space framework.

**Comment by ezrasilvera** [comment]
Completed Initial restructure of space-framework.
