### ISSUE TITLE
bug: syncer end-to-end test does not work on a mac

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#979]
### Describe the bug

See #971 

### Steps To Reproduce

See #971 

### Expected Behavior

The syncer end-to-end test works on the Mac.

**Comment by clubanderson** [comment]
@francostellari please address item 1 in #971 so that we can close #979 (this issue)

**Comment by clubanderson** [comment]
this can be closed - test now works
