### ISSUE TITLE
Maybe create a client-side abstraction over kube-bind, kcp binding

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#982]
The idea of this abstraction is to support a service provider that wants to be able to work with both kube-bind and kcp's APIExport/APIBinding.  I think that would cover the following things.

- The code path from `rest.Config` to informer.  There are choices to be made here about the exact interface for the informer and the associated lister, if any.
- The way that the space ID is extracted from an object delivered by the informer or the lister.

Having such an abstraction could serve either or both of the following two goals.

- Provide long term support for being able to use the relatively efficient kcp APIExport/APIBinding mechanism.
- Provide a temporary ability to use either, at the flip of a runtime switch, to support incremental migration from the kcp mechanism to the kube-bind one.

**Comment by clubanderson** [comment]
moving to sprint 5

**Comment by ezrasilvera** [comment]
We decided eventually to not support kcp-bind
