### ISSUE TITLE
Epic: support production quality deployments and operations 

### ISSUE THREAD

**Issue by pdettori** [kubestellar/kubestellar#990]
### Objective

We need to support production level deployments and operations of KubeStellar on a Kubernetes or OpenShift cluster.

- [x] #993
- [x]  #992 
- [ ] #996 
- [ ] #997
- [ ] #998  
- [x] #859 Support deployment into a Kubernetes cluster

**Comment by clubanderson** [comment]
@MikeSpreitzer @pdettori please look to combine content for #858 into this one.

**Comment by clubanderson** [comment]
@MikeSpreitzer @pdettori can you look to combine this with #858 ?

**Comment by clubanderson** [comment]
closed #858 in favor of this issue
