### ISSUE TITLE
feature:  Build a separate container image for each KS controller

### ISSUE THREAD

**Issue by pdettori** [kubestellar/kubestellar#992]
### Feature Description

To support pod logs and follow best practices around running processes in Kubernetes, we need to generate an operate container image for the KS controllers. Since we do not yet a controller manager we need to create container images for the following binaries:

- [x] placement-translator
- [x] mailbox-controller
- [x] kubestellar-where-resolver

### Proposed Solution

- Use`ko` for all multi-platform builds, and add the `ko` builds to our current CI.
- Support use of image digest instead of tags in helm charts - we may need to generate an index file to correlate git commit ID with image digest
- Example image reference with digest instead of tag: `quay.io/kubestellar/syncer@sha256:525deab696825a3eb3178700d25465fe0e965edd9d1fd32fae40690b3a18dbb0`

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by clubanderson** [comment]
@francostellari can this be closed?

**Comment by clubanderson** [comment]
I think this is done, if you disagree, please reopen.
