### ISSUE TITLE
feature:  Update helm chart to support pod logs for separate container images

### ISSUE THREAD

**Issue by pdettori** [kubestellar/kubestellar#993]
### Feature Description

The current helm chart should be updated to support best practices for pods logging, so that logs can be observable for example with `kubectl logs` or observability tools. This feature depends on #992. 

### Proposed Solution

- [x] decide if single pod with multiple containers or multiple pods with one container per pod - we will start with separate pods
- [x] update the helm chart accordingly (depends on #992)

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by clubanderson** [comment]
working great - thank you - have tested it in several environments.
